/**
 * Data Quality & Great Expectations Ruleset: NumericRangeAndDistribution
 * Description: Z-score anomaly bounds, min-max thresholds, and standard deviation bounds
 */

export interface DataQualityRule {
  assertionId: string;
  ruleName: string;
  category: string;
  targetTable: string;
  targetColumn: string;
  evaluationEngine: string;
  isBlocking: boolean;
  alertSeverity: string;
  autoRemediationAction: string;
}

export const QUALITY_NRD_DATASET: DataQualityRule[] = [
  {
    assertionId: 'ASSERT-NRD-001',
    ruleName: 'NumericRangeAndDistribution Assertion Check #1',
    category: 'min-max thresholds',
    targetTable: 'enterprise_data_mart.table_1',
    targetColumn: 'column_attr_1',
    evaluationEngine: 'GREAT_EXPECTATIONS',
    isBlocking: false,
    alertSeverity: 'HIGH_P2',
    autoRemediationAction: 'RETRY_STAGE_WITH_BACKOFF'
  },
  {
    assertionId: 'ASSERT-NRD-002',
    ruleName: 'NumericRangeAndDistribution Assertion Check #2',
    category: 'and standard deviation bounds',
    targetTable: 'enterprise_data_mart.table_2',
    targetColumn: 'column_attr_2',
    evaluationEngine: 'SQL_ASSERTION',
    isBlocking: false,
    alertSeverity: 'HIGH_P2',
    autoRemediationAction: 'QUARANTINE_ROW_TO_DLQ'
  },
  {
    assertionId: 'ASSERT-NRD-003',
    ruleName: 'NumericRangeAndDistribution Assertion Check #3',
    category: 'Z-score anomaly bounds',
    targetTable: 'enterprise_data_mart.table_3',
    targetColumn: 'column_attr_3',
    evaluationEngine: 'GREAT_EXPECTATIONS',
    isBlocking: true,
    alertSeverity: 'CRITICAL_P1',
    autoRemediationAction: 'RETRY_STAGE_WITH_BACKOFF'
  },
  {
    assertionId: 'ASSERT-NRD-004',
    ruleName: 'NumericRangeAndDistribution Assertion Check #4',
    category: 'min-max thresholds',
    targetTable: 'enterprise_data_mart.table_4',
    targetColumn: 'column_attr_4',
    evaluationEngine: 'SQL_ASSERTION',
    isBlocking: false,
    alertSeverity: 'HIGH_P2',
    autoRemediationAction: 'QUARANTINE_ROW_TO_DLQ'
  },
  {
    assertionId: 'ASSERT-NRD-005',
    ruleName: 'NumericRangeAndDistribution Assertion Check #5',
    category: 'and standard deviation bounds',
    targetTable: 'enterprise_data_mart.table_5',
    targetColumn: 'column_attr_5',
    evaluationEngine: 'GREAT_EXPECTATIONS',
    isBlocking: false,
    alertSeverity: 'HIGH_P2',
    autoRemediationAction: 'RETRY_STAGE_WITH_BACKOFF'
  },
  {
    assertionId: 'ASSERT-NRD-006',
    ruleName: 'NumericRangeAndDistribution Assertion Check #6',
    category: 'Z-score anomaly bounds',
    targetTable: 'enterprise_data_mart.table_6',
    targetColumn: 'column_attr_6',
    evaluationEngine: 'SQL_ASSERTION',
    isBlocking: true,
    alertSeverity: 'CRITICAL_P1',
    autoRemediationAction: 'QUARANTINE_ROW_TO_DLQ'
  },
  {
    assertionId: 'ASSERT-NRD-007',
    ruleName: 'NumericRangeAndDistribution Assertion Check #7',
    category: 'min-max thresholds',
    targetTable: 'enterprise_data_mart.table_7',
    targetColumn: 'column_attr_7',
    evaluationEngine: 'GREAT_EXPECTATIONS',
    isBlocking: false,
    alertSeverity: 'HIGH_P2',
    autoRemediationAction: 'RETRY_STAGE_WITH_BACKOFF'
  },
  {
    assertionId: 'ASSERT-NRD-008',
    ruleName: 'NumericRangeAndDistribution Assertion Check #8',
    category: 'and standard deviation bounds',
    targetTable: 'enterprise_data_mart.table_8',
    targetColumn: 'column_attr_8',
    evaluationEngine: 'SQL_ASSERTION',
    isBlocking: false,
    alertSeverity: 'HIGH_P2',
    autoRemediationAction: 'QUARANTINE_ROW_TO_DLQ'
  },
  {
    assertionId: 'ASSERT-NRD-009',
    ruleName: 'NumericRangeAndDistribution Assertion Check #9',
    category: 'Z-score anomaly bounds',
    targetTable: 'enterprise_data_mart.table_9',
    targetColumn: 'column_attr_9',
    evaluationEngine: 'GREAT_EXPECTATIONS',
    isBlocking: true,
    alertSeverity: 'CRITICAL_P1',
    autoRemediationAction: 'RETRY_STAGE_WITH_BACKOFF'
  },
  {
    assertionId: 'ASSERT-NRD-010',
    ruleName: 'NumericRangeAndDistribution Assertion Check #10',
    category: 'min-max thresholds',
    targetTable: 'enterprise_data_mart.table_10',
    targetColumn: 'column_attr_10',
    evaluationEngine: 'SQL_ASSERTION',
    isBlocking: false,
    alertSeverity: 'HIGH_P2',
    autoRemediationAction: 'QUARANTINE_ROW_TO_DLQ'
  },
  {
    assertionId: 'ASSERT-NRD-011',
    ruleName: 'NumericRangeAndDistribution Assertion Check #11',
    category: 'and standard deviation bounds',
    targetTable: 'enterprise_data_mart.table_11',
    targetColumn: 'column_attr_11',
    evaluationEngine: 'GREAT_EXPECTATIONS',
    isBlocking: false,
    alertSeverity: 'HIGH_P2',
    autoRemediationAction: 'RETRY_STAGE_WITH_BACKOFF'
  },
  {
    assertionId: 'ASSERT-NRD-012',
    ruleName: 'NumericRangeAndDistribution Assertion Check #12',
    category: 'Z-score anomaly bounds',
    targetTable: 'enterprise_data_mart.table_12',
    targetColumn: 'column_attr_12',
    evaluationEngine: 'SQL_ASSERTION',
    isBlocking: true,
    alertSeverity: 'CRITICAL_P1',
    autoRemediationAction: 'QUARANTINE_ROW_TO_DLQ'
  },
  {
    assertionId: 'ASSERT-NRD-013',
    ruleName: 'NumericRangeAndDistribution Assertion Check #13',
    category: 'min-max thresholds',
    targetTable: 'enterprise_data_mart.table_13',
    targetColumn: 'column_attr_13',
    evaluationEngine: 'GREAT_EXPECTATIONS',
    isBlocking: false,
    alertSeverity: 'HIGH_P2',
    autoRemediationAction: 'RETRY_STAGE_WITH_BACKOFF'
  },
  {
    assertionId: 'ASSERT-NRD-014',
    ruleName: 'NumericRangeAndDistribution Assertion Check #14',
    category: 'and standard deviation bounds',
    targetTable: 'enterprise_data_mart.table_14',
    targetColumn: 'column_attr_14',
    evaluationEngine: 'SQL_ASSERTION',
    isBlocking: false,
    alertSeverity: 'HIGH_P2',
    autoRemediationAction: 'QUARANTINE_ROW_TO_DLQ'
  },
  {
    assertionId: 'ASSERT-NRD-015',
    ruleName: 'NumericRangeAndDistribution Assertion Check #15',
    category: 'Z-score anomaly bounds',
    targetTable: 'enterprise_data_mart.table_15',
    targetColumn: 'column_attr_15',
    evaluationEngine: 'GREAT_EXPECTATIONS',
    isBlocking: true,
    alertSeverity: 'CRITICAL_P1',
    autoRemediationAction: 'RETRY_STAGE_WITH_BACKOFF'
  },
  {
    assertionId: 'ASSERT-NRD-016',
    ruleName: 'NumericRangeAndDistribution Assertion Check #16',
    category: 'min-max thresholds',
    targetTable: 'enterprise_data_mart.table_16',
    targetColumn: 'column_attr_16',
    evaluationEngine: 'SQL_ASSERTION',
    isBlocking: false,
    alertSeverity: 'HIGH_P2',
    autoRemediationAction: 'QUARANTINE_ROW_TO_DLQ'
  },
  {
    assertionId: 'ASSERT-NRD-017',
    ruleName: 'NumericRangeAndDistribution Assertion Check #17',
    category: 'and standard deviation bounds',
    targetTable: 'enterprise_data_mart.table_17',
    targetColumn: 'column_attr_17',
    evaluationEngine: 'GREAT_EXPECTATIONS',
    isBlocking: false,
    alertSeverity: 'HIGH_P2',
    autoRemediationAction: 'RETRY_STAGE_WITH_BACKOFF'
  },
  {
    assertionId: 'ASSERT-NRD-018',
    ruleName: 'NumericRangeAndDistribution Assertion Check #18',
    category: 'Z-score anomaly bounds',
    targetTable: 'enterprise_data_mart.table_18',
    targetColumn: 'column_attr_18',
    evaluationEngine: 'SQL_ASSERTION',
    isBlocking: true,
    alertSeverity: 'CRITICAL_P1',
    autoRemediationAction: 'QUARANTINE_ROW_TO_DLQ'
  },
  {
    assertionId: 'ASSERT-NRD-019',
    ruleName: 'NumericRangeAndDistribution Assertion Check #19',
    category: 'min-max thresholds',
    targetTable: 'enterprise_data_mart.table_19',
    targetColumn: 'column_attr_19',
    evaluationEngine: 'GREAT_EXPECTATIONS',
    isBlocking: false,
    alertSeverity: 'HIGH_P2',
    autoRemediationAction: 'RETRY_STAGE_WITH_BACKOFF'
  },
  {
    assertionId: 'ASSERT-NRD-020',
    ruleName: 'NumericRangeAndDistribution Assertion Check #20',
    category: 'and standard deviation bounds',
    targetTable: 'enterprise_data_mart.table_20',
    targetColumn: 'column_attr_0',
    evaluationEngine: 'SQL_ASSERTION',
    isBlocking: false,
    alertSeverity: 'HIGH_P2',
    autoRemediationAction: 'QUARANTINE_ROW_TO_DLQ'
  },
  {
    assertionId: 'ASSERT-NRD-021',
    ruleName: 'NumericRangeAndDistribution Assertion Check #21',
    category: 'Z-score anomaly bounds',
    targetTable: 'enterprise_data_mart.table_21',
    targetColumn: 'column_attr_1',
    evaluationEngine: 'GREAT_EXPECTATIONS',
    isBlocking: true,
    alertSeverity: 'CRITICAL_P1',
    autoRemediationAction: 'RETRY_STAGE_WITH_BACKOFF'
  },
  {
    assertionId: 'ASSERT-NRD-022',
    ruleName: 'NumericRangeAndDistribution Assertion Check #22',
    category: 'min-max thresholds',
    targetTable: 'enterprise_data_mart.table_22',
    targetColumn: 'column_attr_2',
    evaluationEngine: 'SQL_ASSERTION',
    isBlocking: false,
    alertSeverity: 'HIGH_P2',
    autoRemediationAction: 'QUARANTINE_ROW_TO_DLQ'
  },
  {
    assertionId: 'ASSERT-NRD-023',
    ruleName: 'NumericRangeAndDistribution Assertion Check #23',
    category: 'and standard deviation bounds',
    targetTable: 'enterprise_data_mart.table_23',
    targetColumn: 'column_attr_3',
    evaluationEngine: 'GREAT_EXPECTATIONS',
    isBlocking: false,
    alertSeverity: 'HIGH_P2',
    autoRemediationAction: 'RETRY_STAGE_WITH_BACKOFF'
  },
  {
    assertionId: 'ASSERT-NRD-024',
    ruleName: 'NumericRangeAndDistribution Assertion Check #24',
    category: 'Z-score anomaly bounds',
    targetTable: 'enterprise_data_mart.table_24',
    targetColumn: 'column_attr_4',
    evaluationEngine: 'SQL_ASSERTION',
    isBlocking: true,
    alertSeverity: 'CRITICAL_P1',
    autoRemediationAction: 'QUARANTINE_ROW_TO_DLQ'
  },
  {
    assertionId: 'ASSERT-NRD-025',
    ruleName: 'NumericRangeAndDistribution Assertion Check #25',
    category: 'min-max thresholds',
    targetTable: 'enterprise_data_mart.table_25',
    targetColumn: 'column_attr_5',
    evaluationEngine: 'GREAT_EXPECTATIONS',
    isBlocking: false,
    alertSeverity: 'HIGH_P2',
    autoRemediationAction: 'RETRY_STAGE_WITH_BACKOFF'
  },
  {
    assertionId: 'ASSERT-NRD-026',
    ruleName: 'NumericRangeAndDistribution Assertion Check #26',
    category: 'and standard deviation bounds',
    targetTable: 'enterprise_data_mart.table_26',
    targetColumn: 'column_attr_6',
    evaluationEngine: 'SQL_ASSERTION',
    isBlocking: false,
    alertSeverity: 'HIGH_P2',
    autoRemediationAction: 'QUARANTINE_ROW_TO_DLQ'
  },
  {
    assertionId: 'ASSERT-NRD-027',
    ruleName: 'NumericRangeAndDistribution Assertion Check #27',
    category: 'Z-score anomaly bounds',
    targetTable: 'enterprise_data_mart.table_27',
    targetColumn: 'column_attr_7',
    evaluationEngine: 'GREAT_EXPECTATIONS',
    isBlocking: true,
    alertSeverity: 'CRITICAL_P1',
    autoRemediationAction: 'RETRY_STAGE_WITH_BACKOFF'
  },
  {
    assertionId: 'ASSERT-NRD-028',
    ruleName: 'NumericRangeAndDistribution Assertion Check #28',
    category: 'min-max thresholds',
    targetTable: 'enterprise_data_mart.table_28',
    targetColumn: 'column_attr_8',
    evaluationEngine: 'SQL_ASSERTION',
    isBlocking: false,
    alertSeverity: 'HIGH_P2',
    autoRemediationAction: 'QUARANTINE_ROW_TO_DLQ'
  },
  {
    assertionId: 'ASSERT-NRD-029',
    ruleName: 'NumericRangeAndDistribution Assertion Check #29',
    category: 'and standard deviation bounds',
    targetTable: 'enterprise_data_mart.table_29',
    targetColumn: 'column_attr_9',
    evaluationEngine: 'GREAT_EXPECTATIONS',
    isBlocking: false,
    alertSeverity: 'HIGH_P2',
    autoRemediationAction: 'RETRY_STAGE_WITH_BACKOFF'
  },
  {
    assertionId: 'ASSERT-NRD-030',
    ruleName: 'NumericRangeAndDistribution Assertion Check #30',
    category: 'Z-score anomaly bounds',
    targetTable: 'enterprise_data_mart.table_0',
    targetColumn: 'column_attr_10',
    evaluationEngine: 'SQL_ASSERTION',
    isBlocking: true,
    alertSeverity: 'CRITICAL_P1',
    autoRemediationAction: 'QUARANTINE_ROW_TO_DLQ'
  },
  {
    assertionId: 'ASSERT-NRD-031',
    ruleName: 'NumericRangeAndDistribution Assertion Check #31',
    category: 'min-max thresholds',
    targetTable: 'enterprise_data_mart.table_1',
    targetColumn: 'column_attr_11',
    evaluationEngine: 'GREAT_EXPECTATIONS',
    isBlocking: false,
    alertSeverity: 'HIGH_P2',
    autoRemediationAction: 'RETRY_STAGE_WITH_BACKOFF'
  },
  {
    assertionId: 'ASSERT-NRD-032',
    ruleName: 'NumericRangeAndDistribution Assertion Check #32',
    category: 'and standard deviation bounds',
    targetTable: 'enterprise_data_mart.table_2',
    targetColumn: 'column_attr_12',
    evaluationEngine: 'SQL_ASSERTION',
    isBlocking: false,
    alertSeverity: 'HIGH_P2',
    autoRemediationAction: 'QUARANTINE_ROW_TO_DLQ'
  },
  {
    assertionId: 'ASSERT-NRD-033',
    ruleName: 'NumericRangeAndDistribution Assertion Check #33',
    category: 'Z-score anomaly bounds',
    targetTable: 'enterprise_data_mart.table_3',
    targetColumn: 'column_attr_13',
    evaluationEngine: 'GREAT_EXPECTATIONS',
    isBlocking: true,
    alertSeverity: 'CRITICAL_P1',
    autoRemediationAction: 'RETRY_STAGE_WITH_BACKOFF'
  },
  {
    assertionId: 'ASSERT-NRD-034',
    ruleName: 'NumericRangeAndDistribution Assertion Check #34',
    category: 'min-max thresholds',
    targetTable: 'enterprise_data_mart.table_4',
    targetColumn: 'column_attr_14',
    evaluationEngine: 'SQL_ASSERTION',
    isBlocking: false,
    alertSeverity: 'HIGH_P2',
    autoRemediationAction: 'QUARANTINE_ROW_TO_DLQ'
  },
  {
    assertionId: 'ASSERT-NRD-035',
    ruleName: 'NumericRangeAndDistribution Assertion Check #35',
    category: 'and standard deviation bounds',
    targetTable: 'enterprise_data_mart.table_5',
    targetColumn: 'column_attr_15',
    evaluationEngine: 'GREAT_EXPECTATIONS',
    isBlocking: false,
    alertSeverity: 'HIGH_P2',
    autoRemediationAction: 'RETRY_STAGE_WITH_BACKOFF'
  },
  {
    assertionId: 'ASSERT-NRD-036',
    ruleName: 'NumericRangeAndDistribution Assertion Check #36',
    category: 'Z-score anomaly bounds',
    targetTable: 'enterprise_data_mart.table_6',
    targetColumn: 'column_attr_16',
    evaluationEngine: 'SQL_ASSERTION',
    isBlocking: true,
    alertSeverity: 'CRITICAL_P1',
    autoRemediationAction: 'QUARANTINE_ROW_TO_DLQ'
  },
  {
    assertionId: 'ASSERT-NRD-037',
    ruleName: 'NumericRangeAndDistribution Assertion Check #37',
    category: 'min-max thresholds',
    targetTable: 'enterprise_data_mart.table_7',
    targetColumn: 'column_attr_17',
    evaluationEngine: 'GREAT_EXPECTATIONS',
    isBlocking: false,
    alertSeverity: 'HIGH_P2',
    autoRemediationAction: 'RETRY_STAGE_WITH_BACKOFF'
  },
  {
    assertionId: 'ASSERT-NRD-038',
    ruleName: 'NumericRangeAndDistribution Assertion Check #38',
    category: 'and standard deviation bounds',
    targetTable: 'enterprise_data_mart.table_8',
    targetColumn: 'column_attr_18',
    evaluationEngine: 'SQL_ASSERTION',
    isBlocking: false,
    alertSeverity: 'HIGH_P2',
    autoRemediationAction: 'QUARANTINE_ROW_TO_DLQ'
  },
  {
    assertionId: 'ASSERT-NRD-039',
    ruleName: 'NumericRangeAndDistribution Assertion Check #39',
    category: 'Z-score anomaly bounds',
    targetTable: 'enterprise_data_mart.table_9',
    targetColumn: 'column_attr_19',
    evaluationEngine: 'GREAT_EXPECTATIONS',
    isBlocking: true,
    alertSeverity: 'CRITICAL_P1',
    autoRemediationAction: 'RETRY_STAGE_WITH_BACKOFF'
  },
  {
    assertionId: 'ASSERT-NRD-040',
    ruleName: 'NumericRangeAndDistribution Assertion Check #40',
    category: 'min-max thresholds',
    targetTable: 'enterprise_data_mart.table_10',
    targetColumn: 'column_attr_0',
    evaluationEngine: 'SQL_ASSERTION',
    isBlocking: false,
    alertSeverity: 'HIGH_P2',
    autoRemediationAction: 'QUARANTINE_ROW_TO_DLQ'
  },
  {
    assertionId: 'ASSERT-NRD-041',
    ruleName: 'NumericRangeAndDistribution Assertion Check #41',
    category: 'and standard deviation bounds',
    targetTable: 'enterprise_data_mart.table_11',
    targetColumn: 'column_attr_1',
    evaluationEngine: 'GREAT_EXPECTATIONS',
    isBlocking: false,
    alertSeverity: 'HIGH_P2',
    autoRemediationAction: 'RETRY_STAGE_WITH_BACKOFF'
  },
  {
    assertionId: 'ASSERT-NRD-042',
    ruleName: 'NumericRangeAndDistribution Assertion Check #42',
    category: 'Z-score anomaly bounds',
    targetTable: 'enterprise_data_mart.table_12',
    targetColumn: 'column_attr_2',
    evaluationEngine: 'SQL_ASSERTION',
    isBlocking: true,
    alertSeverity: 'CRITICAL_P1',
    autoRemediationAction: 'QUARANTINE_ROW_TO_DLQ'
  },
  {
    assertionId: 'ASSERT-NRD-043',
    ruleName: 'NumericRangeAndDistribution Assertion Check #43',
    category: 'min-max thresholds',
    targetTable: 'enterprise_data_mart.table_13',
    targetColumn: 'column_attr_3',
    evaluationEngine: 'GREAT_EXPECTATIONS',
    isBlocking: false,
    alertSeverity: 'HIGH_P2',
    autoRemediationAction: 'RETRY_STAGE_WITH_BACKOFF'
  },
  {
    assertionId: 'ASSERT-NRD-044',
    ruleName: 'NumericRangeAndDistribution Assertion Check #44',
    category: 'and standard deviation bounds',
    targetTable: 'enterprise_data_mart.table_14',
    targetColumn: 'column_attr_4',
    evaluationEngine: 'SQL_ASSERTION',
    isBlocking: false,
    alertSeverity: 'HIGH_P2',
    autoRemediationAction: 'QUARANTINE_ROW_TO_DLQ'
  },
  {
    assertionId: 'ASSERT-NRD-045',
    ruleName: 'NumericRangeAndDistribution Assertion Check #45',
    category: 'Z-score anomaly bounds',
    targetTable: 'enterprise_data_mart.table_15',
    targetColumn: 'column_attr_5',
    evaluationEngine: 'GREAT_EXPECTATIONS',
    isBlocking: true,
    alertSeverity: 'CRITICAL_P1',
    autoRemediationAction: 'RETRY_STAGE_WITH_BACKOFF'
  },
  {
    assertionId: 'ASSERT-NRD-046',
    ruleName: 'NumericRangeAndDistribution Assertion Check #46',
    category: 'min-max thresholds',
    targetTable: 'enterprise_data_mart.table_16',
    targetColumn: 'column_attr_6',
    evaluationEngine: 'SQL_ASSERTION',
    isBlocking: false,
    alertSeverity: 'HIGH_P2',
    autoRemediationAction: 'QUARANTINE_ROW_TO_DLQ'
  },
  {
    assertionId: 'ASSERT-NRD-047',
    ruleName: 'NumericRangeAndDistribution Assertion Check #47',
    category: 'and standard deviation bounds',
    targetTable: 'enterprise_data_mart.table_17',
    targetColumn: 'column_attr_7',
    evaluationEngine: 'GREAT_EXPECTATIONS',
    isBlocking: false,
    alertSeverity: 'HIGH_P2',
    autoRemediationAction: 'RETRY_STAGE_WITH_BACKOFF'
  },
  {
    assertionId: 'ASSERT-NRD-048',
    ruleName: 'NumericRangeAndDistribution Assertion Check #48',
    category: 'Z-score anomaly bounds',
    targetTable: 'enterprise_data_mart.table_18',
    targetColumn: 'column_attr_8',
    evaluationEngine: 'SQL_ASSERTION',
    isBlocking: true,
    alertSeverity: 'CRITICAL_P1',
    autoRemediationAction: 'QUARANTINE_ROW_TO_DLQ'
  },
  {
    assertionId: 'ASSERT-NRD-049',
    ruleName: 'NumericRangeAndDistribution Assertion Check #49',
    category: 'min-max thresholds',
    targetTable: 'enterprise_data_mart.table_19',
    targetColumn: 'column_attr_9',
    evaluationEngine: 'GREAT_EXPECTATIONS',
    isBlocking: false,
    alertSeverity: 'HIGH_P2',
    autoRemediationAction: 'RETRY_STAGE_WITH_BACKOFF'
  },
  {
    assertionId: 'ASSERT-NRD-050',
    ruleName: 'NumericRangeAndDistribution Assertion Check #50',
    category: 'and standard deviation bounds',
    targetTable: 'enterprise_data_mart.table_20',
    targetColumn: 'column_attr_10',
    evaluationEngine: 'SQL_ASSERTION',
    isBlocking: false,
    alertSeverity: 'HIGH_P2',
    autoRemediationAction: 'QUARANTINE_ROW_TO_DLQ'
  },
  {
    assertionId: 'ASSERT-NRD-051',
    ruleName: 'NumericRangeAndDistribution Assertion Check #51',
    category: 'Z-score anomaly bounds',
    targetTable: 'enterprise_data_mart.table_21',
    targetColumn: 'column_attr_11',
    evaluationEngine: 'GREAT_EXPECTATIONS',
    isBlocking: true,
    alertSeverity: 'CRITICAL_P1',
    autoRemediationAction: 'RETRY_STAGE_WITH_BACKOFF'
  },
  {
    assertionId: 'ASSERT-NRD-052',
    ruleName: 'NumericRangeAndDistribution Assertion Check #52',
    category: 'min-max thresholds',
    targetTable: 'enterprise_data_mart.table_22',
    targetColumn: 'column_attr_12',
    evaluationEngine: 'SQL_ASSERTION',
    isBlocking: false,
    alertSeverity: 'HIGH_P2',
    autoRemediationAction: 'QUARANTINE_ROW_TO_DLQ'
  },
  {
    assertionId: 'ASSERT-NRD-053',
    ruleName: 'NumericRangeAndDistribution Assertion Check #53',
    category: 'and standard deviation bounds',
    targetTable: 'enterprise_data_mart.table_23',
    targetColumn: 'column_attr_13',
    evaluationEngine: 'GREAT_EXPECTATIONS',
    isBlocking: false,
    alertSeverity: 'HIGH_P2',
    autoRemediationAction: 'RETRY_STAGE_WITH_BACKOFF'
  },
  {
    assertionId: 'ASSERT-NRD-054',
    ruleName: 'NumericRangeAndDistribution Assertion Check #54',
    category: 'Z-score anomaly bounds',
    targetTable: 'enterprise_data_mart.table_24',
    targetColumn: 'column_attr_14',
    evaluationEngine: 'SQL_ASSERTION',
    isBlocking: true,
    alertSeverity: 'CRITICAL_P1',
    autoRemediationAction: 'QUARANTINE_ROW_TO_DLQ'
  },
  {
    assertionId: 'ASSERT-NRD-055',
    ruleName: 'NumericRangeAndDistribution Assertion Check #55',
    category: 'min-max thresholds',
    targetTable: 'enterprise_data_mart.table_25',
    targetColumn: 'column_attr_15',
    evaluationEngine: 'GREAT_EXPECTATIONS',
    isBlocking: false,
    alertSeverity: 'HIGH_P2',
    autoRemediationAction: 'RETRY_STAGE_WITH_BACKOFF'
  },
  {
    assertionId: 'ASSERT-NRD-056',
    ruleName: 'NumericRangeAndDistribution Assertion Check #56',
    category: 'and standard deviation bounds',
    targetTable: 'enterprise_data_mart.table_26',
    targetColumn: 'column_attr_16',
    evaluationEngine: 'SQL_ASSERTION',
    isBlocking: false,
    alertSeverity: 'HIGH_P2',
    autoRemediationAction: 'QUARANTINE_ROW_TO_DLQ'
  },
  {
    assertionId: 'ASSERT-NRD-057',
    ruleName: 'NumericRangeAndDistribution Assertion Check #57',
    category: 'Z-score anomaly bounds',
    targetTable: 'enterprise_data_mart.table_27',
    targetColumn: 'column_attr_17',
    evaluationEngine: 'GREAT_EXPECTATIONS',
    isBlocking: true,
    alertSeverity: 'CRITICAL_P1',
    autoRemediationAction: 'RETRY_STAGE_WITH_BACKOFF'
  },
  {
    assertionId: 'ASSERT-NRD-058',
    ruleName: 'NumericRangeAndDistribution Assertion Check #58',
    category: 'min-max thresholds',
    targetTable: 'enterprise_data_mart.table_28',
    targetColumn: 'column_attr_18',
    evaluationEngine: 'SQL_ASSERTION',
    isBlocking: false,
    alertSeverity: 'HIGH_P2',
    autoRemediationAction: 'QUARANTINE_ROW_TO_DLQ'
  },
  {
    assertionId: 'ASSERT-NRD-059',
    ruleName: 'NumericRangeAndDistribution Assertion Check #59',
    category: 'and standard deviation bounds',
    targetTable: 'enterprise_data_mart.table_29',
    targetColumn: 'column_attr_19',
    evaluationEngine: 'GREAT_EXPECTATIONS',
    isBlocking: false,
    alertSeverity: 'HIGH_P2',
    autoRemediationAction: 'RETRY_STAGE_WITH_BACKOFF'
  },
  {
    assertionId: 'ASSERT-NRD-060',
    ruleName: 'NumericRangeAndDistribution Assertion Check #60',
    category: 'Z-score anomaly bounds',
    targetTable: 'enterprise_data_mart.table_0',
    targetColumn: 'column_attr_0',
    evaluationEngine: 'SQL_ASSERTION',
    isBlocking: true,
    alertSeverity: 'CRITICAL_P1',
    autoRemediationAction: 'QUARANTINE_ROW_TO_DLQ'
  },
  {
    assertionId: 'ASSERT-NRD-061',
    ruleName: 'NumericRangeAndDistribution Assertion Check #61',
    category: 'min-max thresholds',
    targetTable: 'enterprise_data_mart.table_1',
    targetColumn: 'column_attr_1',
    evaluationEngine: 'GREAT_EXPECTATIONS',
    isBlocking: false,
    alertSeverity: 'HIGH_P2',
    autoRemediationAction: 'RETRY_STAGE_WITH_BACKOFF'
  },
  {
    assertionId: 'ASSERT-NRD-062',
    ruleName: 'NumericRangeAndDistribution Assertion Check #62',
    category: 'and standard deviation bounds',
    targetTable: 'enterprise_data_mart.table_2',
    targetColumn: 'column_attr_2',
    evaluationEngine: 'SQL_ASSERTION',
    isBlocking: false,
    alertSeverity: 'HIGH_P2',
    autoRemediationAction: 'QUARANTINE_ROW_TO_DLQ'
  },
  {
    assertionId: 'ASSERT-NRD-063',
    ruleName: 'NumericRangeAndDistribution Assertion Check #63',
    category: 'Z-score anomaly bounds',
    targetTable: 'enterprise_data_mart.table_3',
    targetColumn: 'column_attr_3',
    evaluationEngine: 'GREAT_EXPECTATIONS',
    isBlocking: true,
    alertSeverity: 'CRITICAL_P1',
    autoRemediationAction: 'RETRY_STAGE_WITH_BACKOFF'
  },
  {
    assertionId: 'ASSERT-NRD-064',
    ruleName: 'NumericRangeAndDistribution Assertion Check #64',
    category: 'min-max thresholds',
    targetTable: 'enterprise_data_mart.table_4',
    targetColumn: 'column_attr_4',
    evaluationEngine: 'SQL_ASSERTION',
    isBlocking: false,
    alertSeverity: 'HIGH_P2',
    autoRemediationAction: 'QUARANTINE_ROW_TO_DLQ'
  },
  {
    assertionId: 'ASSERT-NRD-065',
    ruleName: 'NumericRangeAndDistribution Assertion Check #65',
    category: 'and standard deviation bounds',
    targetTable: 'enterprise_data_mart.table_5',
    targetColumn: 'column_attr_5',
    evaluationEngine: 'GREAT_EXPECTATIONS',
    isBlocking: false,
    alertSeverity: 'HIGH_P2',
    autoRemediationAction: 'RETRY_STAGE_WITH_BACKOFF'
  },
  {
    assertionId: 'ASSERT-NRD-066',
    ruleName: 'NumericRangeAndDistribution Assertion Check #66',
    category: 'Z-score anomaly bounds',
    targetTable: 'enterprise_data_mart.table_6',
    targetColumn: 'column_attr_6',
    evaluationEngine: 'SQL_ASSERTION',
    isBlocking: true,
    alertSeverity: 'CRITICAL_P1',
    autoRemediationAction: 'QUARANTINE_ROW_TO_DLQ'
  },
  {
    assertionId: 'ASSERT-NRD-067',
    ruleName: 'NumericRangeAndDistribution Assertion Check #67',
    category: 'min-max thresholds',
    targetTable: 'enterprise_data_mart.table_7',
    targetColumn: 'column_attr_7',
    evaluationEngine: 'GREAT_EXPECTATIONS',
    isBlocking: false,
    alertSeverity: 'HIGH_P2',
    autoRemediationAction: 'RETRY_STAGE_WITH_BACKOFF'
  },
  {
    assertionId: 'ASSERT-NRD-068',
    ruleName: 'NumericRangeAndDistribution Assertion Check #68',
    category: 'and standard deviation bounds',
    targetTable: 'enterprise_data_mart.table_8',
    targetColumn: 'column_attr_8',
    evaluationEngine: 'SQL_ASSERTION',
    isBlocking: false,
    alertSeverity: 'HIGH_P2',
    autoRemediationAction: 'QUARANTINE_ROW_TO_DLQ'
  },
  {
    assertionId: 'ASSERT-NRD-069',
    ruleName: 'NumericRangeAndDistribution Assertion Check #69',
    category: 'Z-score anomaly bounds',
    targetTable: 'enterprise_data_mart.table_9',
    targetColumn: 'column_attr_9',
    evaluationEngine: 'GREAT_EXPECTATIONS',
    isBlocking: true,
    alertSeverity: 'CRITICAL_P1',
    autoRemediationAction: 'RETRY_STAGE_WITH_BACKOFF'
  },
  {
    assertionId: 'ASSERT-NRD-070',
    ruleName: 'NumericRangeAndDistribution Assertion Check #70',
    category: 'min-max thresholds',
    targetTable: 'enterprise_data_mart.table_10',
    targetColumn: 'column_attr_10',
    evaluationEngine: 'SQL_ASSERTION',
    isBlocking: false,
    alertSeverity: 'HIGH_P2',
    autoRemediationAction: 'QUARANTINE_ROW_TO_DLQ'
  },
  {
    assertionId: 'ASSERT-NRD-071',
    ruleName: 'NumericRangeAndDistribution Assertion Check #71',
    category: 'and standard deviation bounds',
    targetTable: 'enterprise_data_mart.table_11',
    targetColumn: 'column_attr_11',
    evaluationEngine: 'GREAT_EXPECTATIONS',
    isBlocking: false,
    alertSeverity: 'HIGH_P2',
    autoRemediationAction: 'RETRY_STAGE_WITH_BACKOFF'
  },
  {
    assertionId: 'ASSERT-NRD-072',
    ruleName: 'NumericRangeAndDistribution Assertion Check #72',
    category: 'Z-score anomaly bounds',
    targetTable: 'enterprise_data_mart.table_12',
    targetColumn: 'column_attr_12',
    evaluationEngine: 'SQL_ASSERTION',
    isBlocking: true,
    alertSeverity: 'CRITICAL_P1',
    autoRemediationAction: 'QUARANTINE_ROW_TO_DLQ'
  },
  {
    assertionId: 'ASSERT-NRD-073',
    ruleName: 'NumericRangeAndDistribution Assertion Check #73',
    category: 'min-max thresholds',
    targetTable: 'enterprise_data_mart.table_13',
    targetColumn: 'column_attr_13',
    evaluationEngine: 'GREAT_EXPECTATIONS',
    isBlocking: false,
    alertSeverity: 'HIGH_P2',
    autoRemediationAction: 'RETRY_STAGE_WITH_BACKOFF'
  },
  {
    assertionId: 'ASSERT-NRD-074',
    ruleName: 'NumericRangeAndDistribution Assertion Check #74',
    category: 'and standard deviation bounds',
    targetTable: 'enterprise_data_mart.table_14',
    targetColumn: 'column_attr_14',
    evaluationEngine: 'SQL_ASSERTION',
    isBlocking: false,
    alertSeverity: 'HIGH_P2',
    autoRemediationAction: 'QUARANTINE_ROW_TO_DLQ'
  },
  {
    assertionId: 'ASSERT-NRD-075',
    ruleName: 'NumericRangeAndDistribution Assertion Check #75',
    category: 'Z-score anomaly bounds',
    targetTable: 'enterprise_data_mart.table_15',
    targetColumn: 'column_attr_15',
    evaluationEngine: 'GREAT_EXPECTATIONS',
    isBlocking: true,
    alertSeverity: 'CRITICAL_P1',
    autoRemediationAction: 'RETRY_STAGE_WITH_BACKOFF'
  },
  {
    assertionId: 'ASSERT-NRD-076',
    ruleName: 'NumericRangeAndDistribution Assertion Check #76',
    category: 'min-max thresholds',
    targetTable: 'enterprise_data_mart.table_16',
    targetColumn: 'column_attr_16',
    evaluationEngine: 'SQL_ASSERTION',
    isBlocking: false,
    alertSeverity: 'HIGH_P2',
    autoRemediationAction: 'QUARANTINE_ROW_TO_DLQ'
  },
  {
    assertionId: 'ASSERT-NRD-077',
    ruleName: 'NumericRangeAndDistribution Assertion Check #77',
    category: 'and standard deviation bounds',
    targetTable: 'enterprise_data_mart.table_17',
    targetColumn: 'column_attr_17',
    evaluationEngine: 'GREAT_EXPECTATIONS',
    isBlocking: false,
    alertSeverity: 'HIGH_P2',
    autoRemediationAction: 'RETRY_STAGE_WITH_BACKOFF'
  },
  {
    assertionId: 'ASSERT-NRD-078',
    ruleName: 'NumericRangeAndDistribution Assertion Check #78',
    category: 'Z-score anomaly bounds',
    targetTable: 'enterprise_data_mart.table_18',
    targetColumn: 'column_attr_18',
    evaluationEngine: 'SQL_ASSERTION',
    isBlocking: true,
    alertSeverity: 'CRITICAL_P1',
    autoRemediationAction: 'QUARANTINE_ROW_TO_DLQ'
  },
  {
    assertionId: 'ASSERT-NRD-079',
    ruleName: 'NumericRangeAndDistribution Assertion Check #79',
    category: 'min-max thresholds',
    targetTable: 'enterprise_data_mart.table_19',
    targetColumn: 'column_attr_19',
    evaluationEngine: 'GREAT_EXPECTATIONS',
    isBlocking: false,
    alertSeverity: 'HIGH_P2',
    autoRemediationAction: 'RETRY_STAGE_WITH_BACKOFF'
  },
  {
    assertionId: 'ASSERT-NRD-080',
    ruleName: 'NumericRangeAndDistribution Assertion Check #80',
    category: 'and standard deviation bounds',
    targetTable: 'enterprise_data_mart.table_20',
    targetColumn: 'column_attr_0',
    evaluationEngine: 'SQL_ASSERTION',
    isBlocking: false,
    alertSeverity: 'HIGH_P2',
    autoRemediationAction: 'QUARANTINE_ROW_TO_DLQ'
  },
  {
    assertionId: 'ASSERT-NRD-081',
    ruleName: 'NumericRangeAndDistribution Assertion Check #81',
    category: 'Z-score anomaly bounds',
    targetTable: 'enterprise_data_mart.table_21',
    targetColumn: 'column_attr_1',
    evaluationEngine: 'GREAT_EXPECTATIONS',
    isBlocking: true,
    alertSeverity: 'CRITICAL_P1',
    autoRemediationAction: 'RETRY_STAGE_WITH_BACKOFF'
  },
  {
    assertionId: 'ASSERT-NRD-082',
    ruleName: 'NumericRangeAndDistribution Assertion Check #82',
    category: 'min-max thresholds',
    targetTable: 'enterprise_data_mart.table_22',
    targetColumn: 'column_attr_2',
    evaluationEngine: 'SQL_ASSERTION',
    isBlocking: false,
    alertSeverity: 'HIGH_P2',
    autoRemediationAction: 'QUARANTINE_ROW_TO_DLQ'
  },
  {
    assertionId: 'ASSERT-NRD-083',
    ruleName: 'NumericRangeAndDistribution Assertion Check #83',
    category: 'and standard deviation bounds',
    targetTable: 'enterprise_data_mart.table_23',
    targetColumn: 'column_attr_3',
    evaluationEngine: 'GREAT_EXPECTATIONS',
    isBlocking: false,
    alertSeverity: 'HIGH_P2',
    autoRemediationAction: 'RETRY_STAGE_WITH_BACKOFF'
  },
  {
    assertionId: 'ASSERT-NRD-084',
    ruleName: 'NumericRangeAndDistribution Assertion Check #84',
    category: 'Z-score anomaly bounds',
    targetTable: 'enterprise_data_mart.table_24',
    targetColumn: 'column_attr_4',
    evaluationEngine: 'SQL_ASSERTION',
    isBlocking: true,
    alertSeverity: 'CRITICAL_P1',
    autoRemediationAction: 'QUARANTINE_ROW_TO_DLQ'
  },
  {
    assertionId: 'ASSERT-NRD-085',
    ruleName: 'NumericRangeAndDistribution Assertion Check #85',
    category: 'min-max thresholds',
    targetTable: 'enterprise_data_mart.table_25',
    targetColumn: 'column_attr_5',
    evaluationEngine: 'GREAT_EXPECTATIONS',
    isBlocking: false,
    alertSeverity: 'HIGH_P2',
    autoRemediationAction: 'RETRY_STAGE_WITH_BACKOFF'
  },
  {
    assertionId: 'ASSERT-NRD-086',
    ruleName: 'NumericRangeAndDistribution Assertion Check #86',
    category: 'and standard deviation bounds',
    targetTable: 'enterprise_data_mart.table_26',
    targetColumn: 'column_attr_6',
    evaluationEngine: 'SQL_ASSERTION',
    isBlocking: false,
    alertSeverity: 'HIGH_P2',
    autoRemediationAction: 'QUARANTINE_ROW_TO_DLQ'
  },
  {
    assertionId: 'ASSERT-NRD-087',
    ruleName: 'NumericRangeAndDistribution Assertion Check #87',
    category: 'Z-score anomaly bounds',
    targetTable: 'enterprise_data_mart.table_27',
    targetColumn: 'column_attr_7',
    evaluationEngine: 'GREAT_EXPECTATIONS',
    isBlocking: true,
    alertSeverity: 'CRITICAL_P1',
    autoRemediationAction: 'RETRY_STAGE_WITH_BACKOFF'
  },
  {
    assertionId: 'ASSERT-NRD-088',
    ruleName: 'NumericRangeAndDistribution Assertion Check #88',
    category: 'min-max thresholds',
    targetTable: 'enterprise_data_mart.table_28',
    targetColumn: 'column_attr_8',
    evaluationEngine: 'SQL_ASSERTION',
    isBlocking: false,
    alertSeverity: 'HIGH_P2',
    autoRemediationAction: 'QUARANTINE_ROW_TO_DLQ'
  },
  {
    assertionId: 'ASSERT-NRD-089',
    ruleName: 'NumericRangeAndDistribution Assertion Check #89',
    category: 'and standard deviation bounds',
    targetTable: 'enterprise_data_mart.table_29',
    targetColumn: 'column_attr_9',
    evaluationEngine: 'GREAT_EXPECTATIONS',
    isBlocking: false,
    alertSeverity: 'HIGH_P2',
    autoRemediationAction: 'RETRY_STAGE_WITH_BACKOFF'
  },
  {
    assertionId: 'ASSERT-NRD-090',
    ruleName: 'NumericRangeAndDistribution Assertion Check #90',
    category: 'Z-score anomaly bounds',
    targetTable: 'enterprise_data_mart.table_0',
    targetColumn: 'column_attr_10',
    evaluationEngine: 'SQL_ASSERTION',
    isBlocking: true,
    alertSeverity: 'CRITICAL_P1',
    autoRemediationAction: 'QUARANTINE_ROW_TO_DLQ'
  },
  {
    assertionId: 'ASSERT-NRD-091',
    ruleName: 'NumericRangeAndDistribution Assertion Check #91',
    category: 'min-max thresholds',
    targetTable: 'enterprise_data_mart.table_1',
    targetColumn: 'column_attr_11',
    evaluationEngine: 'GREAT_EXPECTATIONS',
    isBlocking: false,
    alertSeverity: 'HIGH_P2',
    autoRemediationAction: 'RETRY_STAGE_WITH_BACKOFF'
  },
  {
    assertionId: 'ASSERT-NRD-092',
    ruleName: 'NumericRangeAndDistribution Assertion Check #92',
    category: 'and standard deviation bounds',
    targetTable: 'enterprise_data_mart.table_2',
    targetColumn: 'column_attr_12',
    evaluationEngine: 'SQL_ASSERTION',
    isBlocking: false,
    alertSeverity: 'HIGH_P2',
    autoRemediationAction: 'QUARANTINE_ROW_TO_DLQ'
  },
  {
    assertionId: 'ASSERT-NRD-093',
    ruleName: 'NumericRangeAndDistribution Assertion Check #93',
    category: 'Z-score anomaly bounds',
    targetTable: 'enterprise_data_mart.table_3',
    targetColumn: 'column_attr_13',
    evaluationEngine: 'GREAT_EXPECTATIONS',
    isBlocking: true,
    alertSeverity: 'CRITICAL_P1',
    autoRemediationAction: 'RETRY_STAGE_WITH_BACKOFF'
  },
  {
    assertionId: 'ASSERT-NRD-094',
    ruleName: 'NumericRangeAndDistribution Assertion Check #94',
    category: 'min-max thresholds',
    targetTable: 'enterprise_data_mart.table_4',
    targetColumn: 'column_attr_14',
    evaluationEngine: 'SQL_ASSERTION',
    isBlocking: false,
    alertSeverity: 'HIGH_P2',
    autoRemediationAction: 'QUARANTINE_ROW_TO_DLQ'
  },
  {
    assertionId: 'ASSERT-NRD-095',
    ruleName: 'NumericRangeAndDistribution Assertion Check #95',
    category: 'and standard deviation bounds',
    targetTable: 'enterprise_data_mart.table_5',
    targetColumn: 'column_attr_15',
    evaluationEngine: 'GREAT_EXPECTATIONS',
    isBlocking: false,
    alertSeverity: 'HIGH_P2',
    autoRemediationAction: 'RETRY_STAGE_WITH_BACKOFF'
  },
  {
    assertionId: 'ASSERT-NRD-096',
    ruleName: 'NumericRangeAndDistribution Assertion Check #96',
    category: 'Z-score anomaly bounds',
    targetTable: 'enterprise_data_mart.table_6',
    targetColumn: 'column_attr_16',
    evaluationEngine: 'SQL_ASSERTION',
    isBlocking: true,
    alertSeverity: 'CRITICAL_P1',
    autoRemediationAction: 'QUARANTINE_ROW_TO_DLQ'
  },
  {
    assertionId: 'ASSERT-NRD-097',
    ruleName: 'NumericRangeAndDistribution Assertion Check #97',
    category: 'min-max thresholds',
    targetTable: 'enterprise_data_mart.table_7',
    targetColumn: 'column_attr_17',
    evaluationEngine: 'GREAT_EXPECTATIONS',
    isBlocking: false,
    alertSeverity: 'HIGH_P2',
    autoRemediationAction: 'RETRY_STAGE_WITH_BACKOFF'
  },
  {
    assertionId: 'ASSERT-NRD-098',
    ruleName: 'NumericRangeAndDistribution Assertion Check #98',
    category: 'and standard deviation bounds',
    targetTable: 'enterprise_data_mart.table_8',
    targetColumn: 'column_attr_18',
    evaluationEngine: 'SQL_ASSERTION',
    isBlocking: false,
    alertSeverity: 'HIGH_P2',
    autoRemediationAction: 'QUARANTINE_ROW_TO_DLQ'
  },
  {
    assertionId: 'ASSERT-NRD-099',
    ruleName: 'NumericRangeAndDistribution Assertion Check #99',
    category: 'Z-score anomaly bounds',
    targetTable: 'enterprise_data_mart.table_9',
    targetColumn: 'column_attr_19',
    evaluationEngine: 'GREAT_EXPECTATIONS',
    isBlocking: true,
    alertSeverity: 'CRITICAL_P1',
    autoRemediationAction: 'RETRY_STAGE_WITH_BACKOFF'
  },
  {
    assertionId: 'ASSERT-NRD-100',
    ruleName: 'NumericRangeAndDistribution Assertion Check #100',
    category: 'min-max thresholds',
    targetTable: 'enterprise_data_mart.table_10',
    targetColumn: 'column_attr_0',
    evaluationEngine: 'SQL_ASSERTION',
    isBlocking: false,
    alertSeverity: 'HIGH_P2',
    autoRemediationAction: 'QUARANTINE_ROW_TO_DLQ'
  },
  {
    assertionId: 'ASSERT-NRD-101',
    ruleName: 'NumericRangeAndDistribution Assertion Check #101',
    category: 'and standard deviation bounds',
    targetTable: 'enterprise_data_mart.table_11',
    targetColumn: 'column_attr_1',
    evaluationEngine: 'GREAT_EXPECTATIONS',
    isBlocking: false,
    alertSeverity: 'HIGH_P2',
    autoRemediationAction: 'RETRY_STAGE_WITH_BACKOFF'
  },
  {
    assertionId: 'ASSERT-NRD-102',
    ruleName: 'NumericRangeAndDistribution Assertion Check #102',
    category: 'Z-score anomaly bounds',
    targetTable: 'enterprise_data_mart.table_12',
    targetColumn: 'column_attr_2',
    evaluationEngine: 'SQL_ASSERTION',
    isBlocking: true,
    alertSeverity: 'CRITICAL_P1',
    autoRemediationAction: 'QUARANTINE_ROW_TO_DLQ'
  },
  {
    assertionId: 'ASSERT-NRD-103',
    ruleName: 'NumericRangeAndDistribution Assertion Check #103',
    category: 'min-max thresholds',
    targetTable: 'enterprise_data_mart.table_13',
    targetColumn: 'column_attr_3',
    evaluationEngine: 'GREAT_EXPECTATIONS',
    isBlocking: false,
    alertSeverity: 'HIGH_P2',
    autoRemediationAction: 'RETRY_STAGE_WITH_BACKOFF'
  },
  {
    assertionId: 'ASSERT-NRD-104',
    ruleName: 'NumericRangeAndDistribution Assertion Check #104',
    category: 'and standard deviation bounds',
    targetTable: 'enterprise_data_mart.table_14',
    targetColumn: 'column_attr_4',
    evaluationEngine: 'SQL_ASSERTION',
    isBlocking: false,
    alertSeverity: 'HIGH_P2',
    autoRemediationAction: 'QUARANTINE_ROW_TO_DLQ'
  },
  {
    assertionId: 'ASSERT-NRD-105',
    ruleName: 'NumericRangeAndDistribution Assertion Check #105',
    category: 'Z-score anomaly bounds',
    targetTable: 'enterprise_data_mart.table_15',
    targetColumn: 'column_attr_5',
    evaluationEngine: 'GREAT_EXPECTATIONS',
    isBlocking: true,
    alertSeverity: 'CRITICAL_P1',
    autoRemediationAction: 'RETRY_STAGE_WITH_BACKOFF'
  },
  {
    assertionId: 'ASSERT-NRD-106',
    ruleName: 'NumericRangeAndDistribution Assertion Check #106',
    category: 'min-max thresholds',
    targetTable: 'enterprise_data_mart.table_16',
    targetColumn: 'column_attr_6',
    evaluationEngine: 'SQL_ASSERTION',
    isBlocking: false,
    alertSeverity: 'HIGH_P2',
    autoRemediationAction: 'QUARANTINE_ROW_TO_DLQ'
  },
  {
    assertionId: 'ASSERT-NRD-107',
    ruleName: 'NumericRangeAndDistribution Assertion Check #107',
    category: 'and standard deviation bounds',
    targetTable: 'enterprise_data_mart.table_17',
    targetColumn: 'column_attr_7',
    evaluationEngine: 'GREAT_EXPECTATIONS',
    isBlocking: false,
    alertSeverity: 'HIGH_P2',
    autoRemediationAction: 'RETRY_STAGE_WITH_BACKOFF'
  },
  {
    assertionId: 'ASSERT-NRD-108',
    ruleName: 'NumericRangeAndDistribution Assertion Check #108',
    category: 'Z-score anomaly bounds',
    targetTable: 'enterprise_data_mart.table_18',
    targetColumn: 'column_attr_8',
    evaluationEngine: 'SQL_ASSERTION',
    isBlocking: true,
    alertSeverity: 'CRITICAL_P1',
    autoRemediationAction: 'QUARANTINE_ROW_TO_DLQ'
  },
  {
    assertionId: 'ASSERT-NRD-109',
    ruleName: 'NumericRangeAndDistribution Assertion Check #109',
    category: 'min-max thresholds',
    targetTable: 'enterprise_data_mart.table_19',
    targetColumn: 'column_attr_9',
    evaluationEngine: 'GREAT_EXPECTATIONS',
    isBlocking: false,
    alertSeverity: 'HIGH_P2',
    autoRemediationAction: 'RETRY_STAGE_WITH_BACKOFF'
  },
  {
    assertionId: 'ASSERT-NRD-110',
    ruleName: 'NumericRangeAndDistribution Assertion Check #110',
    category: 'and standard deviation bounds',
    targetTable: 'enterprise_data_mart.table_20',
    targetColumn: 'column_attr_10',
    evaluationEngine: 'SQL_ASSERTION',
    isBlocking: false,
    alertSeverity: 'HIGH_P2',
    autoRemediationAction: 'QUARANTINE_ROW_TO_DLQ'
  },
  {
    assertionId: 'ASSERT-NRD-111',
    ruleName: 'NumericRangeAndDistribution Assertion Check #111',
    category: 'Z-score anomaly bounds',
    targetTable: 'enterprise_data_mart.table_21',
    targetColumn: 'column_attr_11',
    evaluationEngine: 'GREAT_EXPECTATIONS',
    isBlocking: true,
    alertSeverity: 'CRITICAL_P1',
    autoRemediationAction: 'RETRY_STAGE_WITH_BACKOFF'
  },
  {
    assertionId: 'ASSERT-NRD-112',
    ruleName: 'NumericRangeAndDistribution Assertion Check #112',
    category: 'min-max thresholds',
    targetTable: 'enterprise_data_mart.table_22',
    targetColumn: 'column_attr_12',
    evaluationEngine: 'SQL_ASSERTION',
    isBlocking: false,
    alertSeverity: 'HIGH_P2',
    autoRemediationAction: 'QUARANTINE_ROW_TO_DLQ'
  },
  {
    assertionId: 'ASSERT-NRD-113',
    ruleName: 'NumericRangeAndDistribution Assertion Check #113',
    category: 'and standard deviation bounds',
    targetTable: 'enterprise_data_mart.table_23',
    targetColumn: 'column_attr_13',
    evaluationEngine: 'GREAT_EXPECTATIONS',
    isBlocking: false,
    alertSeverity: 'HIGH_P2',
    autoRemediationAction: 'RETRY_STAGE_WITH_BACKOFF'
  },
  {
    assertionId: 'ASSERT-NRD-114',
    ruleName: 'NumericRangeAndDistribution Assertion Check #114',
    category: 'Z-score anomaly bounds',
    targetTable: 'enterprise_data_mart.table_24',
    targetColumn: 'column_attr_14',
    evaluationEngine: 'SQL_ASSERTION',
    isBlocking: true,
    alertSeverity: 'CRITICAL_P1',
    autoRemediationAction: 'QUARANTINE_ROW_TO_DLQ'
  },
  {
    assertionId: 'ASSERT-NRD-115',
    ruleName: 'NumericRangeAndDistribution Assertion Check #115',
    category: 'min-max thresholds',
    targetTable: 'enterprise_data_mart.table_25',
    targetColumn: 'column_attr_15',
    evaluationEngine: 'GREAT_EXPECTATIONS',
    isBlocking: false,
    alertSeverity: 'HIGH_P2',
    autoRemediationAction: 'RETRY_STAGE_WITH_BACKOFF'
  },
  {
    assertionId: 'ASSERT-NRD-116',
    ruleName: 'NumericRangeAndDistribution Assertion Check #116',
    category: 'and standard deviation bounds',
    targetTable: 'enterprise_data_mart.table_26',
    targetColumn: 'column_attr_16',
    evaluationEngine: 'SQL_ASSERTION',
    isBlocking: false,
    alertSeverity: 'HIGH_P2',
    autoRemediationAction: 'QUARANTINE_ROW_TO_DLQ'
  },
  {
    assertionId: 'ASSERT-NRD-117',
    ruleName: 'NumericRangeAndDistribution Assertion Check #117',
    category: 'Z-score anomaly bounds',
    targetTable: 'enterprise_data_mart.table_27',
    targetColumn: 'column_attr_17',
    evaluationEngine: 'GREAT_EXPECTATIONS',
    isBlocking: true,
    alertSeverity: 'CRITICAL_P1',
    autoRemediationAction: 'RETRY_STAGE_WITH_BACKOFF'
  },
  {
    assertionId: 'ASSERT-NRD-118',
    ruleName: 'NumericRangeAndDistribution Assertion Check #118',
    category: 'min-max thresholds',
    targetTable: 'enterprise_data_mart.table_28',
    targetColumn: 'column_attr_18',
    evaluationEngine: 'SQL_ASSERTION',
    isBlocking: false,
    alertSeverity: 'HIGH_P2',
    autoRemediationAction: 'QUARANTINE_ROW_TO_DLQ'
  },
  {
    assertionId: 'ASSERT-NRD-119',
    ruleName: 'NumericRangeAndDistribution Assertion Check #119',
    category: 'and standard deviation bounds',
    targetTable: 'enterprise_data_mart.table_29',
    targetColumn: 'column_attr_19',
    evaluationEngine: 'GREAT_EXPECTATIONS',
    isBlocking: false,
    alertSeverity: 'HIGH_P2',
    autoRemediationAction: 'RETRY_STAGE_WITH_BACKOFF'
  },
  {
    assertionId: 'ASSERT-NRD-120',
    ruleName: 'NumericRangeAndDistribution Assertion Check #120',
    category: 'Z-score anomaly bounds',
    targetTable: 'enterprise_data_mart.table_0',
    targetColumn: 'column_attr_0',
    evaluationEngine: 'SQL_ASSERTION',
    isBlocking: true,
    alertSeverity: 'CRITICAL_P1',
    autoRemediationAction: 'QUARANTINE_ROW_TO_DLQ'
  },
  {
    assertionId: 'ASSERT-NRD-121',
    ruleName: 'NumericRangeAndDistribution Assertion Check #121',
    category: 'min-max thresholds',
    targetTable: 'enterprise_data_mart.table_1',
    targetColumn: 'column_attr_1',
    evaluationEngine: 'GREAT_EXPECTATIONS',
    isBlocking: false,
    alertSeverity: 'HIGH_P2',
    autoRemediationAction: 'RETRY_STAGE_WITH_BACKOFF'
  },
  {
    assertionId: 'ASSERT-NRD-122',
    ruleName: 'NumericRangeAndDistribution Assertion Check #122',
    category: 'and standard deviation bounds',
    targetTable: 'enterprise_data_mart.table_2',
    targetColumn: 'column_attr_2',
    evaluationEngine: 'SQL_ASSERTION',
    isBlocking: false,
    alertSeverity: 'HIGH_P2',
    autoRemediationAction: 'QUARANTINE_ROW_TO_DLQ'
  },
  {
    assertionId: 'ASSERT-NRD-123',
    ruleName: 'NumericRangeAndDistribution Assertion Check #123',
    category: 'Z-score anomaly bounds',
    targetTable: 'enterprise_data_mart.table_3',
    targetColumn: 'column_attr_3',
    evaluationEngine: 'GREAT_EXPECTATIONS',
    isBlocking: true,
    alertSeverity: 'CRITICAL_P1',
    autoRemediationAction: 'RETRY_STAGE_WITH_BACKOFF'
  },
  {
    assertionId: 'ASSERT-NRD-124',
    ruleName: 'NumericRangeAndDistribution Assertion Check #124',
    category: 'min-max thresholds',
    targetTable: 'enterprise_data_mart.table_4',
    targetColumn: 'column_attr_4',
    evaluationEngine: 'SQL_ASSERTION',
    isBlocking: false,
    alertSeverity: 'HIGH_P2',
    autoRemediationAction: 'QUARANTINE_ROW_TO_DLQ'
  },
  {
    assertionId: 'ASSERT-NRD-125',
    ruleName: 'NumericRangeAndDistribution Assertion Check #125',
    category: 'and standard deviation bounds',
    targetTable: 'enterprise_data_mart.table_5',
    targetColumn: 'column_attr_5',
    evaluationEngine: 'GREAT_EXPECTATIONS',
    isBlocking: false,
    alertSeverity: 'HIGH_P2',
    autoRemediationAction: 'RETRY_STAGE_WITH_BACKOFF'
  },
  {
    assertionId: 'ASSERT-NRD-126',
    ruleName: 'NumericRangeAndDistribution Assertion Check #126',
    category: 'Z-score anomaly bounds',
    targetTable: 'enterprise_data_mart.table_6',
    targetColumn: 'column_attr_6',
    evaluationEngine: 'SQL_ASSERTION',
    isBlocking: true,
    alertSeverity: 'CRITICAL_P1',
    autoRemediationAction: 'QUARANTINE_ROW_TO_DLQ'
  },
  {
    assertionId: 'ASSERT-NRD-127',
    ruleName: 'NumericRangeAndDistribution Assertion Check #127',
    category: 'min-max thresholds',
    targetTable: 'enterprise_data_mart.table_7',
    targetColumn: 'column_attr_7',
    evaluationEngine: 'GREAT_EXPECTATIONS',
    isBlocking: false,
    alertSeverity: 'HIGH_P2',
    autoRemediationAction: 'RETRY_STAGE_WITH_BACKOFF'
  },
  {
    assertionId: 'ASSERT-NRD-128',
    ruleName: 'NumericRangeAndDistribution Assertion Check #128',
    category: 'and standard deviation bounds',
    targetTable: 'enterprise_data_mart.table_8',
    targetColumn: 'column_attr_8',
    evaluationEngine: 'SQL_ASSERTION',
    isBlocking: false,
    alertSeverity: 'HIGH_P2',
    autoRemediationAction: 'QUARANTINE_ROW_TO_DLQ'
  },
  {
    assertionId: 'ASSERT-NRD-129',
    ruleName: 'NumericRangeAndDistribution Assertion Check #129',
    category: 'Z-score anomaly bounds',
    targetTable: 'enterprise_data_mart.table_9',
    targetColumn: 'column_attr_9',
    evaluationEngine: 'GREAT_EXPECTATIONS',
    isBlocking: true,
    alertSeverity: 'CRITICAL_P1',
    autoRemediationAction: 'RETRY_STAGE_WITH_BACKOFF'
  },
  {
    assertionId: 'ASSERT-NRD-130',
    ruleName: 'NumericRangeAndDistribution Assertion Check #130',
    category: 'min-max thresholds',
    targetTable: 'enterprise_data_mart.table_10',
    targetColumn: 'column_attr_10',
    evaluationEngine: 'SQL_ASSERTION',
    isBlocking: false,
    alertSeverity: 'HIGH_P2',
    autoRemediationAction: 'QUARANTINE_ROW_TO_DLQ'
  },
  {
    assertionId: 'ASSERT-NRD-131',
    ruleName: 'NumericRangeAndDistribution Assertion Check #131',
    category: 'and standard deviation bounds',
    targetTable: 'enterprise_data_mart.table_11',
    targetColumn: 'column_attr_11',
    evaluationEngine: 'GREAT_EXPECTATIONS',
    isBlocking: false,
    alertSeverity: 'HIGH_P2',
    autoRemediationAction: 'RETRY_STAGE_WITH_BACKOFF'
  },
  {
    assertionId: 'ASSERT-NRD-132',
    ruleName: 'NumericRangeAndDistribution Assertion Check #132',
    category: 'Z-score anomaly bounds',
    targetTable: 'enterprise_data_mart.table_12',
    targetColumn: 'column_attr_12',
    evaluationEngine: 'SQL_ASSERTION',
    isBlocking: true,
    alertSeverity: 'CRITICAL_P1',
    autoRemediationAction: 'QUARANTINE_ROW_TO_DLQ'
  },
  {
    assertionId: 'ASSERT-NRD-133',
    ruleName: 'NumericRangeAndDistribution Assertion Check #133',
    category: 'min-max thresholds',
    targetTable: 'enterprise_data_mart.table_13',
    targetColumn: 'column_attr_13',
    evaluationEngine: 'GREAT_EXPECTATIONS',
    isBlocking: false,
    alertSeverity: 'HIGH_P2',
    autoRemediationAction: 'RETRY_STAGE_WITH_BACKOFF'
  },
  {
    assertionId: 'ASSERT-NRD-134',
    ruleName: 'NumericRangeAndDistribution Assertion Check #134',
    category: 'and standard deviation bounds',
    targetTable: 'enterprise_data_mart.table_14',
    targetColumn: 'column_attr_14',
    evaluationEngine: 'SQL_ASSERTION',
    isBlocking: false,
    alertSeverity: 'HIGH_P2',
    autoRemediationAction: 'QUARANTINE_ROW_TO_DLQ'
  },
  {
    assertionId: 'ASSERT-NRD-135',
    ruleName: 'NumericRangeAndDistribution Assertion Check #135',
    category: 'Z-score anomaly bounds',
    targetTable: 'enterprise_data_mart.table_15',
    targetColumn: 'column_attr_15',
    evaluationEngine: 'GREAT_EXPECTATIONS',
    isBlocking: true,
    alertSeverity: 'CRITICAL_P1',
    autoRemediationAction: 'RETRY_STAGE_WITH_BACKOFF'
  },
  {
    assertionId: 'ASSERT-NRD-136',
    ruleName: 'NumericRangeAndDistribution Assertion Check #136',
    category: 'min-max thresholds',
    targetTable: 'enterprise_data_mart.table_16',
    targetColumn: 'column_attr_16',
    evaluationEngine: 'SQL_ASSERTION',
    isBlocking: false,
    alertSeverity: 'HIGH_P2',
    autoRemediationAction: 'QUARANTINE_ROW_TO_DLQ'
  },
  {
    assertionId: 'ASSERT-NRD-137',
    ruleName: 'NumericRangeAndDistribution Assertion Check #137',
    category: 'and standard deviation bounds',
    targetTable: 'enterprise_data_mart.table_17',
    targetColumn: 'column_attr_17',
    evaluationEngine: 'GREAT_EXPECTATIONS',
    isBlocking: false,
    alertSeverity: 'HIGH_P2',
    autoRemediationAction: 'RETRY_STAGE_WITH_BACKOFF'
  },
  {
    assertionId: 'ASSERT-NRD-138',
    ruleName: 'NumericRangeAndDistribution Assertion Check #138',
    category: 'Z-score anomaly bounds',
    targetTable: 'enterprise_data_mart.table_18',
    targetColumn: 'column_attr_18',
    evaluationEngine: 'SQL_ASSERTION',
    isBlocking: true,
    alertSeverity: 'CRITICAL_P1',
    autoRemediationAction: 'QUARANTINE_ROW_TO_DLQ'
  },
  {
    assertionId: 'ASSERT-NRD-139',
    ruleName: 'NumericRangeAndDistribution Assertion Check #139',
    category: 'min-max thresholds',
    targetTable: 'enterprise_data_mart.table_19',
    targetColumn: 'column_attr_19',
    evaluationEngine: 'GREAT_EXPECTATIONS',
    isBlocking: false,
    alertSeverity: 'HIGH_P2',
    autoRemediationAction: 'RETRY_STAGE_WITH_BACKOFF'
  },
  {
    assertionId: 'ASSERT-NRD-140',
    ruleName: 'NumericRangeAndDistribution Assertion Check #140',
    category: 'and standard deviation bounds',
    targetTable: 'enterprise_data_mart.table_20',
    targetColumn: 'column_attr_0',
    evaluationEngine: 'SQL_ASSERTION',
    isBlocking: false,
    alertSeverity: 'HIGH_P2',
    autoRemediationAction: 'QUARANTINE_ROW_TO_DLQ'
  },
  {
    assertionId: 'ASSERT-NRD-141',
    ruleName: 'NumericRangeAndDistribution Assertion Check #141',
    category: 'Z-score anomaly bounds',
    targetTable: 'enterprise_data_mart.table_21',
    targetColumn: 'column_attr_1',
    evaluationEngine: 'GREAT_EXPECTATIONS',
    isBlocking: true,
    alertSeverity: 'CRITICAL_P1',
    autoRemediationAction: 'RETRY_STAGE_WITH_BACKOFF'
  },
  {
    assertionId: 'ASSERT-NRD-142',
    ruleName: 'NumericRangeAndDistribution Assertion Check #142',
    category: 'min-max thresholds',
    targetTable: 'enterprise_data_mart.table_22',
    targetColumn: 'column_attr_2',
    evaluationEngine: 'SQL_ASSERTION',
    isBlocking: false,
    alertSeverity: 'HIGH_P2',
    autoRemediationAction: 'QUARANTINE_ROW_TO_DLQ'
  },
  {
    assertionId: 'ASSERT-NRD-143',
    ruleName: 'NumericRangeAndDistribution Assertion Check #143',
    category: 'and standard deviation bounds',
    targetTable: 'enterprise_data_mart.table_23',
    targetColumn: 'column_attr_3',
    evaluationEngine: 'GREAT_EXPECTATIONS',
    isBlocking: false,
    alertSeverity: 'HIGH_P2',
    autoRemediationAction: 'RETRY_STAGE_WITH_BACKOFF'
  },
  {
    assertionId: 'ASSERT-NRD-144',
    ruleName: 'NumericRangeAndDistribution Assertion Check #144',
    category: 'Z-score anomaly bounds',
    targetTable: 'enterprise_data_mart.table_24',
    targetColumn: 'column_attr_4',
    evaluationEngine: 'SQL_ASSERTION',
    isBlocking: true,
    alertSeverity: 'CRITICAL_P1',
    autoRemediationAction: 'QUARANTINE_ROW_TO_DLQ'
  },
  {
    assertionId: 'ASSERT-NRD-145',
    ruleName: 'NumericRangeAndDistribution Assertion Check #145',
    category: 'min-max thresholds',
    targetTable: 'enterprise_data_mart.table_25',
    targetColumn: 'column_attr_5',
    evaluationEngine: 'GREAT_EXPECTATIONS',
    isBlocking: false,
    alertSeverity: 'HIGH_P2',
    autoRemediationAction: 'RETRY_STAGE_WITH_BACKOFF'
  },
  {
    assertionId: 'ASSERT-NRD-146',
    ruleName: 'NumericRangeAndDistribution Assertion Check #146',
    category: 'and standard deviation bounds',
    targetTable: 'enterprise_data_mart.table_26',
    targetColumn: 'column_attr_6',
    evaluationEngine: 'SQL_ASSERTION',
    isBlocking: false,
    alertSeverity: 'HIGH_P2',
    autoRemediationAction: 'QUARANTINE_ROW_TO_DLQ'
  },
  {
    assertionId: 'ASSERT-NRD-147',
    ruleName: 'NumericRangeAndDistribution Assertion Check #147',
    category: 'Z-score anomaly bounds',
    targetTable: 'enterprise_data_mart.table_27',
    targetColumn: 'column_attr_7',
    evaluationEngine: 'GREAT_EXPECTATIONS',
    isBlocking: true,
    alertSeverity: 'CRITICAL_P1',
    autoRemediationAction: 'RETRY_STAGE_WITH_BACKOFF'
  },
  {
    assertionId: 'ASSERT-NRD-148',
    ruleName: 'NumericRangeAndDistribution Assertion Check #148',
    category: 'min-max thresholds',
    targetTable: 'enterprise_data_mart.table_28',
    targetColumn: 'column_attr_8',
    evaluationEngine: 'SQL_ASSERTION',
    isBlocking: false,
    alertSeverity: 'HIGH_P2',
    autoRemediationAction: 'QUARANTINE_ROW_TO_DLQ'
  },
  {
    assertionId: 'ASSERT-NRD-149',
    ruleName: 'NumericRangeAndDistribution Assertion Check #149',
    category: 'and standard deviation bounds',
    targetTable: 'enterprise_data_mart.table_29',
    targetColumn: 'column_attr_9',
    evaluationEngine: 'GREAT_EXPECTATIONS',
    isBlocking: false,
    alertSeverity: 'HIGH_P2',
    autoRemediationAction: 'RETRY_STAGE_WITH_BACKOFF'
  },
  {
    assertionId: 'ASSERT-NRD-150',
    ruleName: 'NumericRangeAndDistribution Assertion Check #150',
    category: 'Z-score anomaly bounds',
    targetTable: 'enterprise_data_mart.table_0',
    targetColumn: 'column_attr_10',
    evaluationEngine: 'SQL_ASSERTION',
    isBlocking: true,
    alertSeverity: 'CRITICAL_P1',
    autoRemediationAction: 'QUARANTINE_ROW_TO_DLQ'
  }
];
