/**
 * Data Quality & Great Expectations Ruleset: ReferentialIntegrityAndUniqueness
 * Description: Foreign key existence verification, primary key uniqueness constraints, and orphan record counters
 */

export interface DataQualityRule {
  assertionId: string;
  ruleName: string;
  category: string;
  targetTable: string;
  targetColumn: string;
  evaluationEngine: string;
  isBlocking: boolean;
  alertSeverity: string;
  autoRemediationAction: string;
}

export const QUALITY_RIU_DATASET: DataQualityRule[] = [
  {
    assertionId: 'ASSERT-RIU-001',
    ruleName: 'ReferentialIntegrityAndUniqueness Assertion Check #1',
    category: 'primary key uniqueness constraints',
    targetTable: 'enterprise_data_mart.table_1',
    targetColumn: 'column_attr_1',
    evaluationEngine: 'GREAT_EXPECTATIONS',
    isBlocking: false,
    alertSeverity: 'HIGH_P2',
    autoRemediationAction: 'RETRY_STAGE_WITH_BACKOFF'
  },
  {
    assertionId: 'ASSERT-RIU-002',
    ruleName: 'ReferentialIntegrityAndUniqueness Assertion Check #2',
    category: 'and orphan record counters',
    targetTable: 'enterprise_data_mart.table_2',
    targetColumn: 'column_attr_2',
    evaluationEngine: 'SQL_ASSERTION',
    isBlocking: false,
    alertSeverity: 'HIGH_P2',
    autoRemediationAction: 'QUARANTINE_ROW_TO_DLQ'
  },
  {
    assertionId: 'ASSERT-RIU-003',
    ruleName: 'ReferentialIntegrityAndUniqueness Assertion Check #3',
    category: 'Foreign key existence verification',
    targetTable: 'enterprise_data_mart.table_3',
    targetColumn: 'column_attr_3',
    evaluationEngine: 'GREAT_EXPECTATIONS',
    isBlocking: true,
    alertSeverity: 'CRITICAL_P1',
    autoRemediationAction: 'RETRY_STAGE_WITH_BACKOFF'
  },
  {
    assertionId: 'ASSERT-RIU-004',
    ruleName: 'ReferentialIntegrityAndUniqueness Assertion Check #4',
    category: 'primary key uniqueness constraints',
    targetTable: 'enterprise_data_mart.table_4',
    targetColumn: 'column_attr_4',
    evaluationEngine: 'SQL_ASSERTION',
    isBlocking: false,
    alertSeverity: 'HIGH_P2',
    autoRemediationAction: 'QUARANTINE_ROW_TO_DLQ'
  },
  {
    assertionId: 'ASSERT-RIU-005',
    ruleName: 'ReferentialIntegrityAndUniqueness Assertion Check #5',
    category: 'and orphan record counters',
    targetTable: 'enterprise_data_mart.table_5',
    targetColumn: 'column_attr_5',
    evaluationEngine: 'GREAT_EXPECTATIONS',
    isBlocking: false,
    alertSeverity: 'HIGH_P2',
    autoRemediationAction: 'RETRY_STAGE_WITH_BACKOFF'
  },
  {
    assertionId: 'ASSERT-RIU-006',
    ruleName: 'ReferentialIntegrityAndUniqueness Assertion Check #6',
    category: 'Foreign key existence verification',
    targetTable: 'enterprise_data_mart.table_6',
    targetColumn: 'column_attr_6',
    evaluationEngine: 'SQL_ASSERTION',
    isBlocking: true,
    alertSeverity: 'CRITICAL_P1',
    autoRemediationAction: 'QUARANTINE_ROW_TO_DLQ'
  },
  {
    assertionId: 'ASSERT-RIU-007',
    ruleName: 'ReferentialIntegrityAndUniqueness Assertion Check #7',
    category: 'primary key uniqueness constraints',
    targetTable: 'enterprise_data_mart.table_7',
    targetColumn: 'column_attr_7',
    evaluationEngine: 'GREAT_EXPECTATIONS',
    isBlocking: false,
    alertSeverity: 'HIGH_P2',
    autoRemediationAction: 'RETRY_STAGE_WITH_BACKOFF'
  },
  {
    assertionId: 'ASSERT-RIU-008',
    ruleName: 'ReferentialIntegrityAndUniqueness Assertion Check #8',
    category: 'and orphan record counters',
    targetTable: 'enterprise_data_mart.table_8',
    targetColumn: 'column_attr_8',
    evaluationEngine: 'SQL_ASSERTION',
    isBlocking: false,
    alertSeverity: 'HIGH_P2',
    autoRemediationAction: 'QUARANTINE_ROW_TO_DLQ'
  },
  {
    assertionId: 'ASSERT-RIU-009',
    ruleName: 'ReferentialIntegrityAndUniqueness Assertion Check #9',
    category: 'Foreign key existence verification',
    targetTable: 'enterprise_data_mart.table_9',
    targetColumn: 'column_attr_9',
    evaluationEngine: 'GREAT_EXPECTATIONS',
    isBlocking: true,
    alertSeverity: 'CRITICAL_P1',
    autoRemediationAction: 'RETRY_STAGE_WITH_BACKOFF'
  },
  {
    assertionId: 'ASSERT-RIU-010',
    ruleName: 'ReferentialIntegrityAndUniqueness Assertion Check #10',
    category: 'primary key uniqueness constraints',
    targetTable: 'enterprise_data_mart.table_10',
    targetColumn: 'column_attr_10',
    evaluationEngine: 'SQL_ASSERTION',
    isBlocking: false,
    alertSeverity: 'HIGH_P2',
    autoRemediationAction: 'QUARANTINE_ROW_TO_DLQ'
  },
  {
    assertionId: 'ASSERT-RIU-011',
    ruleName: 'ReferentialIntegrityAndUniqueness Assertion Check #11',
    category: 'and orphan record counters',
    targetTable: 'enterprise_data_mart.table_11',
    targetColumn: 'column_attr_11',
    evaluationEngine: 'GREAT_EXPECTATIONS',
    isBlocking: false,
    alertSeverity: 'HIGH_P2',
    autoRemediationAction: 'RETRY_STAGE_WITH_BACKOFF'
  },
  {
    assertionId: 'ASSERT-RIU-012',
    ruleName: 'ReferentialIntegrityAndUniqueness Assertion Check #12',
    category: 'Foreign key existence verification',
    targetTable: 'enterprise_data_mart.table_12',
    targetColumn: 'column_attr_12',
    evaluationEngine: 'SQL_ASSERTION',
    isBlocking: true,
    alertSeverity: 'CRITICAL_P1',
    autoRemediationAction: 'QUARANTINE_ROW_TO_DLQ'
  },
  {
    assertionId: 'ASSERT-RIU-013',
    ruleName: 'ReferentialIntegrityAndUniqueness Assertion Check #13',
    category: 'primary key uniqueness constraints',
    targetTable: 'enterprise_data_mart.table_13',
    targetColumn: 'column_attr_13',
    evaluationEngine: 'GREAT_EXPECTATIONS',
    isBlocking: false,
    alertSeverity: 'HIGH_P2',
    autoRemediationAction: 'RETRY_STAGE_WITH_BACKOFF'
  },
  {
    assertionId: 'ASSERT-RIU-014',
    ruleName: 'ReferentialIntegrityAndUniqueness Assertion Check #14',
    category: 'and orphan record counters',
    targetTable: 'enterprise_data_mart.table_14',
    targetColumn: 'column_attr_14',
    evaluationEngine: 'SQL_ASSERTION',
    isBlocking: false,
    alertSeverity: 'HIGH_P2',
    autoRemediationAction: 'QUARANTINE_ROW_TO_DLQ'
  },
  {
    assertionId: 'ASSERT-RIU-015',
    ruleName: 'ReferentialIntegrityAndUniqueness Assertion Check #15',
    category: 'Foreign key existence verification',
    targetTable: 'enterprise_data_mart.table_15',
    targetColumn: 'column_attr_15',
    evaluationEngine: 'GREAT_EXPECTATIONS',
    isBlocking: true,
    alertSeverity: 'CRITICAL_P1',
    autoRemediationAction: 'RETRY_STAGE_WITH_BACKOFF'
  },
  {
    assertionId: 'ASSERT-RIU-016',
    ruleName: 'ReferentialIntegrityAndUniqueness Assertion Check #16',
    category: 'primary key uniqueness constraints',
    targetTable: 'enterprise_data_mart.table_16',
    targetColumn: 'column_attr_16',
    evaluationEngine: 'SQL_ASSERTION',
    isBlocking: false,
    alertSeverity: 'HIGH_P2',
    autoRemediationAction: 'QUARANTINE_ROW_TO_DLQ'
  },
  {
    assertionId: 'ASSERT-RIU-017',
    ruleName: 'ReferentialIntegrityAndUniqueness Assertion Check #17',
    category: 'and orphan record counters',
    targetTable: 'enterprise_data_mart.table_17',
    targetColumn: 'column_attr_17',
    evaluationEngine: 'GREAT_EXPECTATIONS',
    isBlocking: false,
    alertSeverity: 'HIGH_P2',
    autoRemediationAction: 'RETRY_STAGE_WITH_BACKOFF'
  },
  {
    assertionId: 'ASSERT-RIU-018',
    ruleName: 'ReferentialIntegrityAndUniqueness Assertion Check #18',
    category: 'Foreign key existence verification',
    targetTable: 'enterprise_data_mart.table_18',
    targetColumn: 'column_attr_18',
    evaluationEngine: 'SQL_ASSERTION',
    isBlocking: true,
    alertSeverity: 'CRITICAL_P1',
    autoRemediationAction: 'QUARANTINE_ROW_TO_DLQ'
  },
  {
    assertionId: 'ASSERT-RIU-019',
    ruleName: 'ReferentialIntegrityAndUniqueness Assertion Check #19',
    category: 'primary key uniqueness constraints',
    targetTable: 'enterprise_data_mart.table_19',
    targetColumn: 'column_attr_19',
    evaluationEngine: 'GREAT_EXPECTATIONS',
    isBlocking: false,
    alertSeverity: 'HIGH_P2',
    autoRemediationAction: 'RETRY_STAGE_WITH_BACKOFF'
  },
  {
    assertionId: 'ASSERT-RIU-020',
    ruleName: 'ReferentialIntegrityAndUniqueness Assertion Check #20',
    category: 'and orphan record counters',
    targetTable: 'enterprise_data_mart.table_20',
    targetColumn: 'column_attr_0',
    evaluationEngine: 'SQL_ASSERTION',
    isBlocking: false,
    alertSeverity: 'HIGH_P2',
    autoRemediationAction: 'QUARANTINE_ROW_TO_DLQ'
  },
  {
    assertionId: 'ASSERT-RIU-021',
    ruleName: 'ReferentialIntegrityAndUniqueness Assertion Check #21',
    category: 'Foreign key existence verification',
    targetTable: 'enterprise_data_mart.table_21',
    targetColumn: 'column_attr_1',
    evaluationEngine: 'GREAT_EXPECTATIONS',
    isBlocking: true,
    alertSeverity: 'CRITICAL_P1',
    autoRemediationAction: 'RETRY_STAGE_WITH_BACKOFF'
  },
  {
    assertionId: 'ASSERT-RIU-022',
    ruleName: 'ReferentialIntegrityAndUniqueness Assertion Check #22',
    category: 'primary key uniqueness constraints',
    targetTable: 'enterprise_data_mart.table_22',
    targetColumn: 'column_attr_2',
    evaluationEngine: 'SQL_ASSERTION',
    isBlocking: false,
    alertSeverity: 'HIGH_P2',
    autoRemediationAction: 'QUARANTINE_ROW_TO_DLQ'
  },
  {
    assertionId: 'ASSERT-RIU-023',
    ruleName: 'ReferentialIntegrityAndUniqueness Assertion Check #23',
    category: 'and orphan record counters',
    targetTable: 'enterprise_data_mart.table_23',
    targetColumn: 'column_attr_3',
    evaluationEngine: 'GREAT_EXPECTATIONS',
    isBlocking: false,
    alertSeverity: 'HIGH_P2',
    autoRemediationAction: 'RETRY_STAGE_WITH_BACKOFF'
  },
  {
    assertionId: 'ASSERT-RIU-024',
    ruleName: 'ReferentialIntegrityAndUniqueness Assertion Check #24',
    category: 'Foreign key existence verification',
    targetTable: 'enterprise_data_mart.table_24',
    targetColumn: 'column_attr_4',
    evaluationEngine: 'SQL_ASSERTION',
    isBlocking: true,
    alertSeverity: 'CRITICAL_P1',
    autoRemediationAction: 'QUARANTINE_ROW_TO_DLQ'
  },
  {
    assertionId: 'ASSERT-RIU-025',
    ruleName: 'ReferentialIntegrityAndUniqueness Assertion Check #25',
    category: 'primary key uniqueness constraints',
    targetTable: 'enterprise_data_mart.table_25',
    targetColumn: 'column_attr_5',
    evaluationEngine: 'GREAT_EXPECTATIONS',
    isBlocking: false,
    alertSeverity: 'HIGH_P2',
    autoRemediationAction: 'RETRY_STAGE_WITH_BACKOFF'
  },
  {
    assertionId: 'ASSERT-RIU-026',
    ruleName: 'ReferentialIntegrityAndUniqueness Assertion Check #26',
    category: 'and orphan record counters',
    targetTable: 'enterprise_data_mart.table_26',
    targetColumn: 'column_attr_6',
    evaluationEngine: 'SQL_ASSERTION',
    isBlocking: false,
    alertSeverity: 'HIGH_P2',
    autoRemediationAction: 'QUARANTINE_ROW_TO_DLQ'
  },
  {
    assertionId: 'ASSERT-RIU-027',
    ruleName: 'ReferentialIntegrityAndUniqueness Assertion Check #27',
    category: 'Foreign key existence verification',
    targetTable: 'enterprise_data_mart.table_27',
    targetColumn: 'column_attr_7',
    evaluationEngine: 'GREAT_EXPECTATIONS',
    isBlocking: true,
    alertSeverity: 'CRITICAL_P1',
    autoRemediationAction: 'RETRY_STAGE_WITH_BACKOFF'
  },
  {
    assertionId: 'ASSERT-RIU-028',
    ruleName: 'ReferentialIntegrityAndUniqueness Assertion Check #28',
    category: 'primary key uniqueness constraints',
    targetTable: 'enterprise_data_mart.table_28',
    targetColumn: 'column_attr_8',
    evaluationEngine: 'SQL_ASSERTION',
    isBlocking: false,
    alertSeverity: 'HIGH_P2',
    autoRemediationAction: 'QUARANTINE_ROW_TO_DLQ'
  },
  {
    assertionId: 'ASSERT-RIU-029',
    ruleName: 'ReferentialIntegrityAndUniqueness Assertion Check #29',
    category: 'and orphan record counters',
    targetTable: 'enterprise_data_mart.table_29',
    targetColumn: 'column_attr_9',
    evaluationEngine: 'GREAT_EXPECTATIONS',
    isBlocking: false,
    alertSeverity: 'HIGH_P2',
    autoRemediationAction: 'RETRY_STAGE_WITH_BACKOFF'
  },
  {
    assertionId: 'ASSERT-RIU-030',
    ruleName: 'ReferentialIntegrityAndUniqueness Assertion Check #30',
    category: 'Foreign key existence verification',
    targetTable: 'enterprise_data_mart.table_0',
    targetColumn: 'column_attr_10',
    evaluationEngine: 'SQL_ASSERTION',
    isBlocking: true,
    alertSeverity: 'CRITICAL_P1',
    autoRemediationAction: 'QUARANTINE_ROW_TO_DLQ'
  },
  {
    assertionId: 'ASSERT-RIU-031',
    ruleName: 'ReferentialIntegrityAndUniqueness Assertion Check #31',
    category: 'primary key uniqueness constraints',
    targetTable: 'enterprise_data_mart.table_1',
    targetColumn: 'column_attr_11',
    evaluationEngine: 'GREAT_EXPECTATIONS',
    isBlocking: false,
    alertSeverity: 'HIGH_P2',
    autoRemediationAction: 'RETRY_STAGE_WITH_BACKOFF'
  },
  {
    assertionId: 'ASSERT-RIU-032',
    ruleName: 'ReferentialIntegrityAndUniqueness Assertion Check #32',
    category: 'and orphan record counters',
    targetTable: 'enterprise_data_mart.table_2',
    targetColumn: 'column_attr_12',
    evaluationEngine: 'SQL_ASSERTION',
    isBlocking: false,
    alertSeverity: 'HIGH_P2',
    autoRemediationAction: 'QUARANTINE_ROW_TO_DLQ'
  },
  {
    assertionId: 'ASSERT-RIU-033',
    ruleName: 'ReferentialIntegrityAndUniqueness Assertion Check #33',
    category: 'Foreign key existence verification',
    targetTable: 'enterprise_data_mart.table_3',
    targetColumn: 'column_attr_13',
    evaluationEngine: 'GREAT_EXPECTATIONS',
    isBlocking: true,
    alertSeverity: 'CRITICAL_P1',
    autoRemediationAction: 'RETRY_STAGE_WITH_BACKOFF'
  },
  {
    assertionId: 'ASSERT-RIU-034',
    ruleName: 'ReferentialIntegrityAndUniqueness Assertion Check #34',
    category: 'primary key uniqueness constraints',
    targetTable: 'enterprise_data_mart.table_4',
    targetColumn: 'column_attr_14',
    evaluationEngine: 'SQL_ASSERTION',
    isBlocking: false,
    alertSeverity: 'HIGH_P2',
    autoRemediationAction: 'QUARANTINE_ROW_TO_DLQ'
  },
  {
    assertionId: 'ASSERT-RIU-035',
    ruleName: 'ReferentialIntegrityAndUniqueness Assertion Check #35',
    category: 'and orphan record counters',
    targetTable: 'enterprise_data_mart.table_5',
    targetColumn: 'column_attr_15',
    evaluationEngine: 'GREAT_EXPECTATIONS',
    isBlocking: false,
    alertSeverity: 'HIGH_P2',
    autoRemediationAction: 'RETRY_STAGE_WITH_BACKOFF'
  },
  {
    assertionId: 'ASSERT-RIU-036',
    ruleName: 'ReferentialIntegrityAndUniqueness Assertion Check #36',
    category: 'Foreign key existence verification',
    targetTable: 'enterprise_data_mart.table_6',
    targetColumn: 'column_attr_16',
    evaluationEngine: 'SQL_ASSERTION',
    isBlocking: true,
    alertSeverity: 'CRITICAL_P1',
    autoRemediationAction: 'QUARANTINE_ROW_TO_DLQ'
  },
  {
    assertionId: 'ASSERT-RIU-037',
    ruleName: 'ReferentialIntegrityAndUniqueness Assertion Check #37',
    category: 'primary key uniqueness constraints',
    targetTable: 'enterprise_data_mart.table_7',
    targetColumn: 'column_attr_17',
    evaluationEngine: 'GREAT_EXPECTATIONS',
    isBlocking: false,
    alertSeverity: 'HIGH_P2',
    autoRemediationAction: 'RETRY_STAGE_WITH_BACKOFF'
  },
  {
    assertionId: 'ASSERT-RIU-038',
    ruleName: 'ReferentialIntegrityAndUniqueness Assertion Check #38',
    category: 'and orphan record counters',
    targetTable: 'enterprise_data_mart.table_8',
    targetColumn: 'column_attr_18',
    evaluationEngine: 'SQL_ASSERTION',
    isBlocking: false,
    alertSeverity: 'HIGH_P2',
    autoRemediationAction: 'QUARANTINE_ROW_TO_DLQ'
  },
  {
    assertionId: 'ASSERT-RIU-039',
    ruleName: 'ReferentialIntegrityAndUniqueness Assertion Check #39',
    category: 'Foreign key existence verification',
    targetTable: 'enterprise_data_mart.table_9',
    targetColumn: 'column_attr_19',
    evaluationEngine: 'GREAT_EXPECTATIONS',
    isBlocking: true,
    alertSeverity: 'CRITICAL_P1',
    autoRemediationAction: 'RETRY_STAGE_WITH_BACKOFF'
  },
  {
    assertionId: 'ASSERT-RIU-040',
    ruleName: 'ReferentialIntegrityAndUniqueness Assertion Check #40',
    category: 'primary key uniqueness constraints',
    targetTable: 'enterprise_data_mart.table_10',
    targetColumn: 'column_attr_0',
    evaluationEngine: 'SQL_ASSERTION',
    isBlocking: false,
    alertSeverity: 'HIGH_P2',
    autoRemediationAction: 'QUARANTINE_ROW_TO_DLQ'
  },
  {
    assertionId: 'ASSERT-RIU-041',
    ruleName: 'ReferentialIntegrityAndUniqueness Assertion Check #41',
    category: 'and orphan record counters',
    targetTable: 'enterprise_data_mart.table_11',
    targetColumn: 'column_attr_1',
    evaluationEngine: 'GREAT_EXPECTATIONS',
    isBlocking: false,
    alertSeverity: 'HIGH_P2',
    autoRemediationAction: 'RETRY_STAGE_WITH_BACKOFF'
  },
  {
    assertionId: 'ASSERT-RIU-042',
    ruleName: 'ReferentialIntegrityAndUniqueness Assertion Check #42',
    category: 'Foreign key existence verification',
    targetTable: 'enterprise_data_mart.table_12',
    targetColumn: 'column_attr_2',
    evaluationEngine: 'SQL_ASSERTION',
    isBlocking: true,
    alertSeverity: 'CRITICAL_P1',
    autoRemediationAction: 'QUARANTINE_ROW_TO_DLQ'
  },
  {
    assertionId: 'ASSERT-RIU-043',
    ruleName: 'ReferentialIntegrityAndUniqueness Assertion Check #43',
    category: 'primary key uniqueness constraints',
    targetTable: 'enterprise_data_mart.table_13',
    targetColumn: 'column_attr_3',
    evaluationEngine: 'GREAT_EXPECTATIONS',
    isBlocking: false,
    alertSeverity: 'HIGH_P2',
    autoRemediationAction: 'RETRY_STAGE_WITH_BACKOFF'
  },
  {
    assertionId: 'ASSERT-RIU-044',
    ruleName: 'ReferentialIntegrityAndUniqueness Assertion Check #44',
    category: 'and orphan record counters',
    targetTable: 'enterprise_data_mart.table_14',
    targetColumn: 'column_attr_4',
    evaluationEngine: 'SQL_ASSERTION',
    isBlocking: false,
    alertSeverity: 'HIGH_P2',
    autoRemediationAction: 'QUARANTINE_ROW_TO_DLQ'
  },
  {
    assertionId: 'ASSERT-RIU-045',
    ruleName: 'ReferentialIntegrityAndUniqueness Assertion Check #45',
    category: 'Foreign key existence verification',
    targetTable: 'enterprise_data_mart.table_15',
    targetColumn: 'column_attr_5',
    evaluationEngine: 'GREAT_EXPECTATIONS',
    isBlocking: true,
    alertSeverity: 'CRITICAL_P1',
    autoRemediationAction: 'RETRY_STAGE_WITH_BACKOFF'
  },
  {
    assertionId: 'ASSERT-RIU-046',
    ruleName: 'ReferentialIntegrityAndUniqueness Assertion Check #46',
    category: 'primary key uniqueness constraints',
    targetTable: 'enterprise_data_mart.table_16',
    targetColumn: 'column_attr_6',
    evaluationEngine: 'SQL_ASSERTION',
    isBlocking: false,
    alertSeverity: 'HIGH_P2',
    autoRemediationAction: 'QUARANTINE_ROW_TO_DLQ'
  },
  {
    assertionId: 'ASSERT-RIU-047',
    ruleName: 'ReferentialIntegrityAndUniqueness Assertion Check #47',
    category: 'and orphan record counters',
    targetTable: 'enterprise_data_mart.table_17',
    targetColumn: 'column_attr_7',
    evaluationEngine: 'GREAT_EXPECTATIONS',
    isBlocking: false,
    alertSeverity: 'HIGH_P2',
    autoRemediationAction: 'RETRY_STAGE_WITH_BACKOFF'
  },
  {
    assertionId: 'ASSERT-RIU-048',
    ruleName: 'ReferentialIntegrityAndUniqueness Assertion Check #48',
    category: 'Foreign key existence verification',
    targetTable: 'enterprise_data_mart.table_18',
    targetColumn: 'column_attr_8',
    evaluationEngine: 'SQL_ASSERTION',
    isBlocking: true,
    alertSeverity: 'CRITICAL_P1',
    autoRemediationAction: 'QUARANTINE_ROW_TO_DLQ'
  },
  {
    assertionId: 'ASSERT-RIU-049',
    ruleName: 'ReferentialIntegrityAndUniqueness Assertion Check #49',
    category: 'primary key uniqueness constraints',
    targetTable: 'enterprise_data_mart.table_19',
    targetColumn: 'column_attr_9',
    evaluationEngine: 'GREAT_EXPECTATIONS',
    isBlocking: false,
    alertSeverity: 'HIGH_P2',
    autoRemediationAction: 'RETRY_STAGE_WITH_BACKOFF'
  },
  {
    assertionId: 'ASSERT-RIU-050',
    ruleName: 'ReferentialIntegrityAndUniqueness Assertion Check #50',
    category: 'and orphan record counters',
    targetTable: 'enterprise_data_mart.table_20',
    targetColumn: 'column_attr_10',
    evaluationEngine: 'SQL_ASSERTION',
    isBlocking: false,
    alertSeverity: 'HIGH_P2',
    autoRemediationAction: 'QUARANTINE_ROW_TO_DLQ'
  },
  {
    assertionId: 'ASSERT-RIU-051',
    ruleName: 'ReferentialIntegrityAndUniqueness Assertion Check #51',
    category: 'Foreign key existence verification',
    targetTable: 'enterprise_data_mart.table_21',
    targetColumn: 'column_attr_11',
    evaluationEngine: 'GREAT_EXPECTATIONS',
    isBlocking: true,
    alertSeverity: 'CRITICAL_P1',
    autoRemediationAction: 'RETRY_STAGE_WITH_BACKOFF'
  },
  {
    assertionId: 'ASSERT-RIU-052',
    ruleName: 'ReferentialIntegrityAndUniqueness Assertion Check #52',
    category: 'primary key uniqueness constraints',
    targetTable: 'enterprise_data_mart.table_22',
    targetColumn: 'column_attr_12',
    evaluationEngine: 'SQL_ASSERTION',
    isBlocking: false,
    alertSeverity: 'HIGH_P2',
    autoRemediationAction: 'QUARANTINE_ROW_TO_DLQ'
  },
  {
    assertionId: 'ASSERT-RIU-053',
    ruleName: 'ReferentialIntegrityAndUniqueness Assertion Check #53',
    category: 'and orphan record counters',
    targetTable: 'enterprise_data_mart.table_23',
    targetColumn: 'column_attr_13',
    evaluationEngine: 'GREAT_EXPECTATIONS',
    isBlocking: false,
    alertSeverity: 'HIGH_P2',
    autoRemediationAction: 'RETRY_STAGE_WITH_BACKOFF'
  },
  {
    assertionId: 'ASSERT-RIU-054',
    ruleName: 'ReferentialIntegrityAndUniqueness Assertion Check #54',
    category: 'Foreign key existence verification',
    targetTable: 'enterprise_data_mart.table_24',
    targetColumn: 'column_attr_14',
    evaluationEngine: 'SQL_ASSERTION',
    isBlocking: true,
    alertSeverity: 'CRITICAL_P1',
    autoRemediationAction: 'QUARANTINE_ROW_TO_DLQ'
  },
  {
    assertionId: 'ASSERT-RIU-055',
    ruleName: 'ReferentialIntegrityAndUniqueness Assertion Check #55',
    category: 'primary key uniqueness constraints',
    targetTable: 'enterprise_data_mart.table_25',
    targetColumn: 'column_attr_15',
    evaluationEngine: 'GREAT_EXPECTATIONS',
    isBlocking: false,
    alertSeverity: 'HIGH_P2',
    autoRemediationAction: 'RETRY_STAGE_WITH_BACKOFF'
  },
  {
    assertionId: 'ASSERT-RIU-056',
    ruleName: 'ReferentialIntegrityAndUniqueness Assertion Check #56',
    category: 'and orphan record counters',
    targetTable: 'enterprise_data_mart.table_26',
    targetColumn: 'column_attr_16',
    evaluationEngine: 'SQL_ASSERTION',
    isBlocking: false,
    alertSeverity: 'HIGH_P2',
    autoRemediationAction: 'QUARANTINE_ROW_TO_DLQ'
  },
  {
    assertionId: 'ASSERT-RIU-057',
    ruleName: 'ReferentialIntegrityAndUniqueness Assertion Check #57',
    category: 'Foreign key existence verification',
    targetTable: 'enterprise_data_mart.table_27',
    targetColumn: 'column_attr_17',
    evaluationEngine: 'GREAT_EXPECTATIONS',
    isBlocking: true,
    alertSeverity: 'CRITICAL_P1',
    autoRemediationAction: 'RETRY_STAGE_WITH_BACKOFF'
  },
  {
    assertionId: 'ASSERT-RIU-058',
    ruleName: 'ReferentialIntegrityAndUniqueness Assertion Check #58',
    category: 'primary key uniqueness constraints',
    targetTable: 'enterprise_data_mart.table_28',
    targetColumn: 'column_attr_18',
    evaluationEngine: 'SQL_ASSERTION',
    isBlocking: false,
    alertSeverity: 'HIGH_P2',
    autoRemediationAction: 'QUARANTINE_ROW_TO_DLQ'
  },
  {
    assertionId: 'ASSERT-RIU-059',
    ruleName: 'ReferentialIntegrityAndUniqueness Assertion Check #59',
    category: 'and orphan record counters',
    targetTable: 'enterprise_data_mart.table_29',
    targetColumn: 'column_attr_19',
    evaluationEngine: 'GREAT_EXPECTATIONS',
    isBlocking: false,
    alertSeverity: 'HIGH_P2',
    autoRemediationAction: 'RETRY_STAGE_WITH_BACKOFF'
  },
  {
    assertionId: 'ASSERT-RIU-060',
    ruleName: 'ReferentialIntegrityAndUniqueness Assertion Check #60',
    category: 'Foreign key existence verification',
    targetTable: 'enterprise_data_mart.table_0',
    targetColumn: 'column_attr_0',
    evaluationEngine: 'SQL_ASSERTION',
    isBlocking: true,
    alertSeverity: 'CRITICAL_P1',
    autoRemediationAction: 'QUARANTINE_ROW_TO_DLQ'
  },
  {
    assertionId: 'ASSERT-RIU-061',
    ruleName: 'ReferentialIntegrityAndUniqueness Assertion Check #61',
    category: 'primary key uniqueness constraints',
    targetTable: 'enterprise_data_mart.table_1',
    targetColumn: 'column_attr_1',
    evaluationEngine: 'GREAT_EXPECTATIONS',
    isBlocking: false,
    alertSeverity: 'HIGH_P2',
    autoRemediationAction: 'RETRY_STAGE_WITH_BACKOFF'
  },
  {
    assertionId: 'ASSERT-RIU-062',
    ruleName: 'ReferentialIntegrityAndUniqueness Assertion Check #62',
    category: 'and orphan record counters',
    targetTable: 'enterprise_data_mart.table_2',
    targetColumn: 'column_attr_2',
    evaluationEngine: 'SQL_ASSERTION',
    isBlocking: false,
    alertSeverity: 'HIGH_P2',
    autoRemediationAction: 'QUARANTINE_ROW_TO_DLQ'
  },
  {
    assertionId: 'ASSERT-RIU-063',
    ruleName: 'ReferentialIntegrityAndUniqueness Assertion Check #63',
    category: 'Foreign key existence verification',
    targetTable: 'enterprise_data_mart.table_3',
    targetColumn: 'column_attr_3',
    evaluationEngine: 'GREAT_EXPECTATIONS',
    isBlocking: true,
    alertSeverity: 'CRITICAL_P1',
    autoRemediationAction: 'RETRY_STAGE_WITH_BACKOFF'
  },
  {
    assertionId: 'ASSERT-RIU-064',
    ruleName: 'ReferentialIntegrityAndUniqueness Assertion Check #64',
    category: 'primary key uniqueness constraints',
    targetTable: 'enterprise_data_mart.table_4',
    targetColumn: 'column_attr_4',
    evaluationEngine: 'SQL_ASSERTION',
    isBlocking: false,
    alertSeverity: 'HIGH_P2',
    autoRemediationAction: 'QUARANTINE_ROW_TO_DLQ'
  },
  {
    assertionId: 'ASSERT-RIU-065',
    ruleName: 'ReferentialIntegrityAndUniqueness Assertion Check #65',
    category: 'and orphan record counters',
    targetTable: 'enterprise_data_mart.table_5',
    targetColumn: 'column_attr_5',
    evaluationEngine: 'GREAT_EXPECTATIONS',
    isBlocking: false,
    alertSeverity: 'HIGH_P2',
    autoRemediationAction: 'RETRY_STAGE_WITH_BACKOFF'
  },
  {
    assertionId: 'ASSERT-RIU-066',
    ruleName: 'ReferentialIntegrityAndUniqueness Assertion Check #66',
    category: 'Foreign key existence verification',
    targetTable: 'enterprise_data_mart.table_6',
    targetColumn: 'column_attr_6',
    evaluationEngine: 'SQL_ASSERTION',
    isBlocking: true,
    alertSeverity: 'CRITICAL_P1',
    autoRemediationAction: 'QUARANTINE_ROW_TO_DLQ'
  },
  {
    assertionId: 'ASSERT-RIU-067',
    ruleName: 'ReferentialIntegrityAndUniqueness Assertion Check #67',
    category: 'primary key uniqueness constraints',
    targetTable: 'enterprise_data_mart.table_7',
    targetColumn: 'column_attr_7',
    evaluationEngine: 'GREAT_EXPECTATIONS',
    isBlocking: false,
    alertSeverity: 'HIGH_P2',
    autoRemediationAction: 'RETRY_STAGE_WITH_BACKOFF'
  },
  {
    assertionId: 'ASSERT-RIU-068',
    ruleName: 'ReferentialIntegrityAndUniqueness Assertion Check #68',
    category: 'and orphan record counters',
    targetTable: 'enterprise_data_mart.table_8',
    targetColumn: 'column_attr_8',
    evaluationEngine: 'SQL_ASSERTION',
    isBlocking: false,
    alertSeverity: 'HIGH_P2',
    autoRemediationAction: 'QUARANTINE_ROW_TO_DLQ'
  },
  {
    assertionId: 'ASSERT-RIU-069',
    ruleName: 'ReferentialIntegrityAndUniqueness Assertion Check #69',
    category: 'Foreign key existence verification',
    targetTable: 'enterprise_data_mart.table_9',
    targetColumn: 'column_attr_9',
    evaluationEngine: 'GREAT_EXPECTATIONS',
    isBlocking: true,
    alertSeverity: 'CRITICAL_P1',
    autoRemediationAction: 'RETRY_STAGE_WITH_BACKOFF'
  },
  {
    assertionId: 'ASSERT-RIU-070',
    ruleName: 'ReferentialIntegrityAndUniqueness Assertion Check #70',
    category: 'primary key uniqueness constraints',
    targetTable: 'enterprise_data_mart.table_10',
    targetColumn: 'column_attr_10',
    evaluationEngine: 'SQL_ASSERTION',
    isBlocking: false,
    alertSeverity: 'HIGH_P2',
    autoRemediationAction: 'QUARANTINE_ROW_TO_DLQ'
  },
  {
    assertionId: 'ASSERT-RIU-071',
    ruleName: 'ReferentialIntegrityAndUniqueness Assertion Check #71',
    category: 'and orphan record counters',
    targetTable: 'enterprise_data_mart.table_11',
    targetColumn: 'column_attr_11',
    evaluationEngine: 'GREAT_EXPECTATIONS',
    isBlocking: false,
    alertSeverity: 'HIGH_P2',
    autoRemediationAction: 'RETRY_STAGE_WITH_BACKOFF'
  },
  {
    assertionId: 'ASSERT-RIU-072',
    ruleName: 'ReferentialIntegrityAndUniqueness Assertion Check #72',
    category: 'Foreign key existence verification',
    targetTable: 'enterprise_data_mart.table_12',
    targetColumn: 'column_attr_12',
    evaluationEngine: 'SQL_ASSERTION',
    isBlocking: true,
    alertSeverity: 'CRITICAL_P1',
    autoRemediationAction: 'QUARANTINE_ROW_TO_DLQ'
  },
  {
    assertionId: 'ASSERT-RIU-073',
    ruleName: 'ReferentialIntegrityAndUniqueness Assertion Check #73',
    category: 'primary key uniqueness constraints',
    targetTable: 'enterprise_data_mart.table_13',
    targetColumn: 'column_attr_13',
    evaluationEngine: 'GREAT_EXPECTATIONS',
    isBlocking: false,
    alertSeverity: 'HIGH_P2',
    autoRemediationAction: 'RETRY_STAGE_WITH_BACKOFF'
  },
  {
    assertionId: 'ASSERT-RIU-074',
    ruleName: 'ReferentialIntegrityAndUniqueness Assertion Check #74',
    category: 'and orphan record counters',
    targetTable: 'enterprise_data_mart.table_14',
    targetColumn: 'column_attr_14',
    evaluationEngine: 'SQL_ASSERTION',
    isBlocking: false,
    alertSeverity: 'HIGH_P2',
    autoRemediationAction: 'QUARANTINE_ROW_TO_DLQ'
  },
  {
    assertionId: 'ASSERT-RIU-075',
    ruleName: 'ReferentialIntegrityAndUniqueness Assertion Check #75',
    category: 'Foreign key existence verification',
    targetTable: 'enterprise_data_mart.table_15',
    targetColumn: 'column_attr_15',
    evaluationEngine: 'GREAT_EXPECTATIONS',
    isBlocking: true,
    alertSeverity: 'CRITICAL_P1',
    autoRemediationAction: 'RETRY_STAGE_WITH_BACKOFF'
  },
  {
    assertionId: 'ASSERT-RIU-076',
    ruleName: 'ReferentialIntegrityAndUniqueness Assertion Check #76',
    category: 'primary key uniqueness constraints',
    targetTable: 'enterprise_data_mart.table_16',
    targetColumn: 'column_attr_16',
    evaluationEngine: 'SQL_ASSERTION',
    isBlocking: false,
    alertSeverity: 'HIGH_P2',
    autoRemediationAction: 'QUARANTINE_ROW_TO_DLQ'
  },
  {
    assertionId: 'ASSERT-RIU-077',
    ruleName: 'ReferentialIntegrityAndUniqueness Assertion Check #77',
    category: 'and orphan record counters',
    targetTable: 'enterprise_data_mart.table_17',
    targetColumn: 'column_attr_17',
    evaluationEngine: 'GREAT_EXPECTATIONS',
    isBlocking: false,
    alertSeverity: 'HIGH_P2',
    autoRemediationAction: 'RETRY_STAGE_WITH_BACKOFF'
  },
  {
    assertionId: 'ASSERT-RIU-078',
    ruleName: 'ReferentialIntegrityAndUniqueness Assertion Check #78',
    category: 'Foreign key existence verification',
    targetTable: 'enterprise_data_mart.table_18',
    targetColumn: 'column_attr_18',
    evaluationEngine: 'SQL_ASSERTION',
    isBlocking: true,
    alertSeverity: 'CRITICAL_P1',
    autoRemediationAction: 'QUARANTINE_ROW_TO_DLQ'
  },
  {
    assertionId: 'ASSERT-RIU-079',
    ruleName: 'ReferentialIntegrityAndUniqueness Assertion Check #79',
    category: 'primary key uniqueness constraints',
    targetTable: 'enterprise_data_mart.table_19',
    targetColumn: 'column_attr_19',
    evaluationEngine: 'GREAT_EXPECTATIONS',
    isBlocking: false,
    alertSeverity: 'HIGH_P2',
    autoRemediationAction: 'RETRY_STAGE_WITH_BACKOFF'
  },
  {
    assertionId: 'ASSERT-RIU-080',
    ruleName: 'ReferentialIntegrityAndUniqueness Assertion Check #80',
    category: 'and orphan record counters',
    targetTable: 'enterprise_data_mart.table_20',
    targetColumn: 'column_attr_0',
    evaluationEngine: 'SQL_ASSERTION',
    isBlocking: false,
    alertSeverity: 'HIGH_P2',
    autoRemediationAction: 'QUARANTINE_ROW_TO_DLQ'
  },
  {
    assertionId: 'ASSERT-RIU-081',
    ruleName: 'ReferentialIntegrityAndUniqueness Assertion Check #81',
    category: 'Foreign key existence verification',
    targetTable: 'enterprise_data_mart.table_21',
    targetColumn: 'column_attr_1',
    evaluationEngine: 'GREAT_EXPECTATIONS',
    isBlocking: true,
    alertSeverity: 'CRITICAL_P1',
    autoRemediationAction: 'RETRY_STAGE_WITH_BACKOFF'
  },
  {
    assertionId: 'ASSERT-RIU-082',
    ruleName: 'ReferentialIntegrityAndUniqueness Assertion Check #82',
    category: 'primary key uniqueness constraints',
    targetTable: 'enterprise_data_mart.table_22',
    targetColumn: 'column_attr_2',
    evaluationEngine: 'SQL_ASSERTION',
    isBlocking: false,
    alertSeverity: 'HIGH_P2',
    autoRemediationAction: 'QUARANTINE_ROW_TO_DLQ'
  },
  {
    assertionId: 'ASSERT-RIU-083',
    ruleName: 'ReferentialIntegrityAndUniqueness Assertion Check #83',
    category: 'and orphan record counters',
    targetTable: 'enterprise_data_mart.table_23',
    targetColumn: 'column_attr_3',
    evaluationEngine: 'GREAT_EXPECTATIONS',
    isBlocking: false,
    alertSeverity: 'HIGH_P2',
    autoRemediationAction: 'RETRY_STAGE_WITH_BACKOFF'
  },
  {
    assertionId: 'ASSERT-RIU-084',
    ruleName: 'ReferentialIntegrityAndUniqueness Assertion Check #84',
    category: 'Foreign key existence verification',
    targetTable: 'enterprise_data_mart.table_24',
    targetColumn: 'column_attr_4',
    evaluationEngine: 'SQL_ASSERTION',
    isBlocking: true,
    alertSeverity: 'CRITICAL_P1',
    autoRemediationAction: 'QUARANTINE_ROW_TO_DLQ'
  },
  {
    assertionId: 'ASSERT-RIU-085',
    ruleName: 'ReferentialIntegrityAndUniqueness Assertion Check #85',
    category: 'primary key uniqueness constraints',
    targetTable: 'enterprise_data_mart.table_25',
    targetColumn: 'column_attr_5',
    evaluationEngine: 'GREAT_EXPECTATIONS',
    isBlocking: false,
    alertSeverity: 'HIGH_P2',
    autoRemediationAction: 'RETRY_STAGE_WITH_BACKOFF'
  },
  {
    assertionId: 'ASSERT-RIU-086',
    ruleName: 'ReferentialIntegrityAndUniqueness Assertion Check #86',
    category: 'and orphan record counters',
    targetTable: 'enterprise_data_mart.table_26',
    targetColumn: 'column_attr_6',
    evaluationEngine: 'SQL_ASSERTION',
    isBlocking: false,
    alertSeverity: 'HIGH_P2',
    autoRemediationAction: 'QUARANTINE_ROW_TO_DLQ'
  },
  {
    assertionId: 'ASSERT-RIU-087',
    ruleName: 'ReferentialIntegrityAndUniqueness Assertion Check #87',
    category: 'Foreign key existence verification',
    targetTable: 'enterprise_data_mart.table_27',
    targetColumn: 'column_attr_7',
    evaluationEngine: 'GREAT_EXPECTATIONS',
    isBlocking: true,
    alertSeverity: 'CRITICAL_P1',
    autoRemediationAction: 'RETRY_STAGE_WITH_BACKOFF'
  },
  {
    assertionId: 'ASSERT-RIU-088',
    ruleName: 'ReferentialIntegrityAndUniqueness Assertion Check #88',
    category: 'primary key uniqueness constraints',
    targetTable: 'enterprise_data_mart.table_28',
    targetColumn: 'column_attr_8',
    evaluationEngine: 'SQL_ASSERTION',
    isBlocking: false,
    alertSeverity: 'HIGH_P2',
    autoRemediationAction: 'QUARANTINE_ROW_TO_DLQ'
  },
  {
    assertionId: 'ASSERT-RIU-089',
    ruleName: 'ReferentialIntegrityAndUniqueness Assertion Check #89',
    category: 'and orphan record counters',
    targetTable: 'enterprise_data_mart.table_29',
    targetColumn: 'column_attr_9',
    evaluationEngine: 'GREAT_EXPECTATIONS',
    isBlocking: false,
    alertSeverity: 'HIGH_P2',
    autoRemediationAction: 'RETRY_STAGE_WITH_BACKOFF'
  },
  {
    assertionId: 'ASSERT-RIU-090',
    ruleName: 'ReferentialIntegrityAndUniqueness Assertion Check #90',
    category: 'Foreign key existence verification',
    targetTable: 'enterprise_data_mart.table_0',
    targetColumn: 'column_attr_10',
    evaluationEngine: 'SQL_ASSERTION',
    isBlocking: true,
    alertSeverity: 'CRITICAL_P1',
    autoRemediationAction: 'QUARANTINE_ROW_TO_DLQ'
  },
  {
    assertionId: 'ASSERT-RIU-091',
    ruleName: 'ReferentialIntegrityAndUniqueness Assertion Check #91',
    category: 'primary key uniqueness constraints',
    targetTable: 'enterprise_data_mart.table_1',
    targetColumn: 'column_attr_11',
    evaluationEngine: 'GREAT_EXPECTATIONS',
    isBlocking: false,
    alertSeverity: 'HIGH_P2',
    autoRemediationAction: 'RETRY_STAGE_WITH_BACKOFF'
  },
  {
    assertionId: 'ASSERT-RIU-092',
    ruleName: 'ReferentialIntegrityAndUniqueness Assertion Check #92',
    category: 'and orphan record counters',
    targetTable: 'enterprise_data_mart.table_2',
    targetColumn: 'column_attr_12',
    evaluationEngine: 'SQL_ASSERTION',
    isBlocking: false,
    alertSeverity: 'HIGH_P2',
    autoRemediationAction: 'QUARANTINE_ROW_TO_DLQ'
  },
  {
    assertionId: 'ASSERT-RIU-093',
    ruleName: 'ReferentialIntegrityAndUniqueness Assertion Check #93',
    category: 'Foreign key existence verification',
    targetTable: 'enterprise_data_mart.table_3',
    targetColumn: 'column_attr_13',
    evaluationEngine: 'GREAT_EXPECTATIONS',
    isBlocking: true,
    alertSeverity: 'CRITICAL_P1',
    autoRemediationAction: 'RETRY_STAGE_WITH_BACKOFF'
  },
  {
    assertionId: 'ASSERT-RIU-094',
    ruleName: 'ReferentialIntegrityAndUniqueness Assertion Check #94',
    category: 'primary key uniqueness constraints',
    targetTable: 'enterprise_data_mart.table_4',
    targetColumn: 'column_attr_14',
    evaluationEngine: 'SQL_ASSERTION',
    isBlocking: false,
    alertSeverity: 'HIGH_P2',
    autoRemediationAction: 'QUARANTINE_ROW_TO_DLQ'
  },
  {
    assertionId: 'ASSERT-RIU-095',
    ruleName: 'ReferentialIntegrityAndUniqueness Assertion Check #95',
    category: 'and orphan record counters',
    targetTable: 'enterprise_data_mart.table_5',
    targetColumn: 'column_attr_15',
    evaluationEngine: 'GREAT_EXPECTATIONS',
    isBlocking: false,
    alertSeverity: 'HIGH_P2',
    autoRemediationAction: 'RETRY_STAGE_WITH_BACKOFF'
  },
  {
    assertionId: 'ASSERT-RIU-096',
    ruleName: 'ReferentialIntegrityAndUniqueness Assertion Check #96',
    category: 'Foreign key existence verification',
    targetTable: 'enterprise_data_mart.table_6',
    targetColumn: 'column_attr_16',
    evaluationEngine: 'SQL_ASSERTION',
    isBlocking: true,
    alertSeverity: 'CRITICAL_P1',
    autoRemediationAction: 'QUARANTINE_ROW_TO_DLQ'
  },
  {
    assertionId: 'ASSERT-RIU-097',
    ruleName: 'ReferentialIntegrityAndUniqueness Assertion Check #97',
    category: 'primary key uniqueness constraints',
    targetTable: 'enterprise_data_mart.table_7',
    targetColumn: 'column_attr_17',
    evaluationEngine: 'GREAT_EXPECTATIONS',
    isBlocking: false,
    alertSeverity: 'HIGH_P2',
    autoRemediationAction: 'RETRY_STAGE_WITH_BACKOFF'
  },
  {
    assertionId: 'ASSERT-RIU-098',
    ruleName: 'ReferentialIntegrityAndUniqueness Assertion Check #98',
    category: 'and orphan record counters',
    targetTable: 'enterprise_data_mart.table_8',
    targetColumn: 'column_attr_18',
    evaluationEngine: 'SQL_ASSERTION',
    isBlocking: false,
    alertSeverity: 'HIGH_P2',
    autoRemediationAction: 'QUARANTINE_ROW_TO_DLQ'
  },
  {
    assertionId: 'ASSERT-RIU-099',
    ruleName: 'ReferentialIntegrityAndUniqueness Assertion Check #99',
    category: 'Foreign key existence verification',
    targetTable: 'enterprise_data_mart.table_9',
    targetColumn: 'column_attr_19',
    evaluationEngine: 'GREAT_EXPECTATIONS',
    isBlocking: true,
    alertSeverity: 'CRITICAL_P1',
    autoRemediationAction: 'RETRY_STAGE_WITH_BACKOFF'
  },
  {
    assertionId: 'ASSERT-RIU-100',
    ruleName: 'ReferentialIntegrityAndUniqueness Assertion Check #100',
    category: 'primary key uniqueness constraints',
    targetTable: 'enterprise_data_mart.table_10',
    targetColumn: 'column_attr_0',
    evaluationEngine: 'SQL_ASSERTION',
    isBlocking: false,
    alertSeverity: 'HIGH_P2',
    autoRemediationAction: 'QUARANTINE_ROW_TO_DLQ'
  },
  {
    assertionId: 'ASSERT-RIU-101',
    ruleName: 'ReferentialIntegrityAndUniqueness Assertion Check #101',
    category: 'and orphan record counters',
    targetTable: 'enterprise_data_mart.table_11',
    targetColumn: 'column_attr_1',
    evaluationEngine: 'GREAT_EXPECTATIONS',
    isBlocking: false,
    alertSeverity: 'HIGH_P2',
    autoRemediationAction: 'RETRY_STAGE_WITH_BACKOFF'
  },
  {
    assertionId: 'ASSERT-RIU-102',
    ruleName: 'ReferentialIntegrityAndUniqueness Assertion Check #102',
    category: 'Foreign key existence verification',
    targetTable: 'enterprise_data_mart.table_12',
    targetColumn: 'column_attr_2',
    evaluationEngine: 'SQL_ASSERTION',
    isBlocking: true,
    alertSeverity: 'CRITICAL_P1',
    autoRemediationAction: 'QUARANTINE_ROW_TO_DLQ'
  },
  {
    assertionId: 'ASSERT-RIU-103',
    ruleName: 'ReferentialIntegrityAndUniqueness Assertion Check #103',
    category: 'primary key uniqueness constraints',
    targetTable: 'enterprise_data_mart.table_13',
    targetColumn: 'column_attr_3',
    evaluationEngine: 'GREAT_EXPECTATIONS',
    isBlocking: false,
    alertSeverity: 'HIGH_P2',
    autoRemediationAction: 'RETRY_STAGE_WITH_BACKOFF'
  },
  {
    assertionId: 'ASSERT-RIU-104',
    ruleName: 'ReferentialIntegrityAndUniqueness Assertion Check #104',
    category: 'and orphan record counters',
    targetTable: 'enterprise_data_mart.table_14',
    targetColumn: 'column_attr_4',
    evaluationEngine: 'SQL_ASSERTION',
    isBlocking: false,
    alertSeverity: 'HIGH_P2',
    autoRemediationAction: 'QUARANTINE_ROW_TO_DLQ'
  },
  {
    assertionId: 'ASSERT-RIU-105',
    ruleName: 'ReferentialIntegrityAndUniqueness Assertion Check #105',
    category: 'Foreign key existence verification',
    targetTable: 'enterprise_data_mart.table_15',
    targetColumn: 'column_attr_5',
    evaluationEngine: 'GREAT_EXPECTATIONS',
    isBlocking: true,
    alertSeverity: 'CRITICAL_P1',
    autoRemediationAction: 'RETRY_STAGE_WITH_BACKOFF'
  },
  {
    assertionId: 'ASSERT-RIU-106',
    ruleName: 'ReferentialIntegrityAndUniqueness Assertion Check #106',
    category: 'primary key uniqueness constraints',
    targetTable: 'enterprise_data_mart.table_16',
    targetColumn: 'column_attr_6',
    evaluationEngine: 'SQL_ASSERTION',
    isBlocking: false,
    alertSeverity: 'HIGH_P2',
    autoRemediationAction: 'QUARANTINE_ROW_TO_DLQ'
  },
  {
    assertionId: 'ASSERT-RIU-107',
    ruleName: 'ReferentialIntegrityAndUniqueness Assertion Check #107',
    category: 'and orphan record counters',
    targetTable: 'enterprise_data_mart.table_17',
    targetColumn: 'column_attr_7',
    evaluationEngine: 'GREAT_EXPECTATIONS',
    isBlocking: false,
    alertSeverity: 'HIGH_P2',
    autoRemediationAction: 'RETRY_STAGE_WITH_BACKOFF'
  },
  {
    assertionId: 'ASSERT-RIU-108',
    ruleName: 'ReferentialIntegrityAndUniqueness Assertion Check #108',
    category: 'Foreign key existence verification',
    targetTable: 'enterprise_data_mart.table_18',
    targetColumn: 'column_attr_8',
    evaluationEngine: 'SQL_ASSERTION',
    isBlocking: true,
    alertSeverity: 'CRITICAL_P1',
    autoRemediationAction: 'QUARANTINE_ROW_TO_DLQ'
  },
  {
    assertionId: 'ASSERT-RIU-109',
    ruleName: 'ReferentialIntegrityAndUniqueness Assertion Check #109',
    category: 'primary key uniqueness constraints',
    targetTable: 'enterprise_data_mart.table_19',
    targetColumn: 'column_attr_9',
    evaluationEngine: 'GREAT_EXPECTATIONS',
    isBlocking: false,
    alertSeverity: 'HIGH_P2',
    autoRemediationAction: 'RETRY_STAGE_WITH_BACKOFF'
  },
  {
    assertionId: 'ASSERT-RIU-110',
    ruleName: 'ReferentialIntegrityAndUniqueness Assertion Check #110',
    category: 'and orphan record counters',
    targetTable: 'enterprise_data_mart.table_20',
    targetColumn: 'column_attr_10',
    evaluationEngine: 'SQL_ASSERTION',
    isBlocking: false,
    alertSeverity: 'HIGH_P2',
    autoRemediationAction: 'QUARANTINE_ROW_TO_DLQ'
  },
  {
    assertionId: 'ASSERT-RIU-111',
    ruleName: 'ReferentialIntegrityAndUniqueness Assertion Check #111',
    category: 'Foreign key existence verification',
    targetTable: 'enterprise_data_mart.table_21',
    targetColumn: 'column_attr_11',
    evaluationEngine: 'GREAT_EXPECTATIONS',
    isBlocking: true,
    alertSeverity: 'CRITICAL_P1',
    autoRemediationAction: 'RETRY_STAGE_WITH_BACKOFF'
  },
  {
    assertionId: 'ASSERT-RIU-112',
    ruleName: 'ReferentialIntegrityAndUniqueness Assertion Check #112',
    category: 'primary key uniqueness constraints',
    targetTable: 'enterprise_data_mart.table_22',
    targetColumn: 'column_attr_12',
    evaluationEngine: 'SQL_ASSERTION',
    isBlocking: false,
    alertSeverity: 'HIGH_P2',
    autoRemediationAction: 'QUARANTINE_ROW_TO_DLQ'
  },
  {
    assertionId: 'ASSERT-RIU-113',
    ruleName: 'ReferentialIntegrityAndUniqueness Assertion Check #113',
    category: 'and orphan record counters',
    targetTable: 'enterprise_data_mart.table_23',
    targetColumn: 'column_attr_13',
    evaluationEngine: 'GREAT_EXPECTATIONS',
    isBlocking: false,
    alertSeverity: 'HIGH_P2',
    autoRemediationAction: 'RETRY_STAGE_WITH_BACKOFF'
  },
  {
    assertionId: 'ASSERT-RIU-114',
    ruleName: 'ReferentialIntegrityAndUniqueness Assertion Check #114',
    category: 'Foreign key existence verification',
    targetTable: 'enterprise_data_mart.table_24',
    targetColumn: 'column_attr_14',
    evaluationEngine: 'SQL_ASSERTION',
    isBlocking: true,
    alertSeverity: 'CRITICAL_P1',
    autoRemediationAction: 'QUARANTINE_ROW_TO_DLQ'
  },
  {
    assertionId: 'ASSERT-RIU-115',
    ruleName: 'ReferentialIntegrityAndUniqueness Assertion Check #115',
    category: 'primary key uniqueness constraints',
    targetTable: 'enterprise_data_mart.table_25',
    targetColumn: 'column_attr_15',
    evaluationEngine: 'GREAT_EXPECTATIONS',
    isBlocking: false,
    alertSeverity: 'HIGH_P2',
    autoRemediationAction: 'RETRY_STAGE_WITH_BACKOFF'
  },
  {
    assertionId: 'ASSERT-RIU-116',
    ruleName: 'ReferentialIntegrityAndUniqueness Assertion Check #116',
    category: 'and orphan record counters',
    targetTable: 'enterprise_data_mart.table_26',
    targetColumn: 'column_attr_16',
    evaluationEngine: 'SQL_ASSERTION',
    isBlocking: false,
    alertSeverity: 'HIGH_P2',
    autoRemediationAction: 'QUARANTINE_ROW_TO_DLQ'
  },
  {
    assertionId: 'ASSERT-RIU-117',
    ruleName: 'ReferentialIntegrityAndUniqueness Assertion Check #117',
    category: 'Foreign key existence verification',
    targetTable: 'enterprise_data_mart.table_27',
    targetColumn: 'column_attr_17',
    evaluationEngine: 'GREAT_EXPECTATIONS',
    isBlocking: true,
    alertSeverity: 'CRITICAL_P1',
    autoRemediationAction: 'RETRY_STAGE_WITH_BACKOFF'
  },
  {
    assertionId: 'ASSERT-RIU-118',
    ruleName: 'ReferentialIntegrityAndUniqueness Assertion Check #118',
    category: 'primary key uniqueness constraints',
    targetTable: 'enterprise_data_mart.table_28',
    targetColumn: 'column_attr_18',
    evaluationEngine: 'SQL_ASSERTION',
    isBlocking: false,
    alertSeverity: 'HIGH_P2',
    autoRemediationAction: 'QUARANTINE_ROW_TO_DLQ'
  },
  {
    assertionId: 'ASSERT-RIU-119',
    ruleName: 'ReferentialIntegrityAndUniqueness Assertion Check #119',
    category: 'and orphan record counters',
    targetTable: 'enterprise_data_mart.table_29',
    targetColumn: 'column_attr_19',
    evaluationEngine: 'GREAT_EXPECTATIONS',
    isBlocking: false,
    alertSeverity: 'HIGH_P2',
    autoRemediationAction: 'RETRY_STAGE_WITH_BACKOFF'
  },
  {
    assertionId: 'ASSERT-RIU-120',
    ruleName: 'ReferentialIntegrityAndUniqueness Assertion Check #120',
    category: 'Foreign key existence verification',
    targetTable: 'enterprise_data_mart.table_0',
    targetColumn: 'column_attr_0',
    evaluationEngine: 'SQL_ASSERTION',
    isBlocking: true,
    alertSeverity: 'CRITICAL_P1',
    autoRemediationAction: 'QUARANTINE_ROW_TO_DLQ'
  },
  {
    assertionId: 'ASSERT-RIU-121',
    ruleName: 'ReferentialIntegrityAndUniqueness Assertion Check #121',
    category: 'primary key uniqueness constraints',
    targetTable: 'enterprise_data_mart.table_1',
    targetColumn: 'column_attr_1',
    evaluationEngine: 'GREAT_EXPECTATIONS',
    isBlocking: false,
    alertSeverity: 'HIGH_P2',
    autoRemediationAction: 'RETRY_STAGE_WITH_BACKOFF'
  },
  {
    assertionId: 'ASSERT-RIU-122',
    ruleName: 'ReferentialIntegrityAndUniqueness Assertion Check #122',
    category: 'and orphan record counters',
    targetTable: 'enterprise_data_mart.table_2',
    targetColumn: 'column_attr_2',
    evaluationEngine: 'SQL_ASSERTION',
    isBlocking: false,
    alertSeverity: 'HIGH_P2',
    autoRemediationAction: 'QUARANTINE_ROW_TO_DLQ'
  },
  {
    assertionId: 'ASSERT-RIU-123',
    ruleName: 'ReferentialIntegrityAndUniqueness Assertion Check #123',
    category: 'Foreign key existence verification',
    targetTable: 'enterprise_data_mart.table_3',
    targetColumn: 'column_attr_3',
    evaluationEngine: 'GREAT_EXPECTATIONS',
    isBlocking: true,
    alertSeverity: 'CRITICAL_P1',
    autoRemediationAction: 'RETRY_STAGE_WITH_BACKOFF'
  },
  {
    assertionId: 'ASSERT-RIU-124',
    ruleName: 'ReferentialIntegrityAndUniqueness Assertion Check #124',
    category: 'primary key uniqueness constraints',
    targetTable: 'enterprise_data_mart.table_4',
    targetColumn: 'column_attr_4',
    evaluationEngine: 'SQL_ASSERTION',
    isBlocking: false,
    alertSeverity: 'HIGH_P2',
    autoRemediationAction: 'QUARANTINE_ROW_TO_DLQ'
  },
  {
    assertionId: 'ASSERT-RIU-125',
    ruleName: 'ReferentialIntegrityAndUniqueness Assertion Check #125',
    category: 'and orphan record counters',
    targetTable: 'enterprise_data_mart.table_5',
    targetColumn: 'column_attr_5',
    evaluationEngine: 'GREAT_EXPECTATIONS',
    isBlocking: false,
    alertSeverity: 'HIGH_P2',
    autoRemediationAction: 'RETRY_STAGE_WITH_BACKOFF'
  },
  {
    assertionId: 'ASSERT-RIU-126',
    ruleName: 'ReferentialIntegrityAndUniqueness Assertion Check #126',
    category: 'Foreign key existence verification',
    targetTable: 'enterprise_data_mart.table_6',
    targetColumn: 'column_attr_6',
    evaluationEngine: 'SQL_ASSERTION',
    isBlocking: true,
    alertSeverity: 'CRITICAL_P1',
    autoRemediationAction: 'QUARANTINE_ROW_TO_DLQ'
  },
  {
    assertionId: 'ASSERT-RIU-127',
    ruleName: 'ReferentialIntegrityAndUniqueness Assertion Check #127',
    category: 'primary key uniqueness constraints',
    targetTable: 'enterprise_data_mart.table_7',
    targetColumn: 'column_attr_7',
    evaluationEngine: 'GREAT_EXPECTATIONS',
    isBlocking: false,
    alertSeverity: 'HIGH_P2',
    autoRemediationAction: 'RETRY_STAGE_WITH_BACKOFF'
  },
  {
    assertionId: 'ASSERT-RIU-128',
    ruleName: 'ReferentialIntegrityAndUniqueness Assertion Check #128',
    category: 'and orphan record counters',
    targetTable: 'enterprise_data_mart.table_8',
    targetColumn: 'column_attr_8',
    evaluationEngine: 'SQL_ASSERTION',
    isBlocking: false,
    alertSeverity: 'HIGH_P2',
    autoRemediationAction: 'QUARANTINE_ROW_TO_DLQ'
  },
  {
    assertionId: 'ASSERT-RIU-129',
    ruleName: 'ReferentialIntegrityAndUniqueness Assertion Check #129',
    category: 'Foreign key existence verification',
    targetTable: 'enterprise_data_mart.table_9',
    targetColumn: 'column_attr_9',
    evaluationEngine: 'GREAT_EXPECTATIONS',
    isBlocking: true,
    alertSeverity: 'CRITICAL_P1',
    autoRemediationAction: 'RETRY_STAGE_WITH_BACKOFF'
  },
  {
    assertionId: 'ASSERT-RIU-130',
    ruleName: 'ReferentialIntegrityAndUniqueness Assertion Check #130',
    category: 'primary key uniqueness constraints',
    targetTable: 'enterprise_data_mart.table_10',
    targetColumn: 'column_attr_10',
    evaluationEngine: 'SQL_ASSERTION',
    isBlocking: false,
    alertSeverity: 'HIGH_P2',
    autoRemediationAction: 'QUARANTINE_ROW_TO_DLQ'
  },
  {
    assertionId: 'ASSERT-RIU-131',
    ruleName: 'ReferentialIntegrityAndUniqueness Assertion Check #131',
    category: 'and orphan record counters',
    targetTable: 'enterprise_data_mart.table_11',
    targetColumn: 'column_attr_11',
    evaluationEngine: 'GREAT_EXPECTATIONS',
    isBlocking: false,
    alertSeverity: 'HIGH_P2',
    autoRemediationAction: 'RETRY_STAGE_WITH_BACKOFF'
  },
  {
    assertionId: 'ASSERT-RIU-132',
    ruleName: 'ReferentialIntegrityAndUniqueness Assertion Check #132',
    category: 'Foreign key existence verification',
    targetTable: 'enterprise_data_mart.table_12',
    targetColumn: 'column_attr_12',
    evaluationEngine: 'SQL_ASSERTION',
    isBlocking: true,
    alertSeverity: 'CRITICAL_P1',
    autoRemediationAction: 'QUARANTINE_ROW_TO_DLQ'
  },
  {
    assertionId: 'ASSERT-RIU-133',
    ruleName: 'ReferentialIntegrityAndUniqueness Assertion Check #133',
    category: 'primary key uniqueness constraints',
    targetTable: 'enterprise_data_mart.table_13',
    targetColumn: 'column_attr_13',
    evaluationEngine: 'GREAT_EXPECTATIONS',
    isBlocking: false,
    alertSeverity: 'HIGH_P2',
    autoRemediationAction: 'RETRY_STAGE_WITH_BACKOFF'
  },
  {
    assertionId: 'ASSERT-RIU-134',
    ruleName: 'ReferentialIntegrityAndUniqueness Assertion Check #134',
    category: 'and orphan record counters',
    targetTable: 'enterprise_data_mart.table_14',
    targetColumn: 'column_attr_14',
    evaluationEngine: 'SQL_ASSERTION',
    isBlocking: false,
    alertSeverity: 'HIGH_P2',
    autoRemediationAction: 'QUARANTINE_ROW_TO_DLQ'
  },
  {
    assertionId: 'ASSERT-RIU-135',
    ruleName: 'ReferentialIntegrityAndUniqueness Assertion Check #135',
    category: 'Foreign key existence verification',
    targetTable: 'enterprise_data_mart.table_15',
    targetColumn: 'column_attr_15',
    evaluationEngine: 'GREAT_EXPECTATIONS',
    isBlocking: true,
    alertSeverity: 'CRITICAL_P1',
    autoRemediationAction: 'RETRY_STAGE_WITH_BACKOFF'
  },
  {
    assertionId: 'ASSERT-RIU-136',
    ruleName: 'ReferentialIntegrityAndUniqueness Assertion Check #136',
    category: 'primary key uniqueness constraints',
    targetTable: 'enterprise_data_mart.table_16',
    targetColumn: 'column_attr_16',
    evaluationEngine: 'SQL_ASSERTION',
    isBlocking: false,
    alertSeverity: 'HIGH_P2',
    autoRemediationAction: 'QUARANTINE_ROW_TO_DLQ'
  },
  {
    assertionId: 'ASSERT-RIU-137',
    ruleName: 'ReferentialIntegrityAndUniqueness Assertion Check #137',
    category: 'and orphan record counters',
    targetTable: 'enterprise_data_mart.table_17',
    targetColumn: 'column_attr_17',
    evaluationEngine: 'GREAT_EXPECTATIONS',
    isBlocking: false,
    alertSeverity: 'HIGH_P2',
    autoRemediationAction: 'RETRY_STAGE_WITH_BACKOFF'
  },
  {
    assertionId: 'ASSERT-RIU-138',
    ruleName: 'ReferentialIntegrityAndUniqueness Assertion Check #138',
    category: 'Foreign key existence verification',
    targetTable: 'enterprise_data_mart.table_18',
    targetColumn: 'column_attr_18',
    evaluationEngine: 'SQL_ASSERTION',
    isBlocking: true,
    alertSeverity: 'CRITICAL_P1',
    autoRemediationAction: 'QUARANTINE_ROW_TO_DLQ'
  },
  {
    assertionId: 'ASSERT-RIU-139',
    ruleName: 'ReferentialIntegrityAndUniqueness Assertion Check #139',
    category: 'primary key uniqueness constraints',
    targetTable: 'enterprise_data_mart.table_19',
    targetColumn: 'column_attr_19',
    evaluationEngine: 'GREAT_EXPECTATIONS',
    isBlocking: false,
    alertSeverity: 'HIGH_P2',
    autoRemediationAction: 'RETRY_STAGE_WITH_BACKOFF'
  },
  {
    assertionId: 'ASSERT-RIU-140',
    ruleName: 'ReferentialIntegrityAndUniqueness Assertion Check #140',
    category: 'and orphan record counters',
    targetTable: 'enterprise_data_mart.table_20',
    targetColumn: 'column_attr_0',
    evaluationEngine: 'SQL_ASSERTION',
    isBlocking: false,
    alertSeverity: 'HIGH_P2',
    autoRemediationAction: 'QUARANTINE_ROW_TO_DLQ'
  },
  {
    assertionId: 'ASSERT-RIU-141',
    ruleName: 'ReferentialIntegrityAndUniqueness Assertion Check #141',
    category: 'Foreign key existence verification',
    targetTable: 'enterprise_data_mart.table_21',
    targetColumn: 'column_attr_1',
    evaluationEngine: 'GREAT_EXPECTATIONS',
    isBlocking: true,
    alertSeverity: 'CRITICAL_P1',
    autoRemediationAction: 'RETRY_STAGE_WITH_BACKOFF'
  },
  {
    assertionId: 'ASSERT-RIU-142',
    ruleName: 'ReferentialIntegrityAndUniqueness Assertion Check #142',
    category: 'primary key uniqueness constraints',
    targetTable: 'enterprise_data_mart.table_22',
    targetColumn: 'column_attr_2',
    evaluationEngine: 'SQL_ASSERTION',
    isBlocking: false,
    alertSeverity: 'HIGH_P2',
    autoRemediationAction: 'QUARANTINE_ROW_TO_DLQ'
  },
  {
    assertionId: 'ASSERT-RIU-143',
    ruleName: 'ReferentialIntegrityAndUniqueness Assertion Check #143',
    category: 'and orphan record counters',
    targetTable: 'enterprise_data_mart.table_23',
    targetColumn: 'column_attr_3',
    evaluationEngine: 'GREAT_EXPECTATIONS',
    isBlocking: false,
    alertSeverity: 'HIGH_P2',
    autoRemediationAction: 'RETRY_STAGE_WITH_BACKOFF'
  },
  {
    assertionId: 'ASSERT-RIU-144',
    ruleName: 'ReferentialIntegrityAndUniqueness Assertion Check #144',
    category: 'Foreign key existence verification',
    targetTable: 'enterprise_data_mart.table_24',
    targetColumn: 'column_attr_4',
    evaluationEngine: 'SQL_ASSERTION',
    isBlocking: true,
    alertSeverity: 'CRITICAL_P1',
    autoRemediationAction: 'QUARANTINE_ROW_TO_DLQ'
  },
  {
    assertionId: 'ASSERT-RIU-145',
    ruleName: 'ReferentialIntegrityAndUniqueness Assertion Check #145',
    category: 'primary key uniqueness constraints',
    targetTable: 'enterprise_data_mart.table_25',
    targetColumn: 'column_attr_5',
    evaluationEngine: 'GREAT_EXPECTATIONS',
    isBlocking: false,
    alertSeverity: 'HIGH_P2',
    autoRemediationAction: 'RETRY_STAGE_WITH_BACKOFF'
  },
  {
    assertionId: 'ASSERT-RIU-146',
    ruleName: 'ReferentialIntegrityAndUniqueness Assertion Check #146',
    category: 'and orphan record counters',
    targetTable: 'enterprise_data_mart.table_26',
    targetColumn: 'column_attr_6',
    evaluationEngine: 'SQL_ASSERTION',
    isBlocking: false,
    alertSeverity: 'HIGH_P2',
    autoRemediationAction: 'QUARANTINE_ROW_TO_DLQ'
  },
  {
    assertionId: 'ASSERT-RIU-147',
    ruleName: 'ReferentialIntegrityAndUniqueness Assertion Check #147',
    category: 'Foreign key existence verification',
    targetTable: 'enterprise_data_mart.table_27',
    targetColumn: 'column_attr_7',
    evaluationEngine: 'GREAT_EXPECTATIONS',
    isBlocking: true,
    alertSeverity: 'CRITICAL_P1',
    autoRemediationAction: 'RETRY_STAGE_WITH_BACKOFF'
  },
  {
    assertionId: 'ASSERT-RIU-148',
    ruleName: 'ReferentialIntegrityAndUniqueness Assertion Check #148',
    category: 'primary key uniqueness constraints',
    targetTable: 'enterprise_data_mart.table_28',
    targetColumn: 'column_attr_8',
    evaluationEngine: 'SQL_ASSERTION',
    isBlocking: false,
    alertSeverity: 'HIGH_P2',
    autoRemediationAction: 'QUARANTINE_ROW_TO_DLQ'
  },
  {
    assertionId: 'ASSERT-RIU-149',
    ruleName: 'ReferentialIntegrityAndUniqueness Assertion Check #149',
    category: 'and orphan record counters',
    targetTable: 'enterprise_data_mart.table_29',
    targetColumn: 'column_attr_9',
    evaluationEngine: 'GREAT_EXPECTATIONS',
    isBlocking: false,
    alertSeverity: 'HIGH_P2',
    autoRemediationAction: 'RETRY_STAGE_WITH_BACKOFF'
  },
  {
    assertionId: 'ASSERT-RIU-150',
    ruleName: 'ReferentialIntegrityAndUniqueness Assertion Check #150',
    category: 'Foreign key existence verification',
    targetTable: 'enterprise_data_mart.table_0',
    targetColumn: 'column_attr_10',
    evaluationEngine: 'SQL_ASSERTION',
    isBlocking: true,
    alertSeverity: 'CRITICAL_P1',
    autoRemediationAction: 'QUARANTINE_ROW_TO_DLQ'
  }
];
