/**
 * Data Quality & Great Expectations Ruleset: SchemaDriftAndNullChecks
 * Description: Strict column data type assertions, unexpected new column detectors, and null ratio constraints
 */

export interface DataQualityRule {
  assertionId: string;
  ruleName: string;
  category: string;
  targetTable: string;
  targetColumn: string;
  evaluationEngine: string;
  isBlocking: boolean;
  alertSeverity: string;
  autoRemediationAction: string;
}

export const QUALITY_SDN_DATASET: DataQualityRule[] = [
  {
    assertionId: 'ASSERT-SDN-001',
    ruleName: 'SchemaDriftAndNullChecks Assertion Check #1',
    category: 'unexpected new column detectors',
    targetTable: 'enterprise_data_mart.table_1',
    targetColumn: 'column_attr_1',
    evaluationEngine: 'GREAT_EXPECTATIONS',
    isBlocking: false,
    alertSeverity: 'HIGH_P2',
    autoRemediationAction: 'RETRY_STAGE_WITH_BACKOFF'
  },
  {
    assertionId: 'ASSERT-SDN-002',
    ruleName: 'SchemaDriftAndNullChecks Assertion Check #2',
    category: 'and null ratio constraints',
    targetTable: 'enterprise_data_mart.table_2',
    targetColumn: 'column_attr_2',
    evaluationEngine: 'SQL_ASSERTION',
    isBlocking: false,
    alertSeverity: 'HIGH_P2',
    autoRemediationAction: 'QUARANTINE_ROW_TO_DLQ'
  },
  {
    assertionId: 'ASSERT-SDN-003',
    ruleName: 'SchemaDriftAndNullChecks Assertion Check #3',
    category: 'Strict column data type assertions',
    targetTable: 'enterprise_data_mart.table_3',
    targetColumn: 'column_attr_3',
    evaluationEngine: 'GREAT_EXPECTATIONS',
    isBlocking: true,
    alertSeverity: 'CRITICAL_P1',
    autoRemediationAction: 'RETRY_STAGE_WITH_BACKOFF'
  },
  {
    assertionId: 'ASSERT-SDN-004',
    ruleName: 'SchemaDriftAndNullChecks Assertion Check #4',
    category: 'unexpected new column detectors',
    targetTable: 'enterprise_data_mart.table_4',
    targetColumn: 'column_attr_4',
    evaluationEngine: 'SQL_ASSERTION',
    isBlocking: false,
    alertSeverity: 'HIGH_P2',
    autoRemediationAction: 'QUARANTINE_ROW_TO_DLQ'
  },
  {
    assertionId: 'ASSERT-SDN-005',
    ruleName: 'SchemaDriftAndNullChecks Assertion Check #5',
    category: 'and null ratio constraints',
    targetTable: 'enterprise_data_mart.table_5',
    targetColumn: 'column_attr_5',
    evaluationEngine: 'GREAT_EXPECTATIONS',
    isBlocking: false,
    alertSeverity: 'HIGH_P2',
    autoRemediationAction: 'RETRY_STAGE_WITH_BACKOFF'
  },
  {
    assertionId: 'ASSERT-SDN-006',
    ruleName: 'SchemaDriftAndNullChecks Assertion Check #6',
    category: 'Strict column data type assertions',
    targetTable: 'enterprise_data_mart.table_6',
    targetColumn: 'column_attr_6',
    evaluationEngine: 'SQL_ASSERTION',
    isBlocking: true,
    alertSeverity: 'CRITICAL_P1',
    autoRemediationAction: 'QUARANTINE_ROW_TO_DLQ'
  },
  {
    assertionId: 'ASSERT-SDN-007',
    ruleName: 'SchemaDriftAndNullChecks Assertion Check #7',
    category: 'unexpected new column detectors',
    targetTable: 'enterprise_data_mart.table_7',
    targetColumn: 'column_attr_7',
    evaluationEngine: 'GREAT_EXPECTATIONS',
    isBlocking: false,
    alertSeverity: 'HIGH_P2',
    autoRemediationAction: 'RETRY_STAGE_WITH_BACKOFF'
  },
  {
    assertionId: 'ASSERT-SDN-008',
    ruleName: 'SchemaDriftAndNullChecks Assertion Check #8',
    category: 'and null ratio constraints',
    targetTable: 'enterprise_data_mart.table_8',
    targetColumn: 'column_attr_8',
    evaluationEngine: 'SQL_ASSERTION',
    isBlocking: false,
    alertSeverity: 'HIGH_P2',
    autoRemediationAction: 'QUARANTINE_ROW_TO_DLQ'
  },
  {
    assertionId: 'ASSERT-SDN-009',
    ruleName: 'SchemaDriftAndNullChecks Assertion Check #9',
    category: 'Strict column data type assertions',
    targetTable: 'enterprise_data_mart.table_9',
    targetColumn: 'column_attr_9',
    evaluationEngine: 'GREAT_EXPECTATIONS',
    isBlocking: true,
    alertSeverity: 'CRITICAL_P1',
    autoRemediationAction: 'RETRY_STAGE_WITH_BACKOFF'
  },
  {
    assertionId: 'ASSERT-SDN-010',
    ruleName: 'SchemaDriftAndNullChecks Assertion Check #10',
    category: 'unexpected new column detectors',
    targetTable: 'enterprise_data_mart.table_10',
    targetColumn: 'column_attr_10',
    evaluationEngine: 'SQL_ASSERTION',
    isBlocking: false,
    alertSeverity: 'HIGH_P2',
    autoRemediationAction: 'QUARANTINE_ROW_TO_DLQ'
  },
  {
    assertionId: 'ASSERT-SDN-011',
    ruleName: 'SchemaDriftAndNullChecks Assertion Check #11',
    category: 'and null ratio constraints',
    targetTable: 'enterprise_data_mart.table_11',
    targetColumn: 'column_attr_11',
    evaluationEngine: 'GREAT_EXPECTATIONS',
    isBlocking: false,
    alertSeverity: 'HIGH_P2',
    autoRemediationAction: 'RETRY_STAGE_WITH_BACKOFF'
  },
  {
    assertionId: 'ASSERT-SDN-012',
    ruleName: 'SchemaDriftAndNullChecks Assertion Check #12',
    category: 'Strict column data type assertions',
    targetTable: 'enterprise_data_mart.table_12',
    targetColumn: 'column_attr_12',
    evaluationEngine: 'SQL_ASSERTION',
    isBlocking: true,
    alertSeverity: 'CRITICAL_P1',
    autoRemediationAction: 'QUARANTINE_ROW_TO_DLQ'
  },
  {
    assertionId: 'ASSERT-SDN-013',
    ruleName: 'SchemaDriftAndNullChecks Assertion Check #13',
    category: 'unexpected new column detectors',
    targetTable: 'enterprise_data_mart.table_13',
    targetColumn: 'column_attr_13',
    evaluationEngine: 'GREAT_EXPECTATIONS',
    isBlocking: false,
    alertSeverity: 'HIGH_P2',
    autoRemediationAction: 'RETRY_STAGE_WITH_BACKOFF'
  },
  {
    assertionId: 'ASSERT-SDN-014',
    ruleName: 'SchemaDriftAndNullChecks Assertion Check #14',
    category: 'and null ratio constraints',
    targetTable: 'enterprise_data_mart.table_14',
    targetColumn: 'column_attr_14',
    evaluationEngine: 'SQL_ASSERTION',
    isBlocking: false,
    alertSeverity: 'HIGH_P2',
    autoRemediationAction: 'QUARANTINE_ROW_TO_DLQ'
  },
  {
    assertionId: 'ASSERT-SDN-015',
    ruleName: 'SchemaDriftAndNullChecks Assertion Check #15',
    category: 'Strict column data type assertions',
    targetTable: 'enterprise_data_mart.table_15',
    targetColumn: 'column_attr_15',
    evaluationEngine: 'GREAT_EXPECTATIONS',
    isBlocking: true,
    alertSeverity: 'CRITICAL_P1',
    autoRemediationAction: 'RETRY_STAGE_WITH_BACKOFF'
  },
  {
    assertionId: 'ASSERT-SDN-016',
    ruleName: 'SchemaDriftAndNullChecks Assertion Check #16',
    category: 'unexpected new column detectors',
    targetTable: 'enterprise_data_mart.table_16',
    targetColumn: 'column_attr_16',
    evaluationEngine: 'SQL_ASSERTION',
    isBlocking: false,
    alertSeverity: 'HIGH_P2',
    autoRemediationAction: 'QUARANTINE_ROW_TO_DLQ'
  },
  {
    assertionId: 'ASSERT-SDN-017',
    ruleName: 'SchemaDriftAndNullChecks Assertion Check #17',
    category: 'and null ratio constraints',
    targetTable: 'enterprise_data_mart.table_17',
    targetColumn: 'column_attr_17',
    evaluationEngine: 'GREAT_EXPECTATIONS',
    isBlocking: false,
    alertSeverity: 'HIGH_P2',
    autoRemediationAction: 'RETRY_STAGE_WITH_BACKOFF'
  },
  {
    assertionId: 'ASSERT-SDN-018',
    ruleName: 'SchemaDriftAndNullChecks Assertion Check #18',
    category: 'Strict column data type assertions',
    targetTable: 'enterprise_data_mart.table_18',
    targetColumn: 'column_attr_18',
    evaluationEngine: 'SQL_ASSERTION',
    isBlocking: true,
    alertSeverity: 'CRITICAL_P1',
    autoRemediationAction: 'QUARANTINE_ROW_TO_DLQ'
  },
  {
    assertionId: 'ASSERT-SDN-019',
    ruleName: 'SchemaDriftAndNullChecks Assertion Check #19',
    category: 'unexpected new column detectors',
    targetTable: 'enterprise_data_mart.table_19',
    targetColumn: 'column_attr_19',
    evaluationEngine: 'GREAT_EXPECTATIONS',
    isBlocking: false,
    alertSeverity: 'HIGH_P2',
    autoRemediationAction: 'RETRY_STAGE_WITH_BACKOFF'
  },
  {
    assertionId: 'ASSERT-SDN-020',
    ruleName: 'SchemaDriftAndNullChecks Assertion Check #20',
    category: 'and null ratio constraints',
    targetTable: 'enterprise_data_mart.table_20',
    targetColumn: 'column_attr_0',
    evaluationEngine: 'SQL_ASSERTION',
    isBlocking: false,
    alertSeverity: 'HIGH_P2',
    autoRemediationAction: 'QUARANTINE_ROW_TO_DLQ'
  },
  {
    assertionId: 'ASSERT-SDN-021',
    ruleName: 'SchemaDriftAndNullChecks Assertion Check #21',
    category: 'Strict column data type assertions',
    targetTable: 'enterprise_data_mart.table_21',
    targetColumn: 'column_attr_1',
    evaluationEngine: 'GREAT_EXPECTATIONS',
    isBlocking: true,
    alertSeverity: 'CRITICAL_P1',
    autoRemediationAction: 'RETRY_STAGE_WITH_BACKOFF'
  },
  {
    assertionId: 'ASSERT-SDN-022',
    ruleName: 'SchemaDriftAndNullChecks Assertion Check #22',
    category: 'unexpected new column detectors',
    targetTable: 'enterprise_data_mart.table_22',
    targetColumn: 'column_attr_2',
    evaluationEngine: 'SQL_ASSERTION',
    isBlocking: false,
    alertSeverity: 'HIGH_P2',
    autoRemediationAction: 'QUARANTINE_ROW_TO_DLQ'
  },
  {
    assertionId: 'ASSERT-SDN-023',
    ruleName: 'SchemaDriftAndNullChecks Assertion Check #23',
    category: 'and null ratio constraints',
    targetTable: 'enterprise_data_mart.table_23',
    targetColumn: 'column_attr_3',
    evaluationEngine: 'GREAT_EXPECTATIONS',
    isBlocking: false,
    alertSeverity: 'HIGH_P2',
    autoRemediationAction: 'RETRY_STAGE_WITH_BACKOFF'
  },
  {
    assertionId: 'ASSERT-SDN-024',
    ruleName: 'SchemaDriftAndNullChecks Assertion Check #24',
    category: 'Strict column data type assertions',
    targetTable: 'enterprise_data_mart.table_24',
    targetColumn: 'column_attr_4',
    evaluationEngine: 'SQL_ASSERTION',
    isBlocking: true,
    alertSeverity: 'CRITICAL_P1',
    autoRemediationAction: 'QUARANTINE_ROW_TO_DLQ'
  },
  {
    assertionId: 'ASSERT-SDN-025',
    ruleName: 'SchemaDriftAndNullChecks Assertion Check #25',
    category: 'unexpected new column detectors',
    targetTable: 'enterprise_data_mart.table_25',
    targetColumn: 'column_attr_5',
    evaluationEngine: 'GREAT_EXPECTATIONS',
    isBlocking: false,
    alertSeverity: 'HIGH_P2',
    autoRemediationAction: 'RETRY_STAGE_WITH_BACKOFF'
  },
  {
    assertionId: 'ASSERT-SDN-026',
    ruleName: 'SchemaDriftAndNullChecks Assertion Check #26',
    category: 'and null ratio constraints',
    targetTable: 'enterprise_data_mart.table_26',
    targetColumn: 'column_attr_6',
    evaluationEngine: 'SQL_ASSERTION',
    isBlocking: false,
    alertSeverity: 'HIGH_P2',
    autoRemediationAction: 'QUARANTINE_ROW_TO_DLQ'
  },
  {
    assertionId: 'ASSERT-SDN-027',
    ruleName: 'SchemaDriftAndNullChecks Assertion Check #27',
    category: 'Strict column data type assertions',
    targetTable: 'enterprise_data_mart.table_27',
    targetColumn: 'column_attr_7',
    evaluationEngine: 'GREAT_EXPECTATIONS',
    isBlocking: true,
    alertSeverity: 'CRITICAL_P1',
    autoRemediationAction: 'RETRY_STAGE_WITH_BACKOFF'
  },
  {
    assertionId: 'ASSERT-SDN-028',
    ruleName: 'SchemaDriftAndNullChecks Assertion Check #28',
    category: 'unexpected new column detectors',
    targetTable: 'enterprise_data_mart.table_28',
    targetColumn: 'column_attr_8',
    evaluationEngine: 'SQL_ASSERTION',
    isBlocking: false,
    alertSeverity: 'HIGH_P2',
    autoRemediationAction: 'QUARANTINE_ROW_TO_DLQ'
  },
  {
    assertionId: 'ASSERT-SDN-029',
    ruleName: 'SchemaDriftAndNullChecks Assertion Check #29',
    category: 'and null ratio constraints',
    targetTable: 'enterprise_data_mart.table_29',
    targetColumn: 'column_attr_9',
    evaluationEngine: 'GREAT_EXPECTATIONS',
    isBlocking: false,
    alertSeverity: 'HIGH_P2',
    autoRemediationAction: 'RETRY_STAGE_WITH_BACKOFF'
  },
  {
    assertionId: 'ASSERT-SDN-030',
    ruleName: 'SchemaDriftAndNullChecks Assertion Check #30',
    category: 'Strict column data type assertions',
    targetTable: 'enterprise_data_mart.table_0',
    targetColumn: 'column_attr_10',
    evaluationEngine: 'SQL_ASSERTION',
    isBlocking: true,
    alertSeverity: 'CRITICAL_P1',
    autoRemediationAction: 'QUARANTINE_ROW_TO_DLQ'
  },
  {
    assertionId: 'ASSERT-SDN-031',
    ruleName: 'SchemaDriftAndNullChecks Assertion Check #31',
    category: 'unexpected new column detectors',
    targetTable: 'enterprise_data_mart.table_1',
    targetColumn: 'column_attr_11',
    evaluationEngine: 'GREAT_EXPECTATIONS',
    isBlocking: false,
    alertSeverity: 'HIGH_P2',
    autoRemediationAction: 'RETRY_STAGE_WITH_BACKOFF'
  },
  {
    assertionId: 'ASSERT-SDN-032',
    ruleName: 'SchemaDriftAndNullChecks Assertion Check #32',
    category: 'and null ratio constraints',
    targetTable: 'enterprise_data_mart.table_2',
    targetColumn: 'column_attr_12',
    evaluationEngine: 'SQL_ASSERTION',
    isBlocking: false,
    alertSeverity: 'HIGH_P2',
    autoRemediationAction: 'QUARANTINE_ROW_TO_DLQ'
  },
  {
    assertionId: 'ASSERT-SDN-033',
    ruleName: 'SchemaDriftAndNullChecks Assertion Check #33',
    category: 'Strict column data type assertions',
    targetTable: 'enterprise_data_mart.table_3',
    targetColumn: 'column_attr_13',
    evaluationEngine: 'GREAT_EXPECTATIONS',
    isBlocking: true,
    alertSeverity: 'CRITICAL_P1',
    autoRemediationAction: 'RETRY_STAGE_WITH_BACKOFF'
  },
  {
    assertionId: 'ASSERT-SDN-034',
    ruleName: 'SchemaDriftAndNullChecks Assertion Check #34',
    category: 'unexpected new column detectors',
    targetTable: 'enterprise_data_mart.table_4',
    targetColumn: 'column_attr_14',
    evaluationEngine: 'SQL_ASSERTION',
    isBlocking: false,
    alertSeverity: 'HIGH_P2',
    autoRemediationAction: 'QUARANTINE_ROW_TO_DLQ'
  },
  {
    assertionId: 'ASSERT-SDN-035',
    ruleName: 'SchemaDriftAndNullChecks Assertion Check #35',
    category: 'and null ratio constraints',
    targetTable: 'enterprise_data_mart.table_5',
    targetColumn: 'column_attr_15',
    evaluationEngine: 'GREAT_EXPECTATIONS',
    isBlocking: false,
    alertSeverity: 'HIGH_P2',
    autoRemediationAction: 'RETRY_STAGE_WITH_BACKOFF'
  },
  {
    assertionId: 'ASSERT-SDN-036',
    ruleName: 'SchemaDriftAndNullChecks Assertion Check #36',
    category: 'Strict column data type assertions',
    targetTable: 'enterprise_data_mart.table_6',
    targetColumn: 'column_attr_16',
    evaluationEngine: 'SQL_ASSERTION',
    isBlocking: true,
    alertSeverity: 'CRITICAL_P1',
    autoRemediationAction: 'QUARANTINE_ROW_TO_DLQ'
  },
  {
    assertionId: 'ASSERT-SDN-037',
    ruleName: 'SchemaDriftAndNullChecks Assertion Check #37',
    category: 'unexpected new column detectors',
    targetTable: 'enterprise_data_mart.table_7',
    targetColumn: 'column_attr_17',
    evaluationEngine: 'GREAT_EXPECTATIONS',
    isBlocking: false,
    alertSeverity: 'HIGH_P2',
    autoRemediationAction: 'RETRY_STAGE_WITH_BACKOFF'
  },
  {
    assertionId: 'ASSERT-SDN-038',
    ruleName: 'SchemaDriftAndNullChecks Assertion Check #38',
    category: 'and null ratio constraints',
    targetTable: 'enterprise_data_mart.table_8',
    targetColumn: 'column_attr_18',
    evaluationEngine: 'SQL_ASSERTION',
    isBlocking: false,
    alertSeverity: 'HIGH_P2',
    autoRemediationAction: 'QUARANTINE_ROW_TO_DLQ'
  },
  {
    assertionId: 'ASSERT-SDN-039',
    ruleName: 'SchemaDriftAndNullChecks Assertion Check #39',
    category: 'Strict column data type assertions',
    targetTable: 'enterprise_data_mart.table_9',
    targetColumn: 'column_attr_19',
    evaluationEngine: 'GREAT_EXPECTATIONS',
    isBlocking: true,
    alertSeverity: 'CRITICAL_P1',
    autoRemediationAction: 'RETRY_STAGE_WITH_BACKOFF'
  },
  {
    assertionId: 'ASSERT-SDN-040',
    ruleName: 'SchemaDriftAndNullChecks Assertion Check #40',
    category: 'unexpected new column detectors',
    targetTable: 'enterprise_data_mart.table_10',
    targetColumn: 'column_attr_0',
    evaluationEngine: 'SQL_ASSERTION',
    isBlocking: false,
    alertSeverity: 'HIGH_P2',
    autoRemediationAction: 'QUARANTINE_ROW_TO_DLQ'
  },
  {
    assertionId: 'ASSERT-SDN-041',
    ruleName: 'SchemaDriftAndNullChecks Assertion Check #41',
    category: 'and null ratio constraints',
    targetTable: 'enterprise_data_mart.table_11',
    targetColumn: 'column_attr_1',
    evaluationEngine: 'GREAT_EXPECTATIONS',
    isBlocking: false,
    alertSeverity: 'HIGH_P2',
    autoRemediationAction: 'RETRY_STAGE_WITH_BACKOFF'
  },
  {
    assertionId: 'ASSERT-SDN-042',
    ruleName: 'SchemaDriftAndNullChecks Assertion Check #42',
    category: 'Strict column data type assertions',
    targetTable: 'enterprise_data_mart.table_12',
    targetColumn: 'column_attr_2',
    evaluationEngine: 'SQL_ASSERTION',
    isBlocking: true,
    alertSeverity: 'CRITICAL_P1',
    autoRemediationAction: 'QUARANTINE_ROW_TO_DLQ'
  },
  {
    assertionId: 'ASSERT-SDN-043',
    ruleName: 'SchemaDriftAndNullChecks Assertion Check #43',
    category: 'unexpected new column detectors',
    targetTable: 'enterprise_data_mart.table_13',
    targetColumn: 'column_attr_3',
    evaluationEngine: 'GREAT_EXPECTATIONS',
    isBlocking: false,
    alertSeverity: 'HIGH_P2',
    autoRemediationAction: 'RETRY_STAGE_WITH_BACKOFF'
  },
  {
    assertionId: 'ASSERT-SDN-044',
    ruleName: 'SchemaDriftAndNullChecks Assertion Check #44',
    category: 'and null ratio constraints',
    targetTable: 'enterprise_data_mart.table_14',
    targetColumn: 'column_attr_4',
    evaluationEngine: 'SQL_ASSERTION',
    isBlocking: false,
    alertSeverity: 'HIGH_P2',
    autoRemediationAction: 'QUARANTINE_ROW_TO_DLQ'
  },
  {
    assertionId: 'ASSERT-SDN-045',
    ruleName: 'SchemaDriftAndNullChecks Assertion Check #45',
    category: 'Strict column data type assertions',
    targetTable: 'enterprise_data_mart.table_15',
    targetColumn: 'column_attr_5',
    evaluationEngine: 'GREAT_EXPECTATIONS',
    isBlocking: true,
    alertSeverity: 'CRITICAL_P1',
    autoRemediationAction: 'RETRY_STAGE_WITH_BACKOFF'
  },
  {
    assertionId: 'ASSERT-SDN-046',
    ruleName: 'SchemaDriftAndNullChecks Assertion Check #46',
    category: 'unexpected new column detectors',
    targetTable: 'enterprise_data_mart.table_16',
    targetColumn: 'column_attr_6',
    evaluationEngine: 'SQL_ASSERTION',
    isBlocking: false,
    alertSeverity: 'HIGH_P2',
    autoRemediationAction: 'QUARANTINE_ROW_TO_DLQ'
  },
  {
    assertionId: 'ASSERT-SDN-047',
    ruleName: 'SchemaDriftAndNullChecks Assertion Check #47',
    category: 'and null ratio constraints',
    targetTable: 'enterprise_data_mart.table_17',
    targetColumn: 'column_attr_7',
    evaluationEngine: 'GREAT_EXPECTATIONS',
    isBlocking: false,
    alertSeverity: 'HIGH_P2',
    autoRemediationAction: 'RETRY_STAGE_WITH_BACKOFF'
  },
  {
    assertionId: 'ASSERT-SDN-048',
    ruleName: 'SchemaDriftAndNullChecks Assertion Check #48',
    category: 'Strict column data type assertions',
    targetTable: 'enterprise_data_mart.table_18',
    targetColumn: 'column_attr_8',
    evaluationEngine: 'SQL_ASSERTION',
    isBlocking: true,
    alertSeverity: 'CRITICAL_P1',
    autoRemediationAction: 'QUARANTINE_ROW_TO_DLQ'
  },
  {
    assertionId: 'ASSERT-SDN-049',
    ruleName: 'SchemaDriftAndNullChecks Assertion Check #49',
    category: 'unexpected new column detectors',
    targetTable: 'enterprise_data_mart.table_19',
    targetColumn: 'column_attr_9',
    evaluationEngine: 'GREAT_EXPECTATIONS',
    isBlocking: false,
    alertSeverity: 'HIGH_P2',
    autoRemediationAction: 'RETRY_STAGE_WITH_BACKOFF'
  },
  {
    assertionId: 'ASSERT-SDN-050',
    ruleName: 'SchemaDriftAndNullChecks Assertion Check #50',
    category: 'and null ratio constraints',
    targetTable: 'enterprise_data_mart.table_20',
    targetColumn: 'column_attr_10',
    evaluationEngine: 'SQL_ASSERTION',
    isBlocking: false,
    alertSeverity: 'HIGH_P2',
    autoRemediationAction: 'QUARANTINE_ROW_TO_DLQ'
  },
  {
    assertionId: 'ASSERT-SDN-051',
    ruleName: 'SchemaDriftAndNullChecks Assertion Check #51',
    category: 'Strict column data type assertions',
    targetTable: 'enterprise_data_mart.table_21',
    targetColumn: 'column_attr_11',
    evaluationEngine: 'GREAT_EXPECTATIONS',
    isBlocking: true,
    alertSeverity: 'CRITICAL_P1',
    autoRemediationAction: 'RETRY_STAGE_WITH_BACKOFF'
  },
  {
    assertionId: 'ASSERT-SDN-052',
    ruleName: 'SchemaDriftAndNullChecks Assertion Check #52',
    category: 'unexpected new column detectors',
    targetTable: 'enterprise_data_mart.table_22',
    targetColumn: 'column_attr_12',
    evaluationEngine: 'SQL_ASSERTION',
    isBlocking: false,
    alertSeverity: 'HIGH_P2',
    autoRemediationAction: 'QUARANTINE_ROW_TO_DLQ'
  },
  {
    assertionId: 'ASSERT-SDN-053',
    ruleName: 'SchemaDriftAndNullChecks Assertion Check #53',
    category: 'and null ratio constraints',
    targetTable: 'enterprise_data_mart.table_23',
    targetColumn: 'column_attr_13',
    evaluationEngine: 'GREAT_EXPECTATIONS',
    isBlocking: false,
    alertSeverity: 'HIGH_P2',
    autoRemediationAction: 'RETRY_STAGE_WITH_BACKOFF'
  },
  {
    assertionId: 'ASSERT-SDN-054',
    ruleName: 'SchemaDriftAndNullChecks Assertion Check #54',
    category: 'Strict column data type assertions',
    targetTable: 'enterprise_data_mart.table_24',
    targetColumn: 'column_attr_14',
    evaluationEngine: 'SQL_ASSERTION',
    isBlocking: true,
    alertSeverity: 'CRITICAL_P1',
    autoRemediationAction: 'QUARANTINE_ROW_TO_DLQ'
  },
  {
    assertionId: 'ASSERT-SDN-055',
    ruleName: 'SchemaDriftAndNullChecks Assertion Check #55',
    category: 'unexpected new column detectors',
    targetTable: 'enterprise_data_mart.table_25',
    targetColumn: 'column_attr_15',
    evaluationEngine: 'GREAT_EXPECTATIONS',
    isBlocking: false,
    alertSeverity: 'HIGH_P2',
    autoRemediationAction: 'RETRY_STAGE_WITH_BACKOFF'
  },
  {
    assertionId: 'ASSERT-SDN-056',
    ruleName: 'SchemaDriftAndNullChecks Assertion Check #56',
    category: 'and null ratio constraints',
    targetTable: 'enterprise_data_mart.table_26',
    targetColumn: 'column_attr_16',
    evaluationEngine: 'SQL_ASSERTION',
    isBlocking: false,
    alertSeverity: 'HIGH_P2',
    autoRemediationAction: 'QUARANTINE_ROW_TO_DLQ'
  },
  {
    assertionId: 'ASSERT-SDN-057',
    ruleName: 'SchemaDriftAndNullChecks Assertion Check #57',
    category: 'Strict column data type assertions',
    targetTable: 'enterprise_data_mart.table_27',
    targetColumn: 'column_attr_17',
    evaluationEngine: 'GREAT_EXPECTATIONS',
    isBlocking: true,
    alertSeverity: 'CRITICAL_P1',
    autoRemediationAction: 'RETRY_STAGE_WITH_BACKOFF'
  },
  {
    assertionId: 'ASSERT-SDN-058',
    ruleName: 'SchemaDriftAndNullChecks Assertion Check #58',
    category: 'unexpected new column detectors',
    targetTable: 'enterprise_data_mart.table_28',
    targetColumn: 'column_attr_18',
    evaluationEngine: 'SQL_ASSERTION',
    isBlocking: false,
    alertSeverity: 'HIGH_P2',
    autoRemediationAction: 'QUARANTINE_ROW_TO_DLQ'
  },
  {
    assertionId: 'ASSERT-SDN-059',
    ruleName: 'SchemaDriftAndNullChecks Assertion Check #59',
    category: 'and null ratio constraints',
    targetTable: 'enterprise_data_mart.table_29',
    targetColumn: 'column_attr_19',
    evaluationEngine: 'GREAT_EXPECTATIONS',
    isBlocking: false,
    alertSeverity: 'HIGH_P2',
    autoRemediationAction: 'RETRY_STAGE_WITH_BACKOFF'
  },
  {
    assertionId: 'ASSERT-SDN-060',
    ruleName: 'SchemaDriftAndNullChecks Assertion Check #60',
    category: 'Strict column data type assertions',
    targetTable: 'enterprise_data_mart.table_0',
    targetColumn: 'column_attr_0',
    evaluationEngine: 'SQL_ASSERTION',
    isBlocking: true,
    alertSeverity: 'CRITICAL_P1',
    autoRemediationAction: 'QUARANTINE_ROW_TO_DLQ'
  },
  {
    assertionId: 'ASSERT-SDN-061',
    ruleName: 'SchemaDriftAndNullChecks Assertion Check #61',
    category: 'unexpected new column detectors',
    targetTable: 'enterprise_data_mart.table_1',
    targetColumn: 'column_attr_1',
    evaluationEngine: 'GREAT_EXPECTATIONS',
    isBlocking: false,
    alertSeverity: 'HIGH_P2',
    autoRemediationAction: 'RETRY_STAGE_WITH_BACKOFF'
  },
  {
    assertionId: 'ASSERT-SDN-062',
    ruleName: 'SchemaDriftAndNullChecks Assertion Check #62',
    category: 'and null ratio constraints',
    targetTable: 'enterprise_data_mart.table_2',
    targetColumn: 'column_attr_2',
    evaluationEngine: 'SQL_ASSERTION',
    isBlocking: false,
    alertSeverity: 'HIGH_P2',
    autoRemediationAction: 'QUARANTINE_ROW_TO_DLQ'
  },
  {
    assertionId: 'ASSERT-SDN-063',
    ruleName: 'SchemaDriftAndNullChecks Assertion Check #63',
    category: 'Strict column data type assertions',
    targetTable: 'enterprise_data_mart.table_3',
    targetColumn: 'column_attr_3',
    evaluationEngine: 'GREAT_EXPECTATIONS',
    isBlocking: true,
    alertSeverity: 'CRITICAL_P1',
    autoRemediationAction: 'RETRY_STAGE_WITH_BACKOFF'
  },
  {
    assertionId: 'ASSERT-SDN-064',
    ruleName: 'SchemaDriftAndNullChecks Assertion Check #64',
    category: 'unexpected new column detectors',
    targetTable: 'enterprise_data_mart.table_4',
    targetColumn: 'column_attr_4',
    evaluationEngine: 'SQL_ASSERTION',
    isBlocking: false,
    alertSeverity: 'HIGH_P2',
    autoRemediationAction: 'QUARANTINE_ROW_TO_DLQ'
  },
  {
    assertionId: 'ASSERT-SDN-065',
    ruleName: 'SchemaDriftAndNullChecks Assertion Check #65',
    category: 'and null ratio constraints',
    targetTable: 'enterprise_data_mart.table_5',
    targetColumn: 'column_attr_5',
    evaluationEngine: 'GREAT_EXPECTATIONS',
    isBlocking: false,
    alertSeverity: 'HIGH_P2',
    autoRemediationAction: 'RETRY_STAGE_WITH_BACKOFF'
  },
  {
    assertionId: 'ASSERT-SDN-066',
    ruleName: 'SchemaDriftAndNullChecks Assertion Check #66',
    category: 'Strict column data type assertions',
    targetTable: 'enterprise_data_mart.table_6',
    targetColumn: 'column_attr_6',
    evaluationEngine: 'SQL_ASSERTION',
    isBlocking: true,
    alertSeverity: 'CRITICAL_P1',
    autoRemediationAction: 'QUARANTINE_ROW_TO_DLQ'
  },
  {
    assertionId: 'ASSERT-SDN-067',
    ruleName: 'SchemaDriftAndNullChecks Assertion Check #67',
    category: 'unexpected new column detectors',
    targetTable: 'enterprise_data_mart.table_7',
    targetColumn: 'column_attr_7',
    evaluationEngine: 'GREAT_EXPECTATIONS',
    isBlocking: false,
    alertSeverity: 'HIGH_P2',
    autoRemediationAction: 'RETRY_STAGE_WITH_BACKOFF'
  },
  {
    assertionId: 'ASSERT-SDN-068',
    ruleName: 'SchemaDriftAndNullChecks Assertion Check #68',
    category: 'and null ratio constraints',
    targetTable: 'enterprise_data_mart.table_8',
    targetColumn: 'column_attr_8',
    evaluationEngine: 'SQL_ASSERTION',
    isBlocking: false,
    alertSeverity: 'HIGH_P2',
    autoRemediationAction: 'QUARANTINE_ROW_TO_DLQ'
  },
  {
    assertionId: 'ASSERT-SDN-069',
    ruleName: 'SchemaDriftAndNullChecks Assertion Check #69',
    category: 'Strict column data type assertions',
    targetTable: 'enterprise_data_mart.table_9',
    targetColumn: 'column_attr_9',
    evaluationEngine: 'GREAT_EXPECTATIONS',
    isBlocking: true,
    alertSeverity: 'CRITICAL_P1',
    autoRemediationAction: 'RETRY_STAGE_WITH_BACKOFF'
  },
  {
    assertionId: 'ASSERT-SDN-070',
    ruleName: 'SchemaDriftAndNullChecks Assertion Check #70',
    category: 'unexpected new column detectors',
    targetTable: 'enterprise_data_mart.table_10',
    targetColumn: 'column_attr_10',
    evaluationEngine: 'SQL_ASSERTION',
    isBlocking: false,
    alertSeverity: 'HIGH_P2',
    autoRemediationAction: 'QUARANTINE_ROW_TO_DLQ'
  },
  {
    assertionId: 'ASSERT-SDN-071',
    ruleName: 'SchemaDriftAndNullChecks Assertion Check #71',
    category: 'and null ratio constraints',
    targetTable: 'enterprise_data_mart.table_11',
    targetColumn: 'column_attr_11',
    evaluationEngine: 'GREAT_EXPECTATIONS',
    isBlocking: false,
    alertSeverity: 'HIGH_P2',
    autoRemediationAction: 'RETRY_STAGE_WITH_BACKOFF'
  },
  {
    assertionId: 'ASSERT-SDN-072',
    ruleName: 'SchemaDriftAndNullChecks Assertion Check #72',
    category: 'Strict column data type assertions',
    targetTable: 'enterprise_data_mart.table_12',
    targetColumn: 'column_attr_12',
    evaluationEngine: 'SQL_ASSERTION',
    isBlocking: true,
    alertSeverity: 'CRITICAL_P1',
    autoRemediationAction: 'QUARANTINE_ROW_TO_DLQ'
  },
  {
    assertionId: 'ASSERT-SDN-073',
    ruleName: 'SchemaDriftAndNullChecks Assertion Check #73',
    category: 'unexpected new column detectors',
    targetTable: 'enterprise_data_mart.table_13',
    targetColumn: 'column_attr_13',
    evaluationEngine: 'GREAT_EXPECTATIONS',
    isBlocking: false,
    alertSeverity: 'HIGH_P2',
    autoRemediationAction: 'RETRY_STAGE_WITH_BACKOFF'
  },
  {
    assertionId: 'ASSERT-SDN-074',
    ruleName: 'SchemaDriftAndNullChecks Assertion Check #74',
    category: 'and null ratio constraints',
    targetTable: 'enterprise_data_mart.table_14',
    targetColumn: 'column_attr_14',
    evaluationEngine: 'SQL_ASSERTION',
    isBlocking: false,
    alertSeverity: 'HIGH_P2',
    autoRemediationAction: 'QUARANTINE_ROW_TO_DLQ'
  },
  {
    assertionId: 'ASSERT-SDN-075',
    ruleName: 'SchemaDriftAndNullChecks Assertion Check #75',
    category: 'Strict column data type assertions',
    targetTable: 'enterprise_data_mart.table_15',
    targetColumn: 'column_attr_15',
    evaluationEngine: 'GREAT_EXPECTATIONS',
    isBlocking: true,
    alertSeverity: 'CRITICAL_P1',
    autoRemediationAction: 'RETRY_STAGE_WITH_BACKOFF'
  },
  {
    assertionId: 'ASSERT-SDN-076',
    ruleName: 'SchemaDriftAndNullChecks Assertion Check #76',
    category: 'unexpected new column detectors',
    targetTable: 'enterprise_data_mart.table_16',
    targetColumn: 'column_attr_16',
    evaluationEngine: 'SQL_ASSERTION',
    isBlocking: false,
    alertSeverity: 'HIGH_P2',
    autoRemediationAction: 'QUARANTINE_ROW_TO_DLQ'
  },
  {
    assertionId: 'ASSERT-SDN-077',
    ruleName: 'SchemaDriftAndNullChecks Assertion Check #77',
    category: 'and null ratio constraints',
    targetTable: 'enterprise_data_mart.table_17',
    targetColumn: 'column_attr_17',
    evaluationEngine: 'GREAT_EXPECTATIONS',
    isBlocking: false,
    alertSeverity: 'HIGH_P2',
    autoRemediationAction: 'RETRY_STAGE_WITH_BACKOFF'
  },
  {
    assertionId: 'ASSERT-SDN-078',
    ruleName: 'SchemaDriftAndNullChecks Assertion Check #78',
    category: 'Strict column data type assertions',
    targetTable: 'enterprise_data_mart.table_18',
    targetColumn: 'column_attr_18',
    evaluationEngine: 'SQL_ASSERTION',
    isBlocking: true,
    alertSeverity: 'CRITICAL_P1',
    autoRemediationAction: 'QUARANTINE_ROW_TO_DLQ'
  },
  {
    assertionId: 'ASSERT-SDN-079',
    ruleName: 'SchemaDriftAndNullChecks Assertion Check #79',
    category: 'unexpected new column detectors',
    targetTable: 'enterprise_data_mart.table_19',
    targetColumn: 'column_attr_19',
    evaluationEngine: 'GREAT_EXPECTATIONS',
    isBlocking: false,
    alertSeverity: 'HIGH_P2',
    autoRemediationAction: 'RETRY_STAGE_WITH_BACKOFF'
  },
  {
    assertionId: 'ASSERT-SDN-080',
    ruleName: 'SchemaDriftAndNullChecks Assertion Check #80',
    category: 'and null ratio constraints',
    targetTable: 'enterprise_data_mart.table_20',
    targetColumn: 'column_attr_0',
    evaluationEngine: 'SQL_ASSERTION',
    isBlocking: false,
    alertSeverity: 'HIGH_P2',
    autoRemediationAction: 'QUARANTINE_ROW_TO_DLQ'
  },
  {
    assertionId: 'ASSERT-SDN-081',
    ruleName: 'SchemaDriftAndNullChecks Assertion Check #81',
    category: 'Strict column data type assertions',
    targetTable: 'enterprise_data_mart.table_21',
    targetColumn: 'column_attr_1',
    evaluationEngine: 'GREAT_EXPECTATIONS',
    isBlocking: true,
    alertSeverity: 'CRITICAL_P1',
    autoRemediationAction: 'RETRY_STAGE_WITH_BACKOFF'
  },
  {
    assertionId: 'ASSERT-SDN-082',
    ruleName: 'SchemaDriftAndNullChecks Assertion Check #82',
    category: 'unexpected new column detectors',
    targetTable: 'enterprise_data_mart.table_22',
    targetColumn: 'column_attr_2',
    evaluationEngine: 'SQL_ASSERTION',
    isBlocking: false,
    alertSeverity: 'HIGH_P2',
    autoRemediationAction: 'QUARANTINE_ROW_TO_DLQ'
  },
  {
    assertionId: 'ASSERT-SDN-083',
    ruleName: 'SchemaDriftAndNullChecks Assertion Check #83',
    category: 'and null ratio constraints',
    targetTable: 'enterprise_data_mart.table_23',
    targetColumn: 'column_attr_3',
    evaluationEngine: 'GREAT_EXPECTATIONS',
    isBlocking: false,
    alertSeverity: 'HIGH_P2',
    autoRemediationAction: 'RETRY_STAGE_WITH_BACKOFF'
  },
  {
    assertionId: 'ASSERT-SDN-084',
    ruleName: 'SchemaDriftAndNullChecks Assertion Check #84',
    category: 'Strict column data type assertions',
    targetTable: 'enterprise_data_mart.table_24',
    targetColumn: 'column_attr_4',
    evaluationEngine: 'SQL_ASSERTION',
    isBlocking: true,
    alertSeverity: 'CRITICAL_P1',
    autoRemediationAction: 'QUARANTINE_ROW_TO_DLQ'
  },
  {
    assertionId: 'ASSERT-SDN-085',
    ruleName: 'SchemaDriftAndNullChecks Assertion Check #85',
    category: 'unexpected new column detectors',
    targetTable: 'enterprise_data_mart.table_25',
    targetColumn: 'column_attr_5',
    evaluationEngine: 'GREAT_EXPECTATIONS',
    isBlocking: false,
    alertSeverity: 'HIGH_P2',
    autoRemediationAction: 'RETRY_STAGE_WITH_BACKOFF'
  },
  {
    assertionId: 'ASSERT-SDN-086',
    ruleName: 'SchemaDriftAndNullChecks Assertion Check #86',
    category: 'and null ratio constraints',
    targetTable: 'enterprise_data_mart.table_26',
    targetColumn: 'column_attr_6',
    evaluationEngine: 'SQL_ASSERTION',
    isBlocking: false,
    alertSeverity: 'HIGH_P2',
    autoRemediationAction: 'QUARANTINE_ROW_TO_DLQ'
  },
  {
    assertionId: 'ASSERT-SDN-087',
    ruleName: 'SchemaDriftAndNullChecks Assertion Check #87',
    category: 'Strict column data type assertions',
    targetTable: 'enterprise_data_mart.table_27',
    targetColumn: 'column_attr_7',
    evaluationEngine: 'GREAT_EXPECTATIONS',
    isBlocking: true,
    alertSeverity: 'CRITICAL_P1',
    autoRemediationAction: 'RETRY_STAGE_WITH_BACKOFF'
  },
  {
    assertionId: 'ASSERT-SDN-088',
    ruleName: 'SchemaDriftAndNullChecks Assertion Check #88',
    category: 'unexpected new column detectors',
    targetTable: 'enterprise_data_mart.table_28',
    targetColumn: 'column_attr_8',
    evaluationEngine: 'SQL_ASSERTION',
    isBlocking: false,
    alertSeverity: 'HIGH_P2',
    autoRemediationAction: 'QUARANTINE_ROW_TO_DLQ'
  },
  {
    assertionId: 'ASSERT-SDN-089',
    ruleName: 'SchemaDriftAndNullChecks Assertion Check #89',
    category: 'and null ratio constraints',
    targetTable: 'enterprise_data_mart.table_29',
    targetColumn: 'column_attr_9',
    evaluationEngine: 'GREAT_EXPECTATIONS',
    isBlocking: false,
    alertSeverity: 'HIGH_P2',
    autoRemediationAction: 'RETRY_STAGE_WITH_BACKOFF'
  },
  {
    assertionId: 'ASSERT-SDN-090',
    ruleName: 'SchemaDriftAndNullChecks Assertion Check #90',
    category: 'Strict column data type assertions',
    targetTable: 'enterprise_data_mart.table_0',
    targetColumn: 'column_attr_10',
    evaluationEngine: 'SQL_ASSERTION',
    isBlocking: true,
    alertSeverity: 'CRITICAL_P1',
    autoRemediationAction: 'QUARANTINE_ROW_TO_DLQ'
  },
  {
    assertionId: 'ASSERT-SDN-091',
    ruleName: 'SchemaDriftAndNullChecks Assertion Check #91',
    category: 'unexpected new column detectors',
    targetTable: 'enterprise_data_mart.table_1',
    targetColumn: 'column_attr_11',
    evaluationEngine: 'GREAT_EXPECTATIONS',
    isBlocking: false,
    alertSeverity: 'HIGH_P2',
    autoRemediationAction: 'RETRY_STAGE_WITH_BACKOFF'
  },
  {
    assertionId: 'ASSERT-SDN-092',
    ruleName: 'SchemaDriftAndNullChecks Assertion Check #92',
    category: 'and null ratio constraints',
    targetTable: 'enterprise_data_mart.table_2',
    targetColumn: 'column_attr_12',
    evaluationEngine: 'SQL_ASSERTION',
    isBlocking: false,
    alertSeverity: 'HIGH_P2',
    autoRemediationAction: 'QUARANTINE_ROW_TO_DLQ'
  },
  {
    assertionId: 'ASSERT-SDN-093',
    ruleName: 'SchemaDriftAndNullChecks Assertion Check #93',
    category: 'Strict column data type assertions',
    targetTable: 'enterprise_data_mart.table_3',
    targetColumn: 'column_attr_13',
    evaluationEngine: 'GREAT_EXPECTATIONS',
    isBlocking: true,
    alertSeverity: 'CRITICAL_P1',
    autoRemediationAction: 'RETRY_STAGE_WITH_BACKOFF'
  },
  {
    assertionId: 'ASSERT-SDN-094',
    ruleName: 'SchemaDriftAndNullChecks Assertion Check #94',
    category: 'unexpected new column detectors',
    targetTable: 'enterprise_data_mart.table_4',
    targetColumn: 'column_attr_14',
    evaluationEngine: 'SQL_ASSERTION',
    isBlocking: false,
    alertSeverity: 'HIGH_P2',
    autoRemediationAction: 'QUARANTINE_ROW_TO_DLQ'
  },
  {
    assertionId: 'ASSERT-SDN-095',
    ruleName: 'SchemaDriftAndNullChecks Assertion Check #95',
    category: 'and null ratio constraints',
    targetTable: 'enterprise_data_mart.table_5',
    targetColumn: 'column_attr_15',
    evaluationEngine: 'GREAT_EXPECTATIONS',
    isBlocking: false,
    alertSeverity: 'HIGH_P2',
    autoRemediationAction: 'RETRY_STAGE_WITH_BACKOFF'
  },
  {
    assertionId: 'ASSERT-SDN-096',
    ruleName: 'SchemaDriftAndNullChecks Assertion Check #96',
    category: 'Strict column data type assertions',
    targetTable: 'enterprise_data_mart.table_6',
    targetColumn: 'column_attr_16',
    evaluationEngine: 'SQL_ASSERTION',
    isBlocking: true,
    alertSeverity: 'CRITICAL_P1',
    autoRemediationAction: 'QUARANTINE_ROW_TO_DLQ'
  },
  {
    assertionId: 'ASSERT-SDN-097',
    ruleName: 'SchemaDriftAndNullChecks Assertion Check #97',
    category: 'unexpected new column detectors',
    targetTable: 'enterprise_data_mart.table_7',
    targetColumn: 'column_attr_17',
    evaluationEngine: 'GREAT_EXPECTATIONS',
    isBlocking: false,
    alertSeverity: 'HIGH_P2',
    autoRemediationAction: 'RETRY_STAGE_WITH_BACKOFF'
  },
  {
    assertionId: 'ASSERT-SDN-098',
    ruleName: 'SchemaDriftAndNullChecks Assertion Check #98',
    category: 'and null ratio constraints',
    targetTable: 'enterprise_data_mart.table_8',
    targetColumn: 'column_attr_18',
    evaluationEngine: 'SQL_ASSERTION',
    isBlocking: false,
    alertSeverity: 'HIGH_P2',
    autoRemediationAction: 'QUARANTINE_ROW_TO_DLQ'
  },
  {
    assertionId: 'ASSERT-SDN-099',
    ruleName: 'SchemaDriftAndNullChecks Assertion Check #99',
    category: 'Strict column data type assertions',
    targetTable: 'enterprise_data_mart.table_9',
    targetColumn: 'column_attr_19',
    evaluationEngine: 'GREAT_EXPECTATIONS',
    isBlocking: true,
    alertSeverity: 'CRITICAL_P1',
    autoRemediationAction: 'RETRY_STAGE_WITH_BACKOFF'
  },
  {
    assertionId: 'ASSERT-SDN-100',
    ruleName: 'SchemaDriftAndNullChecks Assertion Check #100',
    category: 'unexpected new column detectors',
    targetTable: 'enterprise_data_mart.table_10',
    targetColumn: 'column_attr_0',
    evaluationEngine: 'SQL_ASSERTION',
    isBlocking: false,
    alertSeverity: 'HIGH_P2',
    autoRemediationAction: 'QUARANTINE_ROW_TO_DLQ'
  },
  {
    assertionId: 'ASSERT-SDN-101',
    ruleName: 'SchemaDriftAndNullChecks Assertion Check #101',
    category: 'and null ratio constraints',
    targetTable: 'enterprise_data_mart.table_11',
    targetColumn: 'column_attr_1',
    evaluationEngine: 'GREAT_EXPECTATIONS',
    isBlocking: false,
    alertSeverity: 'HIGH_P2',
    autoRemediationAction: 'RETRY_STAGE_WITH_BACKOFF'
  },
  {
    assertionId: 'ASSERT-SDN-102',
    ruleName: 'SchemaDriftAndNullChecks Assertion Check #102',
    category: 'Strict column data type assertions',
    targetTable: 'enterprise_data_mart.table_12',
    targetColumn: 'column_attr_2',
    evaluationEngine: 'SQL_ASSERTION',
    isBlocking: true,
    alertSeverity: 'CRITICAL_P1',
    autoRemediationAction: 'QUARANTINE_ROW_TO_DLQ'
  },
  {
    assertionId: 'ASSERT-SDN-103',
    ruleName: 'SchemaDriftAndNullChecks Assertion Check #103',
    category: 'unexpected new column detectors',
    targetTable: 'enterprise_data_mart.table_13',
    targetColumn: 'column_attr_3',
    evaluationEngine: 'GREAT_EXPECTATIONS',
    isBlocking: false,
    alertSeverity: 'HIGH_P2',
    autoRemediationAction: 'RETRY_STAGE_WITH_BACKOFF'
  },
  {
    assertionId: 'ASSERT-SDN-104',
    ruleName: 'SchemaDriftAndNullChecks Assertion Check #104',
    category: 'and null ratio constraints',
    targetTable: 'enterprise_data_mart.table_14',
    targetColumn: 'column_attr_4',
    evaluationEngine: 'SQL_ASSERTION',
    isBlocking: false,
    alertSeverity: 'HIGH_P2',
    autoRemediationAction: 'QUARANTINE_ROW_TO_DLQ'
  },
  {
    assertionId: 'ASSERT-SDN-105',
    ruleName: 'SchemaDriftAndNullChecks Assertion Check #105',
    category: 'Strict column data type assertions',
    targetTable: 'enterprise_data_mart.table_15',
    targetColumn: 'column_attr_5',
    evaluationEngine: 'GREAT_EXPECTATIONS',
    isBlocking: true,
    alertSeverity: 'CRITICAL_P1',
    autoRemediationAction: 'RETRY_STAGE_WITH_BACKOFF'
  },
  {
    assertionId: 'ASSERT-SDN-106',
    ruleName: 'SchemaDriftAndNullChecks Assertion Check #106',
    category: 'unexpected new column detectors',
    targetTable: 'enterprise_data_mart.table_16',
    targetColumn: 'column_attr_6',
    evaluationEngine: 'SQL_ASSERTION',
    isBlocking: false,
    alertSeverity: 'HIGH_P2',
    autoRemediationAction: 'QUARANTINE_ROW_TO_DLQ'
  },
  {
    assertionId: 'ASSERT-SDN-107',
    ruleName: 'SchemaDriftAndNullChecks Assertion Check #107',
    category: 'and null ratio constraints',
    targetTable: 'enterprise_data_mart.table_17',
    targetColumn: 'column_attr_7',
    evaluationEngine: 'GREAT_EXPECTATIONS',
    isBlocking: false,
    alertSeverity: 'HIGH_P2',
    autoRemediationAction: 'RETRY_STAGE_WITH_BACKOFF'
  },
  {
    assertionId: 'ASSERT-SDN-108',
    ruleName: 'SchemaDriftAndNullChecks Assertion Check #108',
    category: 'Strict column data type assertions',
    targetTable: 'enterprise_data_mart.table_18',
    targetColumn: 'column_attr_8',
    evaluationEngine: 'SQL_ASSERTION',
    isBlocking: true,
    alertSeverity: 'CRITICAL_P1',
    autoRemediationAction: 'QUARANTINE_ROW_TO_DLQ'
  },
  {
    assertionId: 'ASSERT-SDN-109',
    ruleName: 'SchemaDriftAndNullChecks Assertion Check #109',
    category: 'unexpected new column detectors',
    targetTable: 'enterprise_data_mart.table_19',
    targetColumn: 'column_attr_9',
    evaluationEngine: 'GREAT_EXPECTATIONS',
    isBlocking: false,
    alertSeverity: 'HIGH_P2',
    autoRemediationAction: 'RETRY_STAGE_WITH_BACKOFF'
  },
  {
    assertionId: 'ASSERT-SDN-110',
    ruleName: 'SchemaDriftAndNullChecks Assertion Check #110',
    category: 'and null ratio constraints',
    targetTable: 'enterprise_data_mart.table_20',
    targetColumn: 'column_attr_10',
    evaluationEngine: 'SQL_ASSERTION',
    isBlocking: false,
    alertSeverity: 'HIGH_P2',
    autoRemediationAction: 'QUARANTINE_ROW_TO_DLQ'
  },
  {
    assertionId: 'ASSERT-SDN-111',
    ruleName: 'SchemaDriftAndNullChecks Assertion Check #111',
    category: 'Strict column data type assertions',
    targetTable: 'enterprise_data_mart.table_21',
    targetColumn: 'column_attr_11',
    evaluationEngine: 'GREAT_EXPECTATIONS',
    isBlocking: true,
    alertSeverity: 'CRITICAL_P1',
    autoRemediationAction: 'RETRY_STAGE_WITH_BACKOFF'
  },
  {
    assertionId: 'ASSERT-SDN-112',
    ruleName: 'SchemaDriftAndNullChecks Assertion Check #112',
    category: 'unexpected new column detectors',
    targetTable: 'enterprise_data_mart.table_22',
    targetColumn: 'column_attr_12',
    evaluationEngine: 'SQL_ASSERTION',
    isBlocking: false,
    alertSeverity: 'HIGH_P2',
    autoRemediationAction: 'QUARANTINE_ROW_TO_DLQ'
  },
  {
    assertionId: 'ASSERT-SDN-113',
    ruleName: 'SchemaDriftAndNullChecks Assertion Check #113',
    category: 'and null ratio constraints',
    targetTable: 'enterprise_data_mart.table_23',
    targetColumn: 'column_attr_13',
    evaluationEngine: 'GREAT_EXPECTATIONS',
    isBlocking: false,
    alertSeverity: 'HIGH_P2',
    autoRemediationAction: 'RETRY_STAGE_WITH_BACKOFF'
  },
  {
    assertionId: 'ASSERT-SDN-114',
    ruleName: 'SchemaDriftAndNullChecks Assertion Check #114',
    category: 'Strict column data type assertions',
    targetTable: 'enterprise_data_mart.table_24',
    targetColumn: 'column_attr_14',
    evaluationEngine: 'SQL_ASSERTION',
    isBlocking: true,
    alertSeverity: 'CRITICAL_P1',
    autoRemediationAction: 'QUARANTINE_ROW_TO_DLQ'
  },
  {
    assertionId: 'ASSERT-SDN-115',
    ruleName: 'SchemaDriftAndNullChecks Assertion Check #115',
    category: 'unexpected new column detectors',
    targetTable: 'enterprise_data_mart.table_25',
    targetColumn: 'column_attr_15',
    evaluationEngine: 'GREAT_EXPECTATIONS',
    isBlocking: false,
    alertSeverity: 'HIGH_P2',
    autoRemediationAction: 'RETRY_STAGE_WITH_BACKOFF'
  },
  {
    assertionId: 'ASSERT-SDN-116',
    ruleName: 'SchemaDriftAndNullChecks Assertion Check #116',
    category: 'and null ratio constraints',
    targetTable: 'enterprise_data_mart.table_26',
    targetColumn: 'column_attr_16',
    evaluationEngine: 'SQL_ASSERTION',
    isBlocking: false,
    alertSeverity: 'HIGH_P2',
    autoRemediationAction: 'QUARANTINE_ROW_TO_DLQ'
  },
  {
    assertionId: 'ASSERT-SDN-117',
    ruleName: 'SchemaDriftAndNullChecks Assertion Check #117',
    category: 'Strict column data type assertions',
    targetTable: 'enterprise_data_mart.table_27',
    targetColumn: 'column_attr_17',
    evaluationEngine: 'GREAT_EXPECTATIONS',
    isBlocking: true,
    alertSeverity: 'CRITICAL_P1',
    autoRemediationAction: 'RETRY_STAGE_WITH_BACKOFF'
  },
  {
    assertionId: 'ASSERT-SDN-118',
    ruleName: 'SchemaDriftAndNullChecks Assertion Check #118',
    category: 'unexpected new column detectors',
    targetTable: 'enterprise_data_mart.table_28',
    targetColumn: 'column_attr_18',
    evaluationEngine: 'SQL_ASSERTION',
    isBlocking: false,
    alertSeverity: 'HIGH_P2',
    autoRemediationAction: 'QUARANTINE_ROW_TO_DLQ'
  },
  {
    assertionId: 'ASSERT-SDN-119',
    ruleName: 'SchemaDriftAndNullChecks Assertion Check #119',
    category: 'and null ratio constraints',
    targetTable: 'enterprise_data_mart.table_29',
    targetColumn: 'column_attr_19',
    evaluationEngine: 'GREAT_EXPECTATIONS',
    isBlocking: false,
    alertSeverity: 'HIGH_P2',
    autoRemediationAction: 'RETRY_STAGE_WITH_BACKOFF'
  },
  {
    assertionId: 'ASSERT-SDN-120',
    ruleName: 'SchemaDriftAndNullChecks Assertion Check #120',
    category: 'Strict column data type assertions',
    targetTable: 'enterprise_data_mart.table_0',
    targetColumn: 'column_attr_0',
    evaluationEngine: 'SQL_ASSERTION',
    isBlocking: true,
    alertSeverity: 'CRITICAL_P1',
    autoRemediationAction: 'QUARANTINE_ROW_TO_DLQ'
  },
  {
    assertionId: 'ASSERT-SDN-121',
    ruleName: 'SchemaDriftAndNullChecks Assertion Check #121',
    category: 'unexpected new column detectors',
    targetTable: 'enterprise_data_mart.table_1',
    targetColumn: 'column_attr_1',
    evaluationEngine: 'GREAT_EXPECTATIONS',
    isBlocking: false,
    alertSeverity: 'HIGH_P2',
    autoRemediationAction: 'RETRY_STAGE_WITH_BACKOFF'
  },
  {
    assertionId: 'ASSERT-SDN-122',
    ruleName: 'SchemaDriftAndNullChecks Assertion Check #122',
    category: 'and null ratio constraints',
    targetTable: 'enterprise_data_mart.table_2',
    targetColumn: 'column_attr_2',
    evaluationEngine: 'SQL_ASSERTION',
    isBlocking: false,
    alertSeverity: 'HIGH_P2',
    autoRemediationAction: 'QUARANTINE_ROW_TO_DLQ'
  },
  {
    assertionId: 'ASSERT-SDN-123',
    ruleName: 'SchemaDriftAndNullChecks Assertion Check #123',
    category: 'Strict column data type assertions',
    targetTable: 'enterprise_data_mart.table_3',
    targetColumn: 'column_attr_3',
    evaluationEngine: 'GREAT_EXPECTATIONS',
    isBlocking: true,
    alertSeverity: 'CRITICAL_P1',
    autoRemediationAction: 'RETRY_STAGE_WITH_BACKOFF'
  },
  {
    assertionId: 'ASSERT-SDN-124',
    ruleName: 'SchemaDriftAndNullChecks Assertion Check #124',
    category: 'unexpected new column detectors',
    targetTable: 'enterprise_data_mart.table_4',
    targetColumn: 'column_attr_4',
    evaluationEngine: 'SQL_ASSERTION',
    isBlocking: false,
    alertSeverity: 'HIGH_P2',
    autoRemediationAction: 'QUARANTINE_ROW_TO_DLQ'
  },
  {
    assertionId: 'ASSERT-SDN-125',
    ruleName: 'SchemaDriftAndNullChecks Assertion Check #125',
    category: 'and null ratio constraints',
    targetTable: 'enterprise_data_mart.table_5',
    targetColumn: 'column_attr_5',
    evaluationEngine: 'GREAT_EXPECTATIONS',
    isBlocking: false,
    alertSeverity: 'HIGH_P2',
    autoRemediationAction: 'RETRY_STAGE_WITH_BACKOFF'
  },
  {
    assertionId: 'ASSERT-SDN-126',
    ruleName: 'SchemaDriftAndNullChecks Assertion Check #126',
    category: 'Strict column data type assertions',
    targetTable: 'enterprise_data_mart.table_6',
    targetColumn: 'column_attr_6',
    evaluationEngine: 'SQL_ASSERTION',
    isBlocking: true,
    alertSeverity: 'CRITICAL_P1',
    autoRemediationAction: 'QUARANTINE_ROW_TO_DLQ'
  },
  {
    assertionId: 'ASSERT-SDN-127',
    ruleName: 'SchemaDriftAndNullChecks Assertion Check #127',
    category: 'unexpected new column detectors',
    targetTable: 'enterprise_data_mart.table_7',
    targetColumn: 'column_attr_7',
    evaluationEngine: 'GREAT_EXPECTATIONS',
    isBlocking: false,
    alertSeverity: 'HIGH_P2',
    autoRemediationAction: 'RETRY_STAGE_WITH_BACKOFF'
  },
  {
    assertionId: 'ASSERT-SDN-128',
    ruleName: 'SchemaDriftAndNullChecks Assertion Check #128',
    category: 'and null ratio constraints',
    targetTable: 'enterprise_data_mart.table_8',
    targetColumn: 'column_attr_8',
    evaluationEngine: 'SQL_ASSERTION',
    isBlocking: false,
    alertSeverity: 'HIGH_P2',
    autoRemediationAction: 'QUARANTINE_ROW_TO_DLQ'
  },
  {
    assertionId: 'ASSERT-SDN-129',
    ruleName: 'SchemaDriftAndNullChecks Assertion Check #129',
    category: 'Strict column data type assertions',
    targetTable: 'enterprise_data_mart.table_9',
    targetColumn: 'column_attr_9',
    evaluationEngine: 'GREAT_EXPECTATIONS',
    isBlocking: true,
    alertSeverity: 'CRITICAL_P1',
    autoRemediationAction: 'RETRY_STAGE_WITH_BACKOFF'
  },
  {
    assertionId: 'ASSERT-SDN-130',
    ruleName: 'SchemaDriftAndNullChecks Assertion Check #130',
    category: 'unexpected new column detectors',
    targetTable: 'enterprise_data_mart.table_10',
    targetColumn: 'column_attr_10',
    evaluationEngine: 'SQL_ASSERTION',
    isBlocking: false,
    alertSeverity: 'HIGH_P2',
    autoRemediationAction: 'QUARANTINE_ROW_TO_DLQ'
  },
  {
    assertionId: 'ASSERT-SDN-131',
    ruleName: 'SchemaDriftAndNullChecks Assertion Check #131',
    category: 'and null ratio constraints',
    targetTable: 'enterprise_data_mart.table_11',
    targetColumn: 'column_attr_11',
    evaluationEngine: 'GREAT_EXPECTATIONS',
    isBlocking: false,
    alertSeverity: 'HIGH_P2',
    autoRemediationAction: 'RETRY_STAGE_WITH_BACKOFF'
  },
  {
    assertionId: 'ASSERT-SDN-132',
    ruleName: 'SchemaDriftAndNullChecks Assertion Check #132',
    category: 'Strict column data type assertions',
    targetTable: 'enterprise_data_mart.table_12',
    targetColumn: 'column_attr_12',
    evaluationEngine: 'SQL_ASSERTION',
    isBlocking: true,
    alertSeverity: 'CRITICAL_P1',
    autoRemediationAction: 'QUARANTINE_ROW_TO_DLQ'
  },
  {
    assertionId: 'ASSERT-SDN-133',
    ruleName: 'SchemaDriftAndNullChecks Assertion Check #133',
    category: 'unexpected new column detectors',
    targetTable: 'enterprise_data_mart.table_13',
    targetColumn: 'column_attr_13',
    evaluationEngine: 'GREAT_EXPECTATIONS',
    isBlocking: false,
    alertSeverity: 'HIGH_P2',
    autoRemediationAction: 'RETRY_STAGE_WITH_BACKOFF'
  },
  {
    assertionId: 'ASSERT-SDN-134',
    ruleName: 'SchemaDriftAndNullChecks Assertion Check #134',
    category: 'and null ratio constraints',
    targetTable: 'enterprise_data_mart.table_14',
    targetColumn: 'column_attr_14',
    evaluationEngine: 'SQL_ASSERTION',
    isBlocking: false,
    alertSeverity: 'HIGH_P2',
    autoRemediationAction: 'QUARANTINE_ROW_TO_DLQ'
  },
  {
    assertionId: 'ASSERT-SDN-135',
    ruleName: 'SchemaDriftAndNullChecks Assertion Check #135',
    category: 'Strict column data type assertions',
    targetTable: 'enterprise_data_mart.table_15',
    targetColumn: 'column_attr_15',
    evaluationEngine: 'GREAT_EXPECTATIONS',
    isBlocking: true,
    alertSeverity: 'CRITICAL_P1',
    autoRemediationAction: 'RETRY_STAGE_WITH_BACKOFF'
  },
  {
    assertionId: 'ASSERT-SDN-136',
    ruleName: 'SchemaDriftAndNullChecks Assertion Check #136',
    category: 'unexpected new column detectors',
    targetTable: 'enterprise_data_mart.table_16',
    targetColumn: 'column_attr_16',
    evaluationEngine: 'SQL_ASSERTION',
    isBlocking: false,
    alertSeverity: 'HIGH_P2',
    autoRemediationAction: 'QUARANTINE_ROW_TO_DLQ'
  },
  {
    assertionId: 'ASSERT-SDN-137',
    ruleName: 'SchemaDriftAndNullChecks Assertion Check #137',
    category: 'and null ratio constraints',
    targetTable: 'enterprise_data_mart.table_17',
    targetColumn: 'column_attr_17',
    evaluationEngine: 'GREAT_EXPECTATIONS',
    isBlocking: false,
    alertSeverity: 'HIGH_P2',
    autoRemediationAction: 'RETRY_STAGE_WITH_BACKOFF'
  },
  {
    assertionId: 'ASSERT-SDN-138',
    ruleName: 'SchemaDriftAndNullChecks Assertion Check #138',
    category: 'Strict column data type assertions',
    targetTable: 'enterprise_data_mart.table_18',
    targetColumn: 'column_attr_18',
    evaluationEngine: 'SQL_ASSERTION',
    isBlocking: true,
    alertSeverity: 'CRITICAL_P1',
    autoRemediationAction: 'QUARANTINE_ROW_TO_DLQ'
  },
  {
    assertionId: 'ASSERT-SDN-139',
    ruleName: 'SchemaDriftAndNullChecks Assertion Check #139',
    category: 'unexpected new column detectors',
    targetTable: 'enterprise_data_mart.table_19',
    targetColumn: 'column_attr_19',
    evaluationEngine: 'GREAT_EXPECTATIONS',
    isBlocking: false,
    alertSeverity: 'HIGH_P2',
    autoRemediationAction: 'RETRY_STAGE_WITH_BACKOFF'
  },
  {
    assertionId: 'ASSERT-SDN-140',
    ruleName: 'SchemaDriftAndNullChecks Assertion Check #140',
    category: 'and null ratio constraints',
    targetTable: 'enterprise_data_mart.table_20',
    targetColumn: 'column_attr_0',
    evaluationEngine: 'SQL_ASSERTION',
    isBlocking: false,
    alertSeverity: 'HIGH_P2',
    autoRemediationAction: 'QUARANTINE_ROW_TO_DLQ'
  },
  {
    assertionId: 'ASSERT-SDN-141',
    ruleName: 'SchemaDriftAndNullChecks Assertion Check #141',
    category: 'Strict column data type assertions',
    targetTable: 'enterprise_data_mart.table_21',
    targetColumn: 'column_attr_1',
    evaluationEngine: 'GREAT_EXPECTATIONS',
    isBlocking: true,
    alertSeverity: 'CRITICAL_P1',
    autoRemediationAction: 'RETRY_STAGE_WITH_BACKOFF'
  },
  {
    assertionId: 'ASSERT-SDN-142',
    ruleName: 'SchemaDriftAndNullChecks Assertion Check #142',
    category: 'unexpected new column detectors',
    targetTable: 'enterprise_data_mart.table_22',
    targetColumn: 'column_attr_2',
    evaluationEngine: 'SQL_ASSERTION',
    isBlocking: false,
    alertSeverity: 'HIGH_P2',
    autoRemediationAction: 'QUARANTINE_ROW_TO_DLQ'
  },
  {
    assertionId: 'ASSERT-SDN-143',
    ruleName: 'SchemaDriftAndNullChecks Assertion Check #143',
    category: 'and null ratio constraints',
    targetTable: 'enterprise_data_mart.table_23',
    targetColumn: 'column_attr_3',
    evaluationEngine: 'GREAT_EXPECTATIONS',
    isBlocking: false,
    alertSeverity: 'HIGH_P2',
    autoRemediationAction: 'RETRY_STAGE_WITH_BACKOFF'
  },
  {
    assertionId: 'ASSERT-SDN-144',
    ruleName: 'SchemaDriftAndNullChecks Assertion Check #144',
    category: 'Strict column data type assertions',
    targetTable: 'enterprise_data_mart.table_24',
    targetColumn: 'column_attr_4',
    evaluationEngine: 'SQL_ASSERTION',
    isBlocking: true,
    alertSeverity: 'CRITICAL_P1',
    autoRemediationAction: 'QUARANTINE_ROW_TO_DLQ'
  },
  {
    assertionId: 'ASSERT-SDN-145',
    ruleName: 'SchemaDriftAndNullChecks Assertion Check #145',
    category: 'unexpected new column detectors',
    targetTable: 'enterprise_data_mart.table_25',
    targetColumn: 'column_attr_5',
    evaluationEngine: 'GREAT_EXPECTATIONS',
    isBlocking: false,
    alertSeverity: 'HIGH_P2',
    autoRemediationAction: 'RETRY_STAGE_WITH_BACKOFF'
  },
  {
    assertionId: 'ASSERT-SDN-146',
    ruleName: 'SchemaDriftAndNullChecks Assertion Check #146',
    category: 'and null ratio constraints',
    targetTable: 'enterprise_data_mart.table_26',
    targetColumn: 'column_attr_6',
    evaluationEngine: 'SQL_ASSERTION',
    isBlocking: false,
    alertSeverity: 'HIGH_P2',
    autoRemediationAction: 'QUARANTINE_ROW_TO_DLQ'
  },
  {
    assertionId: 'ASSERT-SDN-147',
    ruleName: 'SchemaDriftAndNullChecks Assertion Check #147',
    category: 'Strict column data type assertions',
    targetTable: 'enterprise_data_mart.table_27',
    targetColumn: 'column_attr_7',
    evaluationEngine: 'GREAT_EXPECTATIONS',
    isBlocking: true,
    alertSeverity: 'CRITICAL_P1',
    autoRemediationAction: 'RETRY_STAGE_WITH_BACKOFF'
  },
  {
    assertionId: 'ASSERT-SDN-148',
    ruleName: 'SchemaDriftAndNullChecks Assertion Check #148',
    category: 'unexpected new column detectors',
    targetTable: 'enterprise_data_mart.table_28',
    targetColumn: 'column_attr_8',
    evaluationEngine: 'SQL_ASSERTION',
    isBlocking: false,
    alertSeverity: 'HIGH_P2',
    autoRemediationAction: 'QUARANTINE_ROW_TO_DLQ'
  },
  {
    assertionId: 'ASSERT-SDN-149',
    ruleName: 'SchemaDriftAndNullChecks Assertion Check #149',
    category: 'and null ratio constraints',
    targetTable: 'enterprise_data_mart.table_29',
    targetColumn: 'column_attr_9',
    evaluationEngine: 'GREAT_EXPECTATIONS',
    isBlocking: false,
    alertSeverity: 'HIGH_P2',
    autoRemediationAction: 'RETRY_STAGE_WITH_BACKOFF'
  },
  {
    assertionId: 'ASSERT-SDN-150',
    ruleName: 'SchemaDriftAndNullChecks Assertion Check #150',
    category: 'Strict column data type assertions',
    targetTable: 'enterprise_data_mart.table_0',
    targetColumn: 'column_attr_10',
    evaluationEngine: 'SQL_ASSERTION',
    isBlocking: true,
    alertSeverity: 'CRITICAL_P1',
    autoRemediationAction: 'QUARANTINE_ROW_TO_DLQ'
  }
];
