/**
 * Connector Schema & Protocol Directory: CloudDataWarehouseConnectors
 */

export interface ConnectorSpec {
  connectorId: string;
  name: string;
  category: string;
  protocolType: string;
  supportedCompression: string[];
  maxThroughputMbPerSec: number;
  connectionPoolSize: number;
  supportsSchemaEvolution: boolean;
  supportsTransactions: boolean;
}

export const CONNECTORS_DWH_DATASET: ConnectorSpec[] = [
  {
    connectorId: 'CONN-DWH-001',
    name: 'Google BigQuery Storage API (Cluster #1)',
    category: 'CloudDataWarehouseConnectors',
    protocolType: 'BATCH_CDC',
    supportedCompression: ['SNAPPY', 'ZSTD', 'GZIP'],
    maxThroughputMbPerSec: 125,
    connectionPoolSize: 17,
    supportsSchemaEvolution: true,
    supportsTransactions: false
  },
  {
    connectorId: 'CONN-DWH-002',
    name: 'AWS Redshift Serverless Sink (Cluster #2)',
    category: 'CloudDataWarehouseConnectors',
    protocolType: 'BATCH_CDC',
    supportedCompression: ['SNAPPY', 'ZSTD', 'GZIP'],
    maxThroughputMbPerSec: 150,
    connectionPoolSize: 18,
    supportsSchemaEvolution: true,
    supportsTransactions: true
  },
  {
    connectorId: 'CONN-DWH-003',
    name: 'Databricks Delta Sharing (Cluster #3)',
    category: 'CloudDataWarehouseConnectors',
    protocolType: 'BATCH_CDC',
    supportedCompression: ['SNAPPY', 'ZSTD', 'GZIP'],
    maxThroughputMbPerSec: 175,
    connectionPoolSize: 19,
    supportsSchemaEvolution: true,
    supportsTransactions: false
  },
  {
    connectorId: 'CONN-DWH-004',
    name: 'Snowflake Snowpipe Streaming (Cluster #4)',
    category: 'CloudDataWarehouseConnectors',
    protocolType: 'STREAMING',
    supportedCompression: ['SNAPPY', 'ZSTD', 'GZIP'],
    maxThroughputMbPerSec: 200,
    connectionPoolSize: 20,
    supportsSchemaEvolution: true,
    supportsTransactions: true
  },
  {
    connectorId: 'CONN-DWH-005',
    name: 'Google BigQuery Storage API (Cluster #5)',
    category: 'CloudDataWarehouseConnectors',
    protocolType: 'BATCH_CDC',
    supportedCompression: ['SNAPPY', 'ZSTD', 'GZIP'],
    maxThroughputMbPerSec: 225,
    connectionPoolSize: 21,
    supportsSchemaEvolution: true,
    supportsTransactions: false
  },
  {
    connectorId: 'CONN-DWH-006',
    name: 'AWS Redshift Serverless Sink (Cluster #6)',
    category: 'CloudDataWarehouseConnectors',
    protocolType: 'BATCH_CDC',
    supportedCompression: ['SNAPPY', 'ZSTD', 'GZIP'],
    maxThroughputMbPerSec: 250,
    connectionPoolSize: 22,
    supportsSchemaEvolution: true,
    supportsTransactions: true
  },
  {
    connectorId: 'CONN-DWH-007',
    name: 'Databricks Delta Sharing (Cluster #7)',
    category: 'CloudDataWarehouseConnectors',
    protocolType: 'BATCH_CDC',
    supportedCompression: ['SNAPPY', 'ZSTD', 'GZIP'],
    maxThroughputMbPerSec: 275,
    connectionPoolSize: 23,
    supportsSchemaEvolution: true,
    supportsTransactions: false
  },
  {
    connectorId: 'CONN-DWH-008',
    name: 'Snowflake Snowpipe Streaming (Cluster #8)',
    category: 'CloudDataWarehouseConnectors',
    protocolType: 'STREAMING',
    supportedCompression: ['SNAPPY', 'ZSTD', 'GZIP'],
    maxThroughputMbPerSec: 300,
    connectionPoolSize: 24,
    supportsSchemaEvolution: true,
    supportsTransactions: true
  },
  {
    connectorId: 'CONN-DWH-009',
    name: 'Google BigQuery Storage API (Cluster #9)',
    category: 'CloudDataWarehouseConnectors',
    protocolType: 'BATCH_CDC',
    supportedCompression: ['SNAPPY', 'ZSTD', 'GZIP'],
    maxThroughputMbPerSec: 325,
    connectionPoolSize: 25,
    supportsSchemaEvolution: true,
    supportsTransactions: false
  },
  {
    connectorId: 'CONN-DWH-010',
    name: 'AWS Redshift Serverless Sink (Cluster #10)',
    category: 'CloudDataWarehouseConnectors',
    protocolType: 'BATCH_CDC',
    supportedCompression: ['SNAPPY', 'ZSTD', 'GZIP'],
    maxThroughputMbPerSec: 350,
    connectionPoolSize: 26,
    supportsSchemaEvolution: true,
    supportsTransactions: true
  },
  {
    connectorId: 'CONN-DWH-011',
    name: 'Databricks Delta Sharing (Cluster #11)',
    category: 'CloudDataWarehouseConnectors',
    protocolType: 'BATCH_CDC',
    supportedCompression: ['SNAPPY', 'ZSTD', 'GZIP'],
    maxThroughputMbPerSec: 375,
    connectionPoolSize: 27,
    supportsSchemaEvolution: true,
    supportsTransactions: false
  },
  {
    connectorId: 'CONN-DWH-012',
    name: 'Snowflake Snowpipe Streaming (Cluster #12)',
    category: 'CloudDataWarehouseConnectors',
    protocolType: 'STREAMING',
    supportedCompression: ['SNAPPY', 'ZSTD', 'GZIP'],
    maxThroughputMbPerSec: 400,
    connectionPoolSize: 28,
    supportsSchemaEvolution: true,
    supportsTransactions: true
  },
  {
    connectorId: 'CONN-DWH-013',
    name: 'Google BigQuery Storage API (Cluster #13)',
    category: 'CloudDataWarehouseConnectors',
    protocolType: 'BATCH_CDC',
    supportedCompression: ['SNAPPY', 'ZSTD', 'GZIP'],
    maxThroughputMbPerSec: 425,
    connectionPoolSize: 29,
    supportsSchemaEvolution: true,
    supportsTransactions: false
  },
  {
    connectorId: 'CONN-DWH-014',
    name: 'AWS Redshift Serverless Sink (Cluster #14)',
    category: 'CloudDataWarehouseConnectors',
    protocolType: 'BATCH_CDC',
    supportedCompression: ['SNAPPY', 'ZSTD', 'GZIP'],
    maxThroughputMbPerSec: 450,
    connectionPoolSize: 30,
    supportsSchemaEvolution: true,
    supportsTransactions: true
  },
  {
    connectorId: 'CONN-DWH-015',
    name: 'Databricks Delta Sharing (Cluster #15)',
    category: 'CloudDataWarehouseConnectors',
    protocolType: 'BATCH_CDC',
    supportedCompression: ['SNAPPY', 'ZSTD', 'GZIP'],
    maxThroughputMbPerSec: 475,
    connectionPoolSize: 31,
    supportsSchemaEvolution: true,
    supportsTransactions: false
  },
  {
    connectorId: 'CONN-DWH-016',
    name: 'Snowflake Snowpipe Streaming (Cluster #16)',
    category: 'CloudDataWarehouseConnectors',
    protocolType: 'STREAMING',
    supportedCompression: ['SNAPPY', 'ZSTD', 'GZIP'],
    maxThroughputMbPerSec: 500,
    connectionPoolSize: 32,
    supportsSchemaEvolution: true,
    supportsTransactions: true
  },
  {
    connectorId: 'CONN-DWH-017',
    name: 'Google BigQuery Storage API (Cluster #17)',
    category: 'CloudDataWarehouseConnectors',
    protocolType: 'BATCH_CDC',
    supportedCompression: ['SNAPPY', 'ZSTD', 'GZIP'],
    maxThroughputMbPerSec: 525,
    connectionPoolSize: 33,
    supportsSchemaEvolution: true,
    supportsTransactions: false
  },
  {
    connectorId: 'CONN-DWH-018',
    name: 'AWS Redshift Serverless Sink (Cluster #18)',
    category: 'CloudDataWarehouseConnectors',
    protocolType: 'BATCH_CDC',
    supportedCompression: ['SNAPPY', 'ZSTD', 'GZIP'],
    maxThroughputMbPerSec: 550,
    connectionPoolSize: 34,
    supportsSchemaEvolution: true,
    supportsTransactions: true
  },
  {
    connectorId: 'CONN-DWH-019',
    name: 'Databricks Delta Sharing (Cluster #19)',
    category: 'CloudDataWarehouseConnectors',
    protocolType: 'BATCH_CDC',
    supportedCompression: ['SNAPPY', 'ZSTD', 'GZIP'],
    maxThroughputMbPerSec: 575,
    connectionPoolSize: 35,
    supportsSchemaEvolution: true,
    supportsTransactions: false
  },
  {
    connectorId: 'CONN-DWH-020',
    name: 'Snowflake Snowpipe Streaming (Cluster #20)',
    category: 'CloudDataWarehouseConnectors',
    protocolType: 'STREAMING',
    supportedCompression: ['SNAPPY', 'ZSTD', 'GZIP'],
    maxThroughputMbPerSec: 600,
    connectionPoolSize: 36,
    supportsSchemaEvolution: true,
    supportsTransactions: true
  },
  {
    connectorId: 'CONN-DWH-021',
    name: 'Google BigQuery Storage API (Cluster #21)',
    category: 'CloudDataWarehouseConnectors',
    protocolType: 'BATCH_CDC',
    supportedCompression: ['SNAPPY', 'ZSTD', 'GZIP'],
    maxThroughputMbPerSec: 625,
    connectionPoolSize: 37,
    supportsSchemaEvolution: true,
    supportsTransactions: false
  },
  {
    connectorId: 'CONN-DWH-022',
    name: 'AWS Redshift Serverless Sink (Cluster #22)',
    category: 'CloudDataWarehouseConnectors',
    protocolType: 'BATCH_CDC',
    supportedCompression: ['SNAPPY', 'ZSTD', 'GZIP'],
    maxThroughputMbPerSec: 650,
    connectionPoolSize: 38,
    supportsSchemaEvolution: true,
    supportsTransactions: true
  },
  {
    connectorId: 'CONN-DWH-023',
    name: 'Databricks Delta Sharing (Cluster #23)',
    category: 'CloudDataWarehouseConnectors',
    protocolType: 'BATCH_CDC',
    supportedCompression: ['SNAPPY', 'ZSTD', 'GZIP'],
    maxThroughputMbPerSec: 675,
    connectionPoolSize: 39,
    supportsSchemaEvolution: true,
    supportsTransactions: false
  },
  {
    connectorId: 'CONN-DWH-024',
    name: 'Snowflake Snowpipe Streaming (Cluster #24)',
    category: 'CloudDataWarehouseConnectors',
    protocolType: 'STREAMING',
    supportedCompression: ['SNAPPY', 'ZSTD', 'GZIP'],
    maxThroughputMbPerSec: 700,
    connectionPoolSize: 40,
    supportsSchemaEvolution: true,
    supportsTransactions: true
  },
  {
    connectorId: 'CONN-DWH-025',
    name: 'Google BigQuery Storage API (Cluster #25)',
    category: 'CloudDataWarehouseConnectors',
    protocolType: 'BATCH_CDC',
    supportedCompression: ['SNAPPY', 'ZSTD', 'GZIP'],
    maxThroughputMbPerSec: 725,
    connectionPoolSize: 41,
    supportsSchemaEvolution: true,
    supportsTransactions: false
  },
  {
    connectorId: 'CONN-DWH-026',
    name: 'AWS Redshift Serverless Sink (Cluster #26)',
    category: 'CloudDataWarehouseConnectors',
    protocolType: 'BATCH_CDC',
    supportedCompression: ['SNAPPY', 'ZSTD', 'GZIP'],
    maxThroughputMbPerSec: 750,
    connectionPoolSize: 42,
    supportsSchemaEvolution: true,
    supportsTransactions: true
  },
  {
    connectorId: 'CONN-DWH-027',
    name: 'Databricks Delta Sharing (Cluster #27)',
    category: 'CloudDataWarehouseConnectors',
    protocolType: 'BATCH_CDC',
    supportedCompression: ['SNAPPY', 'ZSTD', 'GZIP'],
    maxThroughputMbPerSec: 775,
    connectionPoolSize: 43,
    supportsSchemaEvolution: true,
    supportsTransactions: false
  },
  {
    connectorId: 'CONN-DWH-028',
    name: 'Snowflake Snowpipe Streaming (Cluster #28)',
    category: 'CloudDataWarehouseConnectors',
    protocolType: 'STREAMING',
    supportedCompression: ['SNAPPY', 'ZSTD', 'GZIP'],
    maxThroughputMbPerSec: 800,
    connectionPoolSize: 44,
    supportsSchemaEvolution: true,
    supportsTransactions: true
  },
  {
    connectorId: 'CONN-DWH-029',
    name: 'Google BigQuery Storage API (Cluster #29)',
    category: 'CloudDataWarehouseConnectors',
    protocolType: 'BATCH_CDC',
    supportedCompression: ['SNAPPY', 'ZSTD', 'GZIP'],
    maxThroughputMbPerSec: 825,
    connectionPoolSize: 45,
    supportsSchemaEvolution: true,
    supportsTransactions: false
  },
  {
    connectorId: 'CONN-DWH-030',
    name: 'AWS Redshift Serverless Sink (Cluster #30)',
    category: 'CloudDataWarehouseConnectors',
    protocolType: 'BATCH_CDC',
    supportedCompression: ['SNAPPY', 'ZSTD', 'GZIP'],
    maxThroughputMbPerSec: 850,
    connectionPoolSize: 46,
    supportsSchemaEvolution: true,
    supportsTransactions: true
  },
  {
    connectorId: 'CONN-DWH-031',
    name: 'Databricks Delta Sharing (Cluster #31)',
    category: 'CloudDataWarehouseConnectors',
    protocolType: 'BATCH_CDC',
    supportedCompression: ['SNAPPY', 'ZSTD', 'GZIP'],
    maxThroughputMbPerSec: 875,
    connectionPoolSize: 47,
    supportsSchemaEvolution: true,
    supportsTransactions: false
  },
  {
    connectorId: 'CONN-DWH-032',
    name: 'Snowflake Snowpipe Streaming (Cluster #32)',
    category: 'CloudDataWarehouseConnectors',
    protocolType: 'STREAMING',
    supportedCompression: ['SNAPPY', 'ZSTD', 'GZIP'],
    maxThroughputMbPerSec: 900,
    connectionPoolSize: 16,
    supportsSchemaEvolution: true,
    supportsTransactions: true
  },
  {
    connectorId: 'CONN-DWH-033',
    name: 'Google BigQuery Storage API (Cluster #33)',
    category: 'CloudDataWarehouseConnectors',
    protocolType: 'BATCH_CDC',
    supportedCompression: ['SNAPPY', 'ZSTD', 'GZIP'],
    maxThroughputMbPerSec: 925,
    connectionPoolSize: 17,
    supportsSchemaEvolution: true,
    supportsTransactions: false
  },
  {
    connectorId: 'CONN-DWH-034',
    name: 'AWS Redshift Serverless Sink (Cluster #34)',
    category: 'CloudDataWarehouseConnectors',
    protocolType: 'BATCH_CDC',
    supportedCompression: ['SNAPPY', 'ZSTD', 'GZIP'],
    maxThroughputMbPerSec: 950,
    connectionPoolSize: 18,
    supportsSchemaEvolution: true,
    supportsTransactions: true
  },
  {
    connectorId: 'CONN-DWH-035',
    name: 'Databricks Delta Sharing (Cluster #35)',
    category: 'CloudDataWarehouseConnectors',
    protocolType: 'BATCH_CDC',
    supportedCompression: ['SNAPPY', 'ZSTD', 'GZIP'],
    maxThroughputMbPerSec: 975,
    connectionPoolSize: 19,
    supportsSchemaEvolution: true,
    supportsTransactions: false
  },
  {
    connectorId: 'CONN-DWH-036',
    name: 'Snowflake Snowpipe Streaming (Cluster #36)',
    category: 'CloudDataWarehouseConnectors',
    protocolType: 'STREAMING',
    supportedCompression: ['SNAPPY', 'ZSTD', 'GZIP'],
    maxThroughputMbPerSec: 1000,
    connectionPoolSize: 20,
    supportsSchemaEvolution: true,
    supportsTransactions: true
  },
  {
    connectorId: 'CONN-DWH-037',
    name: 'Google BigQuery Storage API (Cluster #37)',
    category: 'CloudDataWarehouseConnectors',
    protocolType: 'BATCH_CDC',
    supportedCompression: ['SNAPPY', 'ZSTD', 'GZIP'],
    maxThroughputMbPerSec: 1025,
    connectionPoolSize: 21,
    supportsSchemaEvolution: true,
    supportsTransactions: false
  },
  {
    connectorId: 'CONN-DWH-038',
    name: 'AWS Redshift Serverless Sink (Cluster #38)',
    category: 'CloudDataWarehouseConnectors',
    protocolType: 'BATCH_CDC',
    supportedCompression: ['SNAPPY', 'ZSTD', 'GZIP'],
    maxThroughputMbPerSec: 1050,
    connectionPoolSize: 22,
    supportsSchemaEvolution: true,
    supportsTransactions: true
  },
  {
    connectorId: 'CONN-DWH-039',
    name: 'Databricks Delta Sharing (Cluster #39)',
    category: 'CloudDataWarehouseConnectors',
    protocolType: 'BATCH_CDC',
    supportedCompression: ['SNAPPY', 'ZSTD', 'GZIP'],
    maxThroughputMbPerSec: 1075,
    connectionPoolSize: 23,
    supportsSchemaEvolution: true,
    supportsTransactions: false
  },
  {
    connectorId: 'CONN-DWH-040',
    name: 'Snowflake Snowpipe Streaming (Cluster #40)',
    category: 'CloudDataWarehouseConnectors',
    protocolType: 'STREAMING',
    supportedCompression: ['SNAPPY', 'ZSTD', 'GZIP'],
    maxThroughputMbPerSec: 100,
    connectionPoolSize: 24,
    supportsSchemaEvolution: true,
    supportsTransactions: true
  },
  {
    connectorId: 'CONN-DWH-041',
    name: 'Google BigQuery Storage API (Cluster #41)',
    category: 'CloudDataWarehouseConnectors',
    protocolType: 'BATCH_CDC',
    supportedCompression: ['SNAPPY', 'ZSTD', 'GZIP'],
    maxThroughputMbPerSec: 125,
    connectionPoolSize: 25,
    supportsSchemaEvolution: true,
    supportsTransactions: false
  },
  {
    connectorId: 'CONN-DWH-042',
    name: 'AWS Redshift Serverless Sink (Cluster #42)',
    category: 'CloudDataWarehouseConnectors',
    protocolType: 'BATCH_CDC',
    supportedCompression: ['SNAPPY', 'ZSTD', 'GZIP'],
    maxThroughputMbPerSec: 150,
    connectionPoolSize: 26,
    supportsSchemaEvolution: true,
    supportsTransactions: true
  },
  {
    connectorId: 'CONN-DWH-043',
    name: 'Databricks Delta Sharing (Cluster #43)',
    category: 'CloudDataWarehouseConnectors',
    protocolType: 'BATCH_CDC',
    supportedCompression: ['SNAPPY', 'ZSTD', 'GZIP'],
    maxThroughputMbPerSec: 175,
    connectionPoolSize: 27,
    supportsSchemaEvolution: true,
    supportsTransactions: false
  },
  {
    connectorId: 'CONN-DWH-044',
    name: 'Snowflake Snowpipe Streaming (Cluster #44)',
    category: 'CloudDataWarehouseConnectors',
    protocolType: 'STREAMING',
    supportedCompression: ['SNAPPY', 'ZSTD', 'GZIP'],
    maxThroughputMbPerSec: 200,
    connectionPoolSize: 28,
    supportsSchemaEvolution: true,
    supportsTransactions: true
  },
  {
    connectorId: 'CONN-DWH-045',
    name: 'Google BigQuery Storage API (Cluster #45)',
    category: 'CloudDataWarehouseConnectors',
    protocolType: 'BATCH_CDC',
    supportedCompression: ['SNAPPY', 'ZSTD', 'GZIP'],
    maxThroughputMbPerSec: 225,
    connectionPoolSize: 29,
    supportsSchemaEvolution: true,
    supportsTransactions: false
  },
  {
    connectorId: 'CONN-DWH-046',
    name: 'AWS Redshift Serverless Sink (Cluster #46)',
    category: 'CloudDataWarehouseConnectors',
    protocolType: 'BATCH_CDC',
    supportedCompression: ['SNAPPY', 'ZSTD', 'GZIP'],
    maxThroughputMbPerSec: 250,
    connectionPoolSize: 30,
    supportsSchemaEvolution: true,
    supportsTransactions: true
  },
  {
    connectorId: 'CONN-DWH-047',
    name: 'Databricks Delta Sharing (Cluster #47)',
    category: 'CloudDataWarehouseConnectors',
    protocolType: 'BATCH_CDC',
    supportedCompression: ['SNAPPY', 'ZSTD', 'GZIP'],
    maxThroughputMbPerSec: 275,
    connectionPoolSize: 31,
    supportsSchemaEvolution: true,
    supportsTransactions: false
  },
  {
    connectorId: 'CONN-DWH-048',
    name: 'Snowflake Snowpipe Streaming (Cluster #48)',
    category: 'CloudDataWarehouseConnectors',
    protocolType: 'STREAMING',
    supportedCompression: ['SNAPPY', 'ZSTD', 'GZIP'],
    maxThroughputMbPerSec: 300,
    connectionPoolSize: 32,
    supportsSchemaEvolution: true,
    supportsTransactions: true
  },
  {
    connectorId: 'CONN-DWH-049',
    name: 'Google BigQuery Storage API (Cluster #49)',
    category: 'CloudDataWarehouseConnectors',
    protocolType: 'BATCH_CDC',
    supportedCompression: ['SNAPPY', 'ZSTD', 'GZIP'],
    maxThroughputMbPerSec: 325,
    connectionPoolSize: 33,
    supportsSchemaEvolution: true,
    supportsTransactions: false
  },
  {
    connectorId: 'CONN-DWH-050',
    name: 'AWS Redshift Serverless Sink (Cluster #50)',
    category: 'CloudDataWarehouseConnectors',
    protocolType: 'BATCH_CDC',
    supportedCompression: ['SNAPPY', 'ZSTD', 'GZIP'],
    maxThroughputMbPerSec: 350,
    connectionPoolSize: 34,
    supportsSchemaEvolution: true,
    supportsTransactions: true
  },
  {
    connectorId: 'CONN-DWH-051',
    name: 'Databricks Delta Sharing (Cluster #51)',
    category: 'CloudDataWarehouseConnectors',
    protocolType: 'BATCH_CDC',
    supportedCompression: ['SNAPPY', 'ZSTD', 'GZIP'],
    maxThroughputMbPerSec: 375,
    connectionPoolSize: 35,
    supportsSchemaEvolution: true,
    supportsTransactions: false
  },
  {
    connectorId: 'CONN-DWH-052',
    name: 'Snowflake Snowpipe Streaming (Cluster #52)',
    category: 'CloudDataWarehouseConnectors',
    protocolType: 'STREAMING',
    supportedCompression: ['SNAPPY', 'ZSTD', 'GZIP'],
    maxThroughputMbPerSec: 400,
    connectionPoolSize: 36,
    supportsSchemaEvolution: true,
    supportsTransactions: true
  },
  {
    connectorId: 'CONN-DWH-053',
    name: 'Google BigQuery Storage API (Cluster #53)',
    category: 'CloudDataWarehouseConnectors',
    protocolType: 'BATCH_CDC',
    supportedCompression: ['SNAPPY', 'ZSTD', 'GZIP'],
    maxThroughputMbPerSec: 425,
    connectionPoolSize: 37,
    supportsSchemaEvolution: true,
    supportsTransactions: false
  },
  {
    connectorId: 'CONN-DWH-054',
    name: 'AWS Redshift Serverless Sink (Cluster #54)',
    category: 'CloudDataWarehouseConnectors',
    protocolType: 'BATCH_CDC',
    supportedCompression: ['SNAPPY', 'ZSTD', 'GZIP'],
    maxThroughputMbPerSec: 450,
    connectionPoolSize: 38,
    supportsSchemaEvolution: true,
    supportsTransactions: true
  },
  {
    connectorId: 'CONN-DWH-055',
    name: 'Databricks Delta Sharing (Cluster #55)',
    category: 'CloudDataWarehouseConnectors',
    protocolType: 'BATCH_CDC',
    supportedCompression: ['SNAPPY', 'ZSTD', 'GZIP'],
    maxThroughputMbPerSec: 475,
    connectionPoolSize: 39,
    supportsSchemaEvolution: true,
    supportsTransactions: false
  },
  {
    connectorId: 'CONN-DWH-056',
    name: 'Snowflake Snowpipe Streaming (Cluster #56)',
    category: 'CloudDataWarehouseConnectors',
    protocolType: 'STREAMING',
    supportedCompression: ['SNAPPY', 'ZSTD', 'GZIP'],
    maxThroughputMbPerSec: 500,
    connectionPoolSize: 40,
    supportsSchemaEvolution: true,
    supportsTransactions: true
  },
  {
    connectorId: 'CONN-DWH-057',
    name: 'Google BigQuery Storage API (Cluster #57)',
    category: 'CloudDataWarehouseConnectors',
    protocolType: 'BATCH_CDC',
    supportedCompression: ['SNAPPY', 'ZSTD', 'GZIP'],
    maxThroughputMbPerSec: 525,
    connectionPoolSize: 41,
    supportsSchemaEvolution: true,
    supportsTransactions: false
  },
  {
    connectorId: 'CONN-DWH-058',
    name: 'AWS Redshift Serverless Sink (Cluster #58)',
    category: 'CloudDataWarehouseConnectors',
    protocolType: 'BATCH_CDC',
    supportedCompression: ['SNAPPY', 'ZSTD', 'GZIP'],
    maxThroughputMbPerSec: 550,
    connectionPoolSize: 42,
    supportsSchemaEvolution: true,
    supportsTransactions: true
  },
  {
    connectorId: 'CONN-DWH-059',
    name: 'Databricks Delta Sharing (Cluster #59)',
    category: 'CloudDataWarehouseConnectors',
    protocolType: 'BATCH_CDC',
    supportedCompression: ['SNAPPY', 'ZSTD', 'GZIP'],
    maxThroughputMbPerSec: 575,
    connectionPoolSize: 43,
    supportsSchemaEvolution: true,
    supportsTransactions: false
  },
  {
    connectorId: 'CONN-DWH-060',
    name: 'Snowflake Snowpipe Streaming (Cluster #60)',
    category: 'CloudDataWarehouseConnectors',
    protocolType: 'STREAMING',
    supportedCompression: ['SNAPPY', 'ZSTD', 'GZIP'],
    maxThroughputMbPerSec: 600,
    connectionPoolSize: 44,
    supportsSchemaEvolution: true,
    supportsTransactions: true
  },
  {
    connectorId: 'CONN-DWH-061',
    name: 'Google BigQuery Storage API (Cluster #61)',
    category: 'CloudDataWarehouseConnectors',
    protocolType: 'BATCH_CDC',
    supportedCompression: ['SNAPPY', 'ZSTD', 'GZIP'],
    maxThroughputMbPerSec: 625,
    connectionPoolSize: 45,
    supportsSchemaEvolution: true,
    supportsTransactions: false
  },
  {
    connectorId: 'CONN-DWH-062',
    name: 'AWS Redshift Serverless Sink (Cluster #62)',
    category: 'CloudDataWarehouseConnectors',
    protocolType: 'BATCH_CDC',
    supportedCompression: ['SNAPPY', 'ZSTD', 'GZIP'],
    maxThroughputMbPerSec: 650,
    connectionPoolSize: 46,
    supportsSchemaEvolution: true,
    supportsTransactions: true
  },
  {
    connectorId: 'CONN-DWH-063',
    name: 'Databricks Delta Sharing (Cluster #63)',
    category: 'CloudDataWarehouseConnectors',
    protocolType: 'BATCH_CDC',
    supportedCompression: ['SNAPPY', 'ZSTD', 'GZIP'],
    maxThroughputMbPerSec: 675,
    connectionPoolSize: 47,
    supportsSchemaEvolution: true,
    supportsTransactions: false
  },
  {
    connectorId: 'CONN-DWH-064',
    name: 'Snowflake Snowpipe Streaming (Cluster #64)',
    category: 'CloudDataWarehouseConnectors',
    protocolType: 'STREAMING',
    supportedCompression: ['SNAPPY', 'ZSTD', 'GZIP'],
    maxThroughputMbPerSec: 700,
    connectionPoolSize: 16,
    supportsSchemaEvolution: true,
    supportsTransactions: true
  },
  {
    connectorId: 'CONN-DWH-065',
    name: 'Google BigQuery Storage API (Cluster #65)',
    category: 'CloudDataWarehouseConnectors',
    protocolType: 'BATCH_CDC',
    supportedCompression: ['SNAPPY', 'ZSTD', 'GZIP'],
    maxThroughputMbPerSec: 725,
    connectionPoolSize: 17,
    supportsSchemaEvolution: true,
    supportsTransactions: false
  },
  {
    connectorId: 'CONN-DWH-066',
    name: 'AWS Redshift Serverless Sink (Cluster #66)',
    category: 'CloudDataWarehouseConnectors',
    protocolType: 'BATCH_CDC',
    supportedCompression: ['SNAPPY', 'ZSTD', 'GZIP'],
    maxThroughputMbPerSec: 750,
    connectionPoolSize: 18,
    supportsSchemaEvolution: true,
    supportsTransactions: true
  },
  {
    connectorId: 'CONN-DWH-067',
    name: 'Databricks Delta Sharing (Cluster #67)',
    category: 'CloudDataWarehouseConnectors',
    protocolType: 'BATCH_CDC',
    supportedCompression: ['SNAPPY', 'ZSTD', 'GZIP'],
    maxThroughputMbPerSec: 775,
    connectionPoolSize: 19,
    supportsSchemaEvolution: true,
    supportsTransactions: false
  },
  {
    connectorId: 'CONN-DWH-068',
    name: 'Snowflake Snowpipe Streaming (Cluster #68)',
    category: 'CloudDataWarehouseConnectors',
    protocolType: 'STREAMING',
    supportedCompression: ['SNAPPY', 'ZSTD', 'GZIP'],
    maxThroughputMbPerSec: 800,
    connectionPoolSize: 20,
    supportsSchemaEvolution: true,
    supportsTransactions: true
  },
  {
    connectorId: 'CONN-DWH-069',
    name: 'Google BigQuery Storage API (Cluster #69)',
    category: 'CloudDataWarehouseConnectors',
    protocolType: 'BATCH_CDC',
    supportedCompression: ['SNAPPY', 'ZSTD', 'GZIP'],
    maxThroughputMbPerSec: 825,
    connectionPoolSize: 21,
    supportsSchemaEvolution: true,
    supportsTransactions: false
  },
  {
    connectorId: 'CONN-DWH-070',
    name: 'AWS Redshift Serverless Sink (Cluster #70)',
    category: 'CloudDataWarehouseConnectors',
    protocolType: 'BATCH_CDC',
    supportedCompression: ['SNAPPY', 'ZSTD', 'GZIP'],
    maxThroughputMbPerSec: 850,
    connectionPoolSize: 22,
    supportsSchemaEvolution: true,
    supportsTransactions: true
  },
  {
    connectorId: 'CONN-DWH-071',
    name: 'Databricks Delta Sharing (Cluster #71)',
    category: 'CloudDataWarehouseConnectors',
    protocolType: 'BATCH_CDC',
    supportedCompression: ['SNAPPY', 'ZSTD', 'GZIP'],
    maxThroughputMbPerSec: 875,
    connectionPoolSize: 23,
    supportsSchemaEvolution: true,
    supportsTransactions: false
  },
  {
    connectorId: 'CONN-DWH-072',
    name: 'Snowflake Snowpipe Streaming (Cluster #72)',
    category: 'CloudDataWarehouseConnectors',
    protocolType: 'STREAMING',
    supportedCompression: ['SNAPPY', 'ZSTD', 'GZIP'],
    maxThroughputMbPerSec: 900,
    connectionPoolSize: 24,
    supportsSchemaEvolution: true,
    supportsTransactions: true
  },
  {
    connectorId: 'CONN-DWH-073',
    name: 'Google BigQuery Storage API (Cluster #73)',
    category: 'CloudDataWarehouseConnectors',
    protocolType: 'BATCH_CDC',
    supportedCompression: ['SNAPPY', 'ZSTD', 'GZIP'],
    maxThroughputMbPerSec: 925,
    connectionPoolSize: 25,
    supportsSchemaEvolution: true,
    supportsTransactions: false
  },
  {
    connectorId: 'CONN-DWH-074',
    name: 'AWS Redshift Serverless Sink (Cluster #74)',
    category: 'CloudDataWarehouseConnectors',
    protocolType: 'BATCH_CDC',
    supportedCompression: ['SNAPPY', 'ZSTD', 'GZIP'],
    maxThroughputMbPerSec: 950,
    connectionPoolSize: 26,
    supportsSchemaEvolution: true,
    supportsTransactions: true
  },
  {
    connectorId: 'CONN-DWH-075',
    name: 'Databricks Delta Sharing (Cluster #75)',
    category: 'CloudDataWarehouseConnectors',
    protocolType: 'BATCH_CDC',
    supportedCompression: ['SNAPPY', 'ZSTD', 'GZIP'],
    maxThroughputMbPerSec: 975,
    connectionPoolSize: 27,
    supportsSchemaEvolution: true,
    supportsTransactions: false
  },
  {
    connectorId: 'CONN-DWH-076',
    name: 'Snowflake Snowpipe Streaming (Cluster #76)',
    category: 'CloudDataWarehouseConnectors',
    protocolType: 'STREAMING',
    supportedCompression: ['SNAPPY', 'ZSTD', 'GZIP'],
    maxThroughputMbPerSec: 1000,
    connectionPoolSize: 28,
    supportsSchemaEvolution: true,
    supportsTransactions: true
  },
  {
    connectorId: 'CONN-DWH-077',
    name: 'Google BigQuery Storage API (Cluster #77)',
    category: 'CloudDataWarehouseConnectors',
    protocolType: 'BATCH_CDC',
    supportedCompression: ['SNAPPY', 'ZSTD', 'GZIP'],
    maxThroughputMbPerSec: 1025,
    connectionPoolSize: 29,
    supportsSchemaEvolution: true,
    supportsTransactions: false
  },
  {
    connectorId: 'CONN-DWH-078',
    name: 'AWS Redshift Serverless Sink (Cluster #78)',
    category: 'CloudDataWarehouseConnectors',
    protocolType: 'BATCH_CDC',
    supportedCompression: ['SNAPPY', 'ZSTD', 'GZIP'],
    maxThroughputMbPerSec: 1050,
    connectionPoolSize: 30,
    supportsSchemaEvolution: true,
    supportsTransactions: true
  },
  {
    connectorId: 'CONN-DWH-079',
    name: 'Databricks Delta Sharing (Cluster #79)',
    category: 'CloudDataWarehouseConnectors',
    protocolType: 'BATCH_CDC',
    supportedCompression: ['SNAPPY', 'ZSTD', 'GZIP'],
    maxThroughputMbPerSec: 1075,
    connectionPoolSize: 31,
    supportsSchemaEvolution: true,
    supportsTransactions: false
  },
  {
    connectorId: 'CONN-DWH-080',
    name: 'Snowflake Snowpipe Streaming (Cluster #80)',
    category: 'CloudDataWarehouseConnectors',
    protocolType: 'STREAMING',
    supportedCompression: ['SNAPPY', 'ZSTD', 'GZIP'],
    maxThroughputMbPerSec: 100,
    connectionPoolSize: 32,
    supportsSchemaEvolution: true,
    supportsTransactions: true
  },
  {
    connectorId: 'CONN-DWH-081',
    name: 'Google BigQuery Storage API (Cluster #81)',
    category: 'CloudDataWarehouseConnectors',
    protocolType: 'BATCH_CDC',
    supportedCompression: ['SNAPPY', 'ZSTD', 'GZIP'],
    maxThroughputMbPerSec: 125,
    connectionPoolSize: 33,
    supportsSchemaEvolution: true,
    supportsTransactions: false
  },
  {
    connectorId: 'CONN-DWH-082',
    name: 'AWS Redshift Serverless Sink (Cluster #82)',
    category: 'CloudDataWarehouseConnectors',
    protocolType: 'BATCH_CDC',
    supportedCompression: ['SNAPPY', 'ZSTD', 'GZIP'],
    maxThroughputMbPerSec: 150,
    connectionPoolSize: 34,
    supportsSchemaEvolution: true,
    supportsTransactions: true
  },
  {
    connectorId: 'CONN-DWH-083',
    name: 'Databricks Delta Sharing (Cluster #83)',
    category: 'CloudDataWarehouseConnectors',
    protocolType: 'BATCH_CDC',
    supportedCompression: ['SNAPPY', 'ZSTD', 'GZIP'],
    maxThroughputMbPerSec: 175,
    connectionPoolSize: 35,
    supportsSchemaEvolution: true,
    supportsTransactions: false
  },
  {
    connectorId: 'CONN-DWH-084',
    name: 'Snowflake Snowpipe Streaming (Cluster #84)',
    category: 'CloudDataWarehouseConnectors',
    protocolType: 'STREAMING',
    supportedCompression: ['SNAPPY', 'ZSTD', 'GZIP'],
    maxThroughputMbPerSec: 200,
    connectionPoolSize: 36,
    supportsSchemaEvolution: true,
    supportsTransactions: true
  },
  {
    connectorId: 'CONN-DWH-085',
    name: 'Google BigQuery Storage API (Cluster #85)',
    category: 'CloudDataWarehouseConnectors',
    protocolType: 'BATCH_CDC',
    supportedCompression: ['SNAPPY', 'ZSTD', 'GZIP'],
    maxThroughputMbPerSec: 225,
    connectionPoolSize: 37,
    supportsSchemaEvolution: true,
    supportsTransactions: false
  },
  {
    connectorId: 'CONN-DWH-086',
    name: 'AWS Redshift Serverless Sink (Cluster #86)',
    category: 'CloudDataWarehouseConnectors',
    protocolType: 'BATCH_CDC',
    supportedCompression: ['SNAPPY', 'ZSTD', 'GZIP'],
    maxThroughputMbPerSec: 250,
    connectionPoolSize: 38,
    supportsSchemaEvolution: true,
    supportsTransactions: true
  },
  {
    connectorId: 'CONN-DWH-087',
    name: 'Databricks Delta Sharing (Cluster #87)',
    category: 'CloudDataWarehouseConnectors',
    protocolType: 'BATCH_CDC',
    supportedCompression: ['SNAPPY', 'ZSTD', 'GZIP'],
    maxThroughputMbPerSec: 275,
    connectionPoolSize: 39,
    supportsSchemaEvolution: true,
    supportsTransactions: false
  },
  {
    connectorId: 'CONN-DWH-088',
    name: 'Snowflake Snowpipe Streaming (Cluster #88)',
    category: 'CloudDataWarehouseConnectors',
    protocolType: 'STREAMING',
    supportedCompression: ['SNAPPY', 'ZSTD', 'GZIP'],
    maxThroughputMbPerSec: 300,
    connectionPoolSize: 40,
    supportsSchemaEvolution: true,
    supportsTransactions: true
  },
  {
    connectorId: 'CONN-DWH-089',
    name: 'Google BigQuery Storage API (Cluster #89)',
    category: 'CloudDataWarehouseConnectors',
    protocolType: 'BATCH_CDC',
    supportedCompression: ['SNAPPY', 'ZSTD', 'GZIP'],
    maxThroughputMbPerSec: 325,
    connectionPoolSize: 41,
    supportsSchemaEvolution: true,
    supportsTransactions: false
  },
  {
    connectorId: 'CONN-DWH-090',
    name: 'AWS Redshift Serverless Sink (Cluster #90)',
    category: 'CloudDataWarehouseConnectors',
    protocolType: 'BATCH_CDC',
    supportedCompression: ['SNAPPY', 'ZSTD', 'GZIP'],
    maxThroughputMbPerSec: 350,
    connectionPoolSize: 42,
    supportsSchemaEvolution: true,
    supportsTransactions: true
  },
  {
    connectorId: 'CONN-DWH-091',
    name: 'Databricks Delta Sharing (Cluster #91)',
    category: 'CloudDataWarehouseConnectors',
    protocolType: 'BATCH_CDC',
    supportedCompression: ['SNAPPY', 'ZSTD', 'GZIP'],
    maxThroughputMbPerSec: 375,
    connectionPoolSize: 43,
    supportsSchemaEvolution: true,
    supportsTransactions: false
  },
  {
    connectorId: 'CONN-DWH-092',
    name: 'Snowflake Snowpipe Streaming (Cluster #92)',
    category: 'CloudDataWarehouseConnectors',
    protocolType: 'STREAMING',
    supportedCompression: ['SNAPPY', 'ZSTD', 'GZIP'],
    maxThroughputMbPerSec: 400,
    connectionPoolSize: 44,
    supportsSchemaEvolution: true,
    supportsTransactions: true
  },
  {
    connectorId: 'CONN-DWH-093',
    name: 'Google BigQuery Storage API (Cluster #93)',
    category: 'CloudDataWarehouseConnectors',
    protocolType: 'BATCH_CDC',
    supportedCompression: ['SNAPPY', 'ZSTD', 'GZIP'],
    maxThroughputMbPerSec: 425,
    connectionPoolSize: 45,
    supportsSchemaEvolution: true,
    supportsTransactions: false
  },
  {
    connectorId: 'CONN-DWH-094',
    name: 'AWS Redshift Serverless Sink (Cluster #94)',
    category: 'CloudDataWarehouseConnectors',
    protocolType: 'BATCH_CDC',
    supportedCompression: ['SNAPPY', 'ZSTD', 'GZIP'],
    maxThroughputMbPerSec: 450,
    connectionPoolSize: 46,
    supportsSchemaEvolution: true,
    supportsTransactions: true
  },
  {
    connectorId: 'CONN-DWH-095',
    name: 'Databricks Delta Sharing (Cluster #95)',
    category: 'CloudDataWarehouseConnectors',
    protocolType: 'BATCH_CDC',
    supportedCompression: ['SNAPPY', 'ZSTD', 'GZIP'],
    maxThroughputMbPerSec: 475,
    connectionPoolSize: 47,
    supportsSchemaEvolution: true,
    supportsTransactions: false
  },
  {
    connectorId: 'CONN-DWH-096',
    name: 'Snowflake Snowpipe Streaming (Cluster #96)',
    category: 'CloudDataWarehouseConnectors',
    protocolType: 'STREAMING',
    supportedCompression: ['SNAPPY', 'ZSTD', 'GZIP'],
    maxThroughputMbPerSec: 500,
    connectionPoolSize: 16,
    supportsSchemaEvolution: true,
    supportsTransactions: true
  },
  {
    connectorId: 'CONN-DWH-097',
    name: 'Google BigQuery Storage API (Cluster #97)',
    category: 'CloudDataWarehouseConnectors',
    protocolType: 'BATCH_CDC',
    supportedCompression: ['SNAPPY', 'ZSTD', 'GZIP'],
    maxThroughputMbPerSec: 525,
    connectionPoolSize: 17,
    supportsSchemaEvolution: true,
    supportsTransactions: false
  },
  {
    connectorId: 'CONN-DWH-098',
    name: 'AWS Redshift Serverless Sink (Cluster #98)',
    category: 'CloudDataWarehouseConnectors',
    protocolType: 'BATCH_CDC',
    supportedCompression: ['SNAPPY', 'ZSTD', 'GZIP'],
    maxThroughputMbPerSec: 550,
    connectionPoolSize: 18,
    supportsSchemaEvolution: true,
    supportsTransactions: true
  },
  {
    connectorId: 'CONN-DWH-099',
    name: 'Databricks Delta Sharing (Cluster #99)',
    category: 'CloudDataWarehouseConnectors',
    protocolType: 'BATCH_CDC',
    supportedCompression: ['SNAPPY', 'ZSTD', 'GZIP'],
    maxThroughputMbPerSec: 575,
    connectionPoolSize: 19,
    supportsSchemaEvolution: true,
    supportsTransactions: false
  },
  {
    connectorId: 'CONN-DWH-100',
    name: 'Snowflake Snowpipe Streaming (Cluster #100)',
    category: 'CloudDataWarehouseConnectors',
    protocolType: 'STREAMING',
    supportedCompression: ['SNAPPY', 'ZSTD', 'GZIP'],
    maxThroughputMbPerSec: 600,
    connectionPoolSize: 20,
    supportsSchemaEvolution: true,
    supportsTransactions: true
  },
  {
    connectorId: 'CONN-DWH-101',
    name: 'Google BigQuery Storage API (Cluster #101)',
    category: 'CloudDataWarehouseConnectors',
    protocolType: 'BATCH_CDC',
    supportedCompression: ['SNAPPY', 'ZSTD', 'GZIP'],
    maxThroughputMbPerSec: 625,
    connectionPoolSize: 21,
    supportsSchemaEvolution: true,
    supportsTransactions: false
  },
  {
    connectorId: 'CONN-DWH-102',
    name: 'AWS Redshift Serverless Sink (Cluster #102)',
    category: 'CloudDataWarehouseConnectors',
    protocolType: 'BATCH_CDC',
    supportedCompression: ['SNAPPY', 'ZSTD', 'GZIP'],
    maxThroughputMbPerSec: 650,
    connectionPoolSize: 22,
    supportsSchemaEvolution: true,
    supportsTransactions: true
  },
  {
    connectorId: 'CONN-DWH-103',
    name: 'Databricks Delta Sharing (Cluster #103)',
    category: 'CloudDataWarehouseConnectors',
    protocolType: 'BATCH_CDC',
    supportedCompression: ['SNAPPY', 'ZSTD', 'GZIP'],
    maxThroughputMbPerSec: 675,
    connectionPoolSize: 23,
    supportsSchemaEvolution: true,
    supportsTransactions: false
  },
  {
    connectorId: 'CONN-DWH-104',
    name: 'Snowflake Snowpipe Streaming (Cluster #104)',
    category: 'CloudDataWarehouseConnectors',
    protocolType: 'STREAMING',
    supportedCompression: ['SNAPPY', 'ZSTD', 'GZIP'],
    maxThroughputMbPerSec: 700,
    connectionPoolSize: 24,
    supportsSchemaEvolution: true,
    supportsTransactions: true
  },
  {
    connectorId: 'CONN-DWH-105',
    name: 'Google BigQuery Storage API (Cluster #105)',
    category: 'CloudDataWarehouseConnectors',
    protocolType: 'BATCH_CDC',
    supportedCompression: ['SNAPPY', 'ZSTD', 'GZIP'],
    maxThroughputMbPerSec: 725,
    connectionPoolSize: 25,
    supportsSchemaEvolution: true,
    supportsTransactions: false
  },
  {
    connectorId: 'CONN-DWH-106',
    name: 'AWS Redshift Serverless Sink (Cluster #106)',
    category: 'CloudDataWarehouseConnectors',
    protocolType: 'BATCH_CDC',
    supportedCompression: ['SNAPPY', 'ZSTD', 'GZIP'],
    maxThroughputMbPerSec: 750,
    connectionPoolSize: 26,
    supportsSchemaEvolution: true,
    supportsTransactions: true
  },
  {
    connectorId: 'CONN-DWH-107',
    name: 'Databricks Delta Sharing (Cluster #107)',
    category: 'CloudDataWarehouseConnectors',
    protocolType: 'BATCH_CDC',
    supportedCompression: ['SNAPPY', 'ZSTD', 'GZIP'],
    maxThroughputMbPerSec: 775,
    connectionPoolSize: 27,
    supportsSchemaEvolution: true,
    supportsTransactions: false
  },
  {
    connectorId: 'CONN-DWH-108',
    name: 'Snowflake Snowpipe Streaming (Cluster #108)',
    category: 'CloudDataWarehouseConnectors',
    protocolType: 'STREAMING',
    supportedCompression: ['SNAPPY', 'ZSTD', 'GZIP'],
    maxThroughputMbPerSec: 800,
    connectionPoolSize: 28,
    supportsSchemaEvolution: true,
    supportsTransactions: true
  },
  {
    connectorId: 'CONN-DWH-109',
    name: 'Google BigQuery Storage API (Cluster #109)',
    category: 'CloudDataWarehouseConnectors',
    protocolType: 'BATCH_CDC',
    supportedCompression: ['SNAPPY', 'ZSTD', 'GZIP'],
    maxThroughputMbPerSec: 825,
    connectionPoolSize: 29,
    supportsSchemaEvolution: true,
    supportsTransactions: false
  },
  {
    connectorId: 'CONN-DWH-110',
    name: 'AWS Redshift Serverless Sink (Cluster #110)',
    category: 'CloudDataWarehouseConnectors',
    protocolType: 'BATCH_CDC',
    supportedCompression: ['SNAPPY', 'ZSTD', 'GZIP'],
    maxThroughputMbPerSec: 850,
    connectionPoolSize: 30,
    supportsSchemaEvolution: true,
    supportsTransactions: true
  },
  {
    connectorId: 'CONN-DWH-111',
    name: 'Databricks Delta Sharing (Cluster #111)',
    category: 'CloudDataWarehouseConnectors',
    protocolType: 'BATCH_CDC',
    supportedCompression: ['SNAPPY', 'ZSTD', 'GZIP'],
    maxThroughputMbPerSec: 875,
    connectionPoolSize: 31,
    supportsSchemaEvolution: true,
    supportsTransactions: false
  },
  {
    connectorId: 'CONN-DWH-112',
    name: 'Snowflake Snowpipe Streaming (Cluster #112)',
    category: 'CloudDataWarehouseConnectors',
    protocolType: 'STREAMING',
    supportedCompression: ['SNAPPY', 'ZSTD', 'GZIP'],
    maxThroughputMbPerSec: 900,
    connectionPoolSize: 32,
    supportsSchemaEvolution: true,
    supportsTransactions: true
  },
  {
    connectorId: 'CONN-DWH-113',
    name: 'Google BigQuery Storage API (Cluster #113)',
    category: 'CloudDataWarehouseConnectors',
    protocolType: 'BATCH_CDC',
    supportedCompression: ['SNAPPY', 'ZSTD', 'GZIP'],
    maxThroughputMbPerSec: 925,
    connectionPoolSize: 33,
    supportsSchemaEvolution: true,
    supportsTransactions: false
  },
  {
    connectorId: 'CONN-DWH-114',
    name: 'AWS Redshift Serverless Sink (Cluster #114)',
    category: 'CloudDataWarehouseConnectors',
    protocolType: 'BATCH_CDC',
    supportedCompression: ['SNAPPY', 'ZSTD', 'GZIP'],
    maxThroughputMbPerSec: 950,
    connectionPoolSize: 34,
    supportsSchemaEvolution: true,
    supportsTransactions: true
  },
  {
    connectorId: 'CONN-DWH-115',
    name: 'Databricks Delta Sharing (Cluster #115)',
    category: 'CloudDataWarehouseConnectors',
    protocolType: 'BATCH_CDC',
    supportedCompression: ['SNAPPY', 'ZSTD', 'GZIP'],
    maxThroughputMbPerSec: 975,
    connectionPoolSize: 35,
    supportsSchemaEvolution: true,
    supportsTransactions: false
  },
  {
    connectorId: 'CONN-DWH-116',
    name: 'Snowflake Snowpipe Streaming (Cluster #116)',
    category: 'CloudDataWarehouseConnectors',
    protocolType: 'STREAMING',
    supportedCompression: ['SNAPPY', 'ZSTD', 'GZIP'],
    maxThroughputMbPerSec: 1000,
    connectionPoolSize: 36,
    supportsSchemaEvolution: true,
    supportsTransactions: true
  },
  {
    connectorId: 'CONN-DWH-117',
    name: 'Google BigQuery Storage API (Cluster #117)',
    category: 'CloudDataWarehouseConnectors',
    protocolType: 'BATCH_CDC',
    supportedCompression: ['SNAPPY', 'ZSTD', 'GZIP'],
    maxThroughputMbPerSec: 1025,
    connectionPoolSize: 37,
    supportsSchemaEvolution: true,
    supportsTransactions: false
  },
  {
    connectorId: 'CONN-DWH-118',
    name: 'AWS Redshift Serverless Sink (Cluster #118)',
    category: 'CloudDataWarehouseConnectors',
    protocolType: 'BATCH_CDC',
    supportedCompression: ['SNAPPY', 'ZSTD', 'GZIP'],
    maxThroughputMbPerSec: 1050,
    connectionPoolSize: 38,
    supportsSchemaEvolution: true,
    supportsTransactions: true
  },
  {
    connectorId: 'CONN-DWH-119',
    name: 'Databricks Delta Sharing (Cluster #119)',
    category: 'CloudDataWarehouseConnectors',
    protocolType: 'BATCH_CDC',
    supportedCompression: ['SNAPPY', 'ZSTD', 'GZIP'],
    maxThroughputMbPerSec: 1075,
    connectionPoolSize: 39,
    supportsSchemaEvolution: true,
    supportsTransactions: false
  },
  {
    connectorId: 'CONN-DWH-120',
    name: 'Snowflake Snowpipe Streaming (Cluster #120)',
    category: 'CloudDataWarehouseConnectors',
    protocolType: 'STREAMING',
    supportedCompression: ['SNAPPY', 'ZSTD', 'GZIP'],
    maxThroughputMbPerSec: 100,
    connectionPoolSize: 40,
    supportsSchemaEvolution: true,
    supportsTransactions: true
  }
];
