/**
 * Connector Schema & Protocol Directory: StreamingBrokerConnectors
 */

export interface ConnectorSpec {
  connectorId: string;
  name: string;
  category: string;
  protocolType: string;
  supportedCompression: string[];
  maxThroughputMbPerSec: number;
  connectionPoolSize: number;
  supportsSchemaEvolution: boolean;
  supportsTransactions: boolean;
}

export const CONNECTORS_STR_DATASET: ConnectorSpec[] = [
  {
    connectorId: 'CONN-STR-001',
    name: 'AWS Kinesis Firehose Stream (Cluster #1)',
    category: 'StreamingBrokerConnectors',
    protocolType: 'STREAMING',
    supportedCompression: ['SNAPPY', 'ZSTD', 'GZIP'],
    maxThroughputMbPerSec: 125,
    connectionPoolSize: 17,
    supportsSchemaEvolution: true,
    supportsTransactions: false
  },
  {
    connectorId: 'CONN-STR-002',
    name: 'RabbitMQ AMQP Adapter (Cluster #2)',
    category: 'StreamingBrokerConnectors',
    protocolType: 'BATCH_CDC',
    supportedCompression: ['SNAPPY', 'ZSTD', 'GZIP'],
    maxThroughputMbPerSec: 150,
    connectionPoolSize: 18,
    supportsSchemaEvolution: true,
    supportsTransactions: true
  },
  {
    connectorId: 'CONN-STR-003',
    name: 'Apache Pulsar Mesh Client (Cluster #3)',
    category: 'StreamingBrokerConnectors',
    protocolType: 'BATCH_CDC',
    supportedCompression: ['SNAPPY', 'ZSTD', 'GZIP'],
    maxThroughputMbPerSec: 175,
    connectionPoolSize: 19,
    supportsSchemaEvolution: true,
    supportsTransactions: false
  },
  {
    connectorId: 'CONN-STR-004',
    name: 'Apache Kafka Consumer Adapter (Cluster #4)',
    category: 'StreamingBrokerConnectors',
    protocolType: 'STREAMING',
    supportedCompression: ['SNAPPY', 'ZSTD', 'GZIP'],
    maxThroughputMbPerSec: 200,
    connectionPoolSize: 20,
    supportsSchemaEvolution: true,
    supportsTransactions: true
  },
  {
    connectorId: 'CONN-STR-005',
    name: 'AWS Kinesis Firehose Stream (Cluster #5)',
    category: 'StreamingBrokerConnectors',
    protocolType: 'STREAMING',
    supportedCompression: ['SNAPPY', 'ZSTD', 'GZIP'],
    maxThroughputMbPerSec: 225,
    connectionPoolSize: 21,
    supportsSchemaEvolution: true,
    supportsTransactions: false
  },
  {
    connectorId: 'CONN-STR-006',
    name: 'RabbitMQ AMQP Adapter (Cluster #6)',
    category: 'StreamingBrokerConnectors',
    protocolType: 'BATCH_CDC',
    supportedCompression: ['SNAPPY', 'ZSTD', 'GZIP'],
    maxThroughputMbPerSec: 250,
    connectionPoolSize: 22,
    supportsSchemaEvolution: true,
    supportsTransactions: true
  },
  {
    connectorId: 'CONN-STR-007',
    name: 'Apache Pulsar Mesh Client (Cluster #7)',
    category: 'StreamingBrokerConnectors',
    protocolType: 'BATCH_CDC',
    supportedCompression: ['SNAPPY', 'ZSTD', 'GZIP'],
    maxThroughputMbPerSec: 275,
    connectionPoolSize: 23,
    supportsSchemaEvolution: true,
    supportsTransactions: false
  },
  {
    connectorId: 'CONN-STR-008',
    name: 'Apache Kafka Consumer Adapter (Cluster #8)',
    category: 'StreamingBrokerConnectors',
    protocolType: 'STREAMING',
    supportedCompression: ['SNAPPY', 'ZSTD', 'GZIP'],
    maxThroughputMbPerSec: 300,
    connectionPoolSize: 24,
    supportsSchemaEvolution: true,
    supportsTransactions: true
  },
  {
    connectorId: 'CONN-STR-009',
    name: 'AWS Kinesis Firehose Stream (Cluster #9)',
    category: 'StreamingBrokerConnectors',
    protocolType: 'STREAMING',
    supportedCompression: ['SNAPPY', 'ZSTD', 'GZIP'],
    maxThroughputMbPerSec: 325,
    connectionPoolSize: 25,
    supportsSchemaEvolution: true,
    supportsTransactions: false
  },
  {
    connectorId: 'CONN-STR-010',
    name: 'RabbitMQ AMQP Adapter (Cluster #10)',
    category: 'StreamingBrokerConnectors',
    protocolType: 'BATCH_CDC',
    supportedCompression: ['SNAPPY', 'ZSTD', 'GZIP'],
    maxThroughputMbPerSec: 350,
    connectionPoolSize: 26,
    supportsSchemaEvolution: true,
    supportsTransactions: true
  },
  {
    connectorId: 'CONN-STR-011',
    name: 'Apache Pulsar Mesh Client (Cluster #11)',
    category: 'StreamingBrokerConnectors',
    protocolType: 'BATCH_CDC',
    supportedCompression: ['SNAPPY', 'ZSTD', 'GZIP'],
    maxThroughputMbPerSec: 375,
    connectionPoolSize: 27,
    supportsSchemaEvolution: true,
    supportsTransactions: false
  },
  {
    connectorId: 'CONN-STR-012',
    name: 'Apache Kafka Consumer Adapter (Cluster #12)',
    category: 'StreamingBrokerConnectors',
    protocolType: 'STREAMING',
    supportedCompression: ['SNAPPY', 'ZSTD', 'GZIP'],
    maxThroughputMbPerSec: 400,
    connectionPoolSize: 28,
    supportsSchemaEvolution: true,
    supportsTransactions: true
  },
  {
    connectorId: 'CONN-STR-013',
    name: 'AWS Kinesis Firehose Stream (Cluster #13)',
    category: 'StreamingBrokerConnectors',
    protocolType: 'STREAMING',
    supportedCompression: ['SNAPPY', 'ZSTD', 'GZIP'],
    maxThroughputMbPerSec: 425,
    connectionPoolSize: 29,
    supportsSchemaEvolution: true,
    supportsTransactions: false
  },
  {
    connectorId: 'CONN-STR-014',
    name: 'RabbitMQ AMQP Adapter (Cluster #14)',
    category: 'StreamingBrokerConnectors',
    protocolType: 'BATCH_CDC',
    supportedCompression: ['SNAPPY', 'ZSTD', 'GZIP'],
    maxThroughputMbPerSec: 450,
    connectionPoolSize: 30,
    supportsSchemaEvolution: true,
    supportsTransactions: true
  },
  {
    connectorId: 'CONN-STR-015',
    name: 'Apache Pulsar Mesh Client (Cluster #15)',
    category: 'StreamingBrokerConnectors',
    protocolType: 'BATCH_CDC',
    supportedCompression: ['SNAPPY', 'ZSTD', 'GZIP'],
    maxThroughputMbPerSec: 475,
    connectionPoolSize: 31,
    supportsSchemaEvolution: true,
    supportsTransactions: false
  },
  {
    connectorId: 'CONN-STR-016',
    name: 'Apache Kafka Consumer Adapter (Cluster #16)',
    category: 'StreamingBrokerConnectors',
    protocolType: 'STREAMING',
    supportedCompression: ['SNAPPY', 'ZSTD', 'GZIP'],
    maxThroughputMbPerSec: 500,
    connectionPoolSize: 32,
    supportsSchemaEvolution: true,
    supportsTransactions: true
  },
  {
    connectorId: 'CONN-STR-017',
    name: 'AWS Kinesis Firehose Stream (Cluster #17)',
    category: 'StreamingBrokerConnectors',
    protocolType: 'STREAMING',
    supportedCompression: ['SNAPPY', 'ZSTD', 'GZIP'],
    maxThroughputMbPerSec: 525,
    connectionPoolSize: 33,
    supportsSchemaEvolution: true,
    supportsTransactions: false
  },
  {
    connectorId: 'CONN-STR-018',
    name: 'RabbitMQ AMQP Adapter (Cluster #18)',
    category: 'StreamingBrokerConnectors',
    protocolType: 'BATCH_CDC',
    supportedCompression: ['SNAPPY', 'ZSTD', 'GZIP'],
    maxThroughputMbPerSec: 550,
    connectionPoolSize: 34,
    supportsSchemaEvolution: true,
    supportsTransactions: true
  },
  {
    connectorId: 'CONN-STR-019',
    name: 'Apache Pulsar Mesh Client (Cluster #19)',
    category: 'StreamingBrokerConnectors',
    protocolType: 'BATCH_CDC',
    supportedCompression: ['SNAPPY', 'ZSTD', 'GZIP'],
    maxThroughputMbPerSec: 575,
    connectionPoolSize: 35,
    supportsSchemaEvolution: true,
    supportsTransactions: false
  },
  {
    connectorId: 'CONN-STR-020',
    name: 'Apache Kafka Consumer Adapter (Cluster #20)',
    category: 'StreamingBrokerConnectors',
    protocolType: 'STREAMING',
    supportedCompression: ['SNAPPY', 'ZSTD', 'GZIP'],
    maxThroughputMbPerSec: 600,
    connectionPoolSize: 36,
    supportsSchemaEvolution: true,
    supportsTransactions: true
  },
  {
    connectorId: 'CONN-STR-021',
    name: 'AWS Kinesis Firehose Stream (Cluster #21)',
    category: 'StreamingBrokerConnectors',
    protocolType: 'STREAMING',
    supportedCompression: ['SNAPPY', 'ZSTD', 'GZIP'],
    maxThroughputMbPerSec: 625,
    connectionPoolSize: 37,
    supportsSchemaEvolution: true,
    supportsTransactions: false
  },
  {
    connectorId: 'CONN-STR-022',
    name: 'RabbitMQ AMQP Adapter (Cluster #22)',
    category: 'StreamingBrokerConnectors',
    protocolType: 'BATCH_CDC',
    supportedCompression: ['SNAPPY', 'ZSTD', 'GZIP'],
    maxThroughputMbPerSec: 650,
    connectionPoolSize: 38,
    supportsSchemaEvolution: true,
    supportsTransactions: true
  },
  {
    connectorId: 'CONN-STR-023',
    name: 'Apache Pulsar Mesh Client (Cluster #23)',
    category: 'StreamingBrokerConnectors',
    protocolType: 'BATCH_CDC',
    supportedCompression: ['SNAPPY', 'ZSTD', 'GZIP'],
    maxThroughputMbPerSec: 675,
    connectionPoolSize: 39,
    supportsSchemaEvolution: true,
    supportsTransactions: false
  },
  {
    connectorId: 'CONN-STR-024',
    name: 'Apache Kafka Consumer Adapter (Cluster #24)',
    category: 'StreamingBrokerConnectors',
    protocolType: 'STREAMING',
    supportedCompression: ['SNAPPY', 'ZSTD', 'GZIP'],
    maxThroughputMbPerSec: 700,
    connectionPoolSize: 40,
    supportsSchemaEvolution: true,
    supportsTransactions: true
  },
  {
    connectorId: 'CONN-STR-025',
    name: 'AWS Kinesis Firehose Stream (Cluster #25)',
    category: 'StreamingBrokerConnectors',
    protocolType: 'STREAMING',
    supportedCompression: ['SNAPPY', 'ZSTD', 'GZIP'],
    maxThroughputMbPerSec: 725,
    connectionPoolSize: 41,
    supportsSchemaEvolution: true,
    supportsTransactions: false
  },
  {
    connectorId: 'CONN-STR-026',
    name: 'RabbitMQ AMQP Adapter (Cluster #26)',
    category: 'StreamingBrokerConnectors',
    protocolType: 'BATCH_CDC',
    supportedCompression: ['SNAPPY', 'ZSTD', 'GZIP'],
    maxThroughputMbPerSec: 750,
    connectionPoolSize: 42,
    supportsSchemaEvolution: true,
    supportsTransactions: true
  },
  {
    connectorId: 'CONN-STR-027',
    name: 'Apache Pulsar Mesh Client (Cluster #27)',
    category: 'StreamingBrokerConnectors',
    protocolType: 'BATCH_CDC',
    supportedCompression: ['SNAPPY', 'ZSTD', 'GZIP'],
    maxThroughputMbPerSec: 775,
    connectionPoolSize: 43,
    supportsSchemaEvolution: true,
    supportsTransactions: false
  },
  {
    connectorId: 'CONN-STR-028',
    name: 'Apache Kafka Consumer Adapter (Cluster #28)',
    category: 'StreamingBrokerConnectors',
    protocolType: 'STREAMING',
    supportedCompression: ['SNAPPY', 'ZSTD', 'GZIP'],
    maxThroughputMbPerSec: 800,
    connectionPoolSize: 44,
    supportsSchemaEvolution: true,
    supportsTransactions: true
  },
  {
    connectorId: 'CONN-STR-029',
    name: 'AWS Kinesis Firehose Stream (Cluster #29)',
    category: 'StreamingBrokerConnectors',
    protocolType: 'STREAMING',
    supportedCompression: ['SNAPPY', 'ZSTD', 'GZIP'],
    maxThroughputMbPerSec: 825,
    connectionPoolSize: 45,
    supportsSchemaEvolution: true,
    supportsTransactions: false
  },
  {
    connectorId: 'CONN-STR-030',
    name: 'RabbitMQ AMQP Adapter (Cluster #30)',
    category: 'StreamingBrokerConnectors',
    protocolType: 'BATCH_CDC',
    supportedCompression: ['SNAPPY', 'ZSTD', 'GZIP'],
    maxThroughputMbPerSec: 850,
    connectionPoolSize: 46,
    supportsSchemaEvolution: true,
    supportsTransactions: true
  },
  {
    connectorId: 'CONN-STR-031',
    name: 'Apache Pulsar Mesh Client (Cluster #31)',
    category: 'StreamingBrokerConnectors',
    protocolType: 'BATCH_CDC',
    supportedCompression: ['SNAPPY', 'ZSTD', 'GZIP'],
    maxThroughputMbPerSec: 875,
    connectionPoolSize: 47,
    supportsSchemaEvolution: true,
    supportsTransactions: false
  },
  {
    connectorId: 'CONN-STR-032',
    name: 'Apache Kafka Consumer Adapter (Cluster #32)',
    category: 'StreamingBrokerConnectors',
    protocolType: 'STREAMING',
    supportedCompression: ['SNAPPY', 'ZSTD', 'GZIP'],
    maxThroughputMbPerSec: 900,
    connectionPoolSize: 16,
    supportsSchemaEvolution: true,
    supportsTransactions: true
  },
  {
    connectorId: 'CONN-STR-033',
    name: 'AWS Kinesis Firehose Stream (Cluster #33)',
    category: 'StreamingBrokerConnectors',
    protocolType: 'STREAMING',
    supportedCompression: ['SNAPPY', 'ZSTD', 'GZIP'],
    maxThroughputMbPerSec: 925,
    connectionPoolSize: 17,
    supportsSchemaEvolution: true,
    supportsTransactions: false
  },
  {
    connectorId: 'CONN-STR-034',
    name: 'RabbitMQ AMQP Adapter (Cluster #34)',
    category: 'StreamingBrokerConnectors',
    protocolType: 'BATCH_CDC',
    supportedCompression: ['SNAPPY', 'ZSTD', 'GZIP'],
    maxThroughputMbPerSec: 950,
    connectionPoolSize: 18,
    supportsSchemaEvolution: true,
    supportsTransactions: true
  },
  {
    connectorId: 'CONN-STR-035',
    name: 'Apache Pulsar Mesh Client (Cluster #35)',
    category: 'StreamingBrokerConnectors',
    protocolType: 'BATCH_CDC',
    supportedCompression: ['SNAPPY', 'ZSTD', 'GZIP'],
    maxThroughputMbPerSec: 975,
    connectionPoolSize: 19,
    supportsSchemaEvolution: true,
    supportsTransactions: false
  },
  {
    connectorId: 'CONN-STR-036',
    name: 'Apache Kafka Consumer Adapter (Cluster #36)',
    category: 'StreamingBrokerConnectors',
    protocolType: 'STREAMING',
    supportedCompression: ['SNAPPY', 'ZSTD', 'GZIP'],
    maxThroughputMbPerSec: 1000,
    connectionPoolSize: 20,
    supportsSchemaEvolution: true,
    supportsTransactions: true
  },
  {
    connectorId: 'CONN-STR-037',
    name: 'AWS Kinesis Firehose Stream (Cluster #37)',
    category: 'StreamingBrokerConnectors',
    protocolType: 'STREAMING',
    supportedCompression: ['SNAPPY', 'ZSTD', 'GZIP'],
    maxThroughputMbPerSec: 1025,
    connectionPoolSize: 21,
    supportsSchemaEvolution: true,
    supportsTransactions: false
  },
  {
    connectorId: 'CONN-STR-038',
    name: 'RabbitMQ AMQP Adapter (Cluster #38)',
    category: 'StreamingBrokerConnectors',
    protocolType: 'BATCH_CDC',
    supportedCompression: ['SNAPPY', 'ZSTD', 'GZIP'],
    maxThroughputMbPerSec: 1050,
    connectionPoolSize: 22,
    supportsSchemaEvolution: true,
    supportsTransactions: true
  },
  {
    connectorId: 'CONN-STR-039',
    name: 'Apache Pulsar Mesh Client (Cluster #39)',
    category: 'StreamingBrokerConnectors',
    protocolType: 'BATCH_CDC',
    supportedCompression: ['SNAPPY', 'ZSTD', 'GZIP'],
    maxThroughputMbPerSec: 1075,
    connectionPoolSize: 23,
    supportsSchemaEvolution: true,
    supportsTransactions: false
  },
  {
    connectorId: 'CONN-STR-040',
    name: 'Apache Kafka Consumer Adapter (Cluster #40)',
    category: 'StreamingBrokerConnectors',
    protocolType: 'STREAMING',
    supportedCompression: ['SNAPPY', 'ZSTD', 'GZIP'],
    maxThroughputMbPerSec: 100,
    connectionPoolSize: 24,
    supportsSchemaEvolution: true,
    supportsTransactions: true
  },
  {
    connectorId: 'CONN-STR-041',
    name: 'AWS Kinesis Firehose Stream (Cluster #41)',
    category: 'StreamingBrokerConnectors',
    protocolType: 'STREAMING',
    supportedCompression: ['SNAPPY', 'ZSTD', 'GZIP'],
    maxThroughputMbPerSec: 125,
    connectionPoolSize: 25,
    supportsSchemaEvolution: true,
    supportsTransactions: false
  },
  {
    connectorId: 'CONN-STR-042',
    name: 'RabbitMQ AMQP Adapter (Cluster #42)',
    category: 'StreamingBrokerConnectors',
    protocolType: 'BATCH_CDC',
    supportedCompression: ['SNAPPY', 'ZSTD', 'GZIP'],
    maxThroughputMbPerSec: 150,
    connectionPoolSize: 26,
    supportsSchemaEvolution: true,
    supportsTransactions: true
  },
  {
    connectorId: 'CONN-STR-043',
    name: 'Apache Pulsar Mesh Client (Cluster #43)',
    category: 'StreamingBrokerConnectors',
    protocolType: 'BATCH_CDC',
    supportedCompression: ['SNAPPY', 'ZSTD', 'GZIP'],
    maxThroughputMbPerSec: 175,
    connectionPoolSize: 27,
    supportsSchemaEvolution: true,
    supportsTransactions: false
  },
  {
    connectorId: 'CONN-STR-044',
    name: 'Apache Kafka Consumer Adapter (Cluster #44)',
    category: 'StreamingBrokerConnectors',
    protocolType: 'STREAMING',
    supportedCompression: ['SNAPPY', 'ZSTD', 'GZIP'],
    maxThroughputMbPerSec: 200,
    connectionPoolSize: 28,
    supportsSchemaEvolution: true,
    supportsTransactions: true
  },
  {
    connectorId: 'CONN-STR-045',
    name: 'AWS Kinesis Firehose Stream (Cluster #45)',
    category: 'StreamingBrokerConnectors',
    protocolType: 'STREAMING',
    supportedCompression: ['SNAPPY', 'ZSTD', 'GZIP'],
    maxThroughputMbPerSec: 225,
    connectionPoolSize: 29,
    supportsSchemaEvolution: true,
    supportsTransactions: false
  },
  {
    connectorId: 'CONN-STR-046',
    name: 'RabbitMQ AMQP Adapter (Cluster #46)',
    category: 'StreamingBrokerConnectors',
    protocolType: 'BATCH_CDC',
    supportedCompression: ['SNAPPY', 'ZSTD', 'GZIP'],
    maxThroughputMbPerSec: 250,
    connectionPoolSize: 30,
    supportsSchemaEvolution: true,
    supportsTransactions: true
  },
  {
    connectorId: 'CONN-STR-047',
    name: 'Apache Pulsar Mesh Client (Cluster #47)',
    category: 'StreamingBrokerConnectors',
    protocolType: 'BATCH_CDC',
    supportedCompression: ['SNAPPY', 'ZSTD', 'GZIP'],
    maxThroughputMbPerSec: 275,
    connectionPoolSize: 31,
    supportsSchemaEvolution: true,
    supportsTransactions: false
  },
  {
    connectorId: 'CONN-STR-048',
    name: 'Apache Kafka Consumer Adapter (Cluster #48)',
    category: 'StreamingBrokerConnectors',
    protocolType: 'STREAMING',
    supportedCompression: ['SNAPPY', 'ZSTD', 'GZIP'],
    maxThroughputMbPerSec: 300,
    connectionPoolSize: 32,
    supportsSchemaEvolution: true,
    supportsTransactions: true
  },
  {
    connectorId: 'CONN-STR-049',
    name: 'AWS Kinesis Firehose Stream (Cluster #49)',
    category: 'StreamingBrokerConnectors',
    protocolType: 'STREAMING',
    supportedCompression: ['SNAPPY', 'ZSTD', 'GZIP'],
    maxThroughputMbPerSec: 325,
    connectionPoolSize: 33,
    supportsSchemaEvolution: true,
    supportsTransactions: false
  },
  {
    connectorId: 'CONN-STR-050',
    name: 'RabbitMQ AMQP Adapter (Cluster #50)',
    category: 'StreamingBrokerConnectors',
    protocolType: 'BATCH_CDC',
    supportedCompression: ['SNAPPY', 'ZSTD', 'GZIP'],
    maxThroughputMbPerSec: 350,
    connectionPoolSize: 34,
    supportsSchemaEvolution: true,
    supportsTransactions: true
  },
  {
    connectorId: 'CONN-STR-051',
    name: 'Apache Pulsar Mesh Client (Cluster #51)',
    category: 'StreamingBrokerConnectors',
    protocolType: 'BATCH_CDC',
    supportedCompression: ['SNAPPY', 'ZSTD', 'GZIP'],
    maxThroughputMbPerSec: 375,
    connectionPoolSize: 35,
    supportsSchemaEvolution: true,
    supportsTransactions: false
  },
  {
    connectorId: 'CONN-STR-052',
    name: 'Apache Kafka Consumer Adapter (Cluster #52)',
    category: 'StreamingBrokerConnectors',
    protocolType: 'STREAMING',
    supportedCompression: ['SNAPPY', 'ZSTD', 'GZIP'],
    maxThroughputMbPerSec: 400,
    connectionPoolSize: 36,
    supportsSchemaEvolution: true,
    supportsTransactions: true
  },
  {
    connectorId: 'CONN-STR-053',
    name: 'AWS Kinesis Firehose Stream (Cluster #53)',
    category: 'StreamingBrokerConnectors',
    protocolType: 'STREAMING',
    supportedCompression: ['SNAPPY', 'ZSTD', 'GZIP'],
    maxThroughputMbPerSec: 425,
    connectionPoolSize: 37,
    supportsSchemaEvolution: true,
    supportsTransactions: false
  },
  {
    connectorId: 'CONN-STR-054',
    name: 'RabbitMQ AMQP Adapter (Cluster #54)',
    category: 'StreamingBrokerConnectors',
    protocolType: 'BATCH_CDC',
    supportedCompression: ['SNAPPY', 'ZSTD', 'GZIP'],
    maxThroughputMbPerSec: 450,
    connectionPoolSize: 38,
    supportsSchemaEvolution: true,
    supportsTransactions: true
  },
  {
    connectorId: 'CONN-STR-055',
    name: 'Apache Pulsar Mesh Client (Cluster #55)',
    category: 'StreamingBrokerConnectors',
    protocolType: 'BATCH_CDC',
    supportedCompression: ['SNAPPY', 'ZSTD', 'GZIP'],
    maxThroughputMbPerSec: 475,
    connectionPoolSize: 39,
    supportsSchemaEvolution: true,
    supportsTransactions: false
  },
  {
    connectorId: 'CONN-STR-056',
    name: 'Apache Kafka Consumer Adapter (Cluster #56)',
    category: 'StreamingBrokerConnectors',
    protocolType: 'STREAMING',
    supportedCompression: ['SNAPPY', 'ZSTD', 'GZIP'],
    maxThroughputMbPerSec: 500,
    connectionPoolSize: 40,
    supportsSchemaEvolution: true,
    supportsTransactions: true
  },
  {
    connectorId: 'CONN-STR-057',
    name: 'AWS Kinesis Firehose Stream (Cluster #57)',
    category: 'StreamingBrokerConnectors',
    protocolType: 'STREAMING',
    supportedCompression: ['SNAPPY', 'ZSTD', 'GZIP'],
    maxThroughputMbPerSec: 525,
    connectionPoolSize: 41,
    supportsSchemaEvolution: true,
    supportsTransactions: false
  },
  {
    connectorId: 'CONN-STR-058',
    name: 'RabbitMQ AMQP Adapter (Cluster #58)',
    category: 'StreamingBrokerConnectors',
    protocolType: 'BATCH_CDC',
    supportedCompression: ['SNAPPY', 'ZSTD', 'GZIP'],
    maxThroughputMbPerSec: 550,
    connectionPoolSize: 42,
    supportsSchemaEvolution: true,
    supportsTransactions: true
  },
  {
    connectorId: 'CONN-STR-059',
    name: 'Apache Pulsar Mesh Client (Cluster #59)',
    category: 'StreamingBrokerConnectors',
    protocolType: 'BATCH_CDC',
    supportedCompression: ['SNAPPY', 'ZSTD', 'GZIP'],
    maxThroughputMbPerSec: 575,
    connectionPoolSize: 43,
    supportsSchemaEvolution: true,
    supportsTransactions: false
  },
  {
    connectorId: 'CONN-STR-060',
    name: 'Apache Kafka Consumer Adapter (Cluster #60)',
    category: 'StreamingBrokerConnectors',
    protocolType: 'STREAMING',
    supportedCompression: ['SNAPPY', 'ZSTD', 'GZIP'],
    maxThroughputMbPerSec: 600,
    connectionPoolSize: 44,
    supportsSchemaEvolution: true,
    supportsTransactions: true
  },
  {
    connectorId: 'CONN-STR-061',
    name: 'AWS Kinesis Firehose Stream (Cluster #61)',
    category: 'StreamingBrokerConnectors',
    protocolType: 'STREAMING',
    supportedCompression: ['SNAPPY', 'ZSTD', 'GZIP'],
    maxThroughputMbPerSec: 625,
    connectionPoolSize: 45,
    supportsSchemaEvolution: true,
    supportsTransactions: false
  },
  {
    connectorId: 'CONN-STR-062',
    name: 'RabbitMQ AMQP Adapter (Cluster #62)',
    category: 'StreamingBrokerConnectors',
    protocolType: 'BATCH_CDC',
    supportedCompression: ['SNAPPY', 'ZSTD', 'GZIP'],
    maxThroughputMbPerSec: 650,
    connectionPoolSize: 46,
    supportsSchemaEvolution: true,
    supportsTransactions: true
  },
  {
    connectorId: 'CONN-STR-063',
    name: 'Apache Pulsar Mesh Client (Cluster #63)',
    category: 'StreamingBrokerConnectors',
    protocolType: 'BATCH_CDC',
    supportedCompression: ['SNAPPY', 'ZSTD', 'GZIP'],
    maxThroughputMbPerSec: 675,
    connectionPoolSize: 47,
    supportsSchemaEvolution: true,
    supportsTransactions: false
  },
  {
    connectorId: 'CONN-STR-064',
    name: 'Apache Kafka Consumer Adapter (Cluster #64)',
    category: 'StreamingBrokerConnectors',
    protocolType: 'STREAMING',
    supportedCompression: ['SNAPPY', 'ZSTD', 'GZIP'],
    maxThroughputMbPerSec: 700,
    connectionPoolSize: 16,
    supportsSchemaEvolution: true,
    supportsTransactions: true
  },
  {
    connectorId: 'CONN-STR-065',
    name: 'AWS Kinesis Firehose Stream (Cluster #65)',
    category: 'StreamingBrokerConnectors',
    protocolType: 'STREAMING',
    supportedCompression: ['SNAPPY', 'ZSTD', 'GZIP'],
    maxThroughputMbPerSec: 725,
    connectionPoolSize: 17,
    supportsSchemaEvolution: true,
    supportsTransactions: false
  },
  {
    connectorId: 'CONN-STR-066',
    name: 'RabbitMQ AMQP Adapter (Cluster #66)',
    category: 'StreamingBrokerConnectors',
    protocolType: 'BATCH_CDC',
    supportedCompression: ['SNAPPY', 'ZSTD', 'GZIP'],
    maxThroughputMbPerSec: 750,
    connectionPoolSize: 18,
    supportsSchemaEvolution: true,
    supportsTransactions: true
  },
  {
    connectorId: 'CONN-STR-067',
    name: 'Apache Pulsar Mesh Client (Cluster #67)',
    category: 'StreamingBrokerConnectors',
    protocolType: 'BATCH_CDC',
    supportedCompression: ['SNAPPY', 'ZSTD', 'GZIP'],
    maxThroughputMbPerSec: 775,
    connectionPoolSize: 19,
    supportsSchemaEvolution: true,
    supportsTransactions: false
  },
  {
    connectorId: 'CONN-STR-068',
    name: 'Apache Kafka Consumer Adapter (Cluster #68)',
    category: 'StreamingBrokerConnectors',
    protocolType: 'STREAMING',
    supportedCompression: ['SNAPPY', 'ZSTD', 'GZIP'],
    maxThroughputMbPerSec: 800,
    connectionPoolSize: 20,
    supportsSchemaEvolution: true,
    supportsTransactions: true
  },
  {
    connectorId: 'CONN-STR-069',
    name: 'AWS Kinesis Firehose Stream (Cluster #69)',
    category: 'StreamingBrokerConnectors',
    protocolType: 'STREAMING',
    supportedCompression: ['SNAPPY', 'ZSTD', 'GZIP'],
    maxThroughputMbPerSec: 825,
    connectionPoolSize: 21,
    supportsSchemaEvolution: true,
    supportsTransactions: false
  },
  {
    connectorId: 'CONN-STR-070',
    name: 'RabbitMQ AMQP Adapter (Cluster #70)',
    category: 'StreamingBrokerConnectors',
    protocolType: 'BATCH_CDC',
    supportedCompression: ['SNAPPY', 'ZSTD', 'GZIP'],
    maxThroughputMbPerSec: 850,
    connectionPoolSize: 22,
    supportsSchemaEvolution: true,
    supportsTransactions: true
  },
  {
    connectorId: 'CONN-STR-071',
    name: 'Apache Pulsar Mesh Client (Cluster #71)',
    category: 'StreamingBrokerConnectors',
    protocolType: 'BATCH_CDC',
    supportedCompression: ['SNAPPY', 'ZSTD', 'GZIP'],
    maxThroughputMbPerSec: 875,
    connectionPoolSize: 23,
    supportsSchemaEvolution: true,
    supportsTransactions: false
  },
  {
    connectorId: 'CONN-STR-072',
    name: 'Apache Kafka Consumer Adapter (Cluster #72)',
    category: 'StreamingBrokerConnectors',
    protocolType: 'STREAMING',
    supportedCompression: ['SNAPPY', 'ZSTD', 'GZIP'],
    maxThroughputMbPerSec: 900,
    connectionPoolSize: 24,
    supportsSchemaEvolution: true,
    supportsTransactions: true
  },
  {
    connectorId: 'CONN-STR-073',
    name: 'AWS Kinesis Firehose Stream (Cluster #73)',
    category: 'StreamingBrokerConnectors',
    protocolType: 'STREAMING',
    supportedCompression: ['SNAPPY', 'ZSTD', 'GZIP'],
    maxThroughputMbPerSec: 925,
    connectionPoolSize: 25,
    supportsSchemaEvolution: true,
    supportsTransactions: false
  },
  {
    connectorId: 'CONN-STR-074',
    name: 'RabbitMQ AMQP Adapter (Cluster #74)',
    category: 'StreamingBrokerConnectors',
    protocolType: 'BATCH_CDC',
    supportedCompression: ['SNAPPY', 'ZSTD', 'GZIP'],
    maxThroughputMbPerSec: 950,
    connectionPoolSize: 26,
    supportsSchemaEvolution: true,
    supportsTransactions: true
  },
  {
    connectorId: 'CONN-STR-075',
    name: 'Apache Pulsar Mesh Client (Cluster #75)',
    category: 'StreamingBrokerConnectors',
    protocolType: 'BATCH_CDC',
    supportedCompression: ['SNAPPY', 'ZSTD', 'GZIP'],
    maxThroughputMbPerSec: 975,
    connectionPoolSize: 27,
    supportsSchemaEvolution: true,
    supportsTransactions: false
  },
  {
    connectorId: 'CONN-STR-076',
    name: 'Apache Kafka Consumer Adapter (Cluster #76)',
    category: 'StreamingBrokerConnectors',
    protocolType: 'STREAMING',
    supportedCompression: ['SNAPPY', 'ZSTD', 'GZIP'],
    maxThroughputMbPerSec: 1000,
    connectionPoolSize: 28,
    supportsSchemaEvolution: true,
    supportsTransactions: true
  },
  {
    connectorId: 'CONN-STR-077',
    name: 'AWS Kinesis Firehose Stream (Cluster #77)',
    category: 'StreamingBrokerConnectors',
    protocolType: 'STREAMING',
    supportedCompression: ['SNAPPY', 'ZSTD', 'GZIP'],
    maxThroughputMbPerSec: 1025,
    connectionPoolSize: 29,
    supportsSchemaEvolution: true,
    supportsTransactions: false
  },
  {
    connectorId: 'CONN-STR-078',
    name: 'RabbitMQ AMQP Adapter (Cluster #78)',
    category: 'StreamingBrokerConnectors',
    protocolType: 'BATCH_CDC',
    supportedCompression: ['SNAPPY', 'ZSTD', 'GZIP'],
    maxThroughputMbPerSec: 1050,
    connectionPoolSize: 30,
    supportsSchemaEvolution: true,
    supportsTransactions: true
  },
  {
    connectorId: 'CONN-STR-079',
    name: 'Apache Pulsar Mesh Client (Cluster #79)',
    category: 'StreamingBrokerConnectors',
    protocolType: 'BATCH_CDC',
    supportedCompression: ['SNAPPY', 'ZSTD', 'GZIP'],
    maxThroughputMbPerSec: 1075,
    connectionPoolSize: 31,
    supportsSchemaEvolution: true,
    supportsTransactions: false
  },
  {
    connectorId: 'CONN-STR-080',
    name: 'Apache Kafka Consumer Adapter (Cluster #80)',
    category: 'StreamingBrokerConnectors',
    protocolType: 'STREAMING',
    supportedCompression: ['SNAPPY', 'ZSTD', 'GZIP'],
    maxThroughputMbPerSec: 100,
    connectionPoolSize: 32,
    supportsSchemaEvolution: true,
    supportsTransactions: true
  },
  {
    connectorId: 'CONN-STR-081',
    name: 'AWS Kinesis Firehose Stream (Cluster #81)',
    category: 'StreamingBrokerConnectors',
    protocolType: 'STREAMING',
    supportedCompression: ['SNAPPY', 'ZSTD', 'GZIP'],
    maxThroughputMbPerSec: 125,
    connectionPoolSize: 33,
    supportsSchemaEvolution: true,
    supportsTransactions: false
  },
  {
    connectorId: 'CONN-STR-082',
    name: 'RabbitMQ AMQP Adapter (Cluster #82)',
    category: 'StreamingBrokerConnectors',
    protocolType: 'BATCH_CDC',
    supportedCompression: ['SNAPPY', 'ZSTD', 'GZIP'],
    maxThroughputMbPerSec: 150,
    connectionPoolSize: 34,
    supportsSchemaEvolution: true,
    supportsTransactions: true
  },
  {
    connectorId: 'CONN-STR-083',
    name: 'Apache Pulsar Mesh Client (Cluster #83)',
    category: 'StreamingBrokerConnectors',
    protocolType: 'BATCH_CDC',
    supportedCompression: ['SNAPPY', 'ZSTD', 'GZIP'],
    maxThroughputMbPerSec: 175,
    connectionPoolSize: 35,
    supportsSchemaEvolution: true,
    supportsTransactions: false
  },
  {
    connectorId: 'CONN-STR-084',
    name: 'Apache Kafka Consumer Adapter (Cluster #84)',
    category: 'StreamingBrokerConnectors',
    protocolType: 'STREAMING',
    supportedCompression: ['SNAPPY', 'ZSTD', 'GZIP'],
    maxThroughputMbPerSec: 200,
    connectionPoolSize: 36,
    supportsSchemaEvolution: true,
    supportsTransactions: true
  },
  {
    connectorId: 'CONN-STR-085',
    name: 'AWS Kinesis Firehose Stream (Cluster #85)',
    category: 'StreamingBrokerConnectors',
    protocolType: 'STREAMING',
    supportedCompression: ['SNAPPY', 'ZSTD', 'GZIP'],
    maxThroughputMbPerSec: 225,
    connectionPoolSize: 37,
    supportsSchemaEvolution: true,
    supportsTransactions: false
  },
  {
    connectorId: 'CONN-STR-086',
    name: 'RabbitMQ AMQP Adapter (Cluster #86)',
    category: 'StreamingBrokerConnectors',
    protocolType: 'BATCH_CDC',
    supportedCompression: ['SNAPPY', 'ZSTD', 'GZIP'],
    maxThroughputMbPerSec: 250,
    connectionPoolSize: 38,
    supportsSchemaEvolution: true,
    supportsTransactions: true
  },
  {
    connectorId: 'CONN-STR-087',
    name: 'Apache Pulsar Mesh Client (Cluster #87)',
    category: 'StreamingBrokerConnectors',
    protocolType: 'BATCH_CDC',
    supportedCompression: ['SNAPPY', 'ZSTD', 'GZIP'],
    maxThroughputMbPerSec: 275,
    connectionPoolSize: 39,
    supportsSchemaEvolution: true,
    supportsTransactions: false
  },
  {
    connectorId: 'CONN-STR-088',
    name: 'Apache Kafka Consumer Adapter (Cluster #88)',
    category: 'StreamingBrokerConnectors',
    protocolType: 'STREAMING',
    supportedCompression: ['SNAPPY', 'ZSTD', 'GZIP'],
    maxThroughputMbPerSec: 300,
    connectionPoolSize: 40,
    supportsSchemaEvolution: true,
    supportsTransactions: true
  },
  {
    connectorId: 'CONN-STR-089',
    name: 'AWS Kinesis Firehose Stream (Cluster #89)',
    category: 'StreamingBrokerConnectors',
    protocolType: 'STREAMING',
    supportedCompression: ['SNAPPY', 'ZSTD', 'GZIP'],
    maxThroughputMbPerSec: 325,
    connectionPoolSize: 41,
    supportsSchemaEvolution: true,
    supportsTransactions: false
  },
  {
    connectorId: 'CONN-STR-090',
    name: 'RabbitMQ AMQP Adapter (Cluster #90)',
    category: 'StreamingBrokerConnectors',
    protocolType: 'BATCH_CDC',
    supportedCompression: ['SNAPPY', 'ZSTD', 'GZIP'],
    maxThroughputMbPerSec: 350,
    connectionPoolSize: 42,
    supportsSchemaEvolution: true,
    supportsTransactions: true
  },
  {
    connectorId: 'CONN-STR-091',
    name: 'Apache Pulsar Mesh Client (Cluster #91)',
    category: 'StreamingBrokerConnectors',
    protocolType: 'BATCH_CDC',
    supportedCompression: ['SNAPPY', 'ZSTD', 'GZIP'],
    maxThroughputMbPerSec: 375,
    connectionPoolSize: 43,
    supportsSchemaEvolution: true,
    supportsTransactions: false
  },
  {
    connectorId: 'CONN-STR-092',
    name: 'Apache Kafka Consumer Adapter (Cluster #92)',
    category: 'StreamingBrokerConnectors',
    protocolType: 'STREAMING',
    supportedCompression: ['SNAPPY', 'ZSTD', 'GZIP'],
    maxThroughputMbPerSec: 400,
    connectionPoolSize: 44,
    supportsSchemaEvolution: true,
    supportsTransactions: true
  },
  {
    connectorId: 'CONN-STR-093',
    name: 'AWS Kinesis Firehose Stream (Cluster #93)',
    category: 'StreamingBrokerConnectors',
    protocolType: 'STREAMING',
    supportedCompression: ['SNAPPY', 'ZSTD', 'GZIP'],
    maxThroughputMbPerSec: 425,
    connectionPoolSize: 45,
    supportsSchemaEvolution: true,
    supportsTransactions: false
  },
  {
    connectorId: 'CONN-STR-094',
    name: 'RabbitMQ AMQP Adapter (Cluster #94)',
    category: 'StreamingBrokerConnectors',
    protocolType: 'BATCH_CDC',
    supportedCompression: ['SNAPPY', 'ZSTD', 'GZIP'],
    maxThroughputMbPerSec: 450,
    connectionPoolSize: 46,
    supportsSchemaEvolution: true,
    supportsTransactions: true
  },
  {
    connectorId: 'CONN-STR-095',
    name: 'Apache Pulsar Mesh Client (Cluster #95)',
    category: 'StreamingBrokerConnectors',
    protocolType: 'BATCH_CDC',
    supportedCompression: ['SNAPPY', 'ZSTD', 'GZIP'],
    maxThroughputMbPerSec: 475,
    connectionPoolSize: 47,
    supportsSchemaEvolution: true,
    supportsTransactions: false
  },
  {
    connectorId: 'CONN-STR-096',
    name: 'Apache Kafka Consumer Adapter (Cluster #96)',
    category: 'StreamingBrokerConnectors',
    protocolType: 'STREAMING',
    supportedCompression: ['SNAPPY', 'ZSTD', 'GZIP'],
    maxThroughputMbPerSec: 500,
    connectionPoolSize: 16,
    supportsSchemaEvolution: true,
    supportsTransactions: true
  },
  {
    connectorId: 'CONN-STR-097',
    name: 'AWS Kinesis Firehose Stream (Cluster #97)',
    category: 'StreamingBrokerConnectors',
    protocolType: 'STREAMING',
    supportedCompression: ['SNAPPY', 'ZSTD', 'GZIP'],
    maxThroughputMbPerSec: 525,
    connectionPoolSize: 17,
    supportsSchemaEvolution: true,
    supportsTransactions: false
  },
  {
    connectorId: 'CONN-STR-098',
    name: 'RabbitMQ AMQP Adapter (Cluster #98)',
    category: 'StreamingBrokerConnectors',
    protocolType: 'BATCH_CDC',
    supportedCompression: ['SNAPPY', 'ZSTD', 'GZIP'],
    maxThroughputMbPerSec: 550,
    connectionPoolSize: 18,
    supportsSchemaEvolution: true,
    supportsTransactions: true
  },
  {
    connectorId: 'CONN-STR-099',
    name: 'Apache Pulsar Mesh Client (Cluster #99)',
    category: 'StreamingBrokerConnectors',
    protocolType: 'BATCH_CDC',
    supportedCompression: ['SNAPPY', 'ZSTD', 'GZIP'],
    maxThroughputMbPerSec: 575,
    connectionPoolSize: 19,
    supportsSchemaEvolution: true,
    supportsTransactions: false
  },
  {
    connectorId: 'CONN-STR-100',
    name: 'Apache Kafka Consumer Adapter (Cluster #100)',
    category: 'StreamingBrokerConnectors',
    protocolType: 'STREAMING',
    supportedCompression: ['SNAPPY', 'ZSTD', 'GZIP'],
    maxThroughputMbPerSec: 600,
    connectionPoolSize: 20,
    supportsSchemaEvolution: true,
    supportsTransactions: true
  },
  {
    connectorId: 'CONN-STR-101',
    name: 'AWS Kinesis Firehose Stream (Cluster #101)',
    category: 'StreamingBrokerConnectors',
    protocolType: 'STREAMING',
    supportedCompression: ['SNAPPY', 'ZSTD', 'GZIP'],
    maxThroughputMbPerSec: 625,
    connectionPoolSize: 21,
    supportsSchemaEvolution: true,
    supportsTransactions: false
  },
  {
    connectorId: 'CONN-STR-102',
    name: 'RabbitMQ AMQP Adapter (Cluster #102)',
    category: 'StreamingBrokerConnectors',
    protocolType: 'BATCH_CDC',
    supportedCompression: ['SNAPPY', 'ZSTD', 'GZIP'],
    maxThroughputMbPerSec: 650,
    connectionPoolSize: 22,
    supportsSchemaEvolution: true,
    supportsTransactions: true
  },
  {
    connectorId: 'CONN-STR-103',
    name: 'Apache Pulsar Mesh Client (Cluster #103)',
    category: 'StreamingBrokerConnectors',
    protocolType: 'BATCH_CDC',
    supportedCompression: ['SNAPPY', 'ZSTD', 'GZIP'],
    maxThroughputMbPerSec: 675,
    connectionPoolSize: 23,
    supportsSchemaEvolution: true,
    supportsTransactions: false
  },
  {
    connectorId: 'CONN-STR-104',
    name: 'Apache Kafka Consumer Adapter (Cluster #104)',
    category: 'StreamingBrokerConnectors',
    protocolType: 'STREAMING',
    supportedCompression: ['SNAPPY', 'ZSTD', 'GZIP'],
    maxThroughputMbPerSec: 700,
    connectionPoolSize: 24,
    supportsSchemaEvolution: true,
    supportsTransactions: true
  },
  {
    connectorId: 'CONN-STR-105',
    name: 'AWS Kinesis Firehose Stream (Cluster #105)',
    category: 'StreamingBrokerConnectors',
    protocolType: 'STREAMING',
    supportedCompression: ['SNAPPY', 'ZSTD', 'GZIP'],
    maxThroughputMbPerSec: 725,
    connectionPoolSize: 25,
    supportsSchemaEvolution: true,
    supportsTransactions: false
  },
  {
    connectorId: 'CONN-STR-106',
    name: 'RabbitMQ AMQP Adapter (Cluster #106)',
    category: 'StreamingBrokerConnectors',
    protocolType: 'BATCH_CDC',
    supportedCompression: ['SNAPPY', 'ZSTD', 'GZIP'],
    maxThroughputMbPerSec: 750,
    connectionPoolSize: 26,
    supportsSchemaEvolution: true,
    supportsTransactions: true
  },
  {
    connectorId: 'CONN-STR-107',
    name: 'Apache Pulsar Mesh Client (Cluster #107)',
    category: 'StreamingBrokerConnectors',
    protocolType: 'BATCH_CDC',
    supportedCompression: ['SNAPPY', 'ZSTD', 'GZIP'],
    maxThroughputMbPerSec: 775,
    connectionPoolSize: 27,
    supportsSchemaEvolution: true,
    supportsTransactions: false
  },
  {
    connectorId: 'CONN-STR-108',
    name: 'Apache Kafka Consumer Adapter (Cluster #108)',
    category: 'StreamingBrokerConnectors',
    protocolType: 'STREAMING',
    supportedCompression: ['SNAPPY', 'ZSTD', 'GZIP'],
    maxThroughputMbPerSec: 800,
    connectionPoolSize: 28,
    supportsSchemaEvolution: true,
    supportsTransactions: true
  },
  {
    connectorId: 'CONN-STR-109',
    name: 'AWS Kinesis Firehose Stream (Cluster #109)',
    category: 'StreamingBrokerConnectors',
    protocolType: 'STREAMING',
    supportedCompression: ['SNAPPY', 'ZSTD', 'GZIP'],
    maxThroughputMbPerSec: 825,
    connectionPoolSize: 29,
    supportsSchemaEvolution: true,
    supportsTransactions: false
  },
  {
    connectorId: 'CONN-STR-110',
    name: 'RabbitMQ AMQP Adapter (Cluster #110)',
    category: 'StreamingBrokerConnectors',
    protocolType: 'BATCH_CDC',
    supportedCompression: ['SNAPPY', 'ZSTD', 'GZIP'],
    maxThroughputMbPerSec: 850,
    connectionPoolSize: 30,
    supportsSchemaEvolution: true,
    supportsTransactions: true
  },
  {
    connectorId: 'CONN-STR-111',
    name: 'Apache Pulsar Mesh Client (Cluster #111)',
    category: 'StreamingBrokerConnectors',
    protocolType: 'BATCH_CDC',
    supportedCompression: ['SNAPPY', 'ZSTD', 'GZIP'],
    maxThroughputMbPerSec: 875,
    connectionPoolSize: 31,
    supportsSchemaEvolution: true,
    supportsTransactions: false
  },
  {
    connectorId: 'CONN-STR-112',
    name: 'Apache Kafka Consumer Adapter (Cluster #112)',
    category: 'StreamingBrokerConnectors',
    protocolType: 'STREAMING',
    supportedCompression: ['SNAPPY', 'ZSTD', 'GZIP'],
    maxThroughputMbPerSec: 900,
    connectionPoolSize: 32,
    supportsSchemaEvolution: true,
    supportsTransactions: true
  },
  {
    connectorId: 'CONN-STR-113',
    name: 'AWS Kinesis Firehose Stream (Cluster #113)',
    category: 'StreamingBrokerConnectors',
    protocolType: 'STREAMING',
    supportedCompression: ['SNAPPY', 'ZSTD', 'GZIP'],
    maxThroughputMbPerSec: 925,
    connectionPoolSize: 33,
    supportsSchemaEvolution: true,
    supportsTransactions: false
  },
  {
    connectorId: 'CONN-STR-114',
    name: 'RabbitMQ AMQP Adapter (Cluster #114)',
    category: 'StreamingBrokerConnectors',
    protocolType: 'BATCH_CDC',
    supportedCompression: ['SNAPPY', 'ZSTD', 'GZIP'],
    maxThroughputMbPerSec: 950,
    connectionPoolSize: 34,
    supportsSchemaEvolution: true,
    supportsTransactions: true
  },
  {
    connectorId: 'CONN-STR-115',
    name: 'Apache Pulsar Mesh Client (Cluster #115)',
    category: 'StreamingBrokerConnectors',
    protocolType: 'BATCH_CDC',
    supportedCompression: ['SNAPPY', 'ZSTD', 'GZIP'],
    maxThroughputMbPerSec: 975,
    connectionPoolSize: 35,
    supportsSchemaEvolution: true,
    supportsTransactions: false
  },
  {
    connectorId: 'CONN-STR-116',
    name: 'Apache Kafka Consumer Adapter (Cluster #116)',
    category: 'StreamingBrokerConnectors',
    protocolType: 'STREAMING',
    supportedCompression: ['SNAPPY', 'ZSTD', 'GZIP'],
    maxThroughputMbPerSec: 1000,
    connectionPoolSize: 36,
    supportsSchemaEvolution: true,
    supportsTransactions: true
  },
  {
    connectorId: 'CONN-STR-117',
    name: 'AWS Kinesis Firehose Stream (Cluster #117)',
    category: 'StreamingBrokerConnectors',
    protocolType: 'STREAMING',
    supportedCompression: ['SNAPPY', 'ZSTD', 'GZIP'],
    maxThroughputMbPerSec: 1025,
    connectionPoolSize: 37,
    supportsSchemaEvolution: true,
    supportsTransactions: false
  },
  {
    connectorId: 'CONN-STR-118',
    name: 'RabbitMQ AMQP Adapter (Cluster #118)',
    category: 'StreamingBrokerConnectors',
    protocolType: 'BATCH_CDC',
    supportedCompression: ['SNAPPY', 'ZSTD', 'GZIP'],
    maxThroughputMbPerSec: 1050,
    connectionPoolSize: 38,
    supportsSchemaEvolution: true,
    supportsTransactions: true
  },
  {
    connectorId: 'CONN-STR-119',
    name: 'Apache Pulsar Mesh Client (Cluster #119)',
    category: 'StreamingBrokerConnectors',
    protocolType: 'BATCH_CDC',
    supportedCompression: ['SNAPPY', 'ZSTD', 'GZIP'],
    maxThroughputMbPerSec: 1075,
    connectionPoolSize: 39,
    supportsSchemaEvolution: true,
    supportsTransactions: false
  },
  {
    connectorId: 'CONN-STR-120',
    name: 'Apache Kafka Consumer Adapter (Cluster #120)',
    category: 'StreamingBrokerConnectors',
    protocolType: 'STREAMING',
    supportedCompression: ['SNAPPY', 'ZSTD', 'GZIP'],
    maxThroughputMbPerSec: 100,
    connectionPoolSize: 40,
    supportsSchemaEvolution: true,
    supportsTransactions: true
  }
];
