/**
 * Enterprise Data Pipeline DAG Specification: CybersecuritySIEMLogParser
 * Domain Focus: Distributed firewall and auth log parsing, Sigma rule evaluation, and incident response event routing
 * Standard: DataFlow OS Orchestration Engine
 */

export interface EnterprisePipelineDAG {
  dagId: string;
  pipelineName: string;
  domain: string;
  category: string;
  cronSchedule: string;
  sourceProtocol: string;
  sinkProtocol: string;
  batchSizeRecords: number;
  maxParallelTasks: number;
  slaThresholdMinutes: number;
  retryPolicy: { maxRetries: number; backoffExponentialFactor: number; initialDelaySeconds: number };
  validationAssertionsCount: number;
  lineageTrackedColumns: string[];
}

export const PIPELINE_SEC_DATASET: EnterprisePipelineDAG[] = [
  {
    dagId: 'DAG-SEC-001',
    pipelineName: 'CybersecuritySIEMLogParser Production Workflow #1',
    domain: 'CybersecuritySIEMLogParser',
    category: 'Sigma rule evaluation',
    cronSchedule: '1 1 * * *',
    sourceProtocol: 'ICEBERG',
    sinkProtocol: 'BIGQUERY',
    batchSizeRecords: 60000,
    maxParallelTasks: 5,
    slaThresholdMinutes: 16,
    retryPolicy: { maxRetries: 3, backoffExponentialFactor: 2.0, initialDelaySeconds: 30 },
    validationAssertionsCount: 9,
    lineageTrackedColumns: ['record_id', 'source_timestamp', 'payload_hash', 'cleared_amount', 'tenant_id']
  },
  {
    dagId: 'DAG-SEC-002',
    pipelineName: 'CybersecuritySIEMLogParser Production Workflow #2',
    domain: 'CybersecuritySIEMLogParser',
    category: 'and incident response event routing',
    cronSchedule: '2 2 * * *',
    sourceProtocol: 'SNOWFLAKE',
    sinkProtocol: 'SNOWFLAKE',
    batchSizeRecords: 70000,
    maxParallelTasks: 6,
    slaThresholdMinutes: 17,
    retryPolicy: { maxRetries: 3, backoffExponentialFactor: 2.0, initialDelaySeconds: 30 },
    validationAssertionsCount: 10,
    lineageTrackedColumns: ['record_id', 'source_timestamp', 'payload_hash', 'cleared_amount', 'tenant_id']
  },
  {
    dagId: 'DAG-SEC-003',
    pipelineName: 'CybersecuritySIEMLogParser Production Workflow #3',
    domain: 'CybersecuritySIEMLogParser',
    category: 'Distributed firewall and auth log parsing',
    cronSchedule: '3 3 * * *',
    sourceProtocol: 'KAFKA',
    sinkProtocol: 'BIGQUERY',
    batchSizeRecords: 80000,
    maxParallelTasks: 7,
    slaThresholdMinutes: 18,
    retryPolicy: { maxRetries: 3, backoffExponentialFactor: 2.0, initialDelaySeconds: 30 },
    validationAssertionsCount: 11,
    lineageTrackedColumns: ['record_id', 'source_timestamp', 'payload_hash', 'cleared_amount', 'tenant_id']
  },
  {
    dagId: 'DAG-SEC-004',
    pipelineName: 'CybersecuritySIEMLogParser Production Workflow #4',
    domain: 'CybersecuritySIEMLogParser',
    category: 'Sigma rule evaluation',
    cronSchedule: '4 4 * * *',
    sourceProtocol: 'POSTGRES',
    sinkProtocol: 'SNOWFLAKE',
    batchSizeRecords: 90000,
    maxParallelTasks: 8,
    slaThresholdMinutes: 19,
    retryPolicy: { maxRetries: 3, backoffExponentialFactor: 2.0, initialDelaySeconds: 30 },
    validationAssertionsCount: 12,
    lineageTrackedColumns: ['record_id', 'source_timestamp', 'payload_hash', 'cleared_amount', 'tenant_id']
  },
  {
    dagId: 'DAG-SEC-005',
    pipelineName: 'CybersecuritySIEMLogParser Production Workflow #5',
    domain: 'CybersecuritySIEMLogParser',
    category: 'and incident response event routing',
    cronSchedule: '5 5 * * *',
    sourceProtocol: 'ICEBERG',
    sinkProtocol: 'BIGQUERY',
    batchSizeRecords: 100000,
    maxParallelTasks: 9,
    slaThresholdMinutes: 20,
    retryPolicy: { maxRetries: 3, backoffExponentialFactor: 2.0, initialDelaySeconds: 30 },
    validationAssertionsCount: 13,
    lineageTrackedColumns: ['record_id', 'source_timestamp', 'payload_hash', 'cleared_amount', 'tenant_id']
  },
  {
    dagId: 'DAG-SEC-006',
    pipelineName: 'CybersecuritySIEMLogParser Production Workflow #6',
    domain: 'CybersecuritySIEMLogParser',
    category: 'Distributed firewall and auth log parsing',
    cronSchedule: '6 6 * * *',
    sourceProtocol: 'KAFKA',
    sinkProtocol: 'SNOWFLAKE',
    batchSizeRecords: 110000,
    maxParallelTasks: 10,
    slaThresholdMinutes: 21,
    retryPolicy: { maxRetries: 3, backoffExponentialFactor: 2.0, initialDelaySeconds: 30 },
    validationAssertionsCount: 14,
    lineageTrackedColumns: ['record_id', 'source_timestamp', 'payload_hash', 'cleared_amount', 'tenant_id']
  },
  {
    dagId: 'DAG-SEC-007',
    pipelineName: 'CybersecuritySIEMLogParser Production Workflow #7',
    domain: 'CybersecuritySIEMLogParser',
    category: 'Sigma rule evaluation',
    cronSchedule: '7 7 * * *',
    sourceProtocol: 'ICEBERG',
    sinkProtocol: 'BIGQUERY',
    batchSizeRecords: 120000,
    maxParallelTasks: 11,
    slaThresholdMinutes: 22,
    retryPolicy: { maxRetries: 3, backoffExponentialFactor: 2.0, initialDelaySeconds: 30 },
    validationAssertionsCount: 15,
    lineageTrackedColumns: ['record_id', 'source_timestamp', 'payload_hash', 'cleared_amount', 'tenant_id']
  },
  {
    dagId: 'DAG-SEC-008',
    pipelineName: 'CybersecuritySIEMLogParser Production Workflow #8',
    domain: 'CybersecuritySIEMLogParser',
    category: 'and incident response event routing',
    cronSchedule: '8 8 * * *',
    sourceProtocol: 'POSTGRES',
    sinkProtocol: 'SNOWFLAKE',
    batchSizeRecords: 130000,
    maxParallelTasks: 12,
    slaThresholdMinutes: 23,
    retryPolicy: { maxRetries: 3, backoffExponentialFactor: 2.0, initialDelaySeconds: 30 },
    validationAssertionsCount: 16,
    lineageTrackedColumns: ['record_id', 'source_timestamp', 'payload_hash', 'cleared_amount', 'tenant_id']
  },
  {
    dagId: 'DAG-SEC-009',
    pipelineName: 'CybersecuritySIEMLogParser Production Workflow #9',
    domain: 'CybersecuritySIEMLogParser',
    category: 'Distributed firewall and auth log parsing',
    cronSchedule: '9 9 * * *',
    sourceProtocol: 'KAFKA',
    sinkProtocol: 'BIGQUERY',
    batchSizeRecords: 140000,
    maxParallelTasks: 13,
    slaThresholdMinutes: 24,
    retryPolicy: { maxRetries: 3, backoffExponentialFactor: 2.0, initialDelaySeconds: 30 },
    validationAssertionsCount: 17,
    lineageTrackedColumns: ['record_id', 'source_timestamp', 'payload_hash', 'cleared_amount', 'tenant_id']
  },
  {
    dagId: 'DAG-SEC-010',
    pipelineName: 'CybersecuritySIEMLogParser Production Workflow #10',
    domain: 'CybersecuritySIEMLogParser',
    category: 'Sigma rule evaluation',
    cronSchedule: '10 10 * * *',
    sourceProtocol: 'SNOWFLAKE',
    sinkProtocol: 'SNOWFLAKE',
    batchSizeRecords: 150000,
    maxParallelTasks: 14,
    slaThresholdMinutes: 25,
    retryPolicy: { maxRetries: 3, backoffExponentialFactor: 2.0, initialDelaySeconds: 30 },
    validationAssertionsCount: 18,
    lineageTrackedColumns: ['record_id', 'source_timestamp', 'payload_hash', 'cleared_amount', 'tenant_id']
  },
  {
    dagId: 'DAG-SEC-011',
    pipelineName: 'CybersecuritySIEMLogParser Production Workflow #11',
    domain: 'CybersecuritySIEMLogParser',
    category: 'and incident response event routing',
    cronSchedule: '11 11 * * *',
    sourceProtocol: 'ICEBERG',
    sinkProtocol: 'BIGQUERY',
    batchSizeRecords: 160000,
    maxParallelTasks: 15,
    slaThresholdMinutes: 26,
    retryPolicy: { maxRetries: 3, backoffExponentialFactor: 2.0, initialDelaySeconds: 30 },
    validationAssertionsCount: 19,
    lineageTrackedColumns: ['record_id', 'source_timestamp', 'payload_hash', 'cleared_amount', 'tenant_id']
  },
  {
    dagId: 'DAG-SEC-012',
    pipelineName: 'CybersecuritySIEMLogParser Production Workflow #12',
    domain: 'CybersecuritySIEMLogParser',
    category: 'Distributed firewall and auth log parsing',
    cronSchedule: '12 12 * * *',
    sourceProtocol: 'POSTGRES',
    sinkProtocol: 'SNOWFLAKE',
    batchSizeRecords: 170000,
    maxParallelTasks: 4,
    slaThresholdMinutes: 27,
    retryPolicy: { maxRetries: 3, backoffExponentialFactor: 2.0, initialDelaySeconds: 30 },
    validationAssertionsCount: 20,
    lineageTrackedColumns: ['record_id', 'source_timestamp', 'payload_hash', 'cleared_amount', 'tenant_id']
  },
  {
    dagId: 'DAG-SEC-013',
    pipelineName: 'CybersecuritySIEMLogParser Production Workflow #13',
    domain: 'CybersecuritySIEMLogParser',
    category: 'Sigma rule evaluation',
    cronSchedule: '13 13 * * *',
    sourceProtocol: 'ICEBERG',
    sinkProtocol: 'BIGQUERY',
    batchSizeRecords: 180000,
    maxParallelTasks: 5,
    slaThresholdMinutes: 28,
    retryPolicy: { maxRetries: 3, backoffExponentialFactor: 2.0, initialDelaySeconds: 30 },
    validationAssertionsCount: 21,
    lineageTrackedColumns: ['record_id', 'source_timestamp', 'payload_hash', 'cleared_amount', 'tenant_id']
  },
  {
    dagId: 'DAG-SEC-014',
    pipelineName: 'CybersecuritySIEMLogParser Production Workflow #14',
    domain: 'CybersecuritySIEMLogParser',
    category: 'and incident response event routing',
    cronSchedule: '14 14 * * *',
    sourceProtocol: 'SNOWFLAKE',
    sinkProtocol: 'SNOWFLAKE',
    batchSizeRecords: 190000,
    maxParallelTasks: 6,
    slaThresholdMinutes: 29,
    retryPolicy: { maxRetries: 3, backoffExponentialFactor: 2.0, initialDelaySeconds: 30 },
    validationAssertionsCount: 22,
    lineageTrackedColumns: ['record_id', 'source_timestamp', 'payload_hash', 'cleared_amount', 'tenant_id']
  },
  {
    dagId: 'DAG-SEC-015',
    pipelineName: 'CybersecuritySIEMLogParser Production Workflow #15',
    domain: 'CybersecuritySIEMLogParser',
    category: 'Distributed firewall and auth log parsing',
    cronSchedule: '15 15 * * *',
    sourceProtocol: 'KAFKA',
    sinkProtocol: 'BIGQUERY',
    batchSizeRecords: 200000,
    maxParallelTasks: 7,
    slaThresholdMinutes: 30,
    retryPolicy: { maxRetries: 3, backoffExponentialFactor: 2.0, initialDelaySeconds: 30 },
    validationAssertionsCount: 23,
    lineageTrackedColumns: ['record_id', 'source_timestamp', 'payload_hash', 'cleared_amount', 'tenant_id']
  },
  {
    dagId: 'DAG-SEC-016',
    pipelineName: 'CybersecuritySIEMLogParser Production Workflow #16',
    domain: 'CybersecuritySIEMLogParser',
    category: 'Sigma rule evaluation',
    cronSchedule: '16 16 * * *',
    sourceProtocol: 'POSTGRES',
    sinkProtocol: 'SNOWFLAKE',
    batchSizeRecords: 210000,
    maxParallelTasks: 8,
    slaThresholdMinutes: 31,
    retryPolicy: { maxRetries: 3, backoffExponentialFactor: 2.0, initialDelaySeconds: 30 },
    validationAssertionsCount: 8,
    lineageTrackedColumns: ['record_id', 'source_timestamp', 'payload_hash', 'cleared_amount', 'tenant_id']
  },
  {
    dagId: 'DAG-SEC-017',
    pipelineName: 'CybersecuritySIEMLogParser Production Workflow #17',
    domain: 'CybersecuritySIEMLogParser',
    category: 'and incident response event routing',
    cronSchedule: '17 17 * * *',
    sourceProtocol: 'ICEBERG',
    sinkProtocol: 'BIGQUERY',
    batchSizeRecords: 220000,
    maxParallelTasks: 9,
    slaThresholdMinutes: 32,
    retryPolicy: { maxRetries: 3, backoffExponentialFactor: 2.0, initialDelaySeconds: 30 },
    validationAssertionsCount: 9,
    lineageTrackedColumns: ['record_id', 'source_timestamp', 'payload_hash', 'cleared_amount', 'tenant_id']
  },
  {
    dagId: 'DAG-SEC-018',
    pipelineName: 'CybersecuritySIEMLogParser Production Workflow #18',
    domain: 'CybersecuritySIEMLogParser',
    category: 'Distributed firewall and auth log parsing',
    cronSchedule: '18 18 * * *',
    sourceProtocol: 'KAFKA',
    sinkProtocol: 'SNOWFLAKE',
    batchSizeRecords: 230000,
    maxParallelTasks: 10,
    slaThresholdMinutes: 33,
    retryPolicy: { maxRetries: 3, backoffExponentialFactor: 2.0, initialDelaySeconds: 30 },
    validationAssertionsCount: 10,
    lineageTrackedColumns: ['record_id', 'source_timestamp', 'payload_hash', 'cleared_amount', 'tenant_id']
  },
  {
    dagId: 'DAG-SEC-019',
    pipelineName: 'CybersecuritySIEMLogParser Production Workflow #19',
    domain: 'CybersecuritySIEMLogParser',
    category: 'Sigma rule evaluation',
    cronSchedule: '19 19 * * *',
    sourceProtocol: 'ICEBERG',
    sinkProtocol: 'BIGQUERY',
    batchSizeRecords: 240000,
    maxParallelTasks: 11,
    slaThresholdMinutes: 34,
    retryPolicy: { maxRetries: 3, backoffExponentialFactor: 2.0, initialDelaySeconds: 30 },
    validationAssertionsCount: 11,
    lineageTrackedColumns: ['record_id', 'source_timestamp', 'payload_hash', 'cleared_amount', 'tenant_id']
  },
  {
    dagId: 'DAG-SEC-020',
    pipelineName: 'CybersecuritySIEMLogParser Production Workflow #20',
    domain: 'CybersecuritySIEMLogParser',
    category: 'and incident response event routing',
    cronSchedule: '20 20 * * *',
    sourceProtocol: 'POSTGRES',
    sinkProtocol: 'SNOWFLAKE',
    batchSizeRecords: 50000,
    maxParallelTasks: 12,
    slaThresholdMinutes: 35,
    retryPolicy: { maxRetries: 3, backoffExponentialFactor: 2.0, initialDelaySeconds: 30 },
    validationAssertionsCount: 12,
    lineageTrackedColumns: ['record_id', 'source_timestamp', 'payload_hash', 'cleared_amount', 'tenant_id']
  },
  {
    dagId: 'DAG-SEC-021',
    pipelineName: 'CybersecuritySIEMLogParser Production Workflow #21',
    domain: 'CybersecuritySIEMLogParser',
    category: 'Distributed firewall and auth log parsing',
    cronSchedule: '21 21 * * *',
    sourceProtocol: 'KAFKA',
    sinkProtocol: 'BIGQUERY',
    batchSizeRecords: 60000,
    maxParallelTasks: 13,
    slaThresholdMinutes: 36,
    retryPolicy: { maxRetries: 3, backoffExponentialFactor: 2.0, initialDelaySeconds: 30 },
    validationAssertionsCount: 13,
    lineageTrackedColumns: ['record_id', 'source_timestamp', 'payload_hash', 'cleared_amount', 'tenant_id']
  },
  {
    dagId: 'DAG-SEC-022',
    pipelineName: 'CybersecuritySIEMLogParser Production Workflow #22',
    domain: 'CybersecuritySIEMLogParser',
    category: 'Sigma rule evaluation',
    cronSchedule: '22 22 * * *',
    sourceProtocol: 'SNOWFLAKE',
    sinkProtocol: 'SNOWFLAKE',
    batchSizeRecords: 70000,
    maxParallelTasks: 14,
    slaThresholdMinutes: 37,
    retryPolicy: { maxRetries: 3, backoffExponentialFactor: 2.0, initialDelaySeconds: 30 },
    validationAssertionsCount: 14,
    lineageTrackedColumns: ['record_id', 'source_timestamp', 'payload_hash', 'cleared_amount', 'tenant_id']
  },
  {
    dagId: 'DAG-SEC-023',
    pipelineName: 'CybersecuritySIEMLogParser Production Workflow #23',
    domain: 'CybersecuritySIEMLogParser',
    category: 'and incident response event routing',
    cronSchedule: '23 23 * * *',
    sourceProtocol: 'ICEBERG',
    sinkProtocol: 'BIGQUERY',
    batchSizeRecords: 80000,
    maxParallelTasks: 15,
    slaThresholdMinutes: 38,
    retryPolicy: { maxRetries: 3, backoffExponentialFactor: 2.0, initialDelaySeconds: 30 },
    validationAssertionsCount: 15,
    lineageTrackedColumns: ['record_id', 'source_timestamp', 'payload_hash', 'cleared_amount', 'tenant_id']
  },
  {
    dagId: 'DAG-SEC-024',
    pipelineName: 'CybersecuritySIEMLogParser Production Workflow #24',
    domain: 'CybersecuritySIEMLogParser',
    category: 'Distributed firewall and auth log parsing',
    cronSchedule: '24 0 * * *',
    sourceProtocol: 'POSTGRES',
    sinkProtocol: 'SNOWFLAKE',
    batchSizeRecords: 90000,
    maxParallelTasks: 4,
    slaThresholdMinutes: 39,
    retryPolicy: { maxRetries: 3, backoffExponentialFactor: 2.0, initialDelaySeconds: 30 },
    validationAssertionsCount: 16,
    lineageTrackedColumns: ['record_id', 'source_timestamp', 'payload_hash', 'cleared_amount', 'tenant_id']
  },
  {
    dagId: 'DAG-SEC-025',
    pipelineName: 'CybersecuritySIEMLogParser Production Workflow #25',
    domain: 'CybersecuritySIEMLogParser',
    category: 'Sigma rule evaluation',
    cronSchedule: '25 1 * * *',
    sourceProtocol: 'ICEBERG',
    sinkProtocol: 'BIGQUERY',
    batchSizeRecords: 100000,
    maxParallelTasks: 5,
    slaThresholdMinutes: 40,
    retryPolicy: { maxRetries: 3, backoffExponentialFactor: 2.0, initialDelaySeconds: 30 },
    validationAssertionsCount: 17,
    lineageTrackedColumns: ['record_id', 'source_timestamp', 'payload_hash', 'cleared_amount', 'tenant_id']
  },
  {
    dagId: 'DAG-SEC-026',
    pipelineName: 'CybersecuritySIEMLogParser Production Workflow #26',
    domain: 'CybersecuritySIEMLogParser',
    category: 'and incident response event routing',
    cronSchedule: '26 2 * * *',
    sourceProtocol: 'SNOWFLAKE',
    sinkProtocol: 'SNOWFLAKE',
    batchSizeRecords: 110000,
    maxParallelTasks: 6,
    slaThresholdMinutes: 41,
    retryPolicy: { maxRetries: 3, backoffExponentialFactor: 2.0, initialDelaySeconds: 30 },
    validationAssertionsCount: 18,
    lineageTrackedColumns: ['record_id', 'source_timestamp', 'payload_hash', 'cleared_amount', 'tenant_id']
  },
  {
    dagId: 'DAG-SEC-027',
    pipelineName: 'CybersecuritySIEMLogParser Production Workflow #27',
    domain: 'CybersecuritySIEMLogParser',
    category: 'Distributed firewall and auth log parsing',
    cronSchedule: '27 3 * * *',
    sourceProtocol: 'KAFKA',
    sinkProtocol: 'BIGQUERY',
    batchSizeRecords: 120000,
    maxParallelTasks: 7,
    slaThresholdMinutes: 42,
    retryPolicy: { maxRetries: 3, backoffExponentialFactor: 2.0, initialDelaySeconds: 30 },
    validationAssertionsCount: 19,
    lineageTrackedColumns: ['record_id', 'source_timestamp', 'payload_hash', 'cleared_amount', 'tenant_id']
  },
  {
    dagId: 'DAG-SEC-028',
    pipelineName: 'CybersecuritySIEMLogParser Production Workflow #28',
    domain: 'CybersecuritySIEMLogParser',
    category: 'Sigma rule evaluation',
    cronSchedule: '28 4 * * *',
    sourceProtocol: 'POSTGRES',
    sinkProtocol: 'SNOWFLAKE',
    batchSizeRecords: 130000,
    maxParallelTasks: 8,
    slaThresholdMinutes: 43,
    retryPolicy: { maxRetries: 3, backoffExponentialFactor: 2.0, initialDelaySeconds: 30 },
    validationAssertionsCount: 20,
    lineageTrackedColumns: ['record_id', 'source_timestamp', 'payload_hash', 'cleared_amount', 'tenant_id']
  },
  {
    dagId: 'DAG-SEC-029',
    pipelineName: 'CybersecuritySIEMLogParser Production Workflow #29',
    domain: 'CybersecuritySIEMLogParser',
    category: 'and incident response event routing',
    cronSchedule: '29 5 * * *',
    sourceProtocol: 'ICEBERG',
    sinkProtocol: 'BIGQUERY',
    batchSizeRecords: 140000,
    maxParallelTasks: 9,
    slaThresholdMinutes: 44,
    retryPolicy: { maxRetries: 3, backoffExponentialFactor: 2.0, initialDelaySeconds: 30 },
    validationAssertionsCount: 21,
    lineageTrackedColumns: ['record_id', 'source_timestamp', 'payload_hash', 'cleared_amount', 'tenant_id']
  },
  {
    dagId: 'DAG-SEC-030',
    pipelineName: 'CybersecuritySIEMLogParser Production Workflow #30',
    domain: 'CybersecuritySIEMLogParser',
    category: 'Distributed firewall and auth log parsing',
    cronSchedule: '30 6 * * *',
    sourceProtocol: 'KAFKA',
    sinkProtocol: 'SNOWFLAKE',
    batchSizeRecords: 150000,
    maxParallelTasks: 10,
    slaThresholdMinutes: 45,
    retryPolicy: { maxRetries: 3, backoffExponentialFactor: 2.0, initialDelaySeconds: 30 },
    validationAssertionsCount: 22,
    lineageTrackedColumns: ['record_id', 'source_timestamp', 'payload_hash', 'cleared_amount', 'tenant_id']
  },
  {
    dagId: 'DAG-SEC-031',
    pipelineName: 'CybersecuritySIEMLogParser Production Workflow #31',
    domain: 'CybersecuritySIEMLogParser',
    category: 'Sigma rule evaluation',
    cronSchedule: '31 7 * * *',
    sourceProtocol: 'ICEBERG',
    sinkProtocol: 'BIGQUERY',
    batchSizeRecords: 160000,
    maxParallelTasks: 11,
    slaThresholdMinutes: 46,
    retryPolicy: { maxRetries: 3, backoffExponentialFactor: 2.0, initialDelaySeconds: 30 },
    validationAssertionsCount: 23,
    lineageTrackedColumns: ['record_id', 'source_timestamp', 'payload_hash', 'cleared_amount', 'tenant_id']
  },
  {
    dagId: 'DAG-SEC-032',
    pipelineName: 'CybersecuritySIEMLogParser Production Workflow #32',
    domain: 'CybersecuritySIEMLogParser',
    category: 'and incident response event routing',
    cronSchedule: '32 8 * * *',
    sourceProtocol: 'POSTGRES',
    sinkProtocol: 'SNOWFLAKE',
    batchSizeRecords: 170000,
    maxParallelTasks: 12,
    slaThresholdMinutes: 47,
    retryPolicy: { maxRetries: 3, backoffExponentialFactor: 2.0, initialDelaySeconds: 30 },
    validationAssertionsCount: 8,
    lineageTrackedColumns: ['record_id', 'source_timestamp', 'payload_hash', 'cleared_amount', 'tenant_id']
  },
  {
    dagId: 'DAG-SEC-033',
    pipelineName: 'CybersecuritySIEMLogParser Production Workflow #33',
    domain: 'CybersecuritySIEMLogParser',
    category: 'Distributed firewall and auth log parsing',
    cronSchedule: '33 9 * * *',
    sourceProtocol: 'KAFKA',
    sinkProtocol: 'BIGQUERY',
    batchSizeRecords: 180000,
    maxParallelTasks: 13,
    slaThresholdMinutes: 48,
    retryPolicy: { maxRetries: 3, backoffExponentialFactor: 2.0, initialDelaySeconds: 30 },
    validationAssertionsCount: 9,
    lineageTrackedColumns: ['record_id', 'source_timestamp', 'payload_hash', 'cleared_amount', 'tenant_id']
  },
  {
    dagId: 'DAG-SEC-034',
    pipelineName: 'CybersecuritySIEMLogParser Production Workflow #34',
    domain: 'CybersecuritySIEMLogParser',
    category: 'Sigma rule evaluation',
    cronSchedule: '34 10 * * *',
    sourceProtocol: 'SNOWFLAKE',
    sinkProtocol: 'SNOWFLAKE',
    batchSizeRecords: 190000,
    maxParallelTasks: 14,
    slaThresholdMinutes: 49,
    retryPolicy: { maxRetries: 3, backoffExponentialFactor: 2.0, initialDelaySeconds: 30 },
    validationAssertionsCount: 10,
    lineageTrackedColumns: ['record_id', 'source_timestamp', 'payload_hash', 'cleared_amount', 'tenant_id']
  },
  {
    dagId: 'DAG-SEC-035',
    pipelineName: 'CybersecuritySIEMLogParser Production Workflow #35',
    domain: 'CybersecuritySIEMLogParser',
    category: 'and incident response event routing',
    cronSchedule: '35 11 * * *',
    sourceProtocol: 'ICEBERG',
    sinkProtocol: 'BIGQUERY',
    batchSizeRecords: 200000,
    maxParallelTasks: 15,
    slaThresholdMinutes: 50,
    retryPolicy: { maxRetries: 3, backoffExponentialFactor: 2.0, initialDelaySeconds: 30 },
    validationAssertionsCount: 11,
    lineageTrackedColumns: ['record_id', 'source_timestamp', 'payload_hash', 'cleared_amount', 'tenant_id']
  },
  {
    dagId: 'DAG-SEC-036',
    pipelineName: 'CybersecuritySIEMLogParser Production Workflow #36',
    domain: 'CybersecuritySIEMLogParser',
    category: 'Distributed firewall and auth log parsing',
    cronSchedule: '36 12 * * *',
    sourceProtocol: 'POSTGRES',
    sinkProtocol: 'SNOWFLAKE',
    batchSizeRecords: 210000,
    maxParallelTasks: 4,
    slaThresholdMinutes: 51,
    retryPolicy: { maxRetries: 3, backoffExponentialFactor: 2.0, initialDelaySeconds: 30 },
    validationAssertionsCount: 12,
    lineageTrackedColumns: ['record_id', 'source_timestamp', 'payload_hash', 'cleared_amount', 'tenant_id']
  },
  {
    dagId: 'DAG-SEC-037',
    pipelineName: 'CybersecuritySIEMLogParser Production Workflow #37',
    domain: 'CybersecuritySIEMLogParser',
    category: 'Sigma rule evaluation',
    cronSchedule: '37 13 * * *',
    sourceProtocol: 'ICEBERG',
    sinkProtocol: 'BIGQUERY',
    batchSizeRecords: 220000,
    maxParallelTasks: 5,
    slaThresholdMinutes: 52,
    retryPolicy: { maxRetries: 3, backoffExponentialFactor: 2.0, initialDelaySeconds: 30 },
    validationAssertionsCount: 13,
    lineageTrackedColumns: ['record_id', 'source_timestamp', 'payload_hash', 'cleared_amount', 'tenant_id']
  },
  {
    dagId: 'DAG-SEC-038',
    pipelineName: 'CybersecuritySIEMLogParser Production Workflow #38',
    domain: 'CybersecuritySIEMLogParser',
    category: 'and incident response event routing',
    cronSchedule: '38 14 * * *',
    sourceProtocol: 'SNOWFLAKE',
    sinkProtocol: 'SNOWFLAKE',
    batchSizeRecords: 230000,
    maxParallelTasks: 6,
    slaThresholdMinutes: 53,
    retryPolicy: { maxRetries: 3, backoffExponentialFactor: 2.0, initialDelaySeconds: 30 },
    validationAssertionsCount: 14,
    lineageTrackedColumns: ['record_id', 'source_timestamp', 'payload_hash', 'cleared_amount', 'tenant_id']
  },
  {
    dagId: 'DAG-SEC-039',
    pipelineName: 'CybersecuritySIEMLogParser Production Workflow #39',
    domain: 'CybersecuritySIEMLogParser',
    category: 'Distributed firewall and auth log parsing',
    cronSchedule: '39 15 * * *',
    sourceProtocol: 'KAFKA',
    sinkProtocol: 'BIGQUERY',
    batchSizeRecords: 240000,
    maxParallelTasks: 7,
    slaThresholdMinutes: 54,
    retryPolicy: { maxRetries: 3, backoffExponentialFactor: 2.0, initialDelaySeconds: 30 },
    validationAssertionsCount: 15,
    lineageTrackedColumns: ['record_id', 'source_timestamp', 'payload_hash', 'cleared_amount', 'tenant_id']
  },
  {
    dagId: 'DAG-SEC-040',
    pipelineName: 'CybersecuritySIEMLogParser Production Workflow #40',
    domain: 'CybersecuritySIEMLogParser',
    category: 'Sigma rule evaluation',
    cronSchedule: '40 16 * * *',
    sourceProtocol: 'POSTGRES',
    sinkProtocol: 'SNOWFLAKE',
    batchSizeRecords: 50000,
    maxParallelTasks: 8,
    slaThresholdMinutes: 55,
    retryPolicy: { maxRetries: 3, backoffExponentialFactor: 2.0, initialDelaySeconds: 30 },
    validationAssertionsCount: 16,
    lineageTrackedColumns: ['record_id', 'source_timestamp', 'payload_hash', 'cleared_amount', 'tenant_id']
  },
  {
    dagId: 'DAG-SEC-041',
    pipelineName: 'CybersecuritySIEMLogParser Production Workflow #41',
    domain: 'CybersecuritySIEMLogParser',
    category: 'and incident response event routing',
    cronSchedule: '41 17 * * *',
    sourceProtocol: 'ICEBERG',
    sinkProtocol: 'BIGQUERY',
    batchSizeRecords: 60000,
    maxParallelTasks: 9,
    slaThresholdMinutes: 56,
    retryPolicy: { maxRetries: 3, backoffExponentialFactor: 2.0, initialDelaySeconds: 30 },
    validationAssertionsCount: 17,
    lineageTrackedColumns: ['record_id', 'source_timestamp', 'payload_hash', 'cleared_amount', 'tenant_id']
  },
  {
    dagId: 'DAG-SEC-042',
    pipelineName: 'CybersecuritySIEMLogParser Production Workflow #42',
    domain: 'CybersecuritySIEMLogParser',
    category: 'Distributed firewall and auth log parsing',
    cronSchedule: '42 18 * * *',
    sourceProtocol: 'KAFKA',
    sinkProtocol: 'SNOWFLAKE',
    batchSizeRecords: 70000,
    maxParallelTasks: 10,
    slaThresholdMinutes: 57,
    retryPolicy: { maxRetries: 3, backoffExponentialFactor: 2.0, initialDelaySeconds: 30 },
    validationAssertionsCount: 18,
    lineageTrackedColumns: ['record_id', 'source_timestamp', 'payload_hash', 'cleared_amount', 'tenant_id']
  },
  {
    dagId: 'DAG-SEC-043',
    pipelineName: 'CybersecuritySIEMLogParser Production Workflow #43',
    domain: 'CybersecuritySIEMLogParser',
    category: 'Sigma rule evaluation',
    cronSchedule: '43 19 * * *',
    sourceProtocol: 'ICEBERG',
    sinkProtocol: 'BIGQUERY',
    batchSizeRecords: 80000,
    maxParallelTasks: 11,
    slaThresholdMinutes: 58,
    retryPolicy: { maxRetries: 3, backoffExponentialFactor: 2.0, initialDelaySeconds: 30 },
    validationAssertionsCount: 19,
    lineageTrackedColumns: ['record_id', 'source_timestamp', 'payload_hash', 'cleared_amount', 'tenant_id']
  },
  {
    dagId: 'DAG-SEC-044',
    pipelineName: 'CybersecuritySIEMLogParser Production Workflow #44',
    domain: 'CybersecuritySIEMLogParser',
    category: 'and incident response event routing',
    cronSchedule: '44 20 * * *',
    sourceProtocol: 'POSTGRES',
    sinkProtocol: 'SNOWFLAKE',
    batchSizeRecords: 90000,
    maxParallelTasks: 12,
    slaThresholdMinutes: 59,
    retryPolicy: { maxRetries: 3, backoffExponentialFactor: 2.0, initialDelaySeconds: 30 },
    validationAssertionsCount: 20,
    lineageTrackedColumns: ['record_id', 'source_timestamp', 'payload_hash', 'cleared_amount', 'tenant_id']
  },
  {
    dagId: 'DAG-SEC-045',
    pipelineName: 'CybersecuritySIEMLogParser Production Workflow #45',
    domain: 'CybersecuritySIEMLogParser',
    category: 'Distributed firewall and auth log parsing',
    cronSchedule: '45 21 * * *',
    sourceProtocol: 'KAFKA',
    sinkProtocol: 'BIGQUERY',
    batchSizeRecords: 100000,
    maxParallelTasks: 13,
    slaThresholdMinutes: 15,
    retryPolicy: { maxRetries: 3, backoffExponentialFactor: 2.0, initialDelaySeconds: 30 },
    validationAssertionsCount: 21,
    lineageTrackedColumns: ['record_id', 'source_timestamp', 'payload_hash', 'cleared_amount', 'tenant_id']
  },
  {
    dagId: 'DAG-SEC-046',
    pipelineName: 'CybersecuritySIEMLogParser Production Workflow #46',
    domain: 'CybersecuritySIEMLogParser',
    category: 'Sigma rule evaluation',
    cronSchedule: '46 22 * * *',
    sourceProtocol: 'SNOWFLAKE',
    sinkProtocol: 'SNOWFLAKE',
    batchSizeRecords: 110000,
    maxParallelTasks: 14,
    slaThresholdMinutes: 16,
    retryPolicy: { maxRetries: 3, backoffExponentialFactor: 2.0, initialDelaySeconds: 30 },
    validationAssertionsCount: 22,
    lineageTrackedColumns: ['record_id', 'source_timestamp', 'payload_hash', 'cleared_amount', 'tenant_id']
  },
  {
    dagId: 'DAG-SEC-047',
    pipelineName: 'CybersecuritySIEMLogParser Production Workflow #47',
    domain: 'CybersecuritySIEMLogParser',
    category: 'and incident response event routing',
    cronSchedule: '47 23 * * *',
    sourceProtocol: 'ICEBERG',
    sinkProtocol: 'BIGQUERY',
    batchSizeRecords: 120000,
    maxParallelTasks: 15,
    slaThresholdMinutes: 17,
    retryPolicy: { maxRetries: 3, backoffExponentialFactor: 2.0, initialDelaySeconds: 30 },
    validationAssertionsCount: 23,
    lineageTrackedColumns: ['record_id', 'source_timestamp', 'payload_hash', 'cleared_amount', 'tenant_id']
  },
  {
    dagId: 'DAG-SEC-048',
    pipelineName: 'CybersecuritySIEMLogParser Production Workflow #48',
    domain: 'CybersecuritySIEMLogParser',
    category: 'Distributed firewall and auth log parsing',
    cronSchedule: '48 0 * * *',
    sourceProtocol: 'POSTGRES',
    sinkProtocol: 'SNOWFLAKE',
    batchSizeRecords: 130000,
    maxParallelTasks: 4,
    slaThresholdMinutes: 18,
    retryPolicy: { maxRetries: 3, backoffExponentialFactor: 2.0, initialDelaySeconds: 30 },
    validationAssertionsCount: 8,
    lineageTrackedColumns: ['record_id', 'source_timestamp', 'payload_hash', 'cleared_amount', 'tenant_id']
  },
  {
    dagId: 'DAG-SEC-049',
    pipelineName: 'CybersecuritySIEMLogParser Production Workflow #49',
    domain: 'CybersecuritySIEMLogParser',
    category: 'Sigma rule evaluation',
    cronSchedule: '49 1 * * *',
    sourceProtocol: 'ICEBERG',
    sinkProtocol: 'BIGQUERY',
    batchSizeRecords: 140000,
    maxParallelTasks: 5,
    slaThresholdMinutes: 19,
    retryPolicy: { maxRetries: 3, backoffExponentialFactor: 2.0, initialDelaySeconds: 30 },
    validationAssertionsCount: 9,
    lineageTrackedColumns: ['record_id', 'source_timestamp', 'payload_hash', 'cleared_amount', 'tenant_id']
  },
  {
    dagId: 'DAG-SEC-050',
    pipelineName: 'CybersecuritySIEMLogParser Production Workflow #50',
    domain: 'CybersecuritySIEMLogParser',
    category: 'and incident response event routing',
    cronSchedule: '50 2 * * *',
    sourceProtocol: 'SNOWFLAKE',
    sinkProtocol: 'SNOWFLAKE',
    batchSizeRecords: 150000,
    maxParallelTasks: 6,
    slaThresholdMinutes: 20,
    retryPolicy: { maxRetries: 3, backoffExponentialFactor: 2.0, initialDelaySeconds: 30 },
    validationAssertionsCount: 10,
    lineageTrackedColumns: ['record_id', 'source_timestamp', 'payload_hash', 'cleared_amount', 'tenant_id']
  },
  {
    dagId: 'DAG-SEC-051',
    pipelineName: 'CybersecuritySIEMLogParser Production Workflow #51',
    domain: 'CybersecuritySIEMLogParser',
    category: 'Distributed firewall and auth log parsing',
    cronSchedule: '51 3 * * *',
    sourceProtocol: 'KAFKA',
    sinkProtocol: 'BIGQUERY',
    batchSizeRecords: 160000,
    maxParallelTasks: 7,
    slaThresholdMinutes: 21,
    retryPolicy: { maxRetries: 3, backoffExponentialFactor: 2.0, initialDelaySeconds: 30 },
    validationAssertionsCount: 11,
    lineageTrackedColumns: ['record_id', 'source_timestamp', 'payload_hash', 'cleared_amount', 'tenant_id']
  },
  {
    dagId: 'DAG-SEC-052',
    pipelineName: 'CybersecuritySIEMLogParser Production Workflow #52',
    domain: 'CybersecuritySIEMLogParser',
    category: 'Sigma rule evaluation',
    cronSchedule: '52 4 * * *',
    sourceProtocol: 'POSTGRES',
    sinkProtocol: 'SNOWFLAKE',
    batchSizeRecords: 170000,
    maxParallelTasks: 8,
    slaThresholdMinutes: 22,
    retryPolicy: { maxRetries: 3, backoffExponentialFactor: 2.0, initialDelaySeconds: 30 },
    validationAssertionsCount: 12,
    lineageTrackedColumns: ['record_id', 'source_timestamp', 'payload_hash', 'cleared_amount', 'tenant_id']
  },
  {
    dagId: 'DAG-SEC-053',
    pipelineName: 'CybersecuritySIEMLogParser Production Workflow #53',
    domain: 'CybersecuritySIEMLogParser',
    category: 'and incident response event routing',
    cronSchedule: '53 5 * * *',
    sourceProtocol: 'ICEBERG',
    sinkProtocol: 'BIGQUERY',
    batchSizeRecords: 180000,
    maxParallelTasks: 9,
    slaThresholdMinutes: 23,
    retryPolicy: { maxRetries: 3, backoffExponentialFactor: 2.0, initialDelaySeconds: 30 },
    validationAssertionsCount: 13,
    lineageTrackedColumns: ['record_id', 'source_timestamp', 'payload_hash', 'cleared_amount', 'tenant_id']
  },
  {
    dagId: 'DAG-SEC-054',
    pipelineName: 'CybersecuritySIEMLogParser Production Workflow #54',
    domain: 'CybersecuritySIEMLogParser',
    category: 'Distributed firewall and auth log parsing',
    cronSchedule: '54 6 * * *',
    sourceProtocol: 'KAFKA',
    sinkProtocol: 'SNOWFLAKE',
    batchSizeRecords: 190000,
    maxParallelTasks: 10,
    slaThresholdMinutes: 24,
    retryPolicy: { maxRetries: 3, backoffExponentialFactor: 2.0, initialDelaySeconds: 30 },
    validationAssertionsCount: 14,
    lineageTrackedColumns: ['record_id', 'source_timestamp', 'payload_hash', 'cleared_amount', 'tenant_id']
  },
  {
    dagId: 'DAG-SEC-055',
    pipelineName: 'CybersecuritySIEMLogParser Production Workflow #55',
    domain: 'CybersecuritySIEMLogParser',
    category: 'Sigma rule evaluation',
    cronSchedule: '55 7 * * *',
    sourceProtocol: 'ICEBERG',
    sinkProtocol: 'BIGQUERY',
    batchSizeRecords: 200000,
    maxParallelTasks: 11,
    slaThresholdMinutes: 25,
    retryPolicy: { maxRetries: 3, backoffExponentialFactor: 2.0, initialDelaySeconds: 30 },
    validationAssertionsCount: 15,
    lineageTrackedColumns: ['record_id', 'source_timestamp', 'payload_hash', 'cleared_amount', 'tenant_id']
  },
  {
    dagId: 'DAG-SEC-056',
    pipelineName: 'CybersecuritySIEMLogParser Production Workflow #56',
    domain: 'CybersecuritySIEMLogParser',
    category: 'and incident response event routing',
    cronSchedule: '56 8 * * *',
    sourceProtocol: 'POSTGRES',
    sinkProtocol: 'SNOWFLAKE',
    batchSizeRecords: 210000,
    maxParallelTasks: 12,
    slaThresholdMinutes: 26,
    retryPolicy: { maxRetries: 3, backoffExponentialFactor: 2.0, initialDelaySeconds: 30 },
    validationAssertionsCount: 16,
    lineageTrackedColumns: ['record_id', 'source_timestamp', 'payload_hash', 'cleared_amount', 'tenant_id']
  },
  {
    dagId: 'DAG-SEC-057',
    pipelineName: 'CybersecuritySIEMLogParser Production Workflow #57',
    domain: 'CybersecuritySIEMLogParser',
    category: 'Distributed firewall and auth log parsing',
    cronSchedule: '57 9 * * *',
    sourceProtocol: 'KAFKA',
    sinkProtocol: 'BIGQUERY',
    batchSizeRecords: 220000,
    maxParallelTasks: 13,
    slaThresholdMinutes: 27,
    retryPolicy: { maxRetries: 3, backoffExponentialFactor: 2.0, initialDelaySeconds: 30 },
    validationAssertionsCount: 17,
    lineageTrackedColumns: ['record_id', 'source_timestamp', 'payload_hash', 'cleared_amount', 'tenant_id']
  },
  {
    dagId: 'DAG-SEC-058',
    pipelineName: 'CybersecuritySIEMLogParser Production Workflow #58',
    domain: 'CybersecuritySIEMLogParser',
    category: 'Sigma rule evaluation',
    cronSchedule: '58 10 * * *',
    sourceProtocol: 'SNOWFLAKE',
    sinkProtocol: 'SNOWFLAKE',
    batchSizeRecords: 230000,
    maxParallelTasks: 14,
    slaThresholdMinutes: 28,
    retryPolicy: { maxRetries: 3, backoffExponentialFactor: 2.0, initialDelaySeconds: 30 },
    validationAssertionsCount: 18,
    lineageTrackedColumns: ['record_id', 'source_timestamp', 'payload_hash', 'cleared_amount', 'tenant_id']
  },
  {
    dagId: 'DAG-SEC-059',
    pipelineName: 'CybersecuritySIEMLogParser Production Workflow #59',
    domain: 'CybersecuritySIEMLogParser',
    category: 'and incident response event routing',
    cronSchedule: '59 11 * * *',
    sourceProtocol: 'ICEBERG',
    sinkProtocol: 'BIGQUERY',
    batchSizeRecords: 240000,
    maxParallelTasks: 15,
    slaThresholdMinutes: 29,
    retryPolicy: { maxRetries: 3, backoffExponentialFactor: 2.0, initialDelaySeconds: 30 },
    validationAssertionsCount: 19,
    lineageTrackedColumns: ['record_id', 'source_timestamp', 'payload_hash', 'cleared_amount', 'tenant_id']
  },
  {
    dagId: 'DAG-SEC-060',
    pipelineName: 'CybersecuritySIEMLogParser Production Workflow #60',
    domain: 'CybersecuritySIEMLogParser',
    category: 'Distributed firewall and auth log parsing',
    cronSchedule: '0 12 * * *',
    sourceProtocol: 'POSTGRES',
    sinkProtocol: 'SNOWFLAKE',
    batchSizeRecords: 50000,
    maxParallelTasks: 4,
    slaThresholdMinutes: 30,
    retryPolicy: { maxRetries: 3, backoffExponentialFactor: 2.0, initialDelaySeconds: 30 },
    validationAssertionsCount: 20,
    lineageTrackedColumns: ['record_id', 'source_timestamp', 'payload_hash', 'cleared_amount', 'tenant_id']
  },
  {
    dagId: 'DAG-SEC-061',
    pipelineName: 'CybersecuritySIEMLogParser Production Workflow #61',
    domain: 'CybersecuritySIEMLogParser',
    category: 'Sigma rule evaluation',
    cronSchedule: '1 13 * * *',
    sourceProtocol: 'ICEBERG',
    sinkProtocol: 'BIGQUERY',
    batchSizeRecords: 60000,
    maxParallelTasks: 5,
    slaThresholdMinutes: 31,
    retryPolicy: { maxRetries: 3, backoffExponentialFactor: 2.0, initialDelaySeconds: 30 },
    validationAssertionsCount: 21,
    lineageTrackedColumns: ['record_id', 'source_timestamp', 'payload_hash', 'cleared_amount', 'tenant_id']
  },
  {
    dagId: 'DAG-SEC-062',
    pipelineName: 'CybersecuritySIEMLogParser Production Workflow #62',
    domain: 'CybersecuritySIEMLogParser',
    category: 'and incident response event routing',
    cronSchedule: '2 14 * * *',
    sourceProtocol: 'SNOWFLAKE',
    sinkProtocol: 'SNOWFLAKE',
    batchSizeRecords: 70000,
    maxParallelTasks: 6,
    slaThresholdMinutes: 32,
    retryPolicy: { maxRetries: 3, backoffExponentialFactor: 2.0, initialDelaySeconds: 30 },
    validationAssertionsCount: 22,
    lineageTrackedColumns: ['record_id', 'source_timestamp', 'payload_hash', 'cleared_amount', 'tenant_id']
  },
  {
    dagId: 'DAG-SEC-063',
    pipelineName: 'CybersecuritySIEMLogParser Production Workflow #63',
    domain: 'CybersecuritySIEMLogParser',
    category: 'Distributed firewall and auth log parsing',
    cronSchedule: '3 15 * * *',
    sourceProtocol: 'KAFKA',
    sinkProtocol: 'BIGQUERY',
    batchSizeRecords: 80000,
    maxParallelTasks: 7,
    slaThresholdMinutes: 33,
    retryPolicy: { maxRetries: 3, backoffExponentialFactor: 2.0, initialDelaySeconds: 30 },
    validationAssertionsCount: 23,
    lineageTrackedColumns: ['record_id', 'source_timestamp', 'payload_hash', 'cleared_amount', 'tenant_id']
  },
  {
    dagId: 'DAG-SEC-064',
    pipelineName: 'CybersecuritySIEMLogParser Production Workflow #64',
    domain: 'CybersecuritySIEMLogParser',
    category: 'Sigma rule evaluation',
    cronSchedule: '4 16 * * *',
    sourceProtocol: 'POSTGRES',
    sinkProtocol: 'SNOWFLAKE',
    batchSizeRecords: 90000,
    maxParallelTasks: 8,
    slaThresholdMinutes: 34,
    retryPolicy: { maxRetries: 3, backoffExponentialFactor: 2.0, initialDelaySeconds: 30 },
    validationAssertionsCount: 8,
    lineageTrackedColumns: ['record_id', 'source_timestamp', 'payload_hash', 'cleared_amount', 'tenant_id']
  },
  {
    dagId: 'DAG-SEC-065',
    pipelineName: 'CybersecuritySIEMLogParser Production Workflow #65',
    domain: 'CybersecuritySIEMLogParser',
    category: 'and incident response event routing',
    cronSchedule: '5 17 * * *',
    sourceProtocol: 'ICEBERG',
    sinkProtocol: 'BIGQUERY',
    batchSizeRecords: 100000,
    maxParallelTasks: 9,
    slaThresholdMinutes: 35,
    retryPolicy: { maxRetries: 3, backoffExponentialFactor: 2.0, initialDelaySeconds: 30 },
    validationAssertionsCount: 9,
    lineageTrackedColumns: ['record_id', 'source_timestamp', 'payload_hash', 'cleared_amount', 'tenant_id']
  },
  {
    dagId: 'DAG-SEC-066',
    pipelineName: 'CybersecuritySIEMLogParser Production Workflow #66',
    domain: 'CybersecuritySIEMLogParser',
    category: 'Distributed firewall and auth log parsing',
    cronSchedule: '6 18 * * *',
    sourceProtocol: 'KAFKA',
    sinkProtocol: 'SNOWFLAKE',
    batchSizeRecords: 110000,
    maxParallelTasks: 10,
    slaThresholdMinutes: 36,
    retryPolicy: { maxRetries: 3, backoffExponentialFactor: 2.0, initialDelaySeconds: 30 },
    validationAssertionsCount: 10,
    lineageTrackedColumns: ['record_id', 'source_timestamp', 'payload_hash', 'cleared_amount', 'tenant_id']
  },
  {
    dagId: 'DAG-SEC-067',
    pipelineName: 'CybersecuritySIEMLogParser Production Workflow #67',
    domain: 'CybersecuritySIEMLogParser',
    category: 'Sigma rule evaluation',
    cronSchedule: '7 19 * * *',
    sourceProtocol: 'ICEBERG',
    sinkProtocol: 'BIGQUERY',
    batchSizeRecords: 120000,
    maxParallelTasks: 11,
    slaThresholdMinutes: 37,
    retryPolicy: { maxRetries: 3, backoffExponentialFactor: 2.0, initialDelaySeconds: 30 },
    validationAssertionsCount: 11,
    lineageTrackedColumns: ['record_id', 'source_timestamp', 'payload_hash', 'cleared_amount', 'tenant_id']
  },
  {
    dagId: 'DAG-SEC-068',
    pipelineName: 'CybersecuritySIEMLogParser Production Workflow #68',
    domain: 'CybersecuritySIEMLogParser',
    category: 'and incident response event routing',
    cronSchedule: '8 20 * * *',
    sourceProtocol: 'POSTGRES',
    sinkProtocol: 'SNOWFLAKE',
    batchSizeRecords: 130000,
    maxParallelTasks: 12,
    slaThresholdMinutes: 38,
    retryPolicy: { maxRetries: 3, backoffExponentialFactor: 2.0, initialDelaySeconds: 30 },
    validationAssertionsCount: 12,
    lineageTrackedColumns: ['record_id', 'source_timestamp', 'payload_hash', 'cleared_amount', 'tenant_id']
  },
  {
    dagId: 'DAG-SEC-069',
    pipelineName: 'CybersecuritySIEMLogParser Production Workflow #69',
    domain: 'CybersecuritySIEMLogParser',
    category: 'Distributed firewall and auth log parsing',
    cronSchedule: '9 21 * * *',
    sourceProtocol: 'KAFKA',
    sinkProtocol: 'BIGQUERY',
    batchSizeRecords: 140000,
    maxParallelTasks: 13,
    slaThresholdMinutes: 39,
    retryPolicy: { maxRetries: 3, backoffExponentialFactor: 2.0, initialDelaySeconds: 30 },
    validationAssertionsCount: 13,
    lineageTrackedColumns: ['record_id', 'source_timestamp', 'payload_hash', 'cleared_amount', 'tenant_id']
  },
  {
    dagId: 'DAG-SEC-070',
    pipelineName: 'CybersecuritySIEMLogParser Production Workflow #70',
    domain: 'CybersecuritySIEMLogParser',
    category: 'Sigma rule evaluation',
    cronSchedule: '10 22 * * *',
    sourceProtocol: 'SNOWFLAKE',
    sinkProtocol: 'SNOWFLAKE',
    batchSizeRecords: 150000,
    maxParallelTasks: 14,
    slaThresholdMinutes: 40,
    retryPolicy: { maxRetries: 3, backoffExponentialFactor: 2.0, initialDelaySeconds: 30 },
    validationAssertionsCount: 14,
    lineageTrackedColumns: ['record_id', 'source_timestamp', 'payload_hash', 'cleared_amount', 'tenant_id']
  },
  {
    dagId: 'DAG-SEC-071',
    pipelineName: 'CybersecuritySIEMLogParser Production Workflow #71',
    domain: 'CybersecuritySIEMLogParser',
    category: 'and incident response event routing',
    cronSchedule: '11 23 * * *',
    sourceProtocol: 'ICEBERG',
    sinkProtocol: 'BIGQUERY',
    batchSizeRecords: 160000,
    maxParallelTasks: 15,
    slaThresholdMinutes: 41,
    retryPolicy: { maxRetries: 3, backoffExponentialFactor: 2.0, initialDelaySeconds: 30 },
    validationAssertionsCount: 15,
    lineageTrackedColumns: ['record_id', 'source_timestamp', 'payload_hash', 'cleared_amount', 'tenant_id']
  },
  {
    dagId: 'DAG-SEC-072',
    pipelineName: 'CybersecuritySIEMLogParser Production Workflow #72',
    domain: 'CybersecuritySIEMLogParser',
    category: 'Distributed firewall and auth log parsing',
    cronSchedule: '12 0 * * *',
    sourceProtocol: 'POSTGRES',
    sinkProtocol: 'SNOWFLAKE',
    batchSizeRecords: 170000,
    maxParallelTasks: 4,
    slaThresholdMinutes: 42,
    retryPolicy: { maxRetries: 3, backoffExponentialFactor: 2.0, initialDelaySeconds: 30 },
    validationAssertionsCount: 16,
    lineageTrackedColumns: ['record_id', 'source_timestamp', 'payload_hash', 'cleared_amount', 'tenant_id']
  },
  {
    dagId: 'DAG-SEC-073',
    pipelineName: 'CybersecuritySIEMLogParser Production Workflow #73',
    domain: 'CybersecuritySIEMLogParser',
    category: 'Sigma rule evaluation',
    cronSchedule: '13 1 * * *',
    sourceProtocol: 'ICEBERG',
    sinkProtocol: 'BIGQUERY',
    batchSizeRecords: 180000,
    maxParallelTasks: 5,
    slaThresholdMinutes: 43,
    retryPolicy: { maxRetries: 3, backoffExponentialFactor: 2.0, initialDelaySeconds: 30 },
    validationAssertionsCount: 17,
    lineageTrackedColumns: ['record_id', 'source_timestamp', 'payload_hash', 'cleared_amount', 'tenant_id']
  },
  {
    dagId: 'DAG-SEC-074',
    pipelineName: 'CybersecuritySIEMLogParser Production Workflow #74',
    domain: 'CybersecuritySIEMLogParser',
    category: 'and incident response event routing',
    cronSchedule: '14 2 * * *',
    sourceProtocol: 'SNOWFLAKE',
    sinkProtocol: 'SNOWFLAKE',
    batchSizeRecords: 190000,
    maxParallelTasks: 6,
    slaThresholdMinutes: 44,
    retryPolicy: { maxRetries: 3, backoffExponentialFactor: 2.0, initialDelaySeconds: 30 },
    validationAssertionsCount: 18,
    lineageTrackedColumns: ['record_id', 'source_timestamp', 'payload_hash', 'cleared_amount', 'tenant_id']
  },
  {
    dagId: 'DAG-SEC-075',
    pipelineName: 'CybersecuritySIEMLogParser Production Workflow #75',
    domain: 'CybersecuritySIEMLogParser',
    category: 'Distributed firewall and auth log parsing',
    cronSchedule: '15 3 * * *',
    sourceProtocol: 'KAFKA',
    sinkProtocol: 'BIGQUERY',
    batchSizeRecords: 200000,
    maxParallelTasks: 7,
    slaThresholdMinutes: 45,
    retryPolicy: { maxRetries: 3, backoffExponentialFactor: 2.0, initialDelaySeconds: 30 },
    validationAssertionsCount: 19,
    lineageTrackedColumns: ['record_id', 'source_timestamp', 'payload_hash', 'cleared_amount', 'tenant_id']
  },
  {
    dagId: 'DAG-SEC-076',
    pipelineName: 'CybersecuritySIEMLogParser Production Workflow #76',
    domain: 'CybersecuritySIEMLogParser',
    category: 'Sigma rule evaluation',
    cronSchedule: '16 4 * * *',
    sourceProtocol: 'POSTGRES',
    sinkProtocol: 'SNOWFLAKE',
    batchSizeRecords: 210000,
    maxParallelTasks: 8,
    slaThresholdMinutes: 46,
    retryPolicy: { maxRetries: 3, backoffExponentialFactor: 2.0, initialDelaySeconds: 30 },
    validationAssertionsCount: 20,
    lineageTrackedColumns: ['record_id', 'source_timestamp', 'payload_hash', 'cleared_amount', 'tenant_id']
  },
  {
    dagId: 'DAG-SEC-077',
    pipelineName: 'CybersecuritySIEMLogParser Production Workflow #77',
    domain: 'CybersecuritySIEMLogParser',
    category: 'and incident response event routing',
    cronSchedule: '17 5 * * *',
    sourceProtocol: 'ICEBERG',
    sinkProtocol: 'BIGQUERY',
    batchSizeRecords: 220000,
    maxParallelTasks: 9,
    slaThresholdMinutes: 47,
    retryPolicy: { maxRetries: 3, backoffExponentialFactor: 2.0, initialDelaySeconds: 30 },
    validationAssertionsCount: 21,
    lineageTrackedColumns: ['record_id', 'source_timestamp', 'payload_hash', 'cleared_amount', 'tenant_id']
  },
  {
    dagId: 'DAG-SEC-078',
    pipelineName: 'CybersecuritySIEMLogParser Production Workflow #78',
    domain: 'CybersecuritySIEMLogParser',
    category: 'Distributed firewall and auth log parsing',
    cronSchedule: '18 6 * * *',
    sourceProtocol: 'KAFKA',
    sinkProtocol: 'SNOWFLAKE',
    batchSizeRecords: 230000,
    maxParallelTasks: 10,
    slaThresholdMinutes: 48,
    retryPolicy: { maxRetries: 3, backoffExponentialFactor: 2.0, initialDelaySeconds: 30 },
    validationAssertionsCount: 22,
    lineageTrackedColumns: ['record_id', 'source_timestamp', 'payload_hash', 'cleared_amount', 'tenant_id']
  },
  {
    dagId: 'DAG-SEC-079',
    pipelineName: 'CybersecuritySIEMLogParser Production Workflow #79',
    domain: 'CybersecuritySIEMLogParser',
    category: 'Sigma rule evaluation',
    cronSchedule: '19 7 * * *',
    sourceProtocol: 'ICEBERG',
    sinkProtocol: 'BIGQUERY',
    batchSizeRecords: 240000,
    maxParallelTasks: 11,
    slaThresholdMinutes: 49,
    retryPolicy: { maxRetries: 3, backoffExponentialFactor: 2.0, initialDelaySeconds: 30 },
    validationAssertionsCount: 23,
    lineageTrackedColumns: ['record_id', 'source_timestamp', 'payload_hash', 'cleared_amount', 'tenant_id']
  },
  {
    dagId: 'DAG-SEC-080',
    pipelineName: 'CybersecuritySIEMLogParser Production Workflow #80',
    domain: 'CybersecuritySIEMLogParser',
    category: 'and incident response event routing',
    cronSchedule: '20 8 * * *',
    sourceProtocol: 'POSTGRES',
    sinkProtocol: 'SNOWFLAKE',
    batchSizeRecords: 50000,
    maxParallelTasks: 12,
    slaThresholdMinutes: 50,
    retryPolicy: { maxRetries: 3, backoffExponentialFactor: 2.0, initialDelaySeconds: 30 },
    validationAssertionsCount: 8,
    lineageTrackedColumns: ['record_id', 'source_timestamp', 'payload_hash', 'cleared_amount', 'tenant_id']
  },
  {
    dagId: 'DAG-SEC-081',
    pipelineName: 'CybersecuritySIEMLogParser Production Workflow #81',
    domain: 'CybersecuritySIEMLogParser',
    category: 'Distributed firewall and auth log parsing',
    cronSchedule: '21 9 * * *',
    sourceProtocol: 'KAFKA',
    sinkProtocol: 'BIGQUERY',
    batchSizeRecords: 60000,
    maxParallelTasks: 13,
    slaThresholdMinutes: 51,
    retryPolicy: { maxRetries: 3, backoffExponentialFactor: 2.0, initialDelaySeconds: 30 },
    validationAssertionsCount: 9,
    lineageTrackedColumns: ['record_id', 'source_timestamp', 'payload_hash', 'cleared_amount', 'tenant_id']
  },
  {
    dagId: 'DAG-SEC-082',
    pipelineName: 'CybersecuritySIEMLogParser Production Workflow #82',
    domain: 'CybersecuritySIEMLogParser',
    category: 'Sigma rule evaluation',
    cronSchedule: '22 10 * * *',
    sourceProtocol: 'SNOWFLAKE',
    sinkProtocol: 'SNOWFLAKE',
    batchSizeRecords: 70000,
    maxParallelTasks: 14,
    slaThresholdMinutes: 52,
    retryPolicy: { maxRetries: 3, backoffExponentialFactor: 2.0, initialDelaySeconds: 30 },
    validationAssertionsCount: 10,
    lineageTrackedColumns: ['record_id', 'source_timestamp', 'payload_hash', 'cleared_amount', 'tenant_id']
  },
  {
    dagId: 'DAG-SEC-083',
    pipelineName: 'CybersecuritySIEMLogParser Production Workflow #83',
    domain: 'CybersecuritySIEMLogParser',
    category: 'and incident response event routing',
    cronSchedule: '23 11 * * *',
    sourceProtocol: 'ICEBERG',
    sinkProtocol: 'BIGQUERY',
    batchSizeRecords: 80000,
    maxParallelTasks: 15,
    slaThresholdMinutes: 53,
    retryPolicy: { maxRetries: 3, backoffExponentialFactor: 2.0, initialDelaySeconds: 30 },
    validationAssertionsCount: 11,
    lineageTrackedColumns: ['record_id', 'source_timestamp', 'payload_hash', 'cleared_amount', 'tenant_id']
  },
  {
    dagId: 'DAG-SEC-084',
    pipelineName: 'CybersecuritySIEMLogParser Production Workflow #84',
    domain: 'CybersecuritySIEMLogParser',
    category: 'Distributed firewall and auth log parsing',
    cronSchedule: '24 12 * * *',
    sourceProtocol: 'POSTGRES',
    sinkProtocol: 'SNOWFLAKE',
    batchSizeRecords: 90000,
    maxParallelTasks: 4,
    slaThresholdMinutes: 54,
    retryPolicy: { maxRetries: 3, backoffExponentialFactor: 2.0, initialDelaySeconds: 30 },
    validationAssertionsCount: 12,
    lineageTrackedColumns: ['record_id', 'source_timestamp', 'payload_hash', 'cleared_amount', 'tenant_id']
  },
  {
    dagId: 'DAG-SEC-085',
    pipelineName: 'CybersecuritySIEMLogParser Production Workflow #85',
    domain: 'CybersecuritySIEMLogParser',
    category: 'Sigma rule evaluation',
    cronSchedule: '25 13 * * *',
    sourceProtocol: 'ICEBERG',
    sinkProtocol: 'BIGQUERY',
    batchSizeRecords: 100000,
    maxParallelTasks: 5,
    slaThresholdMinutes: 55,
    retryPolicy: { maxRetries: 3, backoffExponentialFactor: 2.0, initialDelaySeconds: 30 },
    validationAssertionsCount: 13,
    lineageTrackedColumns: ['record_id', 'source_timestamp', 'payload_hash', 'cleared_amount', 'tenant_id']
  },
  {
    dagId: 'DAG-SEC-086',
    pipelineName: 'CybersecuritySIEMLogParser Production Workflow #86',
    domain: 'CybersecuritySIEMLogParser',
    category: 'and incident response event routing',
    cronSchedule: '26 14 * * *',
    sourceProtocol: 'SNOWFLAKE',
    sinkProtocol: 'SNOWFLAKE',
    batchSizeRecords: 110000,
    maxParallelTasks: 6,
    slaThresholdMinutes: 56,
    retryPolicy: { maxRetries: 3, backoffExponentialFactor: 2.0, initialDelaySeconds: 30 },
    validationAssertionsCount: 14,
    lineageTrackedColumns: ['record_id', 'source_timestamp', 'payload_hash', 'cleared_amount', 'tenant_id']
  },
  {
    dagId: 'DAG-SEC-087',
    pipelineName: 'CybersecuritySIEMLogParser Production Workflow #87',
    domain: 'CybersecuritySIEMLogParser',
    category: 'Distributed firewall and auth log parsing',
    cronSchedule: '27 15 * * *',
    sourceProtocol: 'KAFKA',
    sinkProtocol: 'BIGQUERY',
    batchSizeRecords: 120000,
    maxParallelTasks: 7,
    slaThresholdMinutes: 57,
    retryPolicy: { maxRetries: 3, backoffExponentialFactor: 2.0, initialDelaySeconds: 30 },
    validationAssertionsCount: 15,
    lineageTrackedColumns: ['record_id', 'source_timestamp', 'payload_hash', 'cleared_amount', 'tenant_id']
  },
  {
    dagId: 'DAG-SEC-088',
    pipelineName: 'CybersecuritySIEMLogParser Production Workflow #88',
    domain: 'CybersecuritySIEMLogParser',
    category: 'Sigma rule evaluation',
    cronSchedule: '28 16 * * *',
    sourceProtocol: 'POSTGRES',
    sinkProtocol: 'SNOWFLAKE',
    batchSizeRecords: 130000,
    maxParallelTasks: 8,
    slaThresholdMinutes: 58,
    retryPolicy: { maxRetries: 3, backoffExponentialFactor: 2.0, initialDelaySeconds: 30 },
    validationAssertionsCount: 16,
    lineageTrackedColumns: ['record_id', 'source_timestamp', 'payload_hash', 'cleared_amount', 'tenant_id']
  },
  {
    dagId: 'DAG-SEC-089',
    pipelineName: 'CybersecuritySIEMLogParser Production Workflow #89',
    domain: 'CybersecuritySIEMLogParser',
    category: 'and incident response event routing',
    cronSchedule: '29 17 * * *',
    sourceProtocol: 'ICEBERG',
    sinkProtocol: 'BIGQUERY',
    batchSizeRecords: 140000,
    maxParallelTasks: 9,
    slaThresholdMinutes: 59,
    retryPolicy: { maxRetries: 3, backoffExponentialFactor: 2.0, initialDelaySeconds: 30 },
    validationAssertionsCount: 17,
    lineageTrackedColumns: ['record_id', 'source_timestamp', 'payload_hash', 'cleared_amount', 'tenant_id']
  },
  {
    dagId: 'DAG-SEC-090',
    pipelineName: 'CybersecuritySIEMLogParser Production Workflow #90',
    domain: 'CybersecuritySIEMLogParser',
    category: 'Distributed firewall and auth log parsing',
    cronSchedule: '30 18 * * *',
    sourceProtocol: 'KAFKA',
    sinkProtocol: 'SNOWFLAKE',
    batchSizeRecords: 150000,
    maxParallelTasks: 10,
    slaThresholdMinutes: 15,
    retryPolicy: { maxRetries: 3, backoffExponentialFactor: 2.0, initialDelaySeconds: 30 },
    validationAssertionsCount: 18,
    lineageTrackedColumns: ['record_id', 'source_timestamp', 'payload_hash', 'cleared_amount', 'tenant_id']
  },
  {
    dagId: 'DAG-SEC-091',
    pipelineName: 'CybersecuritySIEMLogParser Production Workflow #91',
    domain: 'CybersecuritySIEMLogParser',
    category: 'Sigma rule evaluation',
    cronSchedule: '31 19 * * *',
    sourceProtocol: 'ICEBERG',
    sinkProtocol: 'BIGQUERY',
    batchSizeRecords: 160000,
    maxParallelTasks: 11,
    slaThresholdMinutes: 16,
    retryPolicy: { maxRetries: 3, backoffExponentialFactor: 2.0, initialDelaySeconds: 30 },
    validationAssertionsCount: 19,
    lineageTrackedColumns: ['record_id', 'source_timestamp', 'payload_hash', 'cleared_amount', 'tenant_id']
  },
  {
    dagId: 'DAG-SEC-092',
    pipelineName: 'CybersecuritySIEMLogParser Production Workflow #92',
    domain: 'CybersecuritySIEMLogParser',
    category: 'and incident response event routing',
    cronSchedule: '32 20 * * *',
    sourceProtocol: 'POSTGRES',
    sinkProtocol: 'SNOWFLAKE',
    batchSizeRecords: 170000,
    maxParallelTasks: 12,
    slaThresholdMinutes: 17,
    retryPolicy: { maxRetries: 3, backoffExponentialFactor: 2.0, initialDelaySeconds: 30 },
    validationAssertionsCount: 20,
    lineageTrackedColumns: ['record_id', 'source_timestamp', 'payload_hash', 'cleared_amount', 'tenant_id']
  },
  {
    dagId: 'DAG-SEC-093',
    pipelineName: 'CybersecuritySIEMLogParser Production Workflow #93',
    domain: 'CybersecuritySIEMLogParser',
    category: 'Distributed firewall and auth log parsing',
    cronSchedule: '33 21 * * *',
    sourceProtocol: 'KAFKA',
    sinkProtocol: 'BIGQUERY',
    batchSizeRecords: 180000,
    maxParallelTasks: 13,
    slaThresholdMinutes: 18,
    retryPolicy: { maxRetries: 3, backoffExponentialFactor: 2.0, initialDelaySeconds: 30 },
    validationAssertionsCount: 21,
    lineageTrackedColumns: ['record_id', 'source_timestamp', 'payload_hash', 'cleared_amount', 'tenant_id']
  },
  {
    dagId: 'DAG-SEC-094',
    pipelineName: 'CybersecuritySIEMLogParser Production Workflow #94',
    domain: 'CybersecuritySIEMLogParser',
    category: 'Sigma rule evaluation',
    cronSchedule: '34 22 * * *',
    sourceProtocol: 'SNOWFLAKE',
    sinkProtocol: 'SNOWFLAKE',
    batchSizeRecords: 190000,
    maxParallelTasks: 14,
    slaThresholdMinutes: 19,
    retryPolicy: { maxRetries: 3, backoffExponentialFactor: 2.0, initialDelaySeconds: 30 },
    validationAssertionsCount: 22,
    lineageTrackedColumns: ['record_id', 'source_timestamp', 'payload_hash', 'cleared_amount', 'tenant_id']
  },
  {
    dagId: 'DAG-SEC-095',
    pipelineName: 'CybersecuritySIEMLogParser Production Workflow #95',
    domain: 'CybersecuritySIEMLogParser',
    category: 'and incident response event routing',
    cronSchedule: '35 23 * * *',
    sourceProtocol: 'ICEBERG',
    sinkProtocol: 'BIGQUERY',
    batchSizeRecords: 200000,
    maxParallelTasks: 15,
    slaThresholdMinutes: 20,
    retryPolicy: { maxRetries: 3, backoffExponentialFactor: 2.0, initialDelaySeconds: 30 },
    validationAssertionsCount: 23,
    lineageTrackedColumns: ['record_id', 'source_timestamp', 'payload_hash', 'cleared_amount', 'tenant_id']
  },
  {
    dagId: 'DAG-SEC-096',
    pipelineName: 'CybersecuritySIEMLogParser Production Workflow #96',
    domain: 'CybersecuritySIEMLogParser',
    category: 'Distributed firewall and auth log parsing',
    cronSchedule: '36 0 * * *',
    sourceProtocol: 'POSTGRES',
    sinkProtocol: 'SNOWFLAKE',
    batchSizeRecords: 210000,
    maxParallelTasks: 4,
    slaThresholdMinutes: 21,
    retryPolicy: { maxRetries: 3, backoffExponentialFactor: 2.0, initialDelaySeconds: 30 },
    validationAssertionsCount: 8,
    lineageTrackedColumns: ['record_id', 'source_timestamp', 'payload_hash', 'cleared_amount', 'tenant_id']
  },
  {
    dagId: 'DAG-SEC-097',
    pipelineName: 'CybersecuritySIEMLogParser Production Workflow #97',
    domain: 'CybersecuritySIEMLogParser',
    category: 'Sigma rule evaluation',
    cronSchedule: '37 1 * * *',
    sourceProtocol: 'ICEBERG',
    sinkProtocol: 'BIGQUERY',
    batchSizeRecords: 220000,
    maxParallelTasks: 5,
    slaThresholdMinutes: 22,
    retryPolicy: { maxRetries: 3, backoffExponentialFactor: 2.0, initialDelaySeconds: 30 },
    validationAssertionsCount: 9,
    lineageTrackedColumns: ['record_id', 'source_timestamp', 'payload_hash', 'cleared_amount', 'tenant_id']
  },
  {
    dagId: 'DAG-SEC-098',
    pipelineName: 'CybersecuritySIEMLogParser Production Workflow #98',
    domain: 'CybersecuritySIEMLogParser',
    category: 'and incident response event routing',
    cronSchedule: '38 2 * * *',
    sourceProtocol: 'SNOWFLAKE',
    sinkProtocol: 'SNOWFLAKE',
    batchSizeRecords: 230000,
    maxParallelTasks: 6,
    slaThresholdMinutes: 23,
    retryPolicy: { maxRetries: 3, backoffExponentialFactor: 2.0, initialDelaySeconds: 30 },
    validationAssertionsCount: 10,
    lineageTrackedColumns: ['record_id', 'source_timestamp', 'payload_hash', 'cleared_amount', 'tenant_id']
  },
  {
    dagId: 'DAG-SEC-099',
    pipelineName: 'CybersecuritySIEMLogParser Production Workflow #99',
    domain: 'CybersecuritySIEMLogParser',
    category: 'Distributed firewall and auth log parsing',
    cronSchedule: '39 3 * * *',
    sourceProtocol: 'KAFKA',
    sinkProtocol: 'BIGQUERY',
    batchSizeRecords: 240000,
    maxParallelTasks: 7,
    slaThresholdMinutes: 24,
    retryPolicy: { maxRetries: 3, backoffExponentialFactor: 2.0, initialDelaySeconds: 30 },
    validationAssertionsCount: 11,
    lineageTrackedColumns: ['record_id', 'source_timestamp', 'payload_hash', 'cleared_amount', 'tenant_id']
  },
  {
    dagId: 'DAG-SEC-100',
    pipelineName: 'CybersecuritySIEMLogParser Production Workflow #100',
    domain: 'CybersecuritySIEMLogParser',
    category: 'Sigma rule evaluation',
    cronSchedule: '40 4 * * *',
    sourceProtocol: 'POSTGRES',
    sinkProtocol: 'SNOWFLAKE',
    batchSizeRecords: 50000,
    maxParallelTasks: 8,
    slaThresholdMinutes: 25,
    retryPolicy: { maxRetries: 3, backoffExponentialFactor: 2.0, initialDelaySeconds: 30 },
    validationAssertionsCount: 12,
    lineageTrackedColumns: ['record_id', 'source_timestamp', 'payload_hash', 'cleared_amount', 'tenant_id']
  },
  {
    dagId: 'DAG-SEC-101',
    pipelineName: 'CybersecuritySIEMLogParser Production Workflow #101',
    domain: 'CybersecuritySIEMLogParser',
    category: 'and incident response event routing',
    cronSchedule: '41 5 * * *',
    sourceProtocol: 'ICEBERG',
    sinkProtocol: 'BIGQUERY',
    batchSizeRecords: 60000,
    maxParallelTasks: 9,
    slaThresholdMinutes: 26,
    retryPolicy: { maxRetries: 3, backoffExponentialFactor: 2.0, initialDelaySeconds: 30 },
    validationAssertionsCount: 13,
    lineageTrackedColumns: ['record_id', 'source_timestamp', 'payload_hash', 'cleared_amount', 'tenant_id']
  },
  {
    dagId: 'DAG-SEC-102',
    pipelineName: 'CybersecuritySIEMLogParser Production Workflow #102',
    domain: 'CybersecuritySIEMLogParser',
    category: 'Distributed firewall and auth log parsing',
    cronSchedule: '42 6 * * *',
    sourceProtocol: 'KAFKA',
    sinkProtocol: 'SNOWFLAKE',
    batchSizeRecords: 70000,
    maxParallelTasks: 10,
    slaThresholdMinutes: 27,
    retryPolicy: { maxRetries: 3, backoffExponentialFactor: 2.0, initialDelaySeconds: 30 },
    validationAssertionsCount: 14,
    lineageTrackedColumns: ['record_id', 'source_timestamp', 'payload_hash', 'cleared_amount', 'tenant_id']
  },
  {
    dagId: 'DAG-SEC-103',
    pipelineName: 'CybersecuritySIEMLogParser Production Workflow #103',
    domain: 'CybersecuritySIEMLogParser',
    category: 'Sigma rule evaluation',
    cronSchedule: '43 7 * * *',
    sourceProtocol: 'ICEBERG',
    sinkProtocol: 'BIGQUERY',
    batchSizeRecords: 80000,
    maxParallelTasks: 11,
    slaThresholdMinutes: 28,
    retryPolicy: { maxRetries: 3, backoffExponentialFactor: 2.0, initialDelaySeconds: 30 },
    validationAssertionsCount: 15,
    lineageTrackedColumns: ['record_id', 'source_timestamp', 'payload_hash', 'cleared_amount', 'tenant_id']
  },
  {
    dagId: 'DAG-SEC-104',
    pipelineName: 'CybersecuritySIEMLogParser Production Workflow #104',
    domain: 'CybersecuritySIEMLogParser',
    category: 'and incident response event routing',
    cronSchedule: '44 8 * * *',
    sourceProtocol: 'POSTGRES',
    sinkProtocol: 'SNOWFLAKE',
    batchSizeRecords: 90000,
    maxParallelTasks: 12,
    slaThresholdMinutes: 29,
    retryPolicy: { maxRetries: 3, backoffExponentialFactor: 2.0, initialDelaySeconds: 30 },
    validationAssertionsCount: 16,
    lineageTrackedColumns: ['record_id', 'source_timestamp', 'payload_hash', 'cleared_amount', 'tenant_id']
  },
  {
    dagId: 'DAG-SEC-105',
    pipelineName: 'CybersecuritySIEMLogParser Production Workflow #105',
    domain: 'CybersecuritySIEMLogParser',
    category: 'Distributed firewall and auth log parsing',
    cronSchedule: '45 9 * * *',
    sourceProtocol: 'KAFKA',
    sinkProtocol: 'BIGQUERY',
    batchSizeRecords: 100000,
    maxParallelTasks: 13,
    slaThresholdMinutes: 30,
    retryPolicy: { maxRetries: 3, backoffExponentialFactor: 2.0, initialDelaySeconds: 30 },
    validationAssertionsCount: 17,
    lineageTrackedColumns: ['record_id', 'source_timestamp', 'payload_hash', 'cleared_amount', 'tenant_id']
  },
  {
    dagId: 'DAG-SEC-106',
    pipelineName: 'CybersecuritySIEMLogParser Production Workflow #106',
    domain: 'CybersecuritySIEMLogParser',
    category: 'Sigma rule evaluation',
    cronSchedule: '46 10 * * *',
    sourceProtocol: 'SNOWFLAKE',
    sinkProtocol: 'SNOWFLAKE',
    batchSizeRecords: 110000,
    maxParallelTasks: 14,
    slaThresholdMinutes: 31,
    retryPolicy: { maxRetries: 3, backoffExponentialFactor: 2.0, initialDelaySeconds: 30 },
    validationAssertionsCount: 18,
    lineageTrackedColumns: ['record_id', 'source_timestamp', 'payload_hash', 'cleared_amount', 'tenant_id']
  },
  {
    dagId: 'DAG-SEC-107',
    pipelineName: 'CybersecuritySIEMLogParser Production Workflow #107',
    domain: 'CybersecuritySIEMLogParser',
    category: 'and incident response event routing',
    cronSchedule: '47 11 * * *',
    sourceProtocol: 'ICEBERG',
    sinkProtocol: 'BIGQUERY',
    batchSizeRecords: 120000,
    maxParallelTasks: 15,
    slaThresholdMinutes: 32,
    retryPolicy: { maxRetries: 3, backoffExponentialFactor: 2.0, initialDelaySeconds: 30 },
    validationAssertionsCount: 19,
    lineageTrackedColumns: ['record_id', 'source_timestamp', 'payload_hash', 'cleared_amount', 'tenant_id']
  },
  {
    dagId: 'DAG-SEC-108',
    pipelineName: 'CybersecuritySIEMLogParser Production Workflow #108',
    domain: 'CybersecuritySIEMLogParser',
    category: 'Distributed firewall and auth log parsing',
    cronSchedule: '48 12 * * *',
    sourceProtocol: 'POSTGRES',
    sinkProtocol: 'SNOWFLAKE',
    batchSizeRecords: 130000,
    maxParallelTasks: 4,
    slaThresholdMinutes: 33,
    retryPolicy: { maxRetries: 3, backoffExponentialFactor: 2.0, initialDelaySeconds: 30 },
    validationAssertionsCount: 20,
    lineageTrackedColumns: ['record_id', 'source_timestamp', 'payload_hash', 'cleared_amount', 'tenant_id']
  },
  {
    dagId: 'DAG-SEC-109',
    pipelineName: 'CybersecuritySIEMLogParser Production Workflow #109',
    domain: 'CybersecuritySIEMLogParser',
    category: 'Sigma rule evaluation',
    cronSchedule: '49 13 * * *',
    sourceProtocol: 'ICEBERG',
    sinkProtocol: 'BIGQUERY',
    batchSizeRecords: 140000,
    maxParallelTasks: 5,
    slaThresholdMinutes: 34,
    retryPolicy: { maxRetries: 3, backoffExponentialFactor: 2.0, initialDelaySeconds: 30 },
    validationAssertionsCount: 21,
    lineageTrackedColumns: ['record_id', 'source_timestamp', 'payload_hash', 'cleared_amount', 'tenant_id']
  },
  {
    dagId: 'DAG-SEC-110',
    pipelineName: 'CybersecuritySIEMLogParser Production Workflow #110',
    domain: 'CybersecuritySIEMLogParser',
    category: 'and incident response event routing',
    cronSchedule: '50 14 * * *',
    sourceProtocol: 'SNOWFLAKE',
    sinkProtocol: 'SNOWFLAKE',
    batchSizeRecords: 150000,
    maxParallelTasks: 6,
    slaThresholdMinutes: 35,
    retryPolicy: { maxRetries: 3, backoffExponentialFactor: 2.0, initialDelaySeconds: 30 },
    validationAssertionsCount: 22,
    lineageTrackedColumns: ['record_id', 'source_timestamp', 'payload_hash', 'cleared_amount', 'tenant_id']
  },
  {
    dagId: 'DAG-SEC-111',
    pipelineName: 'CybersecuritySIEMLogParser Production Workflow #111',
    domain: 'CybersecuritySIEMLogParser',
    category: 'Distributed firewall and auth log parsing',
    cronSchedule: '51 15 * * *',
    sourceProtocol: 'KAFKA',
    sinkProtocol: 'BIGQUERY',
    batchSizeRecords: 160000,
    maxParallelTasks: 7,
    slaThresholdMinutes: 36,
    retryPolicy: { maxRetries: 3, backoffExponentialFactor: 2.0, initialDelaySeconds: 30 },
    validationAssertionsCount: 23,
    lineageTrackedColumns: ['record_id', 'source_timestamp', 'payload_hash', 'cleared_amount', 'tenant_id']
  },
  {
    dagId: 'DAG-SEC-112',
    pipelineName: 'CybersecuritySIEMLogParser Production Workflow #112',
    domain: 'CybersecuritySIEMLogParser',
    category: 'Sigma rule evaluation',
    cronSchedule: '52 16 * * *',
    sourceProtocol: 'POSTGRES',
    sinkProtocol: 'SNOWFLAKE',
    batchSizeRecords: 170000,
    maxParallelTasks: 8,
    slaThresholdMinutes: 37,
    retryPolicy: { maxRetries: 3, backoffExponentialFactor: 2.0, initialDelaySeconds: 30 },
    validationAssertionsCount: 8,
    lineageTrackedColumns: ['record_id', 'source_timestamp', 'payload_hash', 'cleared_amount', 'tenant_id']
  },
  {
    dagId: 'DAG-SEC-113',
    pipelineName: 'CybersecuritySIEMLogParser Production Workflow #113',
    domain: 'CybersecuritySIEMLogParser',
    category: 'and incident response event routing',
    cronSchedule: '53 17 * * *',
    sourceProtocol: 'ICEBERG',
    sinkProtocol: 'BIGQUERY',
    batchSizeRecords: 180000,
    maxParallelTasks: 9,
    slaThresholdMinutes: 38,
    retryPolicy: { maxRetries: 3, backoffExponentialFactor: 2.0, initialDelaySeconds: 30 },
    validationAssertionsCount: 9,
    lineageTrackedColumns: ['record_id', 'source_timestamp', 'payload_hash', 'cleared_amount', 'tenant_id']
  },
  {
    dagId: 'DAG-SEC-114',
    pipelineName: 'CybersecuritySIEMLogParser Production Workflow #114',
    domain: 'CybersecuritySIEMLogParser',
    category: 'Distributed firewall and auth log parsing',
    cronSchedule: '54 18 * * *',
    sourceProtocol: 'KAFKA',
    sinkProtocol: 'SNOWFLAKE',
    batchSizeRecords: 190000,
    maxParallelTasks: 10,
    slaThresholdMinutes: 39,
    retryPolicy: { maxRetries: 3, backoffExponentialFactor: 2.0, initialDelaySeconds: 30 },
    validationAssertionsCount: 10,
    lineageTrackedColumns: ['record_id', 'source_timestamp', 'payload_hash', 'cleared_amount', 'tenant_id']
  },
  {
    dagId: 'DAG-SEC-115',
    pipelineName: 'CybersecuritySIEMLogParser Production Workflow #115',
    domain: 'CybersecuritySIEMLogParser',
    category: 'Sigma rule evaluation',
    cronSchedule: '55 19 * * *',
    sourceProtocol: 'ICEBERG',
    sinkProtocol: 'BIGQUERY',
    batchSizeRecords: 200000,
    maxParallelTasks: 11,
    slaThresholdMinutes: 40,
    retryPolicy: { maxRetries: 3, backoffExponentialFactor: 2.0, initialDelaySeconds: 30 },
    validationAssertionsCount: 11,
    lineageTrackedColumns: ['record_id', 'source_timestamp', 'payload_hash', 'cleared_amount', 'tenant_id']
  },
  {
    dagId: 'DAG-SEC-116',
    pipelineName: 'CybersecuritySIEMLogParser Production Workflow #116',
    domain: 'CybersecuritySIEMLogParser',
    category: 'and incident response event routing',
    cronSchedule: '56 20 * * *',
    sourceProtocol: 'POSTGRES',
    sinkProtocol: 'SNOWFLAKE',
    batchSizeRecords: 210000,
    maxParallelTasks: 12,
    slaThresholdMinutes: 41,
    retryPolicy: { maxRetries: 3, backoffExponentialFactor: 2.0, initialDelaySeconds: 30 },
    validationAssertionsCount: 12,
    lineageTrackedColumns: ['record_id', 'source_timestamp', 'payload_hash', 'cleared_amount', 'tenant_id']
  },
  {
    dagId: 'DAG-SEC-117',
    pipelineName: 'CybersecuritySIEMLogParser Production Workflow #117',
    domain: 'CybersecuritySIEMLogParser',
    category: 'Distributed firewall and auth log parsing',
    cronSchedule: '57 21 * * *',
    sourceProtocol: 'KAFKA',
    sinkProtocol: 'BIGQUERY',
    batchSizeRecords: 220000,
    maxParallelTasks: 13,
    slaThresholdMinutes: 42,
    retryPolicy: { maxRetries: 3, backoffExponentialFactor: 2.0, initialDelaySeconds: 30 },
    validationAssertionsCount: 13,
    lineageTrackedColumns: ['record_id', 'source_timestamp', 'payload_hash', 'cleared_amount', 'tenant_id']
  },
  {
    dagId: 'DAG-SEC-118',
    pipelineName: 'CybersecuritySIEMLogParser Production Workflow #118',
    domain: 'CybersecuritySIEMLogParser',
    category: 'Sigma rule evaluation',
    cronSchedule: '58 22 * * *',
    sourceProtocol: 'SNOWFLAKE',
    sinkProtocol: 'SNOWFLAKE',
    batchSizeRecords: 230000,
    maxParallelTasks: 14,
    slaThresholdMinutes: 43,
    retryPolicy: { maxRetries: 3, backoffExponentialFactor: 2.0, initialDelaySeconds: 30 },
    validationAssertionsCount: 14,
    lineageTrackedColumns: ['record_id', 'source_timestamp', 'payload_hash', 'cleared_amount', 'tenant_id']
  },
  {
    dagId: 'DAG-SEC-119',
    pipelineName: 'CybersecuritySIEMLogParser Production Workflow #119',
    domain: 'CybersecuritySIEMLogParser',
    category: 'and incident response event routing',
    cronSchedule: '59 23 * * *',
    sourceProtocol: 'ICEBERG',
    sinkProtocol: 'BIGQUERY',
    batchSizeRecords: 240000,
    maxParallelTasks: 15,
    slaThresholdMinutes: 44,
    retryPolicy: { maxRetries: 3, backoffExponentialFactor: 2.0, initialDelaySeconds: 30 },
    validationAssertionsCount: 15,
    lineageTrackedColumns: ['record_id', 'source_timestamp', 'payload_hash', 'cleared_amount', 'tenant_id']
  },
  {
    dagId: 'DAG-SEC-120',
    pipelineName: 'CybersecuritySIEMLogParser Production Workflow #120',
    domain: 'CybersecuritySIEMLogParser',
    category: 'Distributed firewall and auth log parsing',
    cronSchedule: '0 0 * * *',
    sourceProtocol: 'POSTGRES',
    sinkProtocol: 'SNOWFLAKE',
    batchSizeRecords: 50000,
    maxParallelTasks: 4,
    slaThresholdMinutes: 45,
    retryPolicy: { maxRetries: 3, backoffExponentialFactor: 2.0, initialDelaySeconds: 30 },
    validationAssertionsCount: 16,
    lineageTrackedColumns: ['record_id', 'source_timestamp', 'payload_hash', 'cleared_amount', 'tenant_id']
  },
  {
    dagId: 'DAG-SEC-121',
    pipelineName: 'CybersecuritySIEMLogParser Production Workflow #121',
    domain: 'CybersecuritySIEMLogParser',
    category: 'Sigma rule evaluation',
    cronSchedule: '1 1 * * *',
    sourceProtocol: 'ICEBERG',
    sinkProtocol: 'BIGQUERY',
    batchSizeRecords: 60000,
    maxParallelTasks: 5,
    slaThresholdMinutes: 46,
    retryPolicy: { maxRetries: 3, backoffExponentialFactor: 2.0, initialDelaySeconds: 30 },
    validationAssertionsCount: 17,
    lineageTrackedColumns: ['record_id', 'source_timestamp', 'payload_hash', 'cleared_amount', 'tenant_id']
  },
  {
    dagId: 'DAG-SEC-122',
    pipelineName: 'CybersecuritySIEMLogParser Production Workflow #122',
    domain: 'CybersecuritySIEMLogParser',
    category: 'and incident response event routing',
    cronSchedule: '2 2 * * *',
    sourceProtocol: 'SNOWFLAKE',
    sinkProtocol: 'SNOWFLAKE',
    batchSizeRecords: 70000,
    maxParallelTasks: 6,
    slaThresholdMinutes: 47,
    retryPolicy: { maxRetries: 3, backoffExponentialFactor: 2.0, initialDelaySeconds: 30 },
    validationAssertionsCount: 18,
    lineageTrackedColumns: ['record_id', 'source_timestamp', 'payload_hash', 'cleared_amount', 'tenant_id']
  },
  {
    dagId: 'DAG-SEC-123',
    pipelineName: 'CybersecuritySIEMLogParser Production Workflow #123',
    domain: 'CybersecuritySIEMLogParser',
    category: 'Distributed firewall and auth log parsing',
    cronSchedule: '3 3 * * *',
    sourceProtocol: 'KAFKA',
    sinkProtocol: 'BIGQUERY',
    batchSizeRecords: 80000,
    maxParallelTasks: 7,
    slaThresholdMinutes: 48,
    retryPolicy: { maxRetries: 3, backoffExponentialFactor: 2.0, initialDelaySeconds: 30 },
    validationAssertionsCount: 19,
    lineageTrackedColumns: ['record_id', 'source_timestamp', 'payload_hash', 'cleared_amount', 'tenant_id']
  },
  {
    dagId: 'DAG-SEC-124',
    pipelineName: 'CybersecuritySIEMLogParser Production Workflow #124',
    domain: 'CybersecuritySIEMLogParser',
    category: 'Sigma rule evaluation',
    cronSchedule: '4 4 * * *',
    sourceProtocol: 'POSTGRES',
    sinkProtocol: 'SNOWFLAKE',
    batchSizeRecords: 90000,
    maxParallelTasks: 8,
    slaThresholdMinutes: 49,
    retryPolicy: { maxRetries: 3, backoffExponentialFactor: 2.0, initialDelaySeconds: 30 },
    validationAssertionsCount: 20,
    lineageTrackedColumns: ['record_id', 'source_timestamp', 'payload_hash', 'cleared_amount', 'tenant_id']
  },
  {
    dagId: 'DAG-SEC-125',
    pipelineName: 'CybersecuritySIEMLogParser Production Workflow #125',
    domain: 'CybersecuritySIEMLogParser',
    category: 'and incident response event routing',
    cronSchedule: '5 5 * * *',
    sourceProtocol: 'ICEBERG',
    sinkProtocol: 'BIGQUERY',
    batchSizeRecords: 100000,
    maxParallelTasks: 9,
    slaThresholdMinutes: 50,
    retryPolicy: { maxRetries: 3, backoffExponentialFactor: 2.0, initialDelaySeconds: 30 },
    validationAssertionsCount: 21,
    lineageTrackedColumns: ['record_id', 'source_timestamp', 'payload_hash', 'cleared_amount', 'tenant_id']
  },
  {
    dagId: 'DAG-SEC-126',
    pipelineName: 'CybersecuritySIEMLogParser Production Workflow #126',
    domain: 'CybersecuritySIEMLogParser',
    category: 'Distributed firewall and auth log parsing',
    cronSchedule: '6 6 * * *',
    sourceProtocol: 'KAFKA',
    sinkProtocol: 'SNOWFLAKE',
    batchSizeRecords: 110000,
    maxParallelTasks: 10,
    slaThresholdMinutes: 51,
    retryPolicy: { maxRetries: 3, backoffExponentialFactor: 2.0, initialDelaySeconds: 30 },
    validationAssertionsCount: 22,
    lineageTrackedColumns: ['record_id', 'source_timestamp', 'payload_hash', 'cleared_amount', 'tenant_id']
  },
  {
    dagId: 'DAG-SEC-127',
    pipelineName: 'CybersecuritySIEMLogParser Production Workflow #127',
    domain: 'CybersecuritySIEMLogParser',
    category: 'Sigma rule evaluation',
    cronSchedule: '7 7 * * *',
    sourceProtocol: 'ICEBERG',
    sinkProtocol: 'BIGQUERY',
    batchSizeRecords: 120000,
    maxParallelTasks: 11,
    slaThresholdMinutes: 52,
    retryPolicy: { maxRetries: 3, backoffExponentialFactor: 2.0, initialDelaySeconds: 30 },
    validationAssertionsCount: 23,
    lineageTrackedColumns: ['record_id', 'source_timestamp', 'payload_hash', 'cleared_amount', 'tenant_id']
  },
  {
    dagId: 'DAG-SEC-128',
    pipelineName: 'CybersecuritySIEMLogParser Production Workflow #128',
    domain: 'CybersecuritySIEMLogParser',
    category: 'and incident response event routing',
    cronSchedule: '8 8 * * *',
    sourceProtocol: 'POSTGRES',
    sinkProtocol: 'SNOWFLAKE',
    batchSizeRecords: 130000,
    maxParallelTasks: 12,
    slaThresholdMinutes: 53,
    retryPolicy: { maxRetries: 3, backoffExponentialFactor: 2.0, initialDelaySeconds: 30 },
    validationAssertionsCount: 8,
    lineageTrackedColumns: ['record_id', 'source_timestamp', 'payload_hash', 'cleared_amount', 'tenant_id']
  },
  {
    dagId: 'DAG-SEC-129',
    pipelineName: 'CybersecuritySIEMLogParser Production Workflow #129',
    domain: 'CybersecuritySIEMLogParser',
    category: 'Distributed firewall and auth log parsing',
    cronSchedule: '9 9 * * *',
    sourceProtocol: 'KAFKA',
    sinkProtocol: 'BIGQUERY',
    batchSizeRecords: 140000,
    maxParallelTasks: 13,
    slaThresholdMinutes: 54,
    retryPolicy: { maxRetries: 3, backoffExponentialFactor: 2.0, initialDelaySeconds: 30 },
    validationAssertionsCount: 9,
    lineageTrackedColumns: ['record_id', 'source_timestamp', 'payload_hash', 'cleared_amount', 'tenant_id']
  },
  {
    dagId: 'DAG-SEC-130',
    pipelineName: 'CybersecuritySIEMLogParser Production Workflow #130',
    domain: 'CybersecuritySIEMLogParser',
    category: 'Sigma rule evaluation',
    cronSchedule: '10 10 * * *',
    sourceProtocol: 'SNOWFLAKE',
    sinkProtocol: 'SNOWFLAKE',
    batchSizeRecords: 150000,
    maxParallelTasks: 14,
    slaThresholdMinutes: 55,
    retryPolicy: { maxRetries: 3, backoffExponentialFactor: 2.0, initialDelaySeconds: 30 },
    validationAssertionsCount: 10,
    lineageTrackedColumns: ['record_id', 'source_timestamp', 'payload_hash', 'cleared_amount', 'tenant_id']
  },
  {
    dagId: 'DAG-SEC-131',
    pipelineName: 'CybersecuritySIEMLogParser Production Workflow #131',
    domain: 'CybersecuritySIEMLogParser',
    category: 'and incident response event routing',
    cronSchedule: '11 11 * * *',
    sourceProtocol: 'ICEBERG',
    sinkProtocol: 'BIGQUERY',
    batchSizeRecords: 160000,
    maxParallelTasks: 15,
    slaThresholdMinutes: 56,
    retryPolicy: { maxRetries: 3, backoffExponentialFactor: 2.0, initialDelaySeconds: 30 },
    validationAssertionsCount: 11,
    lineageTrackedColumns: ['record_id', 'source_timestamp', 'payload_hash', 'cleared_amount', 'tenant_id']
  },
  {
    dagId: 'DAG-SEC-132',
    pipelineName: 'CybersecuritySIEMLogParser Production Workflow #132',
    domain: 'CybersecuritySIEMLogParser',
    category: 'Distributed firewall and auth log parsing',
    cronSchedule: '12 12 * * *',
    sourceProtocol: 'POSTGRES',
    sinkProtocol: 'SNOWFLAKE',
    batchSizeRecords: 170000,
    maxParallelTasks: 4,
    slaThresholdMinutes: 57,
    retryPolicy: { maxRetries: 3, backoffExponentialFactor: 2.0, initialDelaySeconds: 30 },
    validationAssertionsCount: 12,
    lineageTrackedColumns: ['record_id', 'source_timestamp', 'payload_hash', 'cleared_amount', 'tenant_id']
  },
  {
    dagId: 'DAG-SEC-133',
    pipelineName: 'CybersecuritySIEMLogParser Production Workflow #133',
    domain: 'CybersecuritySIEMLogParser',
    category: 'Sigma rule evaluation',
    cronSchedule: '13 13 * * *',
    sourceProtocol: 'ICEBERG',
    sinkProtocol: 'BIGQUERY',
    batchSizeRecords: 180000,
    maxParallelTasks: 5,
    slaThresholdMinutes: 58,
    retryPolicy: { maxRetries: 3, backoffExponentialFactor: 2.0, initialDelaySeconds: 30 },
    validationAssertionsCount: 13,
    lineageTrackedColumns: ['record_id', 'source_timestamp', 'payload_hash', 'cleared_amount', 'tenant_id']
  },
  {
    dagId: 'DAG-SEC-134',
    pipelineName: 'CybersecuritySIEMLogParser Production Workflow #134',
    domain: 'CybersecuritySIEMLogParser',
    category: 'and incident response event routing',
    cronSchedule: '14 14 * * *',
    sourceProtocol: 'SNOWFLAKE',
    sinkProtocol: 'SNOWFLAKE',
    batchSizeRecords: 190000,
    maxParallelTasks: 6,
    slaThresholdMinutes: 59,
    retryPolicy: { maxRetries: 3, backoffExponentialFactor: 2.0, initialDelaySeconds: 30 },
    validationAssertionsCount: 14,
    lineageTrackedColumns: ['record_id', 'source_timestamp', 'payload_hash', 'cleared_amount', 'tenant_id']
  },
  {
    dagId: 'DAG-SEC-135',
    pipelineName: 'CybersecuritySIEMLogParser Production Workflow #135',
    domain: 'CybersecuritySIEMLogParser',
    category: 'Distributed firewall and auth log parsing',
    cronSchedule: '15 15 * * *',
    sourceProtocol: 'KAFKA',
    sinkProtocol: 'BIGQUERY',
    batchSizeRecords: 200000,
    maxParallelTasks: 7,
    slaThresholdMinutes: 15,
    retryPolicy: { maxRetries: 3, backoffExponentialFactor: 2.0, initialDelaySeconds: 30 },
    validationAssertionsCount: 15,
    lineageTrackedColumns: ['record_id', 'source_timestamp', 'payload_hash', 'cleared_amount', 'tenant_id']
  },
  {
    dagId: 'DAG-SEC-136',
    pipelineName: 'CybersecuritySIEMLogParser Production Workflow #136',
    domain: 'CybersecuritySIEMLogParser',
    category: 'Sigma rule evaluation',
    cronSchedule: '16 16 * * *',
    sourceProtocol: 'POSTGRES',
    sinkProtocol: 'SNOWFLAKE',
    batchSizeRecords: 210000,
    maxParallelTasks: 8,
    slaThresholdMinutes: 16,
    retryPolicy: { maxRetries: 3, backoffExponentialFactor: 2.0, initialDelaySeconds: 30 },
    validationAssertionsCount: 16,
    lineageTrackedColumns: ['record_id', 'source_timestamp', 'payload_hash', 'cleared_amount', 'tenant_id']
  },
  {
    dagId: 'DAG-SEC-137',
    pipelineName: 'CybersecuritySIEMLogParser Production Workflow #137',
    domain: 'CybersecuritySIEMLogParser',
    category: 'and incident response event routing',
    cronSchedule: '17 17 * * *',
    sourceProtocol: 'ICEBERG',
    sinkProtocol: 'BIGQUERY',
    batchSizeRecords: 220000,
    maxParallelTasks: 9,
    slaThresholdMinutes: 17,
    retryPolicy: { maxRetries: 3, backoffExponentialFactor: 2.0, initialDelaySeconds: 30 },
    validationAssertionsCount: 17,
    lineageTrackedColumns: ['record_id', 'source_timestamp', 'payload_hash', 'cleared_amount', 'tenant_id']
  },
  {
    dagId: 'DAG-SEC-138',
    pipelineName: 'CybersecuritySIEMLogParser Production Workflow #138',
    domain: 'CybersecuritySIEMLogParser',
    category: 'Distributed firewall and auth log parsing',
    cronSchedule: '18 18 * * *',
    sourceProtocol: 'KAFKA',
    sinkProtocol: 'SNOWFLAKE',
    batchSizeRecords: 230000,
    maxParallelTasks: 10,
    slaThresholdMinutes: 18,
    retryPolicy: { maxRetries: 3, backoffExponentialFactor: 2.0, initialDelaySeconds: 30 },
    validationAssertionsCount: 18,
    lineageTrackedColumns: ['record_id', 'source_timestamp', 'payload_hash', 'cleared_amount', 'tenant_id']
  },
  {
    dagId: 'DAG-SEC-139',
    pipelineName: 'CybersecuritySIEMLogParser Production Workflow #139',
    domain: 'CybersecuritySIEMLogParser',
    category: 'Sigma rule evaluation',
    cronSchedule: '19 19 * * *',
    sourceProtocol: 'ICEBERG',
    sinkProtocol: 'BIGQUERY',
    batchSizeRecords: 240000,
    maxParallelTasks: 11,
    slaThresholdMinutes: 19,
    retryPolicy: { maxRetries: 3, backoffExponentialFactor: 2.0, initialDelaySeconds: 30 },
    validationAssertionsCount: 19,
    lineageTrackedColumns: ['record_id', 'source_timestamp', 'payload_hash', 'cleared_amount', 'tenant_id']
  },
  {
    dagId: 'DAG-SEC-140',
    pipelineName: 'CybersecuritySIEMLogParser Production Workflow #140',
    domain: 'CybersecuritySIEMLogParser',
    category: 'and incident response event routing',
    cronSchedule: '20 20 * * *',
    sourceProtocol: 'POSTGRES',
    sinkProtocol: 'SNOWFLAKE',
    batchSizeRecords: 50000,
    maxParallelTasks: 12,
    slaThresholdMinutes: 20,
    retryPolicy: { maxRetries: 3, backoffExponentialFactor: 2.0, initialDelaySeconds: 30 },
    validationAssertionsCount: 20,
    lineageTrackedColumns: ['record_id', 'source_timestamp', 'payload_hash', 'cleared_amount', 'tenant_id']
  },
  {
    dagId: 'DAG-SEC-141',
    pipelineName: 'CybersecuritySIEMLogParser Production Workflow #141',
    domain: 'CybersecuritySIEMLogParser',
    category: 'Distributed firewall and auth log parsing',
    cronSchedule: '21 21 * * *',
    sourceProtocol: 'KAFKA',
    sinkProtocol: 'BIGQUERY',
    batchSizeRecords: 60000,
    maxParallelTasks: 13,
    slaThresholdMinutes: 21,
    retryPolicy: { maxRetries: 3, backoffExponentialFactor: 2.0, initialDelaySeconds: 30 },
    validationAssertionsCount: 21,
    lineageTrackedColumns: ['record_id', 'source_timestamp', 'payload_hash', 'cleared_amount', 'tenant_id']
  },
  {
    dagId: 'DAG-SEC-142',
    pipelineName: 'CybersecuritySIEMLogParser Production Workflow #142',
    domain: 'CybersecuritySIEMLogParser',
    category: 'Sigma rule evaluation',
    cronSchedule: '22 22 * * *',
    sourceProtocol: 'SNOWFLAKE',
    sinkProtocol: 'SNOWFLAKE',
    batchSizeRecords: 70000,
    maxParallelTasks: 14,
    slaThresholdMinutes: 22,
    retryPolicy: { maxRetries: 3, backoffExponentialFactor: 2.0, initialDelaySeconds: 30 },
    validationAssertionsCount: 22,
    lineageTrackedColumns: ['record_id', 'source_timestamp', 'payload_hash', 'cleared_amount', 'tenant_id']
  },
  {
    dagId: 'DAG-SEC-143',
    pipelineName: 'CybersecuritySIEMLogParser Production Workflow #143',
    domain: 'CybersecuritySIEMLogParser',
    category: 'and incident response event routing',
    cronSchedule: '23 23 * * *',
    sourceProtocol: 'ICEBERG',
    sinkProtocol: 'BIGQUERY',
    batchSizeRecords: 80000,
    maxParallelTasks: 15,
    slaThresholdMinutes: 23,
    retryPolicy: { maxRetries: 3, backoffExponentialFactor: 2.0, initialDelaySeconds: 30 },
    validationAssertionsCount: 23,
    lineageTrackedColumns: ['record_id', 'source_timestamp', 'payload_hash', 'cleared_amount', 'tenant_id']
  },
  {
    dagId: 'DAG-SEC-144',
    pipelineName: 'CybersecuritySIEMLogParser Production Workflow #144',
    domain: 'CybersecuritySIEMLogParser',
    category: 'Distributed firewall and auth log parsing',
    cronSchedule: '24 0 * * *',
    sourceProtocol: 'POSTGRES',
    sinkProtocol: 'SNOWFLAKE',
    batchSizeRecords: 90000,
    maxParallelTasks: 4,
    slaThresholdMinutes: 24,
    retryPolicy: { maxRetries: 3, backoffExponentialFactor: 2.0, initialDelaySeconds: 30 },
    validationAssertionsCount: 8,
    lineageTrackedColumns: ['record_id', 'source_timestamp', 'payload_hash', 'cleared_amount', 'tenant_id']
  },
  {
    dagId: 'DAG-SEC-145',
    pipelineName: 'CybersecuritySIEMLogParser Production Workflow #145',
    domain: 'CybersecuritySIEMLogParser',
    category: 'Sigma rule evaluation',
    cronSchedule: '25 1 * * *',
    sourceProtocol: 'ICEBERG',
    sinkProtocol: 'BIGQUERY',
    batchSizeRecords: 100000,
    maxParallelTasks: 5,
    slaThresholdMinutes: 25,
    retryPolicy: { maxRetries: 3, backoffExponentialFactor: 2.0, initialDelaySeconds: 30 },
    validationAssertionsCount: 9,
    lineageTrackedColumns: ['record_id', 'source_timestamp', 'payload_hash', 'cleared_amount', 'tenant_id']
  },
  {
    dagId: 'DAG-SEC-146',
    pipelineName: 'CybersecuritySIEMLogParser Production Workflow #146',
    domain: 'CybersecuritySIEMLogParser',
    category: 'and incident response event routing',
    cronSchedule: '26 2 * * *',
    sourceProtocol: 'SNOWFLAKE',
    sinkProtocol: 'SNOWFLAKE',
    batchSizeRecords: 110000,
    maxParallelTasks: 6,
    slaThresholdMinutes: 26,
    retryPolicy: { maxRetries: 3, backoffExponentialFactor: 2.0, initialDelaySeconds: 30 },
    validationAssertionsCount: 10,
    lineageTrackedColumns: ['record_id', 'source_timestamp', 'payload_hash', 'cleared_amount', 'tenant_id']
  },
  {
    dagId: 'DAG-SEC-147',
    pipelineName: 'CybersecuritySIEMLogParser Production Workflow #147',
    domain: 'CybersecuritySIEMLogParser',
    category: 'Distributed firewall and auth log parsing',
    cronSchedule: '27 3 * * *',
    sourceProtocol: 'KAFKA',
    sinkProtocol: 'BIGQUERY',
    batchSizeRecords: 120000,
    maxParallelTasks: 7,
    slaThresholdMinutes: 27,
    retryPolicy: { maxRetries: 3, backoffExponentialFactor: 2.0, initialDelaySeconds: 30 },
    validationAssertionsCount: 11,
    lineageTrackedColumns: ['record_id', 'source_timestamp', 'payload_hash', 'cleared_amount', 'tenant_id']
  },
  {
    dagId: 'DAG-SEC-148',
    pipelineName: 'CybersecuritySIEMLogParser Production Workflow #148',
    domain: 'CybersecuritySIEMLogParser',
    category: 'Sigma rule evaluation',
    cronSchedule: '28 4 * * *',
    sourceProtocol: 'POSTGRES',
    sinkProtocol: 'SNOWFLAKE',
    batchSizeRecords: 130000,
    maxParallelTasks: 8,
    slaThresholdMinutes: 28,
    retryPolicy: { maxRetries: 3, backoffExponentialFactor: 2.0, initialDelaySeconds: 30 },
    validationAssertionsCount: 12,
    lineageTrackedColumns: ['record_id', 'source_timestamp', 'payload_hash', 'cleared_amount', 'tenant_id']
  },
  {
    dagId: 'DAG-SEC-149',
    pipelineName: 'CybersecuritySIEMLogParser Production Workflow #149',
    domain: 'CybersecuritySIEMLogParser',
    category: 'and incident response event routing',
    cronSchedule: '29 5 * * *',
    sourceProtocol: 'ICEBERG',
    sinkProtocol: 'BIGQUERY',
    batchSizeRecords: 140000,
    maxParallelTasks: 9,
    slaThresholdMinutes: 29,
    retryPolicy: { maxRetries: 3, backoffExponentialFactor: 2.0, initialDelaySeconds: 30 },
    validationAssertionsCount: 13,
    lineageTrackedColumns: ['record_id', 'source_timestamp', 'payload_hash', 'cleared_amount', 'tenant_id']
  },
  {
    dagId: 'DAG-SEC-150',
    pipelineName: 'CybersecuritySIEMLogParser Production Workflow #150',
    domain: 'CybersecuritySIEMLogParser',
    category: 'Distributed firewall and auth log parsing',
    cronSchedule: '30 6 * * *',
    sourceProtocol: 'KAFKA',
    sinkProtocol: 'SNOWFLAKE',
    batchSizeRecords: 150000,
    maxParallelTasks: 10,
    slaThresholdMinutes: 30,
    retryPolicy: { maxRetries: 3, backoffExponentialFactor: 2.0, initialDelaySeconds: 30 },
    validationAssertionsCount: 14,
    lineageTrackedColumns: ['record_id', 'source_timestamp', 'payload_hash', 'cleared_amount', 'tenant_id']
  }
];

export class SEC_PipelineCatalog {
  static search(query: string): EnterprisePipelineDAG[] {
    const q = query.toLowerCase().trim();
    if (!q) return PIPELINE_SEC_DATASET.slice(0, 20);
    return PIPELINE_SEC_DATASET.filter(p => p.pipelineName.toLowerCase().includes(q) || p.category.toLowerCase().includes(q));
  }
}
