/**
 * Enterprise Data Pipeline DAG Specification: IoTSensorTelemetryBatch
 * Domain Focus: Industrial SCADA sensor timeseries ingestion, rolling statistical anomaly detection, and predictive maintenance metrics
 * Standard: DataFlow OS Orchestration Engine
 */

export interface EnterprisePipelineDAG {
  dagId: string;
  pipelineName: string;
  domain: string;
  category: string;
  cronSchedule: string;
  sourceProtocol: string;
  sinkProtocol: string;
  batchSizeRecords: number;
  maxParallelTasks: number;
  slaThresholdMinutes: number;
  retryPolicy: { maxRetries: number; backoffExponentialFactor: number; initialDelaySeconds: number };
  validationAssertionsCount: number;
  lineageTrackedColumns: string[];
}

export const PIPELINE_IOT_DATASET: EnterprisePipelineDAG[] = [
  {
    dagId: 'DAG-IOT-001',
    pipelineName: 'IoTSensorTelemetryBatch Production Workflow #1',
    domain: 'IoTSensorTelemetryBatch',
    category: 'rolling statistical anomaly detection',
    cronSchedule: '1 1 * * *',
    sourceProtocol: 'ICEBERG',
    sinkProtocol: 'BIGQUERY',
    batchSizeRecords: 60000,
    maxParallelTasks: 5,
    slaThresholdMinutes: 16,
    retryPolicy: { maxRetries: 3, backoffExponentialFactor: 2.0, initialDelaySeconds: 30 },
    validationAssertionsCount: 9,
    lineageTrackedColumns: ['record_id', 'source_timestamp', 'payload_hash', 'cleared_amount', 'tenant_id']
  },
  {
    dagId: 'DAG-IOT-002',
    pipelineName: 'IoTSensorTelemetryBatch Production Workflow #2',
    domain: 'IoTSensorTelemetryBatch',
    category: 'and predictive maintenance metrics',
    cronSchedule: '2 2 * * *',
    sourceProtocol: 'SNOWFLAKE',
    sinkProtocol: 'SNOWFLAKE',
    batchSizeRecords: 70000,
    maxParallelTasks: 6,
    slaThresholdMinutes: 17,
    retryPolicy: { maxRetries: 3, backoffExponentialFactor: 2.0, initialDelaySeconds: 30 },
    validationAssertionsCount: 10,
    lineageTrackedColumns: ['record_id', 'source_timestamp', 'payload_hash', 'cleared_amount', 'tenant_id']
  },
  {
    dagId: 'DAG-IOT-003',
    pipelineName: 'IoTSensorTelemetryBatch Production Workflow #3',
    domain: 'IoTSensorTelemetryBatch',
    category: 'Industrial SCADA sensor timeseries ingestion',
    cronSchedule: '3 3 * * *',
    sourceProtocol: 'KAFKA',
    sinkProtocol: 'BIGQUERY',
    batchSizeRecords: 80000,
    maxParallelTasks: 7,
    slaThresholdMinutes: 18,
    retryPolicy: { maxRetries: 3, backoffExponentialFactor: 2.0, initialDelaySeconds: 30 },
    validationAssertionsCount: 11,
    lineageTrackedColumns: ['record_id', 'source_timestamp', 'payload_hash', 'cleared_amount', 'tenant_id']
  },
  {
    dagId: 'DAG-IOT-004',
    pipelineName: 'IoTSensorTelemetryBatch Production Workflow #4',
    domain: 'IoTSensorTelemetryBatch',
    category: 'rolling statistical anomaly detection',
    cronSchedule: '4 4 * * *',
    sourceProtocol: 'POSTGRES',
    sinkProtocol: 'SNOWFLAKE',
    batchSizeRecords: 90000,
    maxParallelTasks: 8,
    slaThresholdMinutes: 19,
    retryPolicy: { maxRetries: 3, backoffExponentialFactor: 2.0, initialDelaySeconds: 30 },
    validationAssertionsCount: 12,
    lineageTrackedColumns: ['record_id', 'source_timestamp', 'payload_hash', 'cleared_amount', 'tenant_id']
  },
  {
    dagId: 'DAG-IOT-005',
    pipelineName: 'IoTSensorTelemetryBatch Production Workflow #5',
    domain: 'IoTSensorTelemetryBatch',
    category: 'and predictive maintenance metrics',
    cronSchedule: '5 5 * * *',
    sourceProtocol: 'ICEBERG',
    sinkProtocol: 'BIGQUERY',
    batchSizeRecords: 100000,
    maxParallelTasks: 9,
    slaThresholdMinutes: 20,
    retryPolicy: { maxRetries: 3, backoffExponentialFactor: 2.0, initialDelaySeconds: 30 },
    validationAssertionsCount: 13,
    lineageTrackedColumns: ['record_id', 'source_timestamp', 'payload_hash', 'cleared_amount', 'tenant_id']
  },
  {
    dagId: 'DAG-IOT-006',
    pipelineName: 'IoTSensorTelemetryBatch Production Workflow #6',
    domain: 'IoTSensorTelemetryBatch',
    category: 'Industrial SCADA sensor timeseries ingestion',
    cronSchedule: '6 6 * * *',
    sourceProtocol: 'KAFKA',
    sinkProtocol: 'SNOWFLAKE',
    batchSizeRecords: 110000,
    maxParallelTasks: 10,
    slaThresholdMinutes: 21,
    retryPolicy: { maxRetries: 3, backoffExponentialFactor: 2.0, initialDelaySeconds: 30 },
    validationAssertionsCount: 14,
    lineageTrackedColumns: ['record_id', 'source_timestamp', 'payload_hash', 'cleared_amount', 'tenant_id']
  },
  {
    dagId: 'DAG-IOT-007',
    pipelineName: 'IoTSensorTelemetryBatch Production Workflow #7',
    domain: 'IoTSensorTelemetryBatch',
    category: 'rolling statistical anomaly detection',
    cronSchedule: '7 7 * * *',
    sourceProtocol: 'ICEBERG',
    sinkProtocol: 'BIGQUERY',
    batchSizeRecords: 120000,
    maxParallelTasks: 11,
    slaThresholdMinutes: 22,
    retryPolicy: { maxRetries: 3, backoffExponentialFactor: 2.0, initialDelaySeconds: 30 },
    validationAssertionsCount: 15,
    lineageTrackedColumns: ['record_id', 'source_timestamp', 'payload_hash', 'cleared_amount', 'tenant_id']
  },
  {
    dagId: 'DAG-IOT-008',
    pipelineName: 'IoTSensorTelemetryBatch Production Workflow #8',
    domain: 'IoTSensorTelemetryBatch',
    category: 'and predictive maintenance metrics',
    cronSchedule: '8 8 * * *',
    sourceProtocol: 'POSTGRES',
    sinkProtocol: 'SNOWFLAKE',
    batchSizeRecords: 130000,
    maxParallelTasks: 12,
    slaThresholdMinutes: 23,
    retryPolicy: { maxRetries: 3, backoffExponentialFactor: 2.0, initialDelaySeconds: 30 },
    validationAssertionsCount: 16,
    lineageTrackedColumns: ['record_id', 'source_timestamp', 'payload_hash', 'cleared_amount', 'tenant_id']
  },
  {
    dagId: 'DAG-IOT-009',
    pipelineName: 'IoTSensorTelemetryBatch Production Workflow #9',
    domain: 'IoTSensorTelemetryBatch',
    category: 'Industrial SCADA sensor timeseries ingestion',
    cronSchedule: '9 9 * * *',
    sourceProtocol: 'KAFKA',
    sinkProtocol: 'BIGQUERY',
    batchSizeRecords: 140000,
    maxParallelTasks: 13,
    slaThresholdMinutes: 24,
    retryPolicy: { maxRetries: 3, backoffExponentialFactor: 2.0, initialDelaySeconds: 30 },
    validationAssertionsCount: 17,
    lineageTrackedColumns: ['record_id', 'source_timestamp', 'payload_hash', 'cleared_amount', 'tenant_id']
  },
  {
    dagId: 'DAG-IOT-010',
    pipelineName: 'IoTSensorTelemetryBatch Production Workflow #10',
    domain: 'IoTSensorTelemetryBatch',
    category: 'rolling statistical anomaly detection',
    cronSchedule: '10 10 * * *',
    sourceProtocol: 'SNOWFLAKE',
    sinkProtocol: 'SNOWFLAKE',
    batchSizeRecords: 150000,
    maxParallelTasks: 14,
    slaThresholdMinutes: 25,
    retryPolicy: { maxRetries: 3, backoffExponentialFactor: 2.0, initialDelaySeconds: 30 },
    validationAssertionsCount: 18,
    lineageTrackedColumns: ['record_id', 'source_timestamp', 'payload_hash', 'cleared_amount', 'tenant_id']
  },
  {
    dagId: 'DAG-IOT-011',
    pipelineName: 'IoTSensorTelemetryBatch Production Workflow #11',
    domain: 'IoTSensorTelemetryBatch',
    category: 'and predictive maintenance metrics',
    cronSchedule: '11 11 * * *',
    sourceProtocol: 'ICEBERG',
    sinkProtocol: 'BIGQUERY',
    batchSizeRecords: 160000,
    maxParallelTasks: 15,
    slaThresholdMinutes: 26,
    retryPolicy: { maxRetries: 3, backoffExponentialFactor: 2.0, initialDelaySeconds: 30 },
    validationAssertionsCount: 19,
    lineageTrackedColumns: ['record_id', 'source_timestamp', 'payload_hash', 'cleared_amount', 'tenant_id']
  },
  {
    dagId: 'DAG-IOT-012',
    pipelineName: 'IoTSensorTelemetryBatch Production Workflow #12',
    domain: 'IoTSensorTelemetryBatch',
    category: 'Industrial SCADA sensor timeseries ingestion',
    cronSchedule: '12 12 * * *',
    sourceProtocol: 'POSTGRES',
    sinkProtocol: 'SNOWFLAKE',
    batchSizeRecords: 170000,
    maxParallelTasks: 4,
    slaThresholdMinutes: 27,
    retryPolicy: { maxRetries: 3, backoffExponentialFactor: 2.0, initialDelaySeconds: 30 },
    validationAssertionsCount: 20,
    lineageTrackedColumns: ['record_id', 'source_timestamp', 'payload_hash', 'cleared_amount', 'tenant_id']
  },
  {
    dagId: 'DAG-IOT-013',
    pipelineName: 'IoTSensorTelemetryBatch Production Workflow #13',
    domain: 'IoTSensorTelemetryBatch',
    category: 'rolling statistical anomaly detection',
    cronSchedule: '13 13 * * *',
    sourceProtocol: 'ICEBERG',
    sinkProtocol: 'BIGQUERY',
    batchSizeRecords: 180000,
    maxParallelTasks: 5,
    slaThresholdMinutes: 28,
    retryPolicy: { maxRetries: 3, backoffExponentialFactor: 2.0, initialDelaySeconds: 30 },
    validationAssertionsCount: 21,
    lineageTrackedColumns: ['record_id', 'source_timestamp', 'payload_hash', 'cleared_amount', 'tenant_id']
  },
  {
    dagId: 'DAG-IOT-014',
    pipelineName: 'IoTSensorTelemetryBatch Production Workflow #14',
    domain: 'IoTSensorTelemetryBatch',
    category: 'and predictive maintenance metrics',
    cronSchedule: '14 14 * * *',
    sourceProtocol: 'SNOWFLAKE',
    sinkProtocol: 'SNOWFLAKE',
    batchSizeRecords: 190000,
    maxParallelTasks: 6,
    slaThresholdMinutes: 29,
    retryPolicy: { maxRetries: 3, backoffExponentialFactor: 2.0, initialDelaySeconds: 30 },
    validationAssertionsCount: 22,
    lineageTrackedColumns: ['record_id', 'source_timestamp', 'payload_hash', 'cleared_amount', 'tenant_id']
  },
  {
    dagId: 'DAG-IOT-015',
    pipelineName: 'IoTSensorTelemetryBatch Production Workflow #15',
    domain: 'IoTSensorTelemetryBatch',
    category: 'Industrial SCADA sensor timeseries ingestion',
    cronSchedule: '15 15 * * *',
    sourceProtocol: 'KAFKA',
    sinkProtocol: 'BIGQUERY',
    batchSizeRecords: 200000,
    maxParallelTasks: 7,
    slaThresholdMinutes: 30,
    retryPolicy: { maxRetries: 3, backoffExponentialFactor: 2.0, initialDelaySeconds: 30 },
    validationAssertionsCount: 23,
    lineageTrackedColumns: ['record_id', 'source_timestamp', 'payload_hash', 'cleared_amount', 'tenant_id']
  },
  {
    dagId: 'DAG-IOT-016',
    pipelineName: 'IoTSensorTelemetryBatch Production Workflow #16',
    domain: 'IoTSensorTelemetryBatch',
    category: 'rolling statistical anomaly detection',
    cronSchedule: '16 16 * * *',
    sourceProtocol: 'POSTGRES',
    sinkProtocol: 'SNOWFLAKE',
    batchSizeRecords: 210000,
    maxParallelTasks: 8,
    slaThresholdMinutes: 31,
    retryPolicy: { maxRetries: 3, backoffExponentialFactor: 2.0, initialDelaySeconds: 30 },
    validationAssertionsCount: 8,
    lineageTrackedColumns: ['record_id', 'source_timestamp', 'payload_hash', 'cleared_amount', 'tenant_id']
  },
  {
    dagId: 'DAG-IOT-017',
    pipelineName: 'IoTSensorTelemetryBatch Production Workflow #17',
    domain: 'IoTSensorTelemetryBatch',
    category: 'and predictive maintenance metrics',
    cronSchedule: '17 17 * * *',
    sourceProtocol: 'ICEBERG',
    sinkProtocol: 'BIGQUERY',
    batchSizeRecords: 220000,
    maxParallelTasks: 9,
    slaThresholdMinutes: 32,
    retryPolicy: { maxRetries: 3, backoffExponentialFactor: 2.0, initialDelaySeconds: 30 },
    validationAssertionsCount: 9,
    lineageTrackedColumns: ['record_id', 'source_timestamp', 'payload_hash', 'cleared_amount', 'tenant_id']
  },
  {
    dagId: 'DAG-IOT-018',
    pipelineName: 'IoTSensorTelemetryBatch Production Workflow #18',
    domain: 'IoTSensorTelemetryBatch',
    category: 'Industrial SCADA sensor timeseries ingestion',
    cronSchedule: '18 18 * * *',
    sourceProtocol: 'KAFKA',
    sinkProtocol: 'SNOWFLAKE',
    batchSizeRecords: 230000,
    maxParallelTasks: 10,
    slaThresholdMinutes: 33,
    retryPolicy: { maxRetries: 3, backoffExponentialFactor: 2.0, initialDelaySeconds: 30 },
    validationAssertionsCount: 10,
    lineageTrackedColumns: ['record_id', 'source_timestamp', 'payload_hash', 'cleared_amount', 'tenant_id']
  },
  {
    dagId: 'DAG-IOT-019',
    pipelineName: 'IoTSensorTelemetryBatch Production Workflow #19',
    domain: 'IoTSensorTelemetryBatch',
    category: 'rolling statistical anomaly detection',
    cronSchedule: '19 19 * * *',
    sourceProtocol: 'ICEBERG',
    sinkProtocol: 'BIGQUERY',
    batchSizeRecords: 240000,
    maxParallelTasks: 11,
    slaThresholdMinutes: 34,
    retryPolicy: { maxRetries: 3, backoffExponentialFactor: 2.0, initialDelaySeconds: 30 },
    validationAssertionsCount: 11,
    lineageTrackedColumns: ['record_id', 'source_timestamp', 'payload_hash', 'cleared_amount', 'tenant_id']
  },
  {
    dagId: 'DAG-IOT-020',
    pipelineName: 'IoTSensorTelemetryBatch Production Workflow #20',
    domain: 'IoTSensorTelemetryBatch',
    category: 'and predictive maintenance metrics',
    cronSchedule: '20 20 * * *',
    sourceProtocol: 'POSTGRES',
    sinkProtocol: 'SNOWFLAKE',
    batchSizeRecords: 50000,
    maxParallelTasks: 12,
    slaThresholdMinutes: 35,
    retryPolicy: { maxRetries: 3, backoffExponentialFactor: 2.0, initialDelaySeconds: 30 },
    validationAssertionsCount: 12,
    lineageTrackedColumns: ['record_id', 'source_timestamp', 'payload_hash', 'cleared_amount', 'tenant_id']
  },
  {
    dagId: 'DAG-IOT-021',
    pipelineName: 'IoTSensorTelemetryBatch Production Workflow #21',
    domain: 'IoTSensorTelemetryBatch',
    category: 'Industrial SCADA sensor timeseries ingestion',
    cronSchedule: '21 21 * * *',
    sourceProtocol: 'KAFKA',
    sinkProtocol: 'BIGQUERY',
    batchSizeRecords: 60000,
    maxParallelTasks: 13,
    slaThresholdMinutes: 36,
    retryPolicy: { maxRetries: 3, backoffExponentialFactor: 2.0, initialDelaySeconds: 30 },
    validationAssertionsCount: 13,
    lineageTrackedColumns: ['record_id', 'source_timestamp', 'payload_hash', 'cleared_amount', 'tenant_id']
  },
  {
    dagId: 'DAG-IOT-022',
    pipelineName: 'IoTSensorTelemetryBatch Production Workflow #22',
    domain: 'IoTSensorTelemetryBatch',
    category: 'rolling statistical anomaly detection',
    cronSchedule: '22 22 * * *',
    sourceProtocol: 'SNOWFLAKE',
    sinkProtocol: 'SNOWFLAKE',
    batchSizeRecords: 70000,
    maxParallelTasks: 14,
    slaThresholdMinutes: 37,
    retryPolicy: { maxRetries: 3, backoffExponentialFactor: 2.0, initialDelaySeconds: 30 },
    validationAssertionsCount: 14,
    lineageTrackedColumns: ['record_id', 'source_timestamp', 'payload_hash', 'cleared_amount', 'tenant_id']
  },
  {
    dagId: 'DAG-IOT-023',
    pipelineName: 'IoTSensorTelemetryBatch Production Workflow #23',
    domain: 'IoTSensorTelemetryBatch',
    category: 'and predictive maintenance metrics',
    cronSchedule: '23 23 * * *',
    sourceProtocol: 'ICEBERG',
    sinkProtocol: 'BIGQUERY',
    batchSizeRecords: 80000,
    maxParallelTasks: 15,
    slaThresholdMinutes: 38,
    retryPolicy: { maxRetries: 3, backoffExponentialFactor: 2.0, initialDelaySeconds: 30 },
    validationAssertionsCount: 15,
    lineageTrackedColumns: ['record_id', 'source_timestamp', 'payload_hash', 'cleared_amount', 'tenant_id']
  },
  {
    dagId: 'DAG-IOT-024',
    pipelineName: 'IoTSensorTelemetryBatch Production Workflow #24',
    domain: 'IoTSensorTelemetryBatch',
    category: 'Industrial SCADA sensor timeseries ingestion',
    cronSchedule: '24 0 * * *',
    sourceProtocol: 'POSTGRES',
    sinkProtocol: 'SNOWFLAKE',
    batchSizeRecords: 90000,
    maxParallelTasks: 4,
    slaThresholdMinutes: 39,
    retryPolicy: { maxRetries: 3, backoffExponentialFactor: 2.0, initialDelaySeconds: 30 },
    validationAssertionsCount: 16,
    lineageTrackedColumns: ['record_id', 'source_timestamp', 'payload_hash', 'cleared_amount', 'tenant_id']
  },
  {
    dagId: 'DAG-IOT-025',
    pipelineName: 'IoTSensorTelemetryBatch Production Workflow #25',
    domain: 'IoTSensorTelemetryBatch',
    category: 'rolling statistical anomaly detection',
    cronSchedule: '25 1 * * *',
    sourceProtocol: 'ICEBERG',
    sinkProtocol: 'BIGQUERY',
    batchSizeRecords: 100000,
    maxParallelTasks: 5,
    slaThresholdMinutes: 40,
    retryPolicy: { maxRetries: 3, backoffExponentialFactor: 2.0, initialDelaySeconds: 30 },
    validationAssertionsCount: 17,
    lineageTrackedColumns: ['record_id', 'source_timestamp', 'payload_hash', 'cleared_amount', 'tenant_id']
  },
  {
    dagId: 'DAG-IOT-026',
    pipelineName: 'IoTSensorTelemetryBatch Production Workflow #26',
    domain: 'IoTSensorTelemetryBatch',
    category: 'and predictive maintenance metrics',
    cronSchedule: '26 2 * * *',
    sourceProtocol: 'SNOWFLAKE',
    sinkProtocol: 'SNOWFLAKE',
    batchSizeRecords: 110000,
    maxParallelTasks: 6,
    slaThresholdMinutes: 41,
    retryPolicy: { maxRetries: 3, backoffExponentialFactor: 2.0, initialDelaySeconds: 30 },
    validationAssertionsCount: 18,
    lineageTrackedColumns: ['record_id', 'source_timestamp', 'payload_hash', 'cleared_amount', 'tenant_id']
  },
  {
    dagId: 'DAG-IOT-027',
    pipelineName: 'IoTSensorTelemetryBatch Production Workflow #27',
    domain: 'IoTSensorTelemetryBatch',
    category: 'Industrial SCADA sensor timeseries ingestion',
    cronSchedule: '27 3 * * *',
    sourceProtocol: 'KAFKA',
    sinkProtocol: 'BIGQUERY',
    batchSizeRecords: 120000,
    maxParallelTasks: 7,
    slaThresholdMinutes: 42,
    retryPolicy: { maxRetries: 3, backoffExponentialFactor: 2.0, initialDelaySeconds: 30 },
    validationAssertionsCount: 19,
    lineageTrackedColumns: ['record_id', 'source_timestamp', 'payload_hash', 'cleared_amount', 'tenant_id']
  },
  {
    dagId: 'DAG-IOT-028',
    pipelineName: 'IoTSensorTelemetryBatch Production Workflow #28',
    domain: 'IoTSensorTelemetryBatch',
    category: 'rolling statistical anomaly detection',
    cronSchedule: '28 4 * * *',
    sourceProtocol: 'POSTGRES',
    sinkProtocol: 'SNOWFLAKE',
    batchSizeRecords: 130000,
    maxParallelTasks: 8,
    slaThresholdMinutes: 43,
    retryPolicy: { maxRetries: 3, backoffExponentialFactor: 2.0, initialDelaySeconds: 30 },
    validationAssertionsCount: 20,
    lineageTrackedColumns: ['record_id', 'source_timestamp', 'payload_hash', 'cleared_amount', 'tenant_id']
  },
  {
    dagId: 'DAG-IOT-029',
    pipelineName: 'IoTSensorTelemetryBatch Production Workflow #29',
    domain: 'IoTSensorTelemetryBatch',
    category: 'and predictive maintenance metrics',
    cronSchedule: '29 5 * * *',
    sourceProtocol: 'ICEBERG',
    sinkProtocol: 'BIGQUERY',
    batchSizeRecords: 140000,
    maxParallelTasks: 9,
    slaThresholdMinutes: 44,
    retryPolicy: { maxRetries: 3, backoffExponentialFactor: 2.0, initialDelaySeconds: 30 },
    validationAssertionsCount: 21,
    lineageTrackedColumns: ['record_id', 'source_timestamp', 'payload_hash', 'cleared_amount', 'tenant_id']
  },
  {
    dagId: 'DAG-IOT-030',
    pipelineName: 'IoTSensorTelemetryBatch Production Workflow #30',
    domain: 'IoTSensorTelemetryBatch',
    category: 'Industrial SCADA sensor timeseries ingestion',
    cronSchedule: '30 6 * * *',
    sourceProtocol: 'KAFKA',
    sinkProtocol: 'SNOWFLAKE',
    batchSizeRecords: 150000,
    maxParallelTasks: 10,
    slaThresholdMinutes: 45,
    retryPolicy: { maxRetries: 3, backoffExponentialFactor: 2.0, initialDelaySeconds: 30 },
    validationAssertionsCount: 22,
    lineageTrackedColumns: ['record_id', 'source_timestamp', 'payload_hash', 'cleared_amount', 'tenant_id']
  },
  {
    dagId: 'DAG-IOT-031',
    pipelineName: 'IoTSensorTelemetryBatch Production Workflow #31',
    domain: 'IoTSensorTelemetryBatch',
    category: 'rolling statistical anomaly detection',
    cronSchedule: '31 7 * * *',
    sourceProtocol: 'ICEBERG',
    sinkProtocol: 'BIGQUERY',
    batchSizeRecords: 160000,
    maxParallelTasks: 11,
    slaThresholdMinutes: 46,
    retryPolicy: { maxRetries: 3, backoffExponentialFactor: 2.0, initialDelaySeconds: 30 },
    validationAssertionsCount: 23,
    lineageTrackedColumns: ['record_id', 'source_timestamp', 'payload_hash', 'cleared_amount', 'tenant_id']
  },
  {
    dagId: 'DAG-IOT-032',
    pipelineName: 'IoTSensorTelemetryBatch Production Workflow #32',
    domain: 'IoTSensorTelemetryBatch',
    category: 'and predictive maintenance metrics',
    cronSchedule: '32 8 * * *',
    sourceProtocol: 'POSTGRES',
    sinkProtocol: 'SNOWFLAKE',
    batchSizeRecords: 170000,
    maxParallelTasks: 12,
    slaThresholdMinutes: 47,
    retryPolicy: { maxRetries: 3, backoffExponentialFactor: 2.0, initialDelaySeconds: 30 },
    validationAssertionsCount: 8,
    lineageTrackedColumns: ['record_id', 'source_timestamp', 'payload_hash', 'cleared_amount', 'tenant_id']
  },
  {
    dagId: 'DAG-IOT-033',
    pipelineName: 'IoTSensorTelemetryBatch Production Workflow #33',
    domain: 'IoTSensorTelemetryBatch',
    category: 'Industrial SCADA sensor timeseries ingestion',
    cronSchedule: '33 9 * * *',
    sourceProtocol: 'KAFKA',
    sinkProtocol: 'BIGQUERY',
    batchSizeRecords: 180000,
    maxParallelTasks: 13,
    slaThresholdMinutes: 48,
    retryPolicy: { maxRetries: 3, backoffExponentialFactor: 2.0, initialDelaySeconds: 30 },
    validationAssertionsCount: 9,
    lineageTrackedColumns: ['record_id', 'source_timestamp', 'payload_hash', 'cleared_amount', 'tenant_id']
  },
  {
    dagId: 'DAG-IOT-034',
    pipelineName: 'IoTSensorTelemetryBatch Production Workflow #34',
    domain: 'IoTSensorTelemetryBatch',
    category: 'rolling statistical anomaly detection',
    cronSchedule: '34 10 * * *',
    sourceProtocol: 'SNOWFLAKE',
    sinkProtocol: 'SNOWFLAKE',
    batchSizeRecords: 190000,
    maxParallelTasks: 14,
    slaThresholdMinutes: 49,
    retryPolicy: { maxRetries: 3, backoffExponentialFactor: 2.0, initialDelaySeconds: 30 },
    validationAssertionsCount: 10,
    lineageTrackedColumns: ['record_id', 'source_timestamp', 'payload_hash', 'cleared_amount', 'tenant_id']
  },
  {
    dagId: 'DAG-IOT-035',
    pipelineName: 'IoTSensorTelemetryBatch Production Workflow #35',
    domain: 'IoTSensorTelemetryBatch',
    category: 'and predictive maintenance metrics',
    cronSchedule: '35 11 * * *',
    sourceProtocol: 'ICEBERG',
    sinkProtocol: 'BIGQUERY',
    batchSizeRecords: 200000,
    maxParallelTasks: 15,
    slaThresholdMinutes: 50,
    retryPolicy: { maxRetries: 3, backoffExponentialFactor: 2.0, initialDelaySeconds: 30 },
    validationAssertionsCount: 11,
    lineageTrackedColumns: ['record_id', 'source_timestamp', 'payload_hash', 'cleared_amount', 'tenant_id']
  },
  {
    dagId: 'DAG-IOT-036',
    pipelineName: 'IoTSensorTelemetryBatch Production Workflow #36',
    domain: 'IoTSensorTelemetryBatch',
    category: 'Industrial SCADA sensor timeseries ingestion',
    cronSchedule: '36 12 * * *',
    sourceProtocol: 'POSTGRES',
    sinkProtocol: 'SNOWFLAKE',
    batchSizeRecords: 210000,
    maxParallelTasks: 4,
    slaThresholdMinutes: 51,
    retryPolicy: { maxRetries: 3, backoffExponentialFactor: 2.0, initialDelaySeconds: 30 },
    validationAssertionsCount: 12,
    lineageTrackedColumns: ['record_id', 'source_timestamp', 'payload_hash', 'cleared_amount', 'tenant_id']
  },
  {
    dagId: 'DAG-IOT-037',
    pipelineName: 'IoTSensorTelemetryBatch Production Workflow #37',
    domain: 'IoTSensorTelemetryBatch',
    category: 'rolling statistical anomaly detection',
    cronSchedule: '37 13 * * *',
    sourceProtocol: 'ICEBERG',
    sinkProtocol: 'BIGQUERY',
    batchSizeRecords: 220000,
    maxParallelTasks: 5,
    slaThresholdMinutes: 52,
    retryPolicy: { maxRetries: 3, backoffExponentialFactor: 2.0, initialDelaySeconds: 30 },
    validationAssertionsCount: 13,
    lineageTrackedColumns: ['record_id', 'source_timestamp', 'payload_hash', 'cleared_amount', 'tenant_id']
  },
  {
    dagId: 'DAG-IOT-038',
    pipelineName: 'IoTSensorTelemetryBatch Production Workflow #38',
    domain: 'IoTSensorTelemetryBatch',
    category: 'and predictive maintenance metrics',
    cronSchedule: '38 14 * * *',
    sourceProtocol: 'SNOWFLAKE',
    sinkProtocol: 'SNOWFLAKE',
    batchSizeRecords: 230000,
    maxParallelTasks: 6,
    slaThresholdMinutes: 53,
    retryPolicy: { maxRetries: 3, backoffExponentialFactor: 2.0, initialDelaySeconds: 30 },
    validationAssertionsCount: 14,
    lineageTrackedColumns: ['record_id', 'source_timestamp', 'payload_hash', 'cleared_amount', 'tenant_id']
  },
  {
    dagId: 'DAG-IOT-039',
    pipelineName: 'IoTSensorTelemetryBatch Production Workflow #39',
    domain: 'IoTSensorTelemetryBatch',
    category: 'Industrial SCADA sensor timeseries ingestion',
    cronSchedule: '39 15 * * *',
    sourceProtocol: 'KAFKA',
    sinkProtocol: 'BIGQUERY',
    batchSizeRecords: 240000,
    maxParallelTasks: 7,
    slaThresholdMinutes: 54,
    retryPolicy: { maxRetries: 3, backoffExponentialFactor: 2.0, initialDelaySeconds: 30 },
    validationAssertionsCount: 15,
    lineageTrackedColumns: ['record_id', 'source_timestamp', 'payload_hash', 'cleared_amount', 'tenant_id']
  },
  {
    dagId: 'DAG-IOT-040',
    pipelineName: 'IoTSensorTelemetryBatch Production Workflow #40',
    domain: 'IoTSensorTelemetryBatch',
    category: 'rolling statistical anomaly detection',
    cronSchedule: '40 16 * * *',
    sourceProtocol: 'POSTGRES',
    sinkProtocol: 'SNOWFLAKE',
    batchSizeRecords: 50000,
    maxParallelTasks: 8,
    slaThresholdMinutes: 55,
    retryPolicy: { maxRetries: 3, backoffExponentialFactor: 2.0, initialDelaySeconds: 30 },
    validationAssertionsCount: 16,
    lineageTrackedColumns: ['record_id', 'source_timestamp', 'payload_hash', 'cleared_amount', 'tenant_id']
  },
  {
    dagId: 'DAG-IOT-041',
    pipelineName: 'IoTSensorTelemetryBatch Production Workflow #41',
    domain: 'IoTSensorTelemetryBatch',
    category: 'and predictive maintenance metrics',
    cronSchedule: '41 17 * * *',
    sourceProtocol: 'ICEBERG',
    sinkProtocol: 'BIGQUERY',
    batchSizeRecords: 60000,
    maxParallelTasks: 9,
    slaThresholdMinutes: 56,
    retryPolicy: { maxRetries: 3, backoffExponentialFactor: 2.0, initialDelaySeconds: 30 },
    validationAssertionsCount: 17,
    lineageTrackedColumns: ['record_id', 'source_timestamp', 'payload_hash', 'cleared_amount', 'tenant_id']
  },
  {
    dagId: 'DAG-IOT-042',
    pipelineName: 'IoTSensorTelemetryBatch Production Workflow #42',
    domain: 'IoTSensorTelemetryBatch',
    category: 'Industrial SCADA sensor timeseries ingestion',
    cronSchedule: '42 18 * * *',
    sourceProtocol: 'KAFKA',
    sinkProtocol: 'SNOWFLAKE',
    batchSizeRecords: 70000,
    maxParallelTasks: 10,
    slaThresholdMinutes: 57,
    retryPolicy: { maxRetries: 3, backoffExponentialFactor: 2.0, initialDelaySeconds: 30 },
    validationAssertionsCount: 18,
    lineageTrackedColumns: ['record_id', 'source_timestamp', 'payload_hash', 'cleared_amount', 'tenant_id']
  },
  {
    dagId: 'DAG-IOT-043',
    pipelineName: 'IoTSensorTelemetryBatch Production Workflow #43',
    domain: 'IoTSensorTelemetryBatch',
    category: 'rolling statistical anomaly detection',
    cronSchedule: '43 19 * * *',
    sourceProtocol: 'ICEBERG',
    sinkProtocol: 'BIGQUERY',
    batchSizeRecords: 80000,
    maxParallelTasks: 11,
    slaThresholdMinutes: 58,
    retryPolicy: { maxRetries: 3, backoffExponentialFactor: 2.0, initialDelaySeconds: 30 },
    validationAssertionsCount: 19,
    lineageTrackedColumns: ['record_id', 'source_timestamp', 'payload_hash', 'cleared_amount', 'tenant_id']
  },
  {
    dagId: 'DAG-IOT-044',
    pipelineName: 'IoTSensorTelemetryBatch Production Workflow #44',
    domain: 'IoTSensorTelemetryBatch',
    category: 'and predictive maintenance metrics',
    cronSchedule: '44 20 * * *',
    sourceProtocol: 'POSTGRES',
    sinkProtocol: 'SNOWFLAKE',
    batchSizeRecords: 90000,
    maxParallelTasks: 12,
    slaThresholdMinutes: 59,
    retryPolicy: { maxRetries: 3, backoffExponentialFactor: 2.0, initialDelaySeconds: 30 },
    validationAssertionsCount: 20,
    lineageTrackedColumns: ['record_id', 'source_timestamp', 'payload_hash', 'cleared_amount', 'tenant_id']
  },
  {
    dagId: 'DAG-IOT-045',
    pipelineName: 'IoTSensorTelemetryBatch Production Workflow #45',
    domain: 'IoTSensorTelemetryBatch',
    category: 'Industrial SCADA sensor timeseries ingestion',
    cronSchedule: '45 21 * * *',
    sourceProtocol: 'KAFKA',
    sinkProtocol: 'BIGQUERY',
    batchSizeRecords: 100000,
    maxParallelTasks: 13,
    slaThresholdMinutes: 15,
    retryPolicy: { maxRetries: 3, backoffExponentialFactor: 2.0, initialDelaySeconds: 30 },
    validationAssertionsCount: 21,
    lineageTrackedColumns: ['record_id', 'source_timestamp', 'payload_hash', 'cleared_amount', 'tenant_id']
  },
  {
    dagId: 'DAG-IOT-046',
    pipelineName: 'IoTSensorTelemetryBatch Production Workflow #46',
    domain: 'IoTSensorTelemetryBatch',
    category: 'rolling statistical anomaly detection',
    cronSchedule: '46 22 * * *',
    sourceProtocol: 'SNOWFLAKE',
    sinkProtocol: 'SNOWFLAKE',
    batchSizeRecords: 110000,
    maxParallelTasks: 14,
    slaThresholdMinutes: 16,
    retryPolicy: { maxRetries: 3, backoffExponentialFactor: 2.0, initialDelaySeconds: 30 },
    validationAssertionsCount: 22,
    lineageTrackedColumns: ['record_id', 'source_timestamp', 'payload_hash', 'cleared_amount', 'tenant_id']
  },
  {
    dagId: 'DAG-IOT-047',
    pipelineName: 'IoTSensorTelemetryBatch Production Workflow #47',
    domain: 'IoTSensorTelemetryBatch',
    category: 'and predictive maintenance metrics',
    cronSchedule: '47 23 * * *',
    sourceProtocol: 'ICEBERG',
    sinkProtocol: 'BIGQUERY',
    batchSizeRecords: 120000,
    maxParallelTasks: 15,
    slaThresholdMinutes: 17,
    retryPolicy: { maxRetries: 3, backoffExponentialFactor: 2.0, initialDelaySeconds: 30 },
    validationAssertionsCount: 23,
    lineageTrackedColumns: ['record_id', 'source_timestamp', 'payload_hash', 'cleared_amount', 'tenant_id']
  },
  {
    dagId: 'DAG-IOT-048',
    pipelineName: 'IoTSensorTelemetryBatch Production Workflow #48',
    domain: 'IoTSensorTelemetryBatch',
    category: 'Industrial SCADA sensor timeseries ingestion',
    cronSchedule: '48 0 * * *',
    sourceProtocol: 'POSTGRES',
    sinkProtocol: 'SNOWFLAKE',
    batchSizeRecords: 130000,
    maxParallelTasks: 4,
    slaThresholdMinutes: 18,
    retryPolicy: { maxRetries: 3, backoffExponentialFactor: 2.0, initialDelaySeconds: 30 },
    validationAssertionsCount: 8,
    lineageTrackedColumns: ['record_id', 'source_timestamp', 'payload_hash', 'cleared_amount', 'tenant_id']
  },
  {
    dagId: 'DAG-IOT-049',
    pipelineName: 'IoTSensorTelemetryBatch Production Workflow #49',
    domain: 'IoTSensorTelemetryBatch',
    category: 'rolling statistical anomaly detection',
    cronSchedule: '49 1 * * *',
    sourceProtocol: 'ICEBERG',
    sinkProtocol: 'BIGQUERY',
    batchSizeRecords: 140000,
    maxParallelTasks: 5,
    slaThresholdMinutes: 19,
    retryPolicy: { maxRetries: 3, backoffExponentialFactor: 2.0, initialDelaySeconds: 30 },
    validationAssertionsCount: 9,
    lineageTrackedColumns: ['record_id', 'source_timestamp', 'payload_hash', 'cleared_amount', 'tenant_id']
  },
  {
    dagId: 'DAG-IOT-050',
    pipelineName: 'IoTSensorTelemetryBatch Production Workflow #50',
    domain: 'IoTSensorTelemetryBatch',
    category: 'and predictive maintenance metrics',
    cronSchedule: '50 2 * * *',
    sourceProtocol: 'SNOWFLAKE',
    sinkProtocol: 'SNOWFLAKE',
    batchSizeRecords: 150000,
    maxParallelTasks: 6,
    slaThresholdMinutes: 20,
    retryPolicy: { maxRetries: 3, backoffExponentialFactor: 2.0, initialDelaySeconds: 30 },
    validationAssertionsCount: 10,
    lineageTrackedColumns: ['record_id', 'source_timestamp', 'payload_hash', 'cleared_amount', 'tenant_id']
  },
  {
    dagId: 'DAG-IOT-051',
    pipelineName: 'IoTSensorTelemetryBatch Production Workflow #51',
    domain: 'IoTSensorTelemetryBatch',
    category: 'Industrial SCADA sensor timeseries ingestion',
    cronSchedule: '51 3 * * *',
    sourceProtocol: 'KAFKA',
    sinkProtocol: 'BIGQUERY',
    batchSizeRecords: 160000,
    maxParallelTasks: 7,
    slaThresholdMinutes: 21,
    retryPolicy: { maxRetries: 3, backoffExponentialFactor: 2.0, initialDelaySeconds: 30 },
    validationAssertionsCount: 11,
    lineageTrackedColumns: ['record_id', 'source_timestamp', 'payload_hash', 'cleared_amount', 'tenant_id']
  },
  {
    dagId: 'DAG-IOT-052',
    pipelineName: 'IoTSensorTelemetryBatch Production Workflow #52',
    domain: 'IoTSensorTelemetryBatch',
    category: 'rolling statistical anomaly detection',
    cronSchedule: '52 4 * * *',
    sourceProtocol: 'POSTGRES',
    sinkProtocol: 'SNOWFLAKE',
    batchSizeRecords: 170000,
    maxParallelTasks: 8,
    slaThresholdMinutes: 22,
    retryPolicy: { maxRetries: 3, backoffExponentialFactor: 2.0, initialDelaySeconds: 30 },
    validationAssertionsCount: 12,
    lineageTrackedColumns: ['record_id', 'source_timestamp', 'payload_hash', 'cleared_amount', 'tenant_id']
  },
  {
    dagId: 'DAG-IOT-053',
    pipelineName: 'IoTSensorTelemetryBatch Production Workflow #53',
    domain: 'IoTSensorTelemetryBatch',
    category: 'and predictive maintenance metrics',
    cronSchedule: '53 5 * * *',
    sourceProtocol: 'ICEBERG',
    sinkProtocol: 'BIGQUERY',
    batchSizeRecords: 180000,
    maxParallelTasks: 9,
    slaThresholdMinutes: 23,
    retryPolicy: { maxRetries: 3, backoffExponentialFactor: 2.0, initialDelaySeconds: 30 },
    validationAssertionsCount: 13,
    lineageTrackedColumns: ['record_id', 'source_timestamp', 'payload_hash', 'cleared_amount', 'tenant_id']
  },
  {
    dagId: 'DAG-IOT-054',
    pipelineName: 'IoTSensorTelemetryBatch Production Workflow #54',
    domain: 'IoTSensorTelemetryBatch',
    category: 'Industrial SCADA sensor timeseries ingestion',
    cronSchedule: '54 6 * * *',
    sourceProtocol: 'KAFKA',
    sinkProtocol: 'SNOWFLAKE',
    batchSizeRecords: 190000,
    maxParallelTasks: 10,
    slaThresholdMinutes: 24,
    retryPolicy: { maxRetries: 3, backoffExponentialFactor: 2.0, initialDelaySeconds: 30 },
    validationAssertionsCount: 14,
    lineageTrackedColumns: ['record_id', 'source_timestamp', 'payload_hash', 'cleared_amount', 'tenant_id']
  },
  {
    dagId: 'DAG-IOT-055',
    pipelineName: 'IoTSensorTelemetryBatch Production Workflow #55',
    domain: 'IoTSensorTelemetryBatch',
    category: 'rolling statistical anomaly detection',
    cronSchedule: '55 7 * * *',
    sourceProtocol: 'ICEBERG',
    sinkProtocol: 'BIGQUERY',
    batchSizeRecords: 200000,
    maxParallelTasks: 11,
    slaThresholdMinutes: 25,
    retryPolicy: { maxRetries: 3, backoffExponentialFactor: 2.0, initialDelaySeconds: 30 },
    validationAssertionsCount: 15,
    lineageTrackedColumns: ['record_id', 'source_timestamp', 'payload_hash', 'cleared_amount', 'tenant_id']
  },
  {
    dagId: 'DAG-IOT-056',
    pipelineName: 'IoTSensorTelemetryBatch Production Workflow #56',
    domain: 'IoTSensorTelemetryBatch',
    category: 'and predictive maintenance metrics',
    cronSchedule: '56 8 * * *',
    sourceProtocol: 'POSTGRES',
    sinkProtocol: 'SNOWFLAKE',
    batchSizeRecords: 210000,
    maxParallelTasks: 12,
    slaThresholdMinutes: 26,
    retryPolicy: { maxRetries: 3, backoffExponentialFactor: 2.0, initialDelaySeconds: 30 },
    validationAssertionsCount: 16,
    lineageTrackedColumns: ['record_id', 'source_timestamp', 'payload_hash', 'cleared_amount', 'tenant_id']
  },
  {
    dagId: 'DAG-IOT-057',
    pipelineName: 'IoTSensorTelemetryBatch Production Workflow #57',
    domain: 'IoTSensorTelemetryBatch',
    category: 'Industrial SCADA sensor timeseries ingestion',
    cronSchedule: '57 9 * * *',
    sourceProtocol: 'KAFKA',
    sinkProtocol: 'BIGQUERY',
    batchSizeRecords: 220000,
    maxParallelTasks: 13,
    slaThresholdMinutes: 27,
    retryPolicy: { maxRetries: 3, backoffExponentialFactor: 2.0, initialDelaySeconds: 30 },
    validationAssertionsCount: 17,
    lineageTrackedColumns: ['record_id', 'source_timestamp', 'payload_hash', 'cleared_amount', 'tenant_id']
  },
  {
    dagId: 'DAG-IOT-058',
    pipelineName: 'IoTSensorTelemetryBatch Production Workflow #58',
    domain: 'IoTSensorTelemetryBatch',
    category: 'rolling statistical anomaly detection',
    cronSchedule: '58 10 * * *',
    sourceProtocol: 'SNOWFLAKE',
    sinkProtocol: 'SNOWFLAKE',
    batchSizeRecords: 230000,
    maxParallelTasks: 14,
    slaThresholdMinutes: 28,
    retryPolicy: { maxRetries: 3, backoffExponentialFactor: 2.0, initialDelaySeconds: 30 },
    validationAssertionsCount: 18,
    lineageTrackedColumns: ['record_id', 'source_timestamp', 'payload_hash', 'cleared_amount', 'tenant_id']
  },
  {
    dagId: 'DAG-IOT-059',
    pipelineName: 'IoTSensorTelemetryBatch Production Workflow #59',
    domain: 'IoTSensorTelemetryBatch',
    category: 'and predictive maintenance metrics',
    cronSchedule: '59 11 * * *',
    sourceProtocol: 'ICEBERG',
    sinkProtocol: 'BIGQUERY',
    batchSizeRecords: 240000,
    maxParallelTasks: 15,
    slaThresholdMinutes: 29,
    retryPolicy: { maxRetries: 3, backoffExponentialFactor: 2.0, initialDelaySeconds: 30 },
    validationAssertionsCount: 19,
    lineageTrackedColumns: ['record_id', 'source_timestamp', 'payload_hash', 'cleared_amount', 'tenant_id']
  },
  {
    dagId: 'DAG-IOT-060',
    pipelineName: 'IoTSensorTelemetryBatch Production Workflow #60',
    domain: 'IoTSensorTelemetryBatch',
    category: 'Industrial SCADA sensor timeseries ingestion',
    cronSchedule: '0 12 * * *',
    sourceProtocol: 'POSTGRES',
    sinkProtocol: 'SNOWFLAKE',
    batchSizeRecords: 50000,
    maxParallelTasks: 4,
    slaThresholdMinutes: 30,
    retryPolicy: { maxRetries: 3, backoffExponentialFactor: 2.0, initialDelaySeconds: 30 },
    validationAssertionsCount: 20,
    lineageTrackedColumns: ['record_id', 'source_timestamp', 'payload_hash', 'cleared_amount', 'tenant_id']
  },
  {
    dagId: 'DAG-IOT-061',
    pipelineName: 'IoTSensorTelemetryBatch Production Workflow #61',
    domain: 'IoTSensorTelemetryBatch',
    category: 'rolling statistical anomaly detection',
    cronSchedule: '1 13 * * *',
    sourceProtocol: 'ICEBERG',
    sinkProtocol: 'BIGQUERY',
    batchSizeRecords: 60000,
    maxParallelTasks: 5,
    slaThresholdMinutes: 31,
    retryPolicy: { maxRetries: 3, backoffExponentialFactor: 2.0, initialDelaySeconds: 30 },
    validationAssertionsCount: 21,
    lineageTrackedColumns: ['record_id', 'source_timestamp', 'payload_hash', 'cleared_amount', 'tenant_id']
  },
  {
    dagId: 'DAG-IOT-062',
    pipelineName: 'IoTSensorTelemetryBatch Production Workflow #62',
    domain: 'IoTSensorTelemetryBatch',
    category: 'and predictive maintenance metrics',
    cronSchedule: '2 14 * * *',
    sourceProtocol: 'SNOWFLAKE',
    sinkProtocol: 'SNOWFLAKE',
    batchSizeRecords: 70000,
    maxParallelTasks: 6,
    slaThresholdMinutes: 32,
    retryPolicy: { maxRetries: 3, backoffExponentialFactor: 2.0, initialDelaySeconds: 30 },
    validationAssertionsCount: 22,
    lineageTrackedColumns: ['record_id', 'source_timestamp', 'payload_hash', 'cleared_amount', 'tenant_id']
  },
  {
    dagId: 'DAG-IOT-063',
    pipelineName: 'IoTSensorTelemetryBatch Production Workflow #63',
    domain: 'IoTSensorTelemetryBatch',
    category: 'Industrial SCADA sensor timeseries ingestion',
    cronSchedule: '3 15 * * *',
    sourceProtocol: 'KAFKA',
    sinkProtocol: 'BIGQUERY',
    batchSizeRecords: 80000,
    maxParallelTasks: 7,
    slaThresholdMinutes: 33,
    retryPolicy: { maxRetries: 3, backoffExponentialFactor: 2.0, initialDelaySeconds: 30 },
    validationAssertionsCount: 23,
    lineageTrackedColumns: ['record_id', 'source_timestamp', 'payload_hash', 'cleared_amount', 'tenant_id']
  },
  {
    dagId: 'DAG-IOT-064',
    pipelineName: 'IoTSensorTelemetryBatch Production Workflow #64',
    domain: 'IoTSensorTelemetryBatch',
    category: 'rolling statistical anomaly detection',
    cronSchedule: '4 16 * * *',
    sourceProtocol: 'POSTGRES',
    sinkProtocol: 'SNOWFLAKE',
    batchSizeRecords: 90000,
    maxParallelTasks: 8,
    slaThresholdMinutes: 34,
    retryPolicy: { maxRetries: 3, backoffExponentialFactor: 2.0, initialDelaySeconds: 30 },
    validationAssertionsCount: 8,
    lineageTrackedColumns: ['record_id', 'source_timestamp', 'payload_hash', 'cleared_amount', 'tenant_id']
  },
  {
    dagId: 'DAG-IOT-065',
    pipelineName: 'IoTSensorTelemetryBatch Production Workflow #65',
    domain: 'IoTSensorTelemetryBatch',
    category: 'and predictive maintenance metrics',
    cronSchedule: '5 17 * * *',
    sourceProtocol: 'ICEBERG',
    sinkProtocol: 'BIGQUERY',
    batchSizeRecords: 100000,
    maxParallelTasks: 9,
    slaThresholdMinutes: 35,
    retryPolicy: { maxRetries: 3, backoffExponentialFactor: 2.0, initialDelaySeconds: 30 },
    validationAssertionsCount: 9,
    lineageTrackedColumns: ['record_id', 'source_timestamp', 'payload_hash', 'cleared_amount', 'tenant_id']
  },
  {
    dagId: 'DAG-IOT-066',
    pipelineName: 'IoTSensorTelemetryBatch Production Workflow #66',
    domain: 'IoTSensorTelemetryBatch',
    category: 'Industrial SCADA sensor timeseries ingestion',
    cronSchedule: '6 18 * * *',
    sourceProtocol: 'KAFKA',
    sinkProtocol: 'SNOWFLAKE',
    batchSizeRecords: 110000,
    maxParallelTasks: 10,
    slaThresholdMinutes: 36,
    retryPolicy: { maxRetries: 3, backoffExponentialFactor: 2.0, initialDelaySeconds: 30 },
    validationAssertionsCount: 10,
    lineageTrackedColumns: ['record_id', 'source_timestamp', 'payload_hash', 'cleared_amount', 'tenant_id']
  },
  {
    dagId: 'DAG-IOT-067',
    pipelineName: 'IoTSensorTelemetryBatch Production Workflow #67',
    domain: 'IoTSensorTelemetryBatch',
    category: 'rolling statistical anomaly detection',
    cronSchedule: '7 19 * * *',
    sourceProtocol: 'ICEBERG',
    sinkProtocol: 'BIGQUERY',
    batchSizeRecords: 120000,
    maxParallelTasks: 11,
    slaThresholdMinutes: 37,
    retryPolicy: { maxRetries: 3, backoffExponentialFactor: 2.0, initialDelaySeconds: 30 },
    validationAssertionsCount: 11,
    lineageTrackedColumns: ['record_id', 'source_timestamp', 'payload_hash', 'cleared_amount', 'tenant_id']
  },
  {
    dagId: 'DAG-IOT-068',
    pipelineName: 'IoTSensorTelemetryBatch Production Workflow #68',
    domain: 'IoTSensorTelemetryBatch',
    category: 'and predictive maintenance metrics',
    cronSchedule: '8 20 * * *',
    sourceProtocol: 'POSTGRES',
    sinkProtocol: 'SNOWFLAKE',
    batchSizeRecords: 130000,
    maxParallelTasks: 12,
    slaThresholdMinutes: 38,
    retryPolicy: { maxRetries: 3, backoffExponentialFactor: 2.0, initialDelaySeconds: 30 },
    validationAssertionsCount: 12,
    lineageTrackedColumns: ['record_id', 'source_timestamp', 'payload_hash', 'cleared_amount', 'tenant_id']
  },
  {
    dagId: 'DAG-IOT-069',
    pipelineName: 'IoTSensorTelemetryBatch Production Workflow #69',
    domain: 'IoTSensorTelemetryBatch',
    category: 'Industrial SCADA sensor timeseries ingestion',
    cronSchedule: '9 21 * * *',
    sourceProtocol: 'KAFKA',
    sinkProtocol: 'BIGQUERY',
    batchSizeRecords: 140000,
    maxParallelTasks: 13,
    slaThresholdMinutes: 39,
    retryPolicy: { maxRetries: 3, backoffExponentialFactor: 2.0, initialDelaySeconds: 30 },
    validationAssertionsCount: 13,
    lineageTrackedColumns: ['record_id', 'source_timestamp', 'payload_hash', 'cleared_amount', 'tenant_id']
  },
  {
    dagId: 'DAG-IOT-070',
    pipelineName: 'IoTSensorTelemetryBatch Production Workflow #70',
    domain: 'IoTSensorTelemetryBatch',
    category: 'rolling statistical anomaly detection',
    cronSchedule: '10 22 * * *',
    sourceProtocol: 'SNOWFLAKE',
    sinkProtocol: 'SNOWFLAKE',
    batchSizeRecords: 150000,
    maxParallelTasks: 14,
    slaThresholdMinutes: 40,
    retryPolicy: { maxRetries: 3, backoffExponentialFactor: 2.0, initialDelaySeconds: 30 },
    validationAssertionsCount: 14,
    lineageTrackedColumns: ['record_id', 'source_timestamp', 'payload_hash', 'cleared_amount', 'tenant_id']
  },
  {
    dagId: 'DAG-IOT-071',
    pipelineName: 'IoTSensorTelemetryBatch Production Workflow #71',
    domain: 'IoTSensorTelemetryBatch',
    category: 'and predictive maintenance metrics',
    cronSchedule: '11 23 * * *',
    sourceProtocol: 'ICEBERG',
    sinkProtocol: 'BIGQUERY',
    batchSizeRecords: 160000,
    maxParallelTasks: 15,
    slaThresholdMinutes: 41,
    retryPolicy: { maxRetries: 3, backoffExponentialFactor: 2.0, initialDelaySeconds: 30 },
    validationAssertionsCount: 15,
    lineageTrackedColumns: ['record_id', 'source_timestamp', 'payload_hash', 'cleared_amount', 'tenant_id']
  },
  {
    dagId: 'DAG-IOT-072',
    pipelineName: 'IoTSensorTelemetryBatch Production Workflow #72',
    domain: 'IoTSensorTelemetryBatch',
    category: 'Industrial SCADA sensor timeseries ingestion',
    cronSchedule: '12 0 * * *',
    sourceProtocol: 'POSTGRES',
    sinkProtocol: 'SNOWFLAKE',
    batchSizeRecords: 170000,
    maxParallelTasks: 4,
    slaThresholdMinutes: 42,
    retryPolicy: { maxRetries: 3, backoffExponentialFactor: 2.0, initialDelaySeconds: 30 },
    validationAssertionsCount: 16,
    lineageTrackedColumns: ['record_id', 'source_timestamp', 'payload_hash', 'cleared_amount', 'tenant_id']
  },
  {
    dagId: 'DAG-IOT-073',
    pipelineName: 'IoTSensorTelemetryBatch Production Workflow #73',
    domain: 'IoTSensorTelemetryBatch',
    category: 'rolling statistical anomaly detection',
    cronSchedule: '13 1 * * *',
    sourceProtocol: 'ICEBERG',
    sinkProtocol: 'BIGQUERY',
    batchSizeRecords: 180000,
    maxParallelTasks: 5,
    slaThresholdMinutes: 43,
    retryPolicy: { maxRetries: 3, backoffExponentialFactor: 2.0, initialDelaySeconds: 30 },
    validationAssertionsCount: 17,
    lineageTrackedColumns: ['record_id', 'source_timestamp', 'payload_hash', 'cleared_amount', 'tenant_id']
  },
  {
    dagId: 'DAG-IOT-074',
    pipelineName: 'IoTSensorTelemetryBatch Production Workflow #74',
    domain: 'IoTSensorTelemetryBatch',
    category: 'and predictive maintenance metrics',
    cronSchedule: '14 2 * * *',
    sourceProtocol: 'SNOWFLAKE',
    sinkProtocol: 'SNOWFLAKE',
    batchSizeRecords: 190000,
    maxParallelTasks: 6,
    slaThresholdMinutes: 44,
    retryPolicy: { maxRetries: 3, backoffExponentialFactor: 2.0, initialDelaySeconds: 30 },
    validationAssertionsCount: 18,
    lineageTrackedColumns: ['record_id', 'source_timestamp', 'payload_hash', 'cleared_amount', 'tenant_id']
  },
  {
    dagId: 'DAG-IOT-075',
    pipelineName: 'IoTSensorTelemetryBatch Production Workflow #75',
    domain: 'IoTSensorTelemetryBatch',
    category: 'Industrial SCADA sensor timeseries ingestion',
    cronSchedule: '15 3 * * *',
    sourceProtocol: 'KAFKA',
    sinkProtocol: 'BIGQUERY',
    batchSizeRecords: 200000,
    maxParallelTasks: 7,
    slaThresholdMinutes: 45,
    retryPolicy: { maxRetries: 3, backoffExponentialFactor: 2.0, initialDelaySeconds: 30 },
    validationAssertionsCount: 19,
    lineageTrackedColumns: ['record_id', 'source_timestamp', 'payload_hash', 'cleared_amount', 'tenant_id']
  },
  {
    dagId: 'DAG-IOT-076',
    pipelineName: 'IoTSensorTelemetryBatch Production Workflow #76',
    domain: 'IoTSensorTelemetryBatch',
    category: 'rolling statistical anomaly detection',
    cronSchedule: '16 4 * * *',
    sourceProtocol: 'POSTGRES',
    sinkProtocol: 'SNOWFLAKE',
    batchSizeRecords: 210000,
    maxParallelTasks: 8,
    slaThresholdMinutes: 46,
    retryPolicy: { maxRetries: 3, backoffExponentialFactor: 2.0, initialDelaySeconds: 30 },
    validationAssertionsCount: 20,
    lineageTrackedColumns: ['record_id', 'source_timestamp', 'payload_hash', 'cleared_amount', 'tenant_id']
  },
  {
    dagId: 'DAG-IOT-077',
    pipelineName: 'IoTSensorTelemetryBatch Production Workflow #77',
    domain: 'IoTSensorTelemetryBatch',
    category: 'and predictive maintenance metrics',
    cronSchedule: '17 5 * * *',
    sourceProtocol: 'ICEBERG',
    sinkProtocol: 'BIGQUERY',
    batchSizeRecords: 220000,
    maxParallelTasks: 9,
    slaThresholdMinutes: 47,
    retryPolicy: { maxRetries: 3, backoffExponentialFactor: 2.0, initialDelaySeconds: 30 },
    validationAssertionsCount: 21,
    lineageTrackedColumns: ['record_id', 'source_timestamp', 'payload_hash', 'cleared_amount', 'tenant_id']
  },
  {
    dagId: 'DAG-IOT-078',
    pipelineName: 'IoTSensorTelemetryBatch Production Workflow #78',
    domain: 'IoTSensorTelemetryBatch',
    category: 'Industrial SCADA sensor timeseries ingestion',
    cronSchedule: '18 6 * * *',
    sourceProtocol: 'KAFKA',
    sinkProtocol: 'SNOWFLAKE',
    batchSizeRecords: 230000,
    maxParallelTasks: 10,
    slaThresholdMinutes: 48,
    retryPolicy: { maxRetries: 3, backoffExponentialFactor: 2.0, initialDelaySeconds: 30 },
    validationAssertionsCount: 22,
    lineageTrackedColumns: ['record_id', 'source_timestamp', 'payload_hash', 'cleared_amount', 'tenant_id']
  },
  {
    dagId: 'DAG-IOT-079',
    pipelineName: 'IoTSensorTelemetryBatch Production Workflow #79',
    domain: 'IoTSensorTelemetryBatch',
    category: 'rolling statistical anomaly detection',
    cronSchedule: '19 7 * * *',
    sourceProtocol: 'ICEBERG',
    sinkProtocol: 'BIGQUERY',
    batchSizeRecords: 240000,
    maxParallelTasks: 11,
    slaThresholdMinutes: 49,
    retryPolicy: { maxRetries: 3, backoffExponentialFactor: 2.0, initialDelaySeconds: 30 },
    validationAssertionsCount: 23,
    lineageTrackedColumns: ['record_id', 'source_timestamp', 'payload_hash', 'cleared_amount', 'tenant_id']
  },
  {
    dagId: 'DAG-IOT-080',
    pipelineName: 'IoTSensorTelemetryBatch Production Workflow #80',
    domain: 'IoTSensorTelemetryBatch',
    category: 'and predictive maintenance metrics',
    cronSchedule: '20 8 * * *',
    sourceProtocol: 'POSTGRES',
    sinkProtocol: 'SNOWFLAKE',
    batchSizeRecords: 50000,
    maxParallelTasks: 12,
    slaThresholdMinutes: 50,
    retryPolicy: { maxRetries: 3, backoffExponentialFactor: 2.0, initialDelaySeconds: 30 },
    validationAssertionsCount: 8,
    lineageTrackedColumns: ['record_id', 'source_timestamp', 'payload_hash', 'cleared_amount', 'tenant_id']
  },
  {
    dagId: 'DAG-IOT-081',
    pipelineName: 'IoTSensorTelemetryBatch Production Workflow #81',
    domain: 'IoTSensorTelemetryBatch',
    category: 'Industrial SCADA sensor timeseries ingestion',
    cronSchedule: '21 9 * * *',
    sourceProtocol: 'KAFKA',
    sinkProtocol: 'BIGQUERY',
    batchSizeRecords: 60000,
    maxParallelTasks: 13,
    slaThresholdMinutes: 51,
    retryPolicy: { maxRetries: 3, backoffExponentialFactor: 2.0, initialDelaySeconds: 30 },
    validationAssertionsCount: 9,
    lineageTrackedColumns: ['record_id', 'source_timestamp', 'payload_hash', 'cleared_amount', 'tenant_id']
  },
  {
    dagId: 'DAG-IOT-082',
    pipelineName: 'IoTSensorTelemetryBatch Production Workflow #82',
    domain: 'IoTSensorTelemetryBatch',
    category: 'rolling statistical anomaly detection',
    cronSchedule: '22 10 * * *',
    sourceProtocol: 'SNOWFLAKE',
    sinkProtocol: 'SNOWFLAKE',
    batchSizeRecords: 70000,
    maxParallelTasks: 14,
    slaThresholdMinutes: 52,
    retryPolicy: { maxRetries: 3, backoffExponentialFactor: 2.0, initialDelaySeconds: 30 },
    validationAssertionsCount: 10,
    lineageTrackedColumns: ['record_id', 'source_timestamp', 'payload_hash', 'cleared_amount', 'tenant_id']
  },
  {
    dagId: 'DAG-IOT-083',
    pipelineName: 'IoTSensorTelemetryBatch Production Workflow #83',
    domain: 'IoTSensorTelemetryBatch',
    category: 'and predictive maintenance metrics',
    cronSchedule: '23 11 * * *',
    sourceProtocol: 'ICEBERG',
    sinkProtocol: 'BIGQUERY',
    batchSizeRecords: 80000,
    maxParallelTasks: 15,
    slaThresholdMinutes: 53,
    retryPolicy: { maxRetries: 3, backoffExponentialFactor: 2.0, initialDelaySeconds: 30 },
    validationAssertionsCount: 11,
    lineageTrackedColumns: ['record_id', 'source_timestamp', 'payload_hash', 'cleared_amount', 'tenant_id']
  },
  {
    dagId: 'DAG-IOT-084',
    pipelineName: 'IoTSensorTelemetryBatch Production Workflow #84',
    domain: 'IoTSensorTelemetryBatch',
    category: 'Industrial SCADA sensor timeseries ingestion',
    cronSchedule: '24 12 * * *',
    sourceProtocol: 'POSTGRES',
    sinkProtocol: 'SNOWFLAKE',
    batchSizeRecords: 90000,
    maxParallelTasks: 4,
    slaThresholdMinutes: 54,
    retryPolicy: { maxRetries: 3, backoffExponentialFactor: 2.0, initialDelaySeconds: 30 },
    validationAssertionsCount: 12,
    lineageTrackedColumns: ['record_id', 'source_timestamp', 'payload_hash', 'cleared_amount', 'tenant_id']
  },
  {
    dagId: 'DAG-IOT-085',
    pipelineName: 'IoTSensorTelemetryBatch Production Workflow #85',
    domain: 'IoTSensorTelemetryBatch',
    category: 'rolling statistical anomaly detection',
    cronSchedule: '25 13 * * *',
    sourceProtocol: 'ICEBERG',
    sinkProtocol: 'BIGQUERY',
    batchSizeRecords: 100000,
    maxParallelTasks: 5,
    slaThresholdMinutes: 55,
    retryPolicy: { maxRetries: 3, backoffExponentialFactor: 2.0, initialDelaySeconds: 30 },
    validationAssertionsCount: 13,
    lineageTrackedColumns: ['record_id', 'source_timestamp', 'payload_hash', 'cleared_amount', 'tenant_id']
  },
  {
    dagId: 'DAG-IOT-086',
    pipelineName: 'IoTSensorTelemetryBatch Production Workflow #86',
    domain: 'IoTSensorTelemetryBatch',
    category: 'and predictive maintenance metrics',
    cronSchedule: '26 14 * * *',
    sourceProtocol: 'SNOWFLAKE',
    sinkProtocol: 'SNOWFLAKE',
    batchSizeRecords: 110000,
    maxParallelTasks: 6,
    slaThresholdMinutes: 56,
    retryPolicy: { maxRetries: 3, backoffExponentialFactor: 2.0, initialDelaySeconds: 30 },
    validationAssertionsCount: 14,
    lineageTrackedColumns: ['record_id', 'source_timestamp', 'payload_hash', 'cleared_amount', 'tenant_id']
  },
  {
    dagId: 'DAG-IOT-087',
    pipelineName: 'IoTSensorTelemetryBatch Production Workflow #87',
    domain: 'IoTSensorTelemetryBatch',
    category: 'Industrial SCADA sensor timeseries ingestion',
    cronSchedule: '27 15 * * *',
    sourceProtocol: 'KAFKA',
    sinkProtocol: 'BIGQUERY',
    batchSizeRecords: 120000,
    maxParallelTasks: 7,
    slaThresholdMinutes: 57,
    retryPolicy: { maxRetries: 3, backoffExponentialFactor: 2.0, initialDelaySeconds: 30 },
    validationAssertionsCount: 15,
    lineageTrackedColumns: ['record_id', 'source_timestamp', 'payload_hash', 'cleared_amount', 'tenant_id']
  },
  {
    dagId: 'DAG-IOT-088',
    pipelineName: 'IoTSensorTelemetryBatch Production Workflow #88',
    domain: 'IoTSensorTelemetryBatch',
    category: 'rolling statistical anomaly detection',
    cronSchedule: '28 16 * * *',
    sourceProtocol: 'POSTGRES',
    sinkProtocol: 'SNOWFLAKE',
    batchSizeRecords: 130000,
    maxParallelTasks: 8,
    slaThresholdMinutes: 58,
    retryPolicy: { maxRetries: 3, backoffExponentialFactor: 2.0, initialDelaySeconds: 30 },
    validationAssertionsCount: 16,
    lineageTrackedColumns: ['record_id', 'source_timestamp', 'payload_hash', 'cleared_amount', 'tenant_id']
  },
  {
    dagId: 'DAG-IOT-089',
    pipelineName: 'IoTSensorTelemetryBatch Production Workflow #89',
    domain: 'IoTSensorTelemetryBatch',
    category: 'and predictive maintenance metrics',
    cronSchedule: '29 17 * * *',
    sourceProtocol: 'ICEBERG',
    sinkProtocol: 'BIGQUERY',
    batchSizeRecords: 140000,
    maxParallelTasks: 9,
    slaThresholdMinutes: 59,
    retryPolicy: { maxRetries: 3, backoffExponentialFactor: 2.0, initialDelaySeconds: 30 },
    validationAssertionsCount: 17,
    lineageTrackedColumns: ['record_id', 'source_timestamp', 'payload_hash', 'cleared_amount', 'tenant_id']
  },
  {
    dagId: 'DAG-IOT-090',
    pipelineName: 'IoTSensorTelemetryBatch Production Workflow #90',
    domain: 'IoTSensorTelemetryBatch',
    category: 'Industrial SCADA sensor timeseries ingestion',
    cronSchedule: '30 18 * * *',
    sourceProtocol: 'KAFKA',
    sinkProtocol: 'SNOWFLAKE',
    batchSizeRecords: 150000,
    maxParallelTasks: 10,
    slaThresholdMinutes: 15,
    retryPolicy: { maxRetries: 3, backoffExponentialFactor: 2.0, initialDelaySeconds: 30 },
    validationAssertionsCount: 18,
    lineageTrackedColumns: ['record_id', 'source_timestamp', 'payload_hash', 'cleared_amount', 'tenant_id']
  },
  {
    dagId: 'DAG-IOT-091',
    pipelineName: 'IoTSensorTelemetryBatch Production Workflow #91',
    domain: 'IoTSensorTelemetryBatch',
    category: 'rolling statistical anomaly detection',
    cronSchedule: '31 19 * * *',
    sourceProtocol: 'ICEBERG',
    sinkProtocol: 'BIGQUERY',
    batchSizeRecords: 160000,
    maxParallelTasks: 11,
    slaThresholdMinutes: 16,
    retryPolicy: { maxRetries: 3, backoffExponentialFactor: 2.0, initialDelaySeconds: 30 },
    validationAssertionsCount: 19,
    lineageTrackedColumns: ['record_id', 'source_timestamp', 'payload_hash', 'cleared_amount', 'tenant_id']
  },
  {
    dagId: 'DAG-IOT-092',
    pipelineName: 'IoTSensorTelemetryBatch Production Workflow #92',
    domain: 'IoTSensorTelemetryBatch',
    category: 'and predictive maintenance metrics',
    cronSchedule: '32 20 * * *',
    sourceProtocol: 'POSTGRES',
    sinkProtocol: 'SNOWFLAKE',
    batchSizeRecords: 170000,
    maxParallelTasks: 12,
    slaThresholdMinutes: 17,
    retryPolicy: { maxRetries: 3, backoffExponentialFactor: 2.0, initialDelaySeconds: 30 },
    validationAssertionsCount: 20,
    lineageTrackedColumns: ['record_id', 'source_timestamp', 'payload_hash', 'cleared_amount', 'tenant_id']
  },
  {
    dagId: 'DAG-IOT-093',
    pipelineName: 'IoTSensorTelemetryBatch Production Workflow #93',
    domain: 'IoTSensorTelemetryBatch',
    category: 'Industrial SCADA sensor timeseries ingestion',
    cronSchedule: '33 21 * * *',
    sourceProtocol: 'KAFKA',
    sinkProtocol: 'BIGQUERY',
    batchSizeRecords: 180000,
    maxParallelTasks: 13,
    slaThresholdMinutes: 18,
    retryPolicy: { maxRetries: 3, backoffExponentialFactor: 2.0, initialDelaySeconds: 30 },
    validationAssertionsCount: 21,
    lineageTrackedColumns: ['record_id', 'source_timestamp', 'payload_hash', 'cleared_amount', 'tenant_id']
  },
  {
    dagId: 'DAG-IOT-094',
    pipelineName: 'IoTSensorTelemetryBatch Production Workflow #94',
    domain: 'IoTSensorTelemetryBatch',
    category: 'rolling statistical anomaly detection',
    cronSchedule: '34 22 * * *',
    sourceProtocol: 'SNOWFLAKE',
    sinkProtocol: 'SNOWFLAKE',
    batchSizeRecords: 190000,
    maxParallelTasks: 14,
    slaThresholdMinutes: 19,
    retryPolicy: { maxRetries: 3, backoffExponentialFactor: 2.0, initialDelaySeconds: 30 },
    validationAssertionsCount: 22,
    lineageTrackedColumns: ['record_id', 'source_timestamp', 'payload_hash', 'cleared_amount', 'tenant_id']
  },
  {
    dagId: 'DAG-IOT-095',
    pipelineName: 'IoTSensorTelemetryBatch Production Workflow #95',
    domain: 'IoTSensorTelemetryBatch',
    category: 'and predictive maintenance metrics',
    cronSchedule: '35 23 * * *',
    sourceProtocol: 'ICEBERG',
    sinkProtocol: 'BIGQUERY',
    batchSizeRecords: 200000,
    maxParallelTasks: 15,
    slaThresholdMinutes: 20,
    retryPolicy: { maxRetries: 3, backoffExponentialFactor: 2.0, initialDelaySeconds: 30 },
    validationAssertionsCount: 23,
    lineageTrackedColumns: ['record_id', 'source_timestamp', 'payload_hash', 'cleared_amount', 'tenant_id']
  },
  {
    dagId: 'DAG-IOT-096',
    pipelineName: 'IoTSensorTelemetryBatch Production Workflow #96',
    domain: 'IoTSensorTelemetryBatch',
    category: 'Industrial SCADA sensor timeseries ingestion',
    cronSchedule: '36 0 * * *',
    sourceProtocol: 'POSTGRES',
    sinkProtocol: 'SNOWFLAKE',
    batchSizeRecords: 210000,
    maxParallelTasks: 4,
    slaThresholdMinutes: 21,
    retryPolicy: { maxRetries: 3, backoffExponentialFactor: 2.0, initialDelaySeconds: 30 },
    validationAssertionsCount: 8,
    lineageTrackedColumns: ['record_id', 'source_timestamp', 'payload_hash', 'cleared_amount', 'tenant_id']
  },
  {
    dagId: 'DAG-IOT-097',
    pipelineName: 'IoTSensorTelemetryBatch Production Workflow #97',
    domain: 'IoTSensorTelemetryBatch',
    category: 'rolling statistical anomaly detection',
    cronSchedule: '37 1 * * *',
    sourceProtocol: 'ICEBERG',
    sinkProtocol: 'BIGQUERY',
    batchSizeRecords: 220000,
    maxParallelTasks: 5,
    slaThresholdMinutes: 22,
    retryPolicy: { maxRetries: 3, backoffExponentialFactor: 2.0, initialDelaySeconds: 30 },
    validationAssertionsCount: 9,
    lineageTrackedColumns: ['record_id', 'source_timestamp', 'payload_hash', 'cleared_amount', 'tenant_id']
  },
  {
    dagId: 'DAG-IOT-098',
    pipelineName: 'IoTSensorTelemetryBatch Production Workflow #98',
    domain: 'IoTSensorTelemetryBatch',
    category: 'and predictive maintenance metrics',
    cronSchedule: '38 2 * * *',
    sourceProtocol: 'SNOWFLAKE',
    sinkProtocol: 'SNOWFLAKE',
    batchSizeRecords: 230000,
    maxParallelTasks: 6,
    slaThresholdMinutes: 23,
    retryPolicy: { maxRetries: 3, backoffExponentialFactor: 2.0, initialDelaySeconds: 30 },
    validationAssertionsCount: 10,
    lineageTrackedColumns: ['record_id', 'source_timestamp', 'payload_hash', 'cleared_amount', 'tenant_id']
  },
  {
    dagId: 'DAG-IOT-099',
    pipelineName: 'IoTSensorTelemetryBatch Production Workflow #99',
    domain: 'IoTSensorTelemetryBatch',
    category: 'Industrial SCADA sensor timeseries ingestion',
    cronSchedule: '39 3 * * *',
    sourceProtocol: 'KAFKA',
    sinkProtocol: 'BIGQUERY',
    batchSizeRecords: 240000,
    maxParallelTasks: 7,
    slaThresholdMinutes: 24,
    retryPolicy: { maxRetries: 3, backoffExponentialFactor: 2.0, initialDelaySeconds: 30 },
    validationAssertionsCount: 11,
    lineageTrackedColumns: ['record_id', 'source_timestamp', 'payload_hash', 'cleared_amount', 'tenant_id']
  },
  {
    dagId: 'DAG-IOT-100',
    pipelineName: 'IoTSensorTelemetryBatch Production Workflow #100',
    domain: 'IoTSensorTelemetryBatch',
    category: 'rolling statistical anomaly detection',
    cronSchedule: '40 4 * * *',
    sourceProtocol: 'POSTGRES',
    sinkProtocol: 'SNOWFLAKE',
    batchSizeRecords: 50000,
    maxParallelTasks: 8,
    slaThresholdMinutes: 25,
    retryPolicy: { maxRetries: 3, backoffExponentialFactor: 2.0, initialDelaySeconds: 30 },
    validationAssertionsCount: 12,
    lineageTrackedColumns: ['record_id', 'source_timestamp', 'payload_hash', 'cleared_amount', 'tenant_id']
  },
  {
    dagId: 'DAG-IOT-101',
    pipelineName: 'IoTSensorTelemetryBatch Production Workflow #101',
    domain: 'IoTSensorTelemetryBatch',
    category: 'and predictive maintenance metrics',
    cronSchedule: '41 5 * * *',
    sourceProtocol: 'ICEBERG',
    sinkProtocol: 'BIGQUERY',
    batchSizeRecords: 60000,
    maxParallelTasks: 9,
    slaThresholdMinutes: 26,
    retryPolicy: { maxRetries: 3, backoffExponentialFactor: 2.0, initialDelaySeconds: 30 },
    validationAssertionsCount: 13,
    lineageTrackedColumns: ['record_id', 'source_timestamp', 'payload_hash', 'cleared_amount', 'tenant_id']
  },
  {
    dagId: 'DAG-IOT-102',
    pipelineName: 'IoTSensorTelemetryBatch Production Workflow #102',
    domain: 'IoTSensorTelemetryBatch',
    category: 'Industrial SCADA sensor timeseries ingestion',
    cronSchedule: '42 6 * * *',
    sourceProtocol: 'KAFKA',
    sinkProtocol: 'SNOWFLAKE',
    batchSizeRecords: 70000,
    maxParallelTasks: 10,
    slaThresholdMinutes: 27,
    retryPolicy: { maxRetries: 3, backoffExponentialFactor: 2.0, initialDelaySeconds: 30 },
    validationAssertionsCount: 14,
    lineageTrackedColumns: ['record_id', 'source_timestamp', 'payload_hash', 'cleared_amount', 'tenant_id']
  },
  {
    dagId: 'DAG-IOT-103',
    pipelineName: 'IoTSensorTelemetryBatch Production Workflow #103',
    domain: 'IoTSensorTelemetryBatch',
    category: 'rolling statistical anomaly detection',
    cronSchedule: '43 7 * * *',
    sourceProtocol: 'ICEBERG',
    sinkProtocol: 'BIGQUERY',
    batchSizeRecords: 80000,
    maxParallelTasks: 11,
    slaThresholdMinutes: 28,
    retryPolicy: { maxRetries: 3, backoffExponentialFactor: 2.0, initialDelaySeconds: 30 },
    validationAssertionsCount: 15,
    lineageTrackedColumns: ['record_id', 'source_timestamp', 'payload_hash', 'cleared_amount', 'tenant_id']
  },
  {
    dagId: 'DAG-IOT-104',
    pipelineName: 'IoTSensorTelemetryBatch Production Workflow #104',
    domain: 'IoTSensorTelemetryBatch',
    category: 'and predictive maintenance metrics',
    cronSchedule: '44 8 * * *',
    sourceProtocol: 'POSTGRES',
    sinkProtocol: 'SNOWFLAKE',
    batchSizeRecords: 90000,
    maxParallelTasks: 12,
    slaThresholdMinutes: 29,
    retryPolicy: { maxRetries: 3, backoffExponentialFactor: 2.0, initialDelaySeconds: 30 },
    validationAssertionsCount: 16,
    lineageTrackedColumns: ['record_id', 'source_timestamp', 'payload_hash', 'cleared_amount', 'tenant_id']
  },
  {
    dagId: 'DAG-IOT-105',
    pipelineName: 'IoTSensorTelemetryBatch Production Workflow #105',
    domain: 'IoTSensorTelemetryBatch',
    category: 'Industrial SCADA sensor timeseries ingestion',
    cronSchedule: '45 9 * * *',
    sourceProtocol: 'KAFKA',
    sinkProtocol: 'BIGQUERY',
    batchSizeRecords: 100000,
    maxParallelTasks: 13,
    slaThresholdMinutes: 30,
    retryPolicy: { maxRetries: 3, backoffExponentialFactor: 2.0, initialDelaySeconds: 30 },
    validationAssertionsCount: 17,
    lineageTrackedColumns: ['record_id', 'source_timestamp', 'payload_hash', 'cleared_amount', 'tenant_id']
  },
  {
    dagId: 'DAG-IOT-106',
    pipelineName: 'IoTSensorTelemetryBatch Production Workflow #106',
    domain: 'IoTSensorTelemetryBatch',
    category: 'rolling statistical anomaly detection',
    cronSchedule: '46 10 * * *',
    sourceProtocol: 'SNOWFLAKE',
    sinkProtocol: 'SNOWFLAKE',
    batchSizeRecords: 110000,
    maxParallelTasks: 14,
    slaThresholdMinutes: 31,
    retryPolicy: { maxRetries: 3, backoffExponentialFactor: 2.0, initialDelaySeconds: 30 },
    validationAssertionsCount: 18,
    lineageTrackedColumns: ['record_id', 'source_timestamp', 'payload_hash', 'cleared_amount', 'tenant_id']
  },
  {
    dagId: 'DAG-IOT-107',
    pipelineName: 'IoTSensorTelemetryBatch Production Workflow #107',
    domain: 'IoTSensorTelemetryBatch',
    category: 'and predictive maintenance metrics',
    cronSchedule: '47 11 * * *',
    sourceProtocol: 'ICEBERG',
    sinkProtocol: 'BIGQUERY',
    batchSizeRecords: 120000,
    maxParallelTasks: 15,
    slaThresholdMinutes: 32,
    retryPolicy: { maxRetries: 3, backoffExponentialFactor: 2.0, initialDelaySeconds: 30 },
    validationAssertionsCount: 19,
    lineageTrackedColumns: ['record_id', 'source_timestamp', 'payload_hash', 'cleared_amount', 'tenant_id']
  },
  {
    dagId: 'DAG-IOT-108',
    pipelineName: 'IoTSensorTelemetryBatch Production Workflow #108',
    domain: 'IoTSensorTelemetryBatch',
    category: 'Industrial SCADA sensor timeseries ingestion',
    cronSchedule: '48 12 * * *',
    sourceProtocol: 'POSTGRES',
    sinkProtocol: 'SNOWFLAKE',
    batchSizeRecords: 130000,
    maxParallelTasks: 4,
    slaThresholdMinutes: 33,
    retryPolicy: { maxRetries: 3, backoffExponentialFactor: 2.0, initialDelaySeconds: 30 },
    validationAssertionsCount: 20,
    lineageTrackedColumns: ['record_id', 'source_timestamp', 'payload_hash', 'cleared_amount', 'tenant_id']
  },
  {
    dagId: 'DAG-IOT-109',
    pipelineName: 'IoTSensorTelemetryBatch Production Workflow #109',
    domain: 'IoTSensorTelemetryBatch',
    category: 'rolling statistical anomaly detection',
    cronSchedule: '49 13 * * *',
    sourceProtocol: 'ICEBERG',
    sinkProtocol: 'BIGQUERY',
    batchSizeRecords: 140000,
    maxParallelTasks: 5,
    slaThresholdMinutes: 34,
    retryPolicy: { maxRetries: 3, backoffExponentialFactor: 2.0, initialDelaySeconds: 30 },
    validationAssertionsCount: 21,
    lineageTrackedColumns: ['record_id', 'source_timestamp', 'payload_hash', 'cleared_amount', 'tenant_id']
  },
  {
    dagId: 'DAG-IOT-110',
    pipelineName: 'IoTSensorTelemetryBatch Production Workflow #110',
    domain: 'IoTSensorTelemetryBatch',
    category: 'and predictive maintenance metrics',
    cronSchedule: '50 14 * * *',
    sourceProtocol: 'SNOWFLAKE',
    sinkProtocol: 'SNOWFLAKE',
    batchSizeRecords: 150000,
    maxParallelTasks: 6,
    slaThresholdMinutes: 35,
    retryPolicy: { maxRetries: 3, backoffExponentialFactor: 2.0, initialDelaySeconds: 30 },
    validationAssertionsCount: 22,
    lineageTrackedColumns: ['record_id', 'source_timestamp', 'payload_hash', 'cleared_amount', 'tenant_id']
  },
  {
    dagId: 'DAG-IOT-111',
    pipelineName: 'IoTSensorTelemetryBatch Production Workflow #111',
    domain: 'IoTSensorTelemetryBatch',
    category: 'Industrial SCADA sensor timeseries ingestion',
    cronSchedule: '51 15 * * *',
    sourceProtocol: 'KAFKA',
    sinkProtocol: 'BIGQUERY',
    batchSizeRecords: 160000,
    maxParallelTasks: 7,
    slaThresholdMinutes: 36,
    retryPolicy: { maxRetries: 3, backoffExponentialFactor: 2.0, initialDelaySeconds: 30 },
    validationAssertionsCount: 23,
    lineageTrackedColumns: ['record_id', 'source_timestamp', 'payload_hash', 'cleared_amount', 'tenant_id']
  },
  {
    dagId: 'DAG-IOT-112',
    pipelineName: 'IoTSensorTelemetryBatch Production Workflow #112',
    domain: 'IoTSensorTelemetryBatch',
    category: 'rolling statistical anomaly detection',
    cronSchedule: '52 16 * * *',
    sourceProtocol: 'POSTGRES',
    sinkProtocol: 'SNOWFLAKE',
    batchSizeRecords: 170000,
    maxParallelTasks: 8,
    slaThresholdMinutes: 37,
    retryPolicy: { maxRetries: 3, backoffExponentialFactor: 2.0, initialDelaySeconds: 30 },
    validationAssertionsCount: 8,
    lineageTrackedColumns: ['record_id', 'source_timestamp', 'payload_hash', 'cleared_amount', 'tenant_id']
  },
  {
    dagId: 'DAG-IOT-113',
    pipelineName: 'IoTSensorTelemetryBatch Production Workflow #113',
    domain: 'IoTSensorTelemetryBatch',
    category: 'and predictive maintenance metrics',
    cronSchedule: '53 17 * * *',
    sourceProtocol: 'ICEBERG',
    sinkProtocol: 'BIGQUERY',
    batchSizeRecords: 180000,
    maxParallelTasks: 9,
    slaThresholdMinutes: 38,
    retryPolicy: { maxRetries: 3, backoffExponentialFactor: 2.0, initialDelaySeconds: 30 },
    validationAssertionsCount: 9,
    lineageTrackedColumns: ['record_id', 'source_timestamp', 'payload_hash', 'cleared_amount', 'tenant_id']
  },
  {
    dagId: 'DAG-IOT-114',
    pipelineName: 'IoTSensorTelemetryBatch Production Workflow #114',
    domain: 'IoTSensorTelemetryBatch',
    category: 'Industrial SCADA sensor timeseries ingestion',
    cronSchedule: '54 18 * * *',
    sourceProtocol: 'KAFKA',
    sinkProtocol: 'SNOWFLAKE',
    batchSizeRecords: 190000,
    maxParallelTasks: 10,
    slaThresholdMinutes: 39,
    retryPolicy: { maxRetries: 3, backoffExponentialFactor: 2.0, initialDelaySeconds: 30 },
    validationAssertionsCount: 10,
    lineageTrackedColumns: ['record_id', 'source_timestamp', 'payload_hash', 'cleared_amount', 'tenant_id']
  },
  {
    dagId: 'DAG-IOT-115',
    pipelineName: 'IoTSensorTelemetryBatch Production Workflow #115',
    domain: 'IoTSensorTelemetryBatch',
    category: 'rolling statistical anomaly detection',
    cronSchedule: '55 19 * * *',
    sourceProtocol: 'ICEBERG',
    sinkProtocol: 'BIGQUERY',
    batchSizeRecords: 200000,
    maxParallelTasks: 11,
    slaThresholdMinutes: 40,
    retryPolicy: { maxRetries: 3, backoffExponentialFactor: 2.0, initialDelaySeconds: 30 },
    validationAssertionsCount: 11,
    lineageTrackedColumns: ['record_id', 'source_timestamp', 'payload_hash', 'cleared_amount', 'tenant_id']
  },
  {
    dagId: 'DAG-IOT-116',
    pipelineName: 'IoTSensorTelemetryBatch Production Workflow #116',
    domain: 'IoTSensorTelemetryBatch',
    category: 'and predictive maintenance metrics',
    cronSchedule: '56 20 * * *',
    sourceProtocol: 'POSTGRES',
    sinkProtocol: 'SNOWFLAKE',
    batchSizeRecords: 210000,
    maxParallelTasks: 12,
    slaThresholdMinutes: 41,
    retryPolicy: { maxRetries: 3, backoffExponentialFactor: 2.0, initialDelaySeconds: 30 },
    validationAssertionsCount: 12,
    lineageTrackedColumns: ['record_id', 'source_timestamp', 'payload_hash', 'cleared_amount', 'tenant_id']
  },
  {
    dagId: 'DAG-IOT-117',
    pipelineName: 'IoTSensorTelemetryBatch Production Workflow #117',
    domain: 'IoTSensorTelemetryBatch',
    category: 'Industrial SCADA sensor timeseries ingestion',
    cronSchedule: '57 21 * * *',
    sourceProtocol: 'KAFKA',
    sinkProtocol: 'BIGQUERY',
    batchSizeRecords: 220000,
    maxParallelTasks: 13,
    slaThresholdMinutes: 42,
    retryPolicy: { maxRetries: 3, backoffExponentialFactor: 2.0, initialDelaySeconds: 30 },
    validationAssertionsCount: 13,
    lineageTrackedColumns: ['record_id', 'source_timestamp', 'payload_hash', 'cleared_amount', 'tenant_id']
  },
  {
    dagId: 'DAG-IOT-118',
    pipelineName: 'IoTSensorTelemetryBatch Production Workflow #118',
    domain: 'IoTSensorTelemetryBatch',
    category: 'rolling statistical anomaly detection',
    cronSchedule: '58 22 * * *',
    sourceProtocol: 'SNOWFLAKE',
    sinkProtocol: 'SNOWFLAKE',
    batchSizeRecords: 230000,
    maxParallelTasks: 14,
    slaThresholdMinutes: 43,
    retryPolicy: { maxRetries: 3, backoffExponentialFactor: 2.0, initialDelaySeconds: 30 },
    validationAssertionsCount: 14,
    lineageTrackedColumns: ['record_id', 'source_timestamp', 'payload_hash', 'cleared_amount', 'tenant_id']
  },
  {
    dagId: 'DAG-IOT-119',
    pipelineName: 'IoTSensorTelemetryBatch Production Workflow #119',
    domain: 'IoTSensorTelemetryBatch',
    category: 'and predictive maintenance metrics',
    cronSchedule: '59 23 * * *',
    sourceProtocol: 'ICEBERG',
    sinkProtocol: 'BIGQUERY',
    batchSizeRecords: 240000,
    maxParallelTasks: 15,
    slaThresholdMinutes: 44,
    retryPolicy: { maxRetries: 3, backoffExponentialFactor: 2.0, initialDelaySeconds: 30 },
    validationAssertionsCount: 15,
    lineageTrackedColumns: ['record_id', 'source_timestamp', 'payload_hash', 'cleared_amount', 'tenant_id']
  },
  {
    dagId: 'DAG-IOT-120',
    pipelineName: 'IoTSensorTelemetryBatch Production Workflow #120',
    domain: 'IoTSensorTelemetryBatch',
    category: 'Industrial SCADA sensor timeseries ingestion',
    cronSchedule: '0 0 * * *',
    sourceProtocol: 'POSTGRES',
    sinkProtocol: 'SNOWFLAKE',
    batchSizeRecords: 50000,
    maxParallelTasks: 4,
    slaThresholdMinutes: 45,
    retryPolicy: { maxRetries: 3, backoffExponentialFactor: 2.0, initialDelaySeconds: 30 },
    validationAssertionsCount: 16,
    lineageTrackedColumns: ['record_id', 'source_timestamp', 'payload_hash', 'cleared_amount', 'tenant_id']
  },
  {
    dagId: 'DAG-IOT-121',
    pipelineName: 'IoTSensorTelemetryBatch Production Workflow #121',
    domain: 'IoTSensorTelemetryBatch',
    category: 'rolling statistical anomaly detection',
    cronSchedule: '1 1 * * *',
    sourceProtocol: 'ICEBERG',
    sinkProtocol: 'BIGQUERY',
    batchSizeRecords: 60000,
    maxParallelTasks: 5,
    slaThresholdMinutes: 46,
    retryPolicy: { maxRetries: 3, backoffExponentialFactor: 2.0, initialDelaySeconds: 30 },
    validationAssertionsCount: 17,
    lineageTrackedColumns: ['record_id', 'source_timestamp', 'payload_hash', 'cleared_amount', 'tenant_id']
  },
  {
    dagId: 'DAG-IOT-122',
    pipelineName: 'IoTSensorTelemetryBatch Production Workflow #122',
    domain: 'IoTSensorTelemetryBatch',
    category: 'and predictive maintenance metrics',
    cronSchedule: '2 2 * * *',
    sourceProtocol: 'SNOWFLAKE',
    sinkProtocol: 'SNOWFLAKE',
    batchSizeRecords: 70000,
    maxParallelTasks: 6,
    slaThresholdMinutes: 47,
    retryPolicy: { maxRetries: 3, backoffExponentialFactor: 2.0, initialDelaySeconds: 30 },
    validationAssertionsCount: 18,
    lineageTrackedColumns: ['record_id', 'source_timestamp', 'payload_hash', 'cleared_amount', 'tenant_id']
  },
  {
    dagId: 'DAG-IOT-123',
    pipelineName: 'IoTSensorTelemetryBatch Production Workflow #123',
    domain: 'IoTSensorTelemetryBatch',
    category: 'Industrial SCADA sensor timeseries ingestion',
    cronSchedule: '3 3 * * *',
    sourceProtocol: 'KAFKA',
    sinkProtocol: 'BIGQUERY',
    batchSizeRecords: 80000,
    maxParallelTasks: 7,
    slaThresholdMinutes: 48,
    retryPolicy: { maxRetries: 3, backoffExponentialFactor: 2.0, initialDelaySeconds: 30 },
    validationAssertionsCount: 19,
    lineageTrackedColumns: ['record_id', 'source_timestamp', 'payload_hash', 'cleared_amount', 'tenant_id']
  },
  {
    dagId: 'DAG-IOT-124',
    pipelineName: 'IoTSensorTelemetryBatch Production Workflow #124',
    domain: 'IoTSensorTelemetryBatch',
    category: 'rolling statistical anomaly detection',
    cronSchedule: '4 4 * * *',
    sourceProtocol: 'POSTGRES',
    sinkProtocol: 'SNOWFLAKE',
    batchSizeRecords: 90000,
    maxParallelTasks: 8,
    slaThresholdMinutes: 49,
    retryPolicy: { maxRetries: 3, backoffExponentialFactor: 2.0, initialDelaySeconds: 30 },
    validationAssertionsCount: 20,
    lineageTrackedColumns: ['record_id', 'source_timestamp', 'payload_hash', 'cleared_amount', 'tenant_id']
  },
  {
    dagId: 'DAG-IOT-125',
    pipelineName: 'IoTSensorTelemetryBatch Production Workflow #125',
    domain: 'IoTSensorTelemetryBatch',
    category: 'and predictive maintenance metrics',
    cronSchedule: '5 5 * * *',
    sourceProtocol: 'ICEBERG',
    sinkProtocol: 'BIGQUERY',
    batchSizeRecords: 100000,
    maxParallelTasks: 9,
    slaThresholdMinutes: 50,
    retryPolicy: { maxRetries: 3, backoffExponentialFactor: 2.0, initialDelaySeconds: 30 },
    validationAssertionsCount: 21,
    lineageTrackedColumns: ['record_id', 'source_timestamp', 'payload_hash', 'cleared_amount', 'tenant_id']
  },
  {
    dagId: 'DAG-IOT-126',
    pipelineName: 'IoTSensorTelemetryBatch Production Workflow #126',
    domain: 'IoTSensorTelemetryBatch',
    category: 'Industrial SCADA sensor timeseries ingestion',
    cronSchedule: '6 6 * * *',
    sourceProtocol: 'KAFKA',
    sinkProtocol: 'SNOWFLAKE',
    batchSizeRecords: 110000,
    maxParallelTasks: 10,
    slaThresholdMinutes: 51,
    retryPolicy: { maxRetries: 3, backoffExponentialFactor: 2.0, initialDelaySeconds: 30 },
    validationAssertionsCount: 22,
    lineageTrackedColumns: ['record_id', 'source_timestamp', 'payload_hash', 'cleared_amount', 'tenant_id']
  },
  {
    dagId: 'DAG-IOT-127',
    pipelineName: 'IoTSensorTelemetryBatch Production Workflow #127',
    domain: 'IoTSensorTelemetryBatch',
    category: 'rolling statistical anomaly detection',
    cronSchedule: '7 7 * * *',
    sourceProtocol: 'ICEBERG',
    sinkProtocol: 'BIGQUERY',
    batchSizeRecords: 120000,
    maxParallelTasks: 11,
    slaThresholdMinutes: 52,
    retryPolicy: { maxRetries: 3, backoffExponentialFactor: 2.0, initialDelaySeconds: 30 },
    validationAssertionsCount: 23,
    lineageTrackedColumns: ['record_id', 'source_timestamp', 'payload_hash', 'cleared_amount', 'tenant_id']
  },
  {
    dagId: 'DAG-IOT-128',
    pipelineName: 'IoTSensorTelemetryBatch Production Workflow #128',
    domain: 'IoTSensorTelemetryBatch',
    category: 'and predictive maintenance metrics',
    cronSchedule: '8 8 * * *',
    sourceProtocol: 'POSTGRES',
    sinkProtocol: 'SNOWFLAKE',
    batchSizeRecords: 130000,
    maxParallelTasks: 12,
    slaThresholdMinutes: 53,
    retryPolicy: { maxRetries: 3, backoffExponentialFactor: 2.0, initialDelaySeconds: 30 },
    validationAssertionsCount: 8,
    lineageTrackedColumns: ['record_id', 'source_timestamp', 'payload_hash', 'cleared_amount', 'tenant_id']
  },
  {
    dagId: 'DAG-IOT-129',
    pipelineName: 'IoTSensorTelemetryBatch Production Workflow #129',
    domain: 'IoTSensorTelemetryBatch',
    category: 'Industrial SCADA sensor timeseries ingestion',
    cronSchedule: '9 9 * * *',
    sourceProtocol: 'KAFKA',
    sinkProtocol: 'BIGQUERY',
    batchSizeRecords: 140000,
    maxParallelTasks: 13,
    slaThresholdMinutes: 54,
    retryPolicy: { maxRetries: 3, backoffExponentialFactor: 2.0, initialDelaySeconds: 30 },
    validationAssertionsCount: 9,
    lineageTrackedColumns: ['record_id', 'source_timestamp', 'payload_hash', 'cleared_amount', 'tenant_id']
  },
  {
    dagId: 'DAG-IOT-130',
    pipelineName: 'IoTSensorTelemetryBatch Production Workflow #130',
    domain: 'IoTSensorTelemetryBatch',
    category: 'rolling statistical anomaly detection',
    cronSchedule: '10 10 * * *',
    sourceProtocol: 'SNOWFLAKE',
    sinkProtocol: 'SNOWFLAKE',
    batchSizeRecords: 150000,
    maxParallelTasks: 14,
    slaThresholdMinutes: 55,
    retryPolicy: { maxRetries: 3, backoffExponentialFactor: 2.0, initialDelaySeconds: 30 },
    validationAssertionsCount: 10,
    lineageTrackedColumns: ['record_id', 'source_timestamp', 'payload_hash', 'cleared_amount', 'tenant_id']
  },
  {
    dagId: 'DAG-IOT-131',
    pipelineName: 'IoTSensorTelemetryBatch Production Workflow #131',
    domain: 'IoTSensorTelemetryBatch',
    category: 'and predictive maintenance metrics',
    cronSchedule: '11 11 * * *',
    sourceProtocol: 'ICEBERG',
    sinkProtocol: 'BIGQUERY',
    batchSizeRecords: 160000,
    maxParallelTasks: 15,
    slaThresholdMinutes: 56,
    retryPolicy: { maxRetries: 3, backoffExponentialFactor: 2.0, initialDelaySeconds: 30 },
    validationAssertionsCount: 11,
    lineageTrackedColumns: ['record_id', 'source_timestamp', 'payload_hash', 'cleared_amount', 'tenant_id']
  },
  {
    dagId: 'DAG-IOT-132',
    pipelineName: 'IoTSensorTelemetryBatch Production Workflow #132',
    domain: 'IoTSensorTelemetryBatch',
    category: 'Industrial SCADA sensor timeseries ingestion',
    cronSchedule: '12 12 * * *',
    sourceProtocol: 'POSTGRES',
    sinkProtocol: 'SNOWFLAKE',
    batchSizeRecords: 170000,
    maxParallelTasks: 4,
    slaThresholdMinutes: 57,
    retryPolicy: { maxRetries: 3, backoffExponentialFactor: 2.0, initialDelaySeconds: 30 },
    validationAssertionsCount: 12,
    lineageTrackedColumns: ['record_id', 'source_timestamp', 'payload_hash', 'cleared_amount', 'tenant_id']
  },
  {
    dagId: 'DAG-IOT-133',
    pipelineName: 'IoTSensorTelemetryBatch Production Workflow #133',
    domain: 'IoTSensorTelemetryBatch',
    category: 'rolling statistical anomaly detection',
    cronSchedule: '13 13 * * *',
    sourceProtocol: 'ICEBERG',
    sinkProtocol: 'BIGQUERY',
    batchSizeRecords: 180000,
    maxParallelTasks: 5,
    slaThresholdMinutes: 58,
    retryPolicy: { maxRetries: 3, backoffExponentialFactor: 2.0, initialDelaySeconds: 30 },
    validationAssertionsCount: 13,
    lineageTrackedColumns: ['record_id', 'source_timestamp', 'payload_hash', 'cleared_amount', 'tenant_id']
  },
  {
    dagId: 'DAG-IOT-134',
    pipelineName: 'IoTSensorTelemetryBatch Production Workflow #134',
    domain: 'IoTSensorTelemetryBatch',
    category: 'and predictive maintenance metrics',
    cronSchedule: '14 14 * * *',
    sourceProtocol: 'SNOWFLAKE',
    sinkProtocol: 'SNOWFLAKE',
    batchSizeRecords: 190000,
    maxParallelTasks: 6,
    slaThresholdMinutes: 59,
    retryPolicy: { maxRetries: 3, backoffExponentialFactor: 2.0, initialDelaySeconds: 30 },
    validationAssertionsCount: 14,
    lineageTrackedColumns: ['record_id', 'source_timestamp', 'payload_hash', 'cleared_amount', 'tenant_id']
  },
  {
    dagId: 'DAG-IOT-135',
    pipelineName: 'IoTSensorTelemetryBatch Production Workflow #135',
    domain: 'IoTSensorTelemetryBatch',
    category: 'Industrial SCADA sensor timeseries ingestion',
    cronSchedule: '15 15 * * *',
    sourceProtocol: 'KAFKA',
    sinkProtocol: 'BIGQUERY',
    batchSizeRecords: 200000,
    maxParallelTasks: 7,
    slaThresholdMinutes: 15,
    retryPolicy: { maxRetries: 3, backoffExponentialFactor: 2.0, initialDelaySeconds: 30 },
    validationAssertionsCount: 15,
    lineageTrackedColumns: ['record_id', 'source_timestamp', 'payload_hash', 'cleared_amount', 'tenant_id']
  },
  {
    dagId: 'DAG-IOT-136',
    pipelineName: 'IoTSensorTelemetryBatch Production Workflow #136',
    domain: 'IoTSensorTelemetryBatch',
    category: 'rolling statistical anomaly detection',
    cronSchedule: '16 16 * * *',
    sourceProtocol: 'POSTGRES',
    sinkProtocol: 'SNOWFLAKE',
    batchSizeRecords: 210000,
    maxParallelTasks: 8,
    slaThresholdMinutes: 16,
    retryPolicy: { maxRetries: 3, backoffExponentialFactor: 2.0, initialDelaySeconds: 30 },
    validationAssertionsCount: 16,
    lineageTrackedColumns: ['record_id', 'source_timestamp', 'payload_hash', 'cleared_amount', 'tenant_id']
  },
  {
    dagId: 'DAG-IOT-137',
    pipelineName: 'IoTSensorTelemetryBatch Production Workflow #137',
    domain: 'IoTSensorTelemetryBatch',
    category: 'and predictive maintenance metrics',
    cronSchedule: '17 17 * * *',
    sourceProtocol: 'ICEBERG',
    sinkProtocol: 'BIGQUERY',
    batchSizeRecords: 220000,
    maxParallelTasks: 9,
    slaThresholdMinutes: 17,
    retryPolicy: { maxRetries: 3, backoffExponentialFactor: 2.0, initialDelaySeconds: 30 },
    validationAssertionsCount: 17,
    lineageTrackedColumns: ['record_id', 'source_timestamp', 'payload_hash', 'cleared_amount', 'tenant_id']
  },
  {
    dagId: 'DAG-IOT-138',
    pipelineName: 'IoTSensorTelemetryBatch Production Workflow #138',
    domain: 'IoTSensorTelemetryBatch',
    category: 'Industrial SCADA sensor timeseries ingestion',
    cronSchedule: '18 18 * * *',
    sourceProtocol: 'KAFKA',
    sinkProtocol: 'SNOWFLAKE',
    batchSizeRecords: 230000,
    maxParallelTasks: 10,
    slaThresholdMinutes: 18,
    retryPolicy: { maxRetries: 3, backoffExponentialFactor: 2.0, initialDelaySeconds: 30 },
    validationAssertionsCount: 18,
    lineageTrackedColumns: ['record_id', 'source_timestamp', 'payload_hash', 'cleared_amount', 'tenant_id']
  },
  {
    dagId: 'DAG-IOT-139',
    pipelineName: 'IoTSensorTelemetryBatch Production Workflow #139',
    domain: 'IoTSensorTelemetryBatch',
    category: 'rolling statistical anomaly detection',
    cronSchedule: '19 19 * * *',
    sourceProtocol: 'ICEBERG',
    sinkProtocol: 'BIGQUERY',
    batchSizeRecords: 240000,
    maxParallelTasks: 11,
    slaThresholdMinutes: 19,
    retryPolicy: { maxRetries: 3, backoffExponentialFactor: 2.0, initialDelaySeconds: 30 },
    validationAssertionsCount: 19,
    lineageTrackedColumns: ['record_id', 'source_timestamp', 'payload_hash', 'cleared_amount', 'tenant_id']
  },
  {
    dagId: 'DAG-IOT-140',
    pipelineName: 'IoTSensorTelemetryBatch Production Workflow #140',
    domain: 'IoTSensorTelemetryBatch',
    category: 'and predictive maintenance metrics',
    cronSchedule: '20 20 * * *',
    sourceProtocol: 'POSTGRES',
    sinkProtocol: 'SNOWFLAKE',
    batchSizeRecords: 50000,
    maxParallelTasks: 12,
    slaThresholdMinutes: 20,
    retryPolicy: { maxRetries: 3, backoffExponentialFactor: 2.0, initialDelaySeconds: 30 },
    validationAssertionsCount: 20,
    lineageTrackedColumns: ['record_id', 'source_timestamp', 'payload_hash', 'cleared_amount', 'tenant_id']
  },
  {
    dagId: 'DAG-IOT-141',
    pipelineName: 'IoTSensorTelemetryBatch Production Workflow #141',
    domain: 'IoTSensorTelemetryBatch',
    category: 'Industrial SCADA sensor timeseries ingestion',
    cronSchedule: '21 21 * * *',
    sourceProtocol: 'KAFKA',
    sinkProtocol: 'BIGQUERY',
    batchSizeRecords: 60000,
    maxParallelTasks: 13,
    slaThresholdMinutes: 21,
    retryPolicy: { maxRetries: 3, backoffExponentialFactor: 2.0, initialDelaySeconds: 30 },
    validationAssertionsCount: 21,
    lineageTrackedColumns: ['record_id', 'source_timestamp', 'payload_hash', 'cleared_amount', 'tenant_id']
  },
  {
    dagId: 'DAG-IOT-142',
    pipelineName: 'IoTSensorTelemetryBatch Production Workflow #142',
    domain: 'IoTSensorTelemetryBatch',
    category: 'rolling statistical anomaly detection',
    cronSchedule: '22 22 * * *',
    sourceProtocol: 'SNOWFLAKE',
    sinkProtocol: 'SNOWFLAKE',
    batchSizeRecords: 70000,
    maxParallelTasks: 14,
    slaThresholdMinutes: 22,
    retryPolicy: { maxRetries: 3, backoffExponentialFactor: 2.0, initialDelaySeconds: 30 },
    validationAssertionsCount: 22,
    lineageTrackedColumns: ['record_id', 'source_timestamp', 'payload_hash', 'cleared_amount', 'tenant_id']
  },
  {
    dagId: 'DAG-IOT-143',
    pipelineName: 'IoTSensorTelemetryBatch Production Workflow #143',
    domain: 'IoTSensorTelemetryBatch',
    category: 'and predictive maintenance metrics',
    cronSchedule: '23 23 * * *',
    sourceProtocol: 'ICEBERG',
    sinkProtocol: 'BIGQUERY',
    batchSizeRecords: 80000,
    maxParallelTasks: 15,
    slaThresholdMinutes: 23,
    retryPolicy: { maxRetries: 3, backoffExponentialFactor: 2.0, initialDelaySeconds: 30 },
    validationAssertionsCount: 23,
    lineageTrackedColumns: ['record_id', 'source_timestamp', 'payload_hash', 'cleared_amount', 'tenant_id']
  },
  {
    dagId: 'DAG-IOT-144',
    pipelineName: 'IoTSensorTelemetryBatch Production Workflow #144',
    domain: 'IoTSensorTelemetryBatch',
    category: 'Industrial SCADA sensor timeseries ingestion',
    cronSchedule: '24 0 * * *',
    sourceProtocol: 'POSTGRES',
    sinkProtocol: 'SNOWFLAKE',
    batchSizeRecords: 90000,
    maxParallelTasks: 4,
    slaThresholdMinutes: 24,
    retryPolicy: { maxRetries: 3, backoffExponentialFactor: 2.0, initialDelaySeconds: 30 },
    validationAssertionsCount: 8,
    lineageTrackedColumns: ['record_id', 'source_timestamp', 'payload_hash', 'cleared_amount', 'tenant_id']
  },
  {
    dagId: 'DAG-IOT-145',
    pipelineName: 'IoTSensorTelemetryBatch Production Workflow #145',
    domain: 'IoTSensorTelemetryBatch',
    category: 'rolling statistical anomaly detection',
    cronSchedule: '25 1 * * *',
    sourceProtocol: 'ICEBERG',
    sinkProtocol: 'BIGQUERY',
    batchSizeRecords: 100000,
    maxParallelTasks: 5,
    slaThresholdMinutes: 25,
    retryPolicy: { maxRetries: 3, backoffExponentialFactor: 2.0, initialDelaySeconds: 30 },
    validationAssertionsCount: 9,
    lineageTrackedColumns: ['record_id', 'source_timestamp', 'payload_hash', 'cleared_amount', 'tenant_id']
  },
  {
    dagId: 'DAG-IOT-146',
    pipelineName: 'IoTSensorTelemetryBatch Production Workflow #146',
    domain: 'IoTSensorTelemetryBatch',
    category: 'and predictive maintenance metrics',
    cronSchedule: '26 2 * * *',
    sourceProtocol: 'SNOWFLAKE',
    sinkProtocol: 'SNOWFLAKE',
    batchSizeRecords: 110000,
    maxParallelTasks: 6,
    slaThresholdMinutes: 26,
    retryPolicy: { maxRetries: 3, backoffExponentialFactor: 2.0, initialDelaySeconds: 30 },
    validationAssertionsCount: 10,
    lineageTrackedColumns: ['record_id', 'source_timestamp', 'payload_hash', 'cleared_amount', 'tenant_id']
  },
  {
    dagId: 'DAG-IOT-147',
    pipelineName: 'IoTSensorTelemetryBatch Production Workflow #147',
    domain: 'IoTSensorTelemetryBatch',
    category: 'Industrial SCADA sensor timeseries ingestion',
    cronSchedule: '27 3 * * *',
    sourceProtocol: 'KAFKA',
    sinkProtocol: 'BIGQUERY',
    batchSizeRecords: 120000,
    maxParallelTasks: 7,
    slaThresholdMinutes: 27,
    retryPolicy: { maxRetries: 3, backoffExponentialFactor: 2.0, initialDelaySeconds: 30 },
    validationAssertionsCount: 11,
    lineageTrackedColumns: ['record_id', 'source_timestamp', 'payload_hash', 'cleared_amount', 'tenant_id']
  },
  {
    dagId: 'DAG-IOT-148',
    pipelineName: 'IoTSensorTelemetryBatch Production Workflow #148',
    domain: 'IoTSensorTelemetryBatch',
    category: 'rolling statistical anomaly detection',
    cronSchedule: '28 4 * * *',
    sourceProtocol: 'POSTGRES',
    sinkProtocol: 'SNOWFLAKE',
    batchSizeRecords: 130000,
    maxParallelTasks: 8,
    slaThresholdMinutes: 28,
    retryPolicy: { maxRetries: 3, backoffExponentialFactor: 2.0, initialDelaySeconds: 30 },
    validationAssertionsCount: 12,
    lineageTrackedColumns: ['record_id', 'source_timestamp', 'payload_hash', 'cleared_amount', 'tenant_id']
  },
  {
    dagId: 'DAG-IOT-149',
    pipelineName: 'IoTSensorTelemetryBatch Production Workflow #149',
    domain: 'IoTSensorTelemetryBatch',
    category: 'and predictive maintenance metrics',
    cronSchedule: '29 5 * * *',
    sourceProtocol: 'ICEBERG',
    sinkProtocol: 'BIGQUERY',
    batchSizeRecords: 140000,
    maxParallelTasks: 9,
    slaThresholdMinutes: 29,
    retryPolicy: { maxRetries: 3, backoffExponentialFactor: 2.0, initialDelaySeconds: 30 },
    validationAssertionsCount: 13,
    lineageTrackedColumns: ['record_id', 'source_timestamp', 'payload_hash', 'cleared_amount', 'tenant_id']
  },
  {
    dagId: 'DAG-IOT-150',
    pipelineName: 'IoTSensorTelemetryBatch Production Workflow #150',
    domain: 'IoTSensorTelemetryBatch',
    category: 'Industrial SCADA sensor timeseries ingestion',
    cronSchedule: '30 6 * * *',
    sourceProtocol: 'KAFKA',
    sinkProtocol: 'SNOWFLAKE',
    batchSizeRecords: 150000,
    maxParallelTasks: 10,
    slaThresholdMinutes: 30,
    retryPolicy: { maxRetries: 3, backoffExponentialFactor: 2.0, initialDelaySeconds: 30 },
    validationAssertionsCount: 14,
    lineageTrackedColumns: ['record_id', 'source_timestamp', 'payload_hash', 'cleared_amount', 'tenant_id']
  }
];

export class IOT_PipelineCatalog {
  static search(query: string): EnterprisePipelineDAG[] {
    const q = query.toLowerCase().trim();
    if (!q) return PIPELINE_IOT_DATASET.slice(0, 20);
    return PIPELINE_IOT_DATASET.filter(p => p.pipelineName.toLowerCase().includes(q) || p.category.toLowerCase().includes(q));
  }
}
